[example config]:add linux-apche-errorlog.md
alibaba/ilogtail pull request #1001
Opened 2023-07-12 08:28 UTC by Gump9

add linux-apche-errorlog.md

2023-07-12 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1001) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1001) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1001) it.</sub>

2023-07-13 02:24 UTC, henryzhx8 reviewed
段与段之间要空行，装一个yaml插件检查一下格式

2023-07-13 02:26 UTC, henryzhx8 requested changes

2023-07-13 02:26 UTC, henryzhx8 commented on example_config/user_contrib/linux-apache-errorlog.md
> +```
```后边加上语言类型，比如yaml，plain或者json等

2023-07-13 02:26 UTC, henryzhx8 commented on example_config/user_contrib/linux-apache-errorlog.md
> +2023-07-12 07:19:30 {"__tag__:__path__":"./log/apache_errorlog.log","timestamp":"Thu May 12 08:28:57.652118 2011","day":"Thu","month":"May","monthday":"12","time":"08:28:57.652118","year":"2011","dat
这边的输出为什么会有一个单独的时间在前边？

2023-07-13 02:35 UTC, henryzhx8 reviewed
CLA问题处理一下

2023-07-13 04:57 UTC, Gump9 commented on example_config/user_contrib/linux-apache-errorlog.md
> +2023-07-12 07:19:30 {"__tag__:__path__":"./log/apache_errorlog.log","timestamp":"Thu May 12 08:28:57.652118 2011","day":"Thu","month":"May","monthday":"12","time":"08:28:57.652118","year":"2011","dat
> 这边的输出为什么会有一个单独的时间在前边？

这个第二条提取的日志好像有问题，我再看看，单独时间是指那个timestamp吗？timestamp是正则表达式里的。还是最前面的单独时间？那个好像是提取时间。我用json格式的日志提取也会有呀

2023-07-13 05:22 UTC, Gump9 commented on example_config/user_contrib/linux-apache-errorlog.md
> +2023-07-12 07:19:30 {"__tag__:__path__":"./log/apache_errorlog.log","timestamp":"Thu May 12 08:28:57.652118 2011","day":"Thu","month":"May","monthday":"12","time":"08:28:57.652118","year":"2011","dat
> > 这边的输出为什么会有一个单独的时间在前边？
> 
> 这个第二条提取的日志好像有问题，我再看看，单独时间是指那个timestamp吗？timestamp是正则表达式里的。还是最前面的单独时间？那个好像是提取时间。我用json格式的日志提取也会有呀

破案了，样例搞错了，星期三是Wed不是Wes

2023-07-14 02:31 UTC, henryzhx8 approved these changes

2023-07-14 02:31 UTC, merged