Add vivado_synth_log.md
alibaba/ilogtail pull request #1002
Opened 2023-07-12 08:49 UTC by 4lex49

Vivado综合日志采样样例

2023-07-12 08:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1002) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1002) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1002) it.</sub>

2023-07-12 09:13 UTC, 4lex49 commented
请问能否帮助我为这个PR加上`example config`的label？我这里似乎权限不足

2023-07-12 15:31 UTC, yyuuttaaoo commented
厉害厉害，和ilogtail和芯片设计也扯上关系了: D

2023-07-13 02:27 UTC, henryzhx8 commented on example_config/user_contrib/vivado-synth-log.md
> +```
```后边需要加上语言类型，plain、yaml或json等

2023-07-13 02:29 UTC, henryzhx8 requested changes

2023-07-13 02:29 UTC, henryzhx8 commented on example_config/user_contrib/vivado-synth-log.md
> +2023-07-12 07:00:23 {"__tag__:__path__":"/mnt/hgfs/synth_25/runme.log","log_type":"WARNING","log_id":"Synth 8-6779","content":"Delay data for wire-load model not found, using default","__time__":"168
这个最前面的时间是怎么出来的？

2023-07-13 03:22 UTC, Lr-Young commented
厉害厉害，和ilogtail和芯片设计也扯上关系了: D

2023-07-13 09:13 UTC, 4lex49 commented on example_config/user_contrib/vivado-synth-log.md
> +```
已添加"plain"的语言类型

2023-07-13 09:14 UTC, 4lex49 commented on example_config/user_contrib/vivado-synth-log.md
> +2023-07-12 07:00:23 {"__tag__:__path__":"/mnt/hgfs/synth_25/runme.log","log_type":"WARNING","log_id":"Synth 8-6779","content":"Delay data for wire-load model not found, using default","__time__":"168
是ilogtail采样结果自带的，新的commit已手动删除并重新排版

2023-07-14 02:34 UTC, henryzhx8 approved these changes

2023-07-14 02:34 UTC, merged