Export ports to create k8s service
alibaba/ilogtail pull request #1003
Opened 2023-07-12 11:31 UTC by Takuka0311

2023-07-13 11:59 UTC, messixukejia approved these changes

2023-07-13 11:59 UTC, messixukejia commented on pluginmanager/logtail_port_manager.go
> +	if !exportLogtailPortsRunning {
确认下这个是否有必要

2023-07-14 02:34 UTC, Takuka0311 commented on pluginmanager/logtail_port_manager.go
> +	if !exportLogtailPortsRunning {
本意是为了确保这个函数只运行一次。以往使用的是这样的写法，现在改用sync.Once

2023-07-18 08:25 UTC, linrunqi08 requested changes

2023-07-18 08:25 UTC, linrunqi08 commented on pluginmanager/logtail_port_manager.go
> +		port, err := strconv.ParseUint((strings.Split(fields[1], ":")[1]), 16, 32)
同上，加注释

2023-07-18 11:43 UTC, Takuka0311 commented on pluginmanager/logtail_port_manager.go
> +	exportLogtailPortsPort = 18689
done

2023-07-18 11:55 UTC, Takuka0311 commented on pluginmanager/logtail_port_manager.go
> +		port, err := strconv.ParseUint((strings.Split(fields[1], ":")[1]), 16, 32)
done

2023-07-18 11:56 UTC, Takuka0311 commented on pluginmanager/logtail_port_manager.go
> +		if strings.HasPrefix(protocol, "tcp") && fields[3] != "0A" {
done

2023-07-27 03:38 UTC, linrunqi08 approved these changes

2023-07-27 03:50 UTC, merged