[example config] add linux-mysql-error-log.md
alibaba/ilogtail pull request #1007
Opened 2023-07-12 16:24 UTC by alph00

2023-07-12 16:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1007) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1007) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1007) it.</sub>

2023-07-13 02:34 UTC, henryzhx8 requested changes

2023-07-13 02:34 UTC, henryzhx8 commented on example_config/user_contrib/linux-mysql-error-log.md
> +
多余的行删去

2023-07-13 02:34 UTC, henryzhx8 commented on example_config/user_contrib/linux-mysql-error-log.md
> +2023-07-08 23:55:08
这行删掉吧

2023-07-13 02:34 UTC, henryzhx8 commented on example_config/user_contrib/linux-mysql-error-log.md
> +
空行删掉

2023-07-13 06:52 UTC, alph00 commented on example_config/user_contrib/linux-mysql-error-log.md
> +
好的

2023-07-14 02:35 UTC, henryzhx8 approved these changes

2023-07-14 02:35 UTC, merged