com.west2online.ClashX.log
alibaba/ilogtail pull request #1009
Opened 2023-07-13 05:18 UTC by liuw515

2023-07-13 05:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1009) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1009) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1009) it.</sub>

2023-07-14 02:46 UTC, henryzhx8 requested changes
段落之间需要空行，装一个yaml插件检查一下格式

2023-07-14 02:46 UTC, henryzhx8 commented on example_config/com.west2online.ClashX.log.md
> +```
```后面需要写上语言类型

2023-07-17 02:56 UTC, liuw515 commented on example_config/com.west2online.ClashX.log.md
> +```
我更新了，现在可以了嘛

2023-07-18 01:39 UTC, henryzhx8 approved these changes

2023-07-18 01:39 UTC, merged