[WIP]: add metric new
alibaba/ilogtail pull request #1015
Opened 2023-07-14 07:56 UTC by linrunqi08

2023-08-01 06:56 UTC, messixukejia approved these changes

2023-08-01 06:56 UTC, messixukejia commented on core/monitor/LogtaiMetric.cpp
> +        LOG_INFO(sLogger, ("CreateMetrics", "mSnapshottingHead"));
这个info日志有点缺乏辨识度，要么CreateMetrics增加点上下文，要么改成debu

2023-08-01 06:56 UTC, messixukejia commented on core/CMakeLists.txt
> +        controller event event_handler event_listener helper log_pb logger monitor
changelog

2023-08-01 06:56 UTC, messixukejia commented on core/CMakeLists.txt
> +        parser plugin polling processor reader profile_sender sender shennong sdk
文档增加一个开发指南吧

2023-08-01 06:56 UTC, messixukejia commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    MetricExportor::GetInstance()->PushMetrics();
ut没有assert

2023-08-02 07:35 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +        LOG_INFO(sLogger, ("CreateMetrics", "mSnapshottingHead"));
这个是测试时使用的，已删除

2023-08-02 07:35 UTC, linrunqi08 commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    MetricExportor::GetInstance()->PushMetrics();
done

2023-08-02 07:38 UTC, linrunqi08 commented on core/CMakeLists.txt
> +        controller event event_handler event_listener helper log_pb logger monitor
done

2023-08-11 09:51 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Counter(std::string name);
```suggestion
        Counter(const std::string &name);
```

2023-08-11 09:51 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        ~Counter();
```suggestion
```

2023-08-11 09:55 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        std::string GetName();
```suggestion
        const std::string& GetName() const;
```

2023-08-11 09:55 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        uint64_t GetTimestamp();
```suggestion
        const uint64_t GetTimestamp() const;
```

2023-08-11 09:55 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        uint64_t GetValue();
```suggestion
        const uint64_t GetValue() const;
```

2023-08-11 09:57 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
同一个类的方法放一起

2023-08-11 10:01 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        void Set(uint64_t val);
Counter为什么会有set方法？是不是应该再定义一个Gauge类用于记录实时值，建议不要复用

2023-08-11 10:51 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +typedef std::shared_ptr<Counter> CounterPtr;
```suggestion
using CounterPtr = std::shared_ptr<Counter> CounterPtr;
```

2023-08-11 10:53 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
用初始化列表
```suggestion
Counter::Counter(const std::string& name): mName(name), mVal(0), mTimeStamp(time(nullptr)) {}
```

2023-08-11 10:54 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
```suggestion
```

2023-08-11 10:54 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
初始化列表

2023-08-11 10:54 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
```suggestion
```

2023-08-11 10:57 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        std::vector<CounterPtr> mValues;
有其它类型的metric怎么办？

2023-08-11 10:57 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        ~Metrics();
```suggestion
```

2023-08-11 10:58 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Metrics(std::vector<std::pair<std::string, std::string> > labels);
```suggestion
        Metrics(const std::vector<std::pair<std::string, std::string> >& labels);
```

2023-08-11 10:59 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +    CounterPtr counterPtr(new Counter(name));
用make_shared

2023-08-11 11:00 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +    CounterPtr counterPtr(new Counter(name));
用make_shared

2023-08-11 11:01 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        CounterPtr CreateCounter(std::string Name);
```suggestion
        CounterPtr CreateCounter(const std::string& Name);
```

2023-08-11 11:02 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Metrics* next = NULL;
public?

2023-08-11 11:05 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Counter* CopyAndReset();
功能拆分吧，我看就是给复制metric用的：copy的部分用复制构造函数，然后再专门提供一个reset函数

2023-08-11 11:05 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +
```suggestion
```

2023-08-11 11:06 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Metrics* Copy();
用复制构造函数

2023-08-11 11:08 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        const std::vector<std::pair<std::string, std::string>>& GetLabels();
```suggestion
        const std::vector<std::pair<std::string, std::string>>& GetLabels() const;
```

2023-08-11 11:08 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        const std::vector<CounterPtr>& GetValues();
```suggestion
        const std::vector<CounterPtr>& GetValues() const;
```

2023-08-11 11:09 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
```suggestion
```

2023-08-11 11:10 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +Metrics::Metrics(std::vector<std::pair<std::string, std::string>> labels) {
初始化列表

2023-08-11 11:10 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
初始化列表

2023-08-11 11:13 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        std::mutex mSnapshottingMutex;
把mutex和保护对象放一起

2023-08-11 11:17 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        ~WriteMetrics();
为什么要设成private？是有意的还是啥？private的话都不能new了吧

2023-08-11 11:23 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +
```suggestion
```

2023-08-11 11:46 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +    std::lock_guard<std::mutex> lock(mMutex);
可以放到122行前

2023-08-11 11:58 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +            preTmp = preTmp->next;
165和170行可以拿出来

2023-08-11 11:58 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +            continue;
用else吧

2023-08-11 11:59 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +        std::lock_guard<std::mutex> lock(mMutex);
这里的锁不是mSnapshottingMutex？

2023-08-11 12:03 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +        if (mSnapshottingHead) {
这里加锁的粒度可以进一步减小，遍历过程无需加锁，只需要头上的操作

2023-08-11 12:04 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        ~ReadMetrics();
```suggestion
```

2023-08-11 14:02 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Metrics* CreateMetrics(std::vector<std::pair<std::string, std::string>> Labels);
返回值改为unique_ptr吧，这个metrics除了创建者所有之外，应该不存在共享吧？

2023-08-11 14:08 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        void DestroyMetrics(Metrics* metrics);
把这个函数改成lambda作为unique_ptr的deleter，这样避免创建者忘记调用Destroy函数，做到RAII。

2023-08-11 14:19 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        void ReadAsPrometheus();
没实现的先注释掉吧

2023-08-11 14:22 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +        for (std::vector<std::pair<std::string, std::string>>::iterator it = labels.begin(); it != labels.end(); ++it) {
```suggestion
        for (auto &item: tmp->GetLabels()) {
```

2023-08-11 14:23 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +        for (std::vector<std::pair<std::string, std::string>>::iterator it = labels.begin(); it != labels.end(); ++it) {
```suggestion
        for (auto &item: tmp->GetLabels()) {
```

2023-08-11 14:41 UTC, henryzhx8 requested changes
语法上的小问题比较多，需要注意

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +            std::pair<std::string, std::string> pair = *it;
```suggestion
        for (auto &item: tmp->GetLabels()) {
```

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        ReadWriteLock mReadWriteLock;
1. 放到private里
2. NULL改成nullptr

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/MetricExportor.h
> +    ~MetricExportor() {}
```suggestion
```

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/MetricExportor.h
> +    int32_t mLastSnapshotTime;
移到private

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +#include <list>
```suggestion
```

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +#include "logger/Logger.h"
```suggestion
```

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +#include "common/StringTools.h"
这个哪里用到了？cpp里用到的头文件不要在这里include，这里是最小集合

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/MetricExportor.h
> +#include <json/json.h>
```suggestion
```

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/MetricExportor.h
> +#include "log_pb/sls_logs.pb.h"
```suggestion
```

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/MetricExportor.cpp
> +    mLastSnapshotTime = 0;
1. 写死的？
2. 用初始化列表

2023-08-11 14:41 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        void ReadAsMap(std::map<std::string, std::string> map);
建议新建一个模版函数Read，然后把这些具体的函数放在private里.

2023-08-14 03:22 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        Counter(std::string name);
done

2023-08-14 03:22 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        ~Counter();
done

2023-08-14 03:22 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        std::string GetName();
done

2023-08-14 03:22 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        uint64_t GetTimestamp();
done

2023-08-14 03:24 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        uint64_t GetValue();
done

2023-08-14 10:01 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +}
done

2023-08-14 10:02 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        void Set(uint64_t val);
done

2023-08-14 11:10 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +}
done

2023-08-14 11:10 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        ~Metrics();
done

2023-08-14 11:10 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        std::vector<CounterPtr> mValues;
改成了抽象类

2023-08-14 11:20 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +    CounterPtr counterPtr(new Counter(name));
done

2023-08-14 11:27 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        const std::vector<std::pair<std::string, std::string>>& GetLabels();
done

2023-08-14 11:27 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        const std::vector<CounterPtr>& GetValues();
done

2023-08-14 11:27 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +}
done

2023-08-15 14:50 UTC, yyuuttaaoo commented on core/monitor/LogtailMetric.h
> +        Metrics* CreateMetrics(std::vector<std::pair<std::string, std::string>> Labels);
不是，ownership在WriteMetrics，使用方是引用。看了下面的评论，这么说可以自定义一个MetricRef类给包装一下

2023-08-16 06:10 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        void ReadAsPrometheus();
done

2023-08-16 06:10 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        void DestroyMetrics(Metrics* metrics);
done

2023-08-16 06:10 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        Metrics* CreateMetrics(std::vector<std::pair<std::string, std::string>> Labels);
done

2023-08-16 06:11 UTC, linrunqi08 commented on core/monitor/MetricExportor.h
> +#include <json/json.h>
done

2023-08-16 06:11 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +#include <list>
done

2023-08-16 06:12 UTC, linrunqi08 commented on core/monitor/MetricExportor.h
> +    int32_t mLastSnapshotTime;
done

2023-08-16 06:12 UTC, linrunqi08 commented on core/monitor/MetricExportor.h
> +    ~MetricExportor() {}
done

2023-08-16 08:15 UTC, yyuuttaaoo commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    Metrics* fileMetric3 = WriteMetrics::GetInstance()->CreateMetrics(labels);
这里为啥不用MetricPtr？

2023-08-16 08:33 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +            delete toDeleted;
之前讨论可以在snapshot完成后再删除

2023-08-16 08:36 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +            preTmp = preTmp->next;
公共部分不要放在if、else里。比如rTmp = snapshot;preTmp = preTmp->next;

2023-08-16 08:39 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +    Metrics* emptyHead = new Metrics();
这个可以直接用临时变量，然后用个指针指向它，不用new。

2023-08-16 09:44 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +    mDeleted.store(true);
直接=就行了，因为读的地方也没.load()

2023-08-16 09:46 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +Metrics* Metrics::Copy() {
这个是不是也叫CopyAndReset?

2023-08-16 09:48 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +Metrics* WriteMetrics::CreateMetrics(std::vector<std::pair<std::string, std::string>> labels) {
入参如果大部分情况下都是一次性的，可以考虑用vector &&，调用点显示std::move

2023-08-16 09:48 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +    Metrics* cur = new Metrics(labels);
这个构造函数类似，是不是可以考虑将label move到metrics里

2023-08-16 11:11 UTC, yyuuttaaoo commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    MetricExportor::GetInstance()->PushMetrics();
之后再增加一下写未删除的指标，并再此取值测试snapshot delete没有破坏未删除指标，同时copy and reset工作正确

2023-08-16 11:31 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +    counter->mTimestamp = mTimestamp.exchange(0);
不用时间

2023-08-17 09:43 UTC, henryzhx8 requested changes

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        const std::string GetName() const;
```suggestion
        const std::string& GetName() const;
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        void Set(uint64_t val);
```suggestion
        Gauge(const std::string &name);   
        void Set(uint64_t val);
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Gauge* CopyAndReset();
```suggestion
        Gauge* CopyAndReset() override;
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Counter(const std::string name);
```suggestion
        Counter(const std::string &name);
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        Counter* CopyAndReset();
```suggestion
        Counter* CopyAndReset() override;
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +using GaugePtr = std::shared_ptr<Gauge>;
CounterPtr和GaugePtr有什么用？用指针是因为基类指针能转换，子类指针并没有什么用
```suggestion
using MetricPtr = std::shared_ptr<BaseMetric>;
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        CounterPtr CreateCounter(const std::string Name);
```suggestion
        CounterPtr CreateCounter(const std::string &Name);
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +        GaugePtr CreateGauge(const std::string Name);
```suggestion
        GaugePtr CreateGauge(const std::string &Name);
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +    mVal = (uint64_t)0;
和头文件签名对齐，用初始化列表
```suggestion
Counter::Counter(const std::string &name, uint64_t val = 0): mName(name), mVal(val) {}
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +    counter->mVal = mVal.exchange(0);
```suggestion
    return new Counter(mName, mVal.exchange(0));
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
同上吧

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +Metrics::Metrics(const std::vector<std::pair<std::string, std::string>>& labels) : mLabels(std::move(labels)), mDeleted(false) {}
这里labels是一次性的？ move的话入参得是&&，不是&

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +    CounterPtr counterPtr = std::make_shared<Counter>(name);
```suggestion
    MetricPtr counterPtr = std::make_shared<Counter>(name);
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +    GaugePtr gaugePtr = std::make_shared<Gauge>(name);
```suggestion
    MetricPtr gaugePtr = std::make_shared<Gauge>(name);
```

2023-08-17 09:43 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +class MetricsRef {
这个MetricsRef和MetricPtr名字太像了，而且是两回事，Metrics是不是应该改个名字啥的？

2023-08-22 12:48 UTC, yyuuttaaoo requested changes

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    MetricPtr fileCounter = fileMetric.Get()->CreateCounter("filed1");
其实这里设计的测试竞争非常不激烈，所以我感觉多线程的意义不大。而且多线程bug很难测出来。。。一个UT不测出来不等于没问题。

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    MetricExportor::GetInstance()->PushMetrics(true);
这后面加一段DeleteMetric，和修改剩下metric value的。下面多线程测试比较复杂，先把单线程的整明白。测试的目的是确实读了之后Write结构还能delete，确实剩下的没破坏，还能write，值也是对的，因为read被清空了。当然我觉得这已经有点不太UT了，但至少覆盖是不是会全一些，最好当然是每个函数有独立清晰的UT。

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/MetricExportor.cpp
> +MetricExportor::MetricExportor() : mSendInterval(60), mLastSendTime(time(NULL) - (rand() % (mSendInterval / 10)) * 10) {}
为啥还要/10？

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +Metrics* ReadMetrics::GetHead() {
const修饰?

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtailMetric.h
> +        void ReadAsLogGroup(std::map<std::string, sls_logs::LogGroup*>& logGroupMap);
把mReadWriteLock声明为mutable，这个也可以用const修饰

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtailMetric.h
> +        Metrics* GetHead();
const？

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtailMetric.h
>          bool IsDeleted();
const？

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +    while(toDeleteHead) {
code style

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +                    mHead->SetNext(nullptr);
这里应该不用为head单独设置，因为竞争的是mHead指针，不是mHead指向的对象。修改对象的next没人竞争。
所以到这里就可以break了
前一半是确定新mHead，这个确定了，后面遍历的时候mHead的IsDelete直接忽略，因为这里已经判定过了。后面的正常判定IsDelete

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +    if (tmpHeadNext) {
修改后是不是只要tmpHead了，不需要管tmpHeadNext

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +ReadMetrics::ReadMetrics() {}
析构呢？mHead链表需要删除吧

2023-08-22 12:48 UTC, yyuuttaaoo commented on core/monitor/LogtailMetric.h
>          WriteMetrics();
where is destructor?
do we need to delete mHead list?

2023-08-23 01:46 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +class MetricsRef {
done

2023-08-23 02:29 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +Metrics* WriteMetrics::CreateMetrics(const std::vector<std::pair<std::string, std::string>>& labels) {
done

2023-08-23 02:59 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +    while(toDeleteHead) {
done

2023-08-23 05:56 UTC, linrunqi08 commented on core/unittest/monitor/LogtailMetricUnittest.cpp
>      // first test left 1, 1 + (1 + 2 + 3 + 4)
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
>          bool IsDeleted();
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        Metrics* GetHead();
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +Metrics* ReadMetrics::GetHead() {
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    MetricExportor::GetInstance()->PushMetrics(true);
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/unittest/monitor/LogtailMetricUnittest.cpp
> +    MetricPtr fileCounter = fileMetric.Get()->CreateCounter("filed1");
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
>  bool Metrics::IsDeleted() {
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +Metrics* Metrics::GetNext() {
done

2023-08-23 06:05 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +Metrics* WriteMetrics::GetHead() {
done

2023-08-23 06:12 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +        void ReadAsLogGroup(std::map<std::string, sls_logs::LogGroup*>& logGroupMap);
done

2023-08-23 06:17 UTC, linrunqi08 commented on core/monitor/MetricExportor.cpp
> +MetricExportor::MetricExportor() : mSendInterval(60), mLastSendTime(time(NULL) - (rand() % (mSendInterval / 10)) * 10) {}
这里启动的时候，在当前时间-mSendInterval ～ 当前时间的范围内随机生成一个数字，作为mLastSendTime

2023-08-23 08:17 UTC, yyuuttaaoo requested changes

2023-08-23 08:17 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +const bool MetricsRecord::IsDeleted() const {
const bool的const不要，返回值的都不需要加const

2023-08-23 08:17 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +MetricsRecord* MetricsRecordRef::operator->() const {
这种返回指针的可能要小心，虽然mMetrics是不可能被修改的，但这是一个链表，后面的东西可能会被改，所以我感觉需要提供2个版本，语义才足够清晰

const MetricsRecord* MetricsRecordRef::operator->() const
MetricsRecord* MetricsRecordRef::operator->()

2023-08-23 08:17 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +            std::make_shared<std::vector<std::pair<std::string, std::string>>>(labels));
把这个也using一下？叫MetricLabels？
std::vector<std::pair<std::string, std::string>>

2023-08-23 08:17 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +    while (mHead) {
lock

2023-08-23 08:17 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +        tmpHead = mHead;
tmpHead这个变量可以不用，我觉得把preTmp这个变量用好就行了，此时他就代表head

2023-08-23 08:17 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +MetricsRecord* ReadMetrics::GetHead() const {
如果不准改就返回const 指针

如果要提供能改的版本，就加个非const版本函数

2023-08-23 10:21 UTC, henryzhx8 requested changes

2023-08-23 10:21 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +    MetricNameValuePtr CreateGauge(const std::string& Name);
还是返回原类型

2023-08-23 10:21 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
删了吧

2023-08-23 10:21 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +    void Init(const std::vector<std::pair<std::string, std::string>>& labels);
```suggestion
    void Init(std::vector<std::pair<std::string, std::string>>&& labels);
```

2023-08-23 10:21 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +            std::make_shared<std::vector<std::pair<std::string, std::string>>>(labels));
```suggestion
        mMetrics = WriteMetrics::GetInstance()->CreateMetricsRecords(
            std::make_shared<std::vector<std::pair<std::string, std::string>>>(std::move(labels)));
```

2023-08-23 12:02 UTC, henryzhx8 requested changes
文件后都加上一行空行

2023-08-23 12:02 UTC, henryzhx8 commented on core/monitor/LogtaiMetric.cpp
> +}
这边和metricptr的init函数是不是调用顺序换换？

2023-08-23 12:02 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +    void Clear();
同前

2023-08-23 12:20 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +}
done

2023-08-23 12:21 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +}
done

2023-08-23 12:21 UTC, linrunqi08 commented on core/monitor/LogtaiMetric.cpp
> +}
done

2023-08-23 12:23 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +    MetricNameValuePtr CreateGauge(const std::string& Name);
done

2023-08-23 12:23 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +    const bool IsDeleted() const;
done

2023-08-24 02:34 UTC, yyuuttaaoo approved these changes

2023-08-24 05:19 UTC, henryzhx8 approved these changes

2023-08-24 05:55 UTC, merged