Fix host ip
alibaba/ilogtail pull request #1019
Opened 2023-07-18 07:16 UTC by TuShengTao

improve the logic for obtaining IP based on the hostname.

2023-07-18 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1019) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1019) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1019) it.</sub>

2023-07-19 07:57 UTC, yyuuttaaoo requested changes

2023-07-19 07:57 UTC, yyuuttaaoo commented on core/common/MachineInfoUtil.cpp
> +            tmpAddrPtr = &((struct sockaddr_in*)ifa->ifa_addr)->sin_addr;
可能需要先判断是否为null
The ifa_addr field points to a structure containing the interface
       address.  (The sa_family subfield should be consulted to
       determine the format of the address structure.)  This field may
       contain a null pointer.

2023-07-19 07:57 UTC, yyuuttaaoo commented on core/common/MachineInfoUtil.cpp
> +    getifaddrs(&ifAddrStruct);
缺少对应的freeifaddrs

2023-07-19 07:57 UTC, yyuuttaaoo commented on core/common/MachineInfoUtil.cpp
> +    std::map<std::string, std::string> ifaMap;
能否稍微再优化一下，复用一下这个map，在GetAnyAvailableIP直接使用，现在这样实现后代码重复了。

2023-07-19 08:49 UTC, TuShengTao commented on core/common/MachineInfoUtil.cpp
> +    std::map<std::string, std::string> ifaMap;
恩，我再看看；你意思是GetAnyAvailableIP里面复用GetNicIpv4Info 返回的map是吧

2023-07-27 03:49 UTC, yyuuttaaoo commented on core/common/MachineInfoUtil.cpp
> +    std::map<std::string, std::string> ifaMap;
是的

2023-08-08 13:39 UTC, yyuuttaaoo approved these changes

2023-08-08 13:47 UTC, yyuuttaaoo requested changes

2023-08-08 13:47 UTC, yyuuttaaoo commented on core/common/MachineInfoUtil.cpp
> -            if (!ip.empty() && !StartWith(ip, "127.")) {
这个逻辑是否完全和判断interface是lo等价？要不不要删掉，放到lo的判断后面？

2023-08-09 08:46 UTC, TuShengTao commented on core/common/MachineInfoUtil.cpp
> -            if (!ip.empty() && !StartWith(ip, "127.")) {
从 https://www.ietf.org/rfc/rfc3330.txt 来看 ，lo 逻辑的判断 对比 ip判空以及过滤 127.* 范围是大于的，代码语义上是等价的，lo过滤逻辑也过滤掉了ipv6的本地回环地址，不仅是ipv4的

2023-08-09 08:48 UTC, TuShengTao commented on core/common/MachineInfoUtil.cpp
> -            if (!ip.empty() && !StartWith(ip, "127.")) {
![image](https://github.com/alibaba/ilogtail/assets/50161350/9e18926d-2a83-4443-83cc-c63e9a7fe9dd)

2023-08-09 08:50 UTC, TuShengTao commented on core/common/MachineInfoUtil.cpp
> -            if (!ip.empty() && !StartWith(ip, "127.")) {
我目前考虑的是，如果放到lo判断的后面，会不会就是重复？

2023-09-26 07:22 UTC, yyuuttaaoo approved these changes

2023-09-26 07:22 UTC, merged