feat:parse nanosecond from log
alibaba/ilogtail pull request #1026
Opened 2023-07-24 04:07 UTC by Abingcbc

2023-07-26 12:32 UTC, messixukejia requested changes

2023-07-26 12:32 UTC, messixukejia commented on core/common/TimeUtil.cpp
> +const char* Strptime(const char* buf, const char* fmt, LogtailTime* ts, int32_t specifiedYear /* = -1 */) {
1、测试下100M/s，每条200字节场景下每条全量解析，跟 直接解析到s（相同s字符串匹配）的性能差异
2、如果差，需要考虑下优化方案
3、用例增加同一秒内不同ns测试场景

2023-07-26 12:34 UTC, messixukejia requested changes

2023-07-26 12:34 UTC, messixukejia commented on core/common/TimeUtil.cpp
>      if (!preciseTimestampConfig.enabled) {
preciseTimestampConfig.enabled 收一收，兼容代码，不要太发散了

2023-07-27 01:12 UTC, messixukejia requested changes

2023-07-27 01:12 UTC, messixukejia commented on core/common/TimeUtil.cpp
> +    struct tm* tm = &tm_;
做下bechmark比较下跟之前仅支持到s的性能差异
1、之前仅支持到s的代码
2、新代码只解析到s
3、新代码解析到%f

2023-07-27 03:17 UTC, Abingcbc commented on core/common/Strptime.cpp
> +        conv_nanosecond((const unsigned char*)(buf + 10), nanosecond);
unix 秒级时间戳的长度一定为10

2023-07-27 03:18 UTC, Abingcbc commented on core/common/Strptime.cpp
> +        if (NULL == localtime_r(&t, tm))
是的，这块在logtail代码已经有使用。https://github.com/alibaba/ilogtail/blob/657e3634ff29ffe5e502ef988859451f4692834a/core/common/TimeUtil.cpp#L42-L47

2023-08-09 05:47 UTC, messixukejia commented on core/parser/LogParser.cpp
> +        strptimeResult = Strptime(curTimeStr.c_str(), timeFormat, &logTime, nanosecondLength, specifiedYear);
在Strptime函数，注释说明返回值的意义吧。

2023-08-09 05:47 UTC, messixukejia commented on core/parser/LogParser.cpp
> +        Strptime(curTimeStr.substr(timeStr.length()).c_str(), "%f", &logTime, nanosecondLength);
这里不需要像495一样判断返回值？

2023-08-09 05:47 UTC, messixukejia commented on core/common/TimeUtil.cpp
> -    if (!preciseTimestampConfig.enabled) {
preciseTimestampConfig.enabled 尽量少一点

2023-08-09 05:47 UTC, messixukejia commented on core/common/TimeUtil.cpp
> +#include "common/Strptime.h"
1、s处理的性能测试
日志内容："2012-01-01 15:04:59"
时间格式："%Y-%m-%d %H:%M:%S"

2、行为的处理行为
2016/01/02 12:59:59.987654321 +0700 (UTC)    
%Y/%m/%d %H:%M:%S.%f %z (%Z)

3、完整pipeline的测试，特别是时区的处理

2023-08-09 05:51 UTC, messixukejia commented on core/parser/LogParser.cpp
> +    logTime.tv_sec = logTime.tv_sec - timeZoneOffsetSecond;
时区给下测试用例

2023-08-10 06:21 UTC, messixukejia commented on core/common/TimeUtil.cpp
> +    return the position of the parsing ends.
说明下解析失败的返回值

2023-08-10 07:48 UTC, messixukejia approved these changes

2023-08-14 03:05 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +                logTime.tv_sec = -1;
-1 or 0

2023-08-14 08:23 UTC, Abingcbc commented on core/common/Strptime.cpp
> +#endif
更新为了 master 版本里的 https://raw.githubusercontent.com/msys2/MINGW-packages/master/mingw-w64-libkml/strptime.c

2023-08-14 08:54 UTC, Abingcbc commented on core/reader/LogFileReader.cpp
> +                logTime.tv_sec = -1;
LogFileReader里的ParserLogTime只有在 LogIntegrity 里使用，应该之后会被弃用掉

2023-08-15 14:38 UTC, yyuuttaaoo requested changes

2023-08-15 14:38 UTC, yyuuttaaoo commented on core/common/Strptime.cpp
> +        n = strtoll(secondBuf, &cp, 10);
返回的cp指向已失效的临时变量。另外，如果串的长度<10有问题吗？

2023-08-16 02:43 UTC, yyuuttaaoo approved these changes

2023-08-16 02:44 UTC, merged