upload otel trace processor
alibaba/ilogtail pull request #1028
Opened 2023-07-25 14:06 UTC by qiansheng91

2023-08-01 08:47 UTC, messixukejia requested changes

2023-08-01 08:47 UTC, messixukejia commented on plugins/processor/otel/processor_otel_trace.go
> +		logger.Warningf(p.context.GetRuntimeContext(), "PROCESSOR_OTEL_TRACE_DATA_FORMAT", "data format is empty, use protobuf")
Format强依赖于输入的日志，不太适合默认protobuf吧。直接报错不加载是不是更好

2023-08-01 10:55 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlp_trace_parser.go
> +func ConvertTrace(td ptrace.Traces) ([]*protocol.Log, int) {
pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go里面有预留ConvertOtlpTraceV1的函数（最后几行），这边是不是可以统一一下？比如把两个文件合并起来，或者把函数名改一改？
![image](https://github.com/alibaba/ilogtail/assets/66948919/753faf7b-99e2-4e89-a50d-0cc5fecec29f)

2023-08-02 01:47 UTC, qiansheng91 commented on plugins/processor/otel/processor_otel_trace.go
> +		logger.Warningf(p.context.GetRuntimeContext(), "PROCESSOR_OTEL_TRACE_DATA_FORMAT", "data format is empty, use protobuf")
默认为空

2023-08-02 01:49 UTC, qiansheng91 commented on plugins/processor/otel/processor_otel_trace.go
> +		logger.Warningf(p.context.GetRuntimeContext(), "PROCESSOR_OTEL_TRACE_DATA_FORMAT", "data format is empty, use protobuf")
直接报错

2023-08-08 13:04 UTC, yyuuttaaoo commented on plugins/processor/otel/processor_otel_trace.go
> +		logger.Warningf(p.context.GetRuntimeContext(), "PROCESSOR_OTEL_TRACE_DATA_FORMAT", "data format is empty, use protobuf")
现在支持哪些类型？值判断空合理吗

2023-08-08 13:04 UTC, yyuuttaaoo commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go
otlp目录下2个文件名和其他的居然不一样风格

2023-08-09 06:37 UTC, qiansheng91 commented on docs/cn/data-pipeline/processor/processor-otel-trace.md
> +[Stable](../stability-level.md)
目前这个已经是稳定版本的

2023-08-09 06:46 UTC, qiansheng91 commented on plugins/processor/otel/processor_otel_trace.go
> +		logger.Warningf(p.context.GetRuntimeContext(), "PROCESSOR_OTEL_TRACE_DATA_FORMAT", "data format is empty, use protobuf")
目前主要是三类： protojson， json， protobuf， 默认为protobuf

2023-08-09 06:47 UTC, qiansheng91 commented on pkg/protocol/decoder/opentelemetry/otlp_trace_parser.go
> +func ConvertTrace(td ptrace.Traces) ([]*protocol.Log, int) {
这个目前还没有支持，等下个版本在调整

2023-08-09 11:50 UTC, messixukejia approved these changes

2023-08-09 11:55 UTC, merged