fix profile file name in container
alibaba/ilogtail pull request #1033
Opened 2023-08-01 02:30 UTC by linrunqi08

2023-08-01 05:39 UTC, messixukejia approved these changes

2023-08-01 05:39 UTC, messixukejia commented on core/profiler/LogFileProfiler.cpp
>                                              const std::string& filename,
加了realFilename后，filename是否就可以删掉了?

2023-08-01 05:39 UTC, messixukejia commented on core/profiler/LogFileProfiler.h
> +              mRealFilename(realFilename),
名字改下？  hostFileName？ 注释说明下差异

2023-08-01 09:02 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
>                                              const std::string& filename,
filename还是保留，跟原来字段语义一致，hostFileName新增字段

2023-08-01 09:12 UTC, yyuuttaaoo requested changes

2023-08-01 09:12 UTC, yyuuttaaoo commented on core/processor/LogProcess.cpp
> +                      ("project", projectName)("logstore", category)("filename", logPath)("realFilename", hostLogPath)("read_bytes", readBytes)(
这里还叫realFilename？变量又发明了一个hostLogPath，代码库中是否所有概念一样的的地方命名都保持一致？在reader中叫的是mDockerPath

2023-08-01 09:12 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
> +    contentPtr->set_value(statistic->mHostFilename.empty() ? "logstore_statistics" : statistic->mHostFilename);
不存在的时候，这个值还需要设置吗？

2023-08-01 09:13 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.h
> +              mRealFilename(realFilename),
done

2023-08-01 10:09 UTC, messixukejia commented on core/profiler/LogFileProfiler.cpp
>                                              const std::string& filename,
保留的意义是什么？

2023-08-02 06:51 UTC, linrunqi08 commented on core/processor/LogProcess.cpp
> +                      ("project", projectName)("logstore", category)("filename", logPath)("realFilename", hostLogPath)("read_bytes", readBytes)(
done，命名已统一

2023-08-02 06:51 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +    contentPtr->set_value(statistic->mHostFilename.empty() ? "logstore_statistics" : statistic->mHostFilename);
不需要，这里已修改

2023-08-02 07:32 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
>                                              const std::string& filename,
filename.empty()的判断 修改了。保留的话，主要还是为了兼容，因为有客户已经在用这个字段了，突然删掉或者改掉值的含义，可能会有问题。另外，filename本身也是有一定价值的，客户可以看到容器内的路径

2023-08-03 02:09 UTC, yyuuttaaoo approved these changes

2023-08-03 02:10 UTC, merged