fix filename mismatch for empty file inode reuse
alibaba/ilogtail pull request #1101
Opened 2023-08-30 04:46 UTC by yyuuttaaoo

2023-08-31 02:48 UTC, henryzhx8 requested changes

2023-08-31 02:48 UTC, henryzhx8 commented on core/reader/LogFileReader.cpp
> +    mRealLogPath = mHostLogPath;
这个先不要急着加吧,之前故意延迟赋值,不确定是不是有别的case会break掉

2023-08-31 06:03 UTC, messixukejia approved these changes

2023-09-03 03:27 UTC, henryzhx8 approved these changes

2023-09-03 12:05 UTC, merged