feat: plugin ProcessorParseTimestampNative
alibaba/ilogtail pull request #1105
Opened 2023-08-31 02:20 UTC by Abingcbc

2023-09-01 16:46 UTC, yyuuttaaoo requested changes

2023-09-01 16:46 UTC, yyuuttaaoo commented on core/processor/LogProcess.cpp
> +        if (enableTimestampNanosecond) {
&& logEvent.GetTimestampNanosecond() > 0

2023-09-01 16:46 UTC, yyuuttaaoo commented on core/processor/ProcessorParseTimestampNative.cpp
> +        sb.size = snprintf(sb.data, sb.capacity, "%lu", preciseTimestamp);
可能和20取一下min保险一些

2023-09-01 16:46 UTC, yyuuttaaoo commented on core/processor/ProcessorParseTimestampNative.cpp
> +    LogtailTime logTime = {0, 0};
这是cache的一部分？

2023-09-01 16:46 UTC, yyuuttaaoo commented on core/unittest/parser/LogTimeParserUnittest.cpp
>          time_t expectLogTimeBase = 1484147107;
224行不用base变量吗

2023-09-01 16:46 UTC, yyuuttaaoo commented on plugins/input/skywalkingv3/testdata/clr_metrics.json
这些样例都开启了EnableTimestampNanosecond吗？默认不是关闭么

2023-09-01 23:59 UTC, messixukejia requested changes

2023-09-01 23:59 UTC, messixukejia commented on core/config/UserLogConfigParser.cpp
> +        if (advancedVal.isMember("enable_timestamp_nanosecond") && advancedVal["enable_timestamp_nanosecond"].isBool()) {
是否记录到配置变更的表格里？

2023-09-01 23:59 UTC, messixukejia commented on core/common/TimeUtil.cpp
> -    if (BOOL_FLAG(enable_timestamp_nanosecond)) {
正常处理nanosecond也有0，需要加&& nanosecond != 0判断吗？@yyuuttaaoo

2023-09-01 23:59 UTC, messixukejia commented on core/processor/LogProcess.cpp
> +        if (enableTimestampNanosecond) {
set_time、set_time_ns应该是一个原子操作，统一改成SetLogTime。其他地方都检查下。

2023-09-01 23:59 UTC, messixukejia commented on core/processor/ProcessorSplitRegexNative.cpp
>          targetEvent->SetTimestamp(sourceEvent.GetTimestamp()); // it is easy to forget other fields, better solution?
targetEvent->SetTimestamp(sourceEvent.GetTimestamp()); // it is easy to forget other fields, better solution?
        targetEvent->SetTimestampNanosecond(sourceEvent.GetTimestampNanosecond());
合成一个函数？

2023-09-01 23:59 UTC, messixukejia commented on core/config/UserLogConfigParser.cpp
> +            cfg.mAdvancedConfig.mEnableTimestampNanosecond = GetBoolValue(advancedVal, "enable_timestamp_nanosecond");
不复用enable_precise_timestamp，新建一个是因为兼容性？

2023-09-01 23:59 UTC, messixukejia commented on core/common/LogtailCommonFlags.cpp
>  DEFINE_FLAG_BOOL(enable_root_path_collection, "", false);
是否往sls发送场景测试过？

2023-09-01 23:59 UTC, messixukejia commented on core/common/LogtailCommonFlags.cpp
>  DEFINE_FLAG_INT32(fuse_file_max_count, "max file total count from fuse root dir", 10000);
changelog

2023-09-01 23:59 UTC, messixukejia commented on core/parser/LogParser.cpp
> +        bool isTimestampNanosecond = (strcmp(timeFormat, "%s") == 0) && (curTimeStr.length() > timeStr.length());
如果开关没开，有配了%f，会是什么效果？

2023-09-01 23:59 UTC, messixukejia commented on core/common/TimeUtil.cpp
> +void SetLogTime(sls_logs::Log* log, time_t second, long nanosecond, bool ignoreNanosecond) {
![image](https://github.com/alibaba/ilogtail/assets/13250519/842bf5f3-d37e-4864-b5e1-ea64237d6741)
为什么调用点，全是默认值false？全开？

2023-09-02 03:32 UTC, messixukejia requested changes

2023-09-02 03:32 UTC, messixukejia commented on core/common/LogtailCommonFlags.cpp
>  DEFINE_FLAG_BOOL(enable_root_path_collection, "", false);
后端
1、支持ns集群
2、不支持ns集群

开关：功能开关

pipelie：c++ pipeline、go pipeline、老c++

发送的数据类型：采集的日志、监控日志

2023-09-02 03:32 UTC, messixukejia commented on core/common/LogtailCommonFlags.cpp
>  DEFINE_FLAG_BOOL(enable_root_path_collection, "", false);
所有调用SetLogTime需要给出是否需要ns，跟配置无关的是否必须发送ns？

2023-09-02 03:32 UTC, messixukejia commented on pluginmanager/plugin_runner_v1.go
>  							protocol.SetLogTime(l, uint32(nowTime.Unix()), uint32(nowTime.Nanosecond()))
stdoutstdout场景前端怎么配

老版，增加
![image](https://github.com/alibaba/ilogtail/assets/13250519/bbfe26e2-e301-4054-88ab-7e295b81488f)
新版？？

2023-09-02 03:36 UTC, messixukejia requested changes

2023-09-02 03:36 UTC, messixukejia commented on core/common/LogtailCommonFlags.cpp
>  DEFINE_FLAG_INT32(fuse_dir_max_depth, "max depth from fuse root dir", 100);
文档也需要改下

![image](https://github.com/alibaba/ilogtail/assets/13250519/72ed1003-ad3f-49ce-93c8-cf52cc972122)
这里面的EnablePreciseTimestamp参数，后面备注下已废弃。

2023-09-05 07:24 UTC, Abingcbc commented on core/processor/ProcessorParseTimestampNative.cpp
> +    LogtailTime logTime = {0, 0};
是的，上次解析出来的时间戳

2023-09-05 08:05 UTC, Abingcbc commented on core/config/UserLogConfigParser.cpp
> +            cfg.mAdvancedConfig.mEnableTimestampNanosecond = GetBoolValue(advancedVal, "enable_timestamp_nanosecond");
是的，两个字段表示填入的字段是不一样的。enable_precise_timestamp控制填入precise_timestamp_key，enable_timestamp_nanosecond控制填入pb的 TimeNs

2023-09-05 08:06 UTC, Abingcbc commented on core/parser/LogParser.cpp
> +        bool isTimestampNanosecond = (strcmp(timeFormat, "%s") == 0) && (curTimeStr.length() > timeStr.length());
解析了纳秒，但是不会填入到字段中

2023-09-06 02:12 UTC, Abingcbc commented on core/config/UserLogConfigParser.cpp
> +        if (advancedVal.isMember("enable_timestamp_nanosecond") && advancedVal["enable_timestamp_nanosecond"].isBool()) {
已经记录了

2023-09-06 04:12 UTC, Abingcbc commented on plugins/input/skywalkingv3/testdata/clr_metrics.json
感觉input和converter那边可能要默认开启纳秒，否则可能flusher那里填字段但是取不到值。如果关闭的话，在processor之后统一重置掉。

2023-09-07 15:44 UTC, yyuuttaaoo commented on core/models/MetricEvent.cpp
>  bool MetricEvent::FromJson(const Json::Value& root) {
为啥这个把nano给取消了？我看go那边好像有？

2023-09-07 15:44 UTC, yyuuttaaoo commented on core/models/SpanEvent.cpp
>      SetTimestamp(root["timestamp"].asInt64());
为啥给nano取消了？

2023-09-07 15:44 UTC, yyuuttaaoo commented on core/common/TimeUtil.cpp
> +void SetLogTime(sls_logs::Log* log, time_t second, long nanosecond) {
可以和Go统一一下SetLogTimeWithNano

2023-09-08 01:27 UTC, messixukejia commented on core/config/UserLogConfigParser.cpp
> +        if (advancedVal.isMember("enable_timestamp_nanosecond") && advancedVal["enable_timestamp_nanosecond"].isBool()) {
![image](https://github.com/alibaba/ilogtail/assets/13250519/d60d043b-2454-4991-8dc9-aba032e1ef81)
登记的名字都不一致？

2023-09-08 01:32 UTC, Abingcbc commented on core/config/UserLogConfigParser.cpp
> +        if (advancedVal.isMember("enable_timestamp_nanosecond") && advancedVal["enable_timestamp_nanosecond"].isBool()) {
统一成enable_timestamp_nanosecond了

2023-09-08 01:50 UTC, messixukejia commented on core/observer/network/NetworkObserver.cpp
> +        SetLogTime(&item, now.tv_sec);
这里确定不需要ns？

2023-09-08 01:50 UTC, messixukejia commented on pkg/protocol/sls_logs.pb.helper.go
> +func SetLogTimeWithNano(log *Log, second uint32, nanosecond uint32) {
SetLogTimeWithNano 都是处理的时候默认加ns，后面删除，注释说明下删除的地方

2023-09-08 01:50 UTC, messixukejia commented on pkg/helper/log_helper.go
> +	protocol.SetLogTime(&slsLog, uint32(t.Unix()))
这个文件里的三个函数都不统一？是不是都应该是ns

2023-09-08 02:19 UTC, messixukejia commented on pkg/protocol/sls_logs.pb.helper.go
> +func SetLogTimeWithNano(log *Log, second uint32, nanosecond uint32) {
C++ go

2023-09-08 02:20 UTC, messixukejia commented on core/observer/network/NetworkObserver.cpp
> +        SetLogTime(&item, now.tv_sec);
注释下 不动的原因

2023-09-08 02:24 UTC, messixukejia commented on pkg/helper/profile/pyroscope/jfr/jfr.go
> -			protocol.SetLogTime(log, uint32(startTime/1e9), uint32(startTime%1e9))
用户数据面

2023-09-11 01:59 UTC, yyuuttaaoo commented on core/processor/ProcessorParseTimestampNative.cpp
>          ++(*mHistoryFailures);
这个指标在新版也实现一下吧

2023-09-11 01:59 UTC, yyuuttaaoo commented on core/processor/ProcessorParseTimestampNative.cpp
> +        mProcDiscardRecordsTotal->Add(1);
解析失败目前是不会丢弃的，见ProcessorParseTimestampNative::ProcessEvent。可以加个通用的变量比如mDiscardParseFailure如果为true那么丢弃，但目前默认就是false，并且也不能改。

2023-09-12 06:59 UTC, yyuuttaaoo approved these changes

2023-09-12 07:57 UTC, messixukejia approved these changes

2023-09-12 07:58 UTC, merged