add metric to plugin demo
alibaba/ilogtail pull request #1106
Opened 2023-08-31 07:35 UTC by linrunqi08

2023-09-05 08:36 UTC, yyuuttaaoo requested changes

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/monitor/LogtailMetric.h
> +    void PreparePluginCommonLabels(MetricLabels& labels,
一般习惯是输入参数在前输出在后

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/monitor/MetricConstants.h
> +const std::string METRIC_PROC_IN_RECORDS_TOTAL = "proc_in_records_total";
.h中声明，.cpp中定义赋值。可以看原来的constants.h

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/processor/ProcessorParseRegexNative.cpp
> +    WriteMetrics::GetInstance()->PreparePluginCommonLabels(labels,
看起来这个方法是不是放到processor基类里面更方便？

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/processor/ProcessorParseRegexNative.cpp
> +                                                           PLUGIN_PROCESSOR_PARSE_REGEX_NATIVE);
少了个斜杠后的id维度？

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/processor/ProcessorParseRegexNative.cpp
> +    uint64_t startTime = GetCurrentTimeInMicroSeconds();
这个是不是应该基类来弄？

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/processor/ProcessorParseRegexNative.cpp
> +        mProcOutRecordsTotal->Add(1);
这些也是

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/processor/ProcessorParseRegexNative.cpp
> +    mProcInRecordsTotal->Add(1);
感觉discard需要processor自己做，in和out也是基类

2023-09-05 08:36 UTC, yyuuttaaoo commented on core/processor/ProcessorParseRegexNative.cpp
> +    mProcOutRecordsSizeBytes->Add(keyValueSize);
那个outsize发送打包有特殊用处所以+5，作为metric不该加

2023-09-05 15:04 UTC, linrunqi08 commented on core/monitor/LogtailMetric.h
> +    void PreparePluginCommonLabels(MetricLabels& labels,
done

2023-09-05 15:04 UTC, linrunqi08 commented on core/processor/ProcessorParseRegexNative.cpp
> +    uint64_t startTime = GetCurrentTimeInMicroSeconds();
done

2023-09-06 05:58 UTC, yyuuttaaoo commented on core/plugin/ProcessorInstance.cpp
> +    if (inited) {
反过来写，if (!inited) { return false; }
下面就不用缩进了

2023-09-06 05:58 UTC, yyuuttaaoo commented on core/plugin/ProcessorInstance.cpp
> +    mProcInRecordsTotal->Add(inSize);
大小是不是也在这里统计呢？可以假定PipelineEventGroup有一个virtual的EventsSizeBytes()方法，后面具体实现？

2023-09-06 05:58 UTC, yyuuttaaoo commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    SetMetricsRecordRef(Name(), GetProcessorInstance() == nullptr ? "" : GetProcessorInstance()->Id());
我觉得这里可以fast fail，如果没设置instance可以直接拒绝init

2023-09-06 05:58 UTC, yyuuttaaoo commented on core/plugin/ProcessorInstance.h
> +    ProcessorInstance() = default;
这个构造函数哪个需要用到？

2023-09-06 16:56 UTC, linrunqi08 commented on core/plugin/ProcessorInstance.cpp
> +    mProcInRecordsTotal->Add(inSize);
在PipelineEventGroup和PipelineEvent中预留了size的方法，后面实现了再加指标

2023-09-07 07:34 UTC, yyuuttaaoo approved these changes

2023-09-07 07:46 UTC, merged