Gcc 9.3.1 update
alibaba/ilogtail pull request #1108
Opened 2023-09-01 08:15 UTC by quzard

2023-09-01 08:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1108) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1108) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: quzard<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1108) it.</sub>

2023-09-01 15:46 UTC, yyuuttaaoo requested changes

2023-09-01 15:46 UTC, yyuuttaaoo commented on core/CMakeLists.txt
> +option(ENABLE_COMPATIBLE_MODE "Build Logtail in compatible mode (for low version Linux)" ON)
don't modify this

2023-09-01 15:46 UTC, yyuuttaaoo commented on core/deps/spdlog/sinks/rotating_file_sink-inl.h
内置的rotate on open不能用吗？能用就不用这个了

2023-09-01 15:46 UTC, yyuuttaaoo commented on .devcontainer/Dockerfile
> +FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail-build-linux:gcc_9.3.1_test
需要一个多架构的去掉_test的镜像

2023-09-01 15:46 UTC, yyuuttaaoo commented on core/observer/network/protocols/common.h
> +        if (true && sLogger->should_log(spdlog::level::trace)) {
Will the original code compile under 9.3.1?

2023-09-01 15:46 UTC, yyuuttaaoo commented on docker/Dockerfile.ilogtail-toolchain-linux
> +RUN yum makecache
is line 85 and 86 essential?

2023-09-01 15:46 UTC, yyuuttaaoo commented on docker/Dockerfile.ilogtail-toolchain-linux
> +RUN yum -y install curl-devel expat-devel gettext-devel openssl-devel perl-devel python3-devel zlib-devel \
is this required?

2023-09-01 15:46 UTC, yyuuttaaoo commented on docker/Dockerfile.ilogtail-toolchain-linux
> +RUN yum -y install epel-release centos-release-scl
please merge line 69 and 70 into one and append the following code to reduce the image size.
``` shell
&& yum -y clean all && rm -fr /var/cache && rm -rf /core.*
```

2023-09-01 15:46 UTC, yyuuttaaoo commented on scripts/gen_build_scripts.sh
> -ENABLE_COMPATIBLE_MODE=${ENABLE_COMPATIBLE_MODE:-OFF}
not required. the switch will be turn on in git workflow

2023-09-02 03:21 UTC, quzard commented on .github/workflows/build-core.yaml
> +    timeout-minutes: 100
一小时够了，我只是测试时怕超时，就都改高了。

2023-09-02 03:22 UTC, quzard commented on .github/workflows/build-core.yaml
> +      - name: clean
action会有几率报容量不够的错误。

2023-09-02 03:22 UTC, quzard commented on core/CMakeLists.txt
> +option(ENABLE_COMPATIBLE_MODE "Build Logtail in compatible mode (for low version Linux)" ON)
ok

2023-09-02 03:22 UTC, quzard commented on core/deps/spdlog/sinks/rotating_file_sink-inl.h
之前测试了一下，内置的rotate on open不能用。

2023-09-02 03:22 UTC, quzard commented on .devcontainer/Dockerfile
> +FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail-build-linux:gcc_9.3.1_test
ok

2023-09-04 06:57 UTC, quzard commented on core/observer/network/protocols/common.h
> +        if (true && sLogger->should_log(spdlog::level::trace)) {
不修改编译会不通过

2023-09-05 01:42 UTC, quzard commented on core/observer/network/protocols/common.h
> +        if (true && sLogger->should_log(spdlog::level::trace)) {
/workspaces/ilogtail_github/core/observer/network/protocols/common.h: In member function 'bool logtail::CommonCache<reqType, respType, aggregatorType, eventType, capacity>::TryStitcherByResp()':
/workspaces/ilogtail_github/core/observer/network/protocols/common.h:384:94: error: expression cannot be used as a function
  384 |                       ("head_req", this->mHeadRequestsIdx)("tail_req", this->mTailRequestsIdx)(
      |                                                                                              ^
/workspaces/ilogtail_github/core/observer/network/protocols/common.h:383:13: error: there are no arguments to 'LOG_TRACE' that depend on a template parameter, so a declaration of 'LOG_TRACE' must be available [-fpermissive]
  383 |             LOG_TRACE(sLogger,
      |             ^~~~~~~~~
/workspaces/ilogtail_github/core/observer/network/protocols/common.h:383:13: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)

2023-09-05 13:10 UTC, messixukejia approved these changes

2023-09-07 02:10 UTC, yyuuttaaoo approved these changes

2023-09-07 13:38 UTC, merged