WIP feat: plugin ProcessorParseApsaraNative
alibaba/ilogtail pull request #1113
Opened 2023-09-04 02:23 UTC by Abingcbc

2023-09-07 16:25 UTC, yyuuttaaoo requested changes

2023-09-07 16:25 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +static const int32_t MAX_BASE_FIELD_NUM = 10;
LogParser::MAX_BASE_FIELD_NUM 和这个关系是啥，感觉都用了

2023-09-07 16:25 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +        ++(*mParseFailures);
这应该是mHistoryFailures

2023-09-07 16:25 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    if (mAdjustApsaraMicroTimezone) {
记个todo，后面这个参数废弃

2023-09-07 16:25 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    time_t logTime = ApsaraEasyReadLogTimeParser(buffer, timeStrCache, lastLogTime, logTime_in_micro);
看明白了，这个的恶心之处在于，有可能有2种格式。
有2个问题
1. 是否应该单独作为一个ProcessorParseApsaraTimestampNative？
2. 实现能否复用Strptime？

2023-09-07 16:31 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    int beg_index = 0;
这个变量无用

2023-09-08 01:54 UTC, messixukejia commented on core/processor/ProcessorParseApsaraNative.cpp
> +    // TODO set miscrosecond logTime_in_micro * 1000 % 1000000000
这个依赖ns那个合入？

2023-09-08 06:26 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
> +                    "content" : "[2023-09-04 13:15:04.862181]\t[info]\t[385658]\t/ilogtail/AppConfigBase.cpp:100\t\tAppConfigBase AppConfigBase:success",
解析后content是不是应该没了？
这个功能和上报rawlog的功能一起看一下是否实现正确。
参考core/processor/ProcessorParseRegexNative.cpp:92-105，1.x保持bug行为，2.0 fix，可以注释里也写一下

2023-09-08 06:28 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
> +void ProcessorParseApsaraNativeUnittest::TestProcessWholeLine() {
这个parser自带时间，正常的可能问题不大，主要可以测一下异常情况会不会挂，比如意外截断
[2023-09-04 13:15:0
[2023-09-04 13:15:0[info

2023-09-13 18:05 UTC, Abingcbc commented on core/processor/ProcessorParseApsaraNative.cpp
> +    time_t logTime = ApsaraEasyReadLogTimeParser(buffer, timeStrCache, lastLogTime, logTime_in_micro);
复用Strptime简化了解析时间戳的逻辑

2023-09-18 05:45 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    mUploadRawLog = componentConfig.GetConfig().mUploadRawLog;
这个功能实现了吗？

2023-09-19 06:10 UTC, Abingcbc commented on core/processor/ProcessorParseApsaraNative.cpp
> +    // int32_t beginIndexArray[LogParser::MAX_BASE_FIELD_NUM] = {0};
gcc4编译 LogParser::MAX_BASE_FIELD_NUM 有问题，忘记改回来了

2023-09-19 07:37 UTC, yyuuttaaoo approved these changes

2023-09-19 07:38 UTC, merged