init checkpoint
alibaba/ilogtail pull request #1119
Opened 2023-09-07 08:31 UTC by Takuka0311

2023-09-09 02:43 UTC, messixukejia requested changes

2023-09-09 02:43 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +            LOG_WARNING(sLogger, ("get all adhoc checkpoint files", "failed"));
涉及失败可能的函数加返回码，这里return

2023-09-09 02:43 UTC, messixukejia commented on core/checkpoint/AdhocJobCheckpoint.h
> +    bool UpdateAdhocFileCheckpoint(AdhocFileCheckpointKey adhocFileCheckpointKey, AdhocFileCheckpointPtr adhocFileCheckpointPtr);
不变用const
结构体用*

2023-09-09 02:43 UTC, messixukejia commented on core/checkpoint/AdhocJobCheckpoint.cpp
> +        std::ifstream ifs("json_file.json");
这个是做什么的

2023-09-09 02:43 UTC, messixukejia commented on core/input/InputStaticFile.cpp
> +    mAdhocFileManager->Run();
mAdhocFileManager是个单例，每个InputStaticFile类都run？

代码的逻辑层次要明确

2023-09-09 02:46 UTC, messixukejia commented on core/CMakeLists.txt
>  set(SUB_DIRECTORIES_LIST
自己好好思考下那里是并发的，怎么保证效率

2023-09-09 02:47 UTC, messixukejia commented on core/unittest/checkpoint/AdhocCheckpointManagerUnittest.cpp
> +
UT测试要有条理性，先把测试设计给下

2023-09-09 02:51 UTC, messixukejia commented on core/checkpoint/AdhocJobCheckpoint.cpp
> +        mCurrentFileIndex++;
mCurrentFileIndex 放在这里可能不是太好，不符合功能单一的原则

2023-09-18 05:04 UTC, henryzhx8 requested changes

2023-09-18 05:37 UTC, Takuka0311 commented on core/event/Event.h
> +#define EVENT_STATIC_FILE (1024)
这个是之前临时加的，后面和reader一起重写

2023-09-18 05:38 UTC, Takuka0311 commented on core/checkpoint/AdhocFileCheckpoint.h
> +    int64_t mFileSize;
标记这个文件已经读完了

2023-09-18 06:27 UTC, Takuka0311 commented on core/checkpoint/AdhocFileCheckpoint.h
> +    std::mutex mMutex;
精简了一下

2023-09-18 06:27 UTC, Takuka0311 commented on core/checkpoint/AdhocJobCheckpoint.h
> +    std::string mStorePath;
我放这里主要是希望job级别的文件管理与Manager无关，可以再讨论一下

2023-09-19 02:40 UTC, messixukejia requested changes

2023-09-19 02:40 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +    LOG_WARNING(sLogger, ("AdhocCheckpointManager", "Exit"));
什么场景会到这行日志？还打了一个warning

2023-09-19 02:40 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +/*
冲突处理下

2023-09-19 02:40 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +        for (auto& p : mAdhocJobCheckpointMap) {
mAdhocJobCheckpointMap 不涉及锁？

2023-09-19 03:34 UTC, messixukejia requested changes

2023-09-19 03:34 UTC, messixukejia commented on core/checkpoint/AdhocJobCheckpoint.cpp
> +int32_t AdhocJobCheckpoint::GetCurrentFileIndex() {
直接返回结果，AdhocFileManager不需要再保存mJobFileLists

2023-09-19 03:34 UTC, messixukejia commented on core/file_server/AdhocFileManager.cpp
> +    // ReadFile(ev, fileCpPtr);
文件不存在的衔接，这里需要注意下

2023-09-20 01:21 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +DEFINE_FLAG_STRING(adhoc_check_point_file_dir, "", "/tmp/logtail_adhoc_checkpoint");
没解决前不要关掉

2023-09-20 01:25 UTC, messixukejia commented on core/checkpoint/AdhocJobCheckpoint.cpp
> +void AdhocJobCheckpoint::AddFileCheckpoint(AdhocFileCheckpointPtr fileCheckpoint) {
入口都收到manager了，这里还会并行吗？

2023-09-20 02:19 UTC, Takuka0311 commented on core/checkpoint/AdhocJobCheckpoint.cpp
> +void AdhocJobCheckpoint::AddFileCheckpoint(AdhocFileCheckpointPtr fileCheckpoint) {
哦不会，这里只在Job初始化的时候调用，不会和其他函数并行。已修改

2023-09-20 08:13 UTC, messixukejia requested changes

2023-09-20 08:13 UTC, messixukejia commented on core/checkpoint/AdhocJobCheckpoint.cpp
> +        mFileCount = root["job_file_count"].asInt();
测试下字段不存在时直接下标访问的效果

2023-09-20 08:13 UTC, messixukejia commented on core/checkpoint/AdhocJobCheckpoint.cpp
> +bool AdhocJobCheckpoint::Load(const std::string& path) {
path是不是应该是AdhocJob的固有属性，而不是每次传入

2023-09-20 08:13 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +            jobCheckpoint->AddFileCheckpoint(fileCheckpoint);
统一把锁收到manager这一层，要不然内外两层都有锁，容易死锁

2023-09-20 08:13 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +    AdhocJobCheckpointPtr jobCheckpoint = GetAdhocJobCheckpoint(jobName);
先简单点，整体入口加锁吧。整个机制基本都是穿行的，不会有很多的锁竞争

2023-09-20 08:13 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +            p.second->Dump(GetJobCheckpointPath(p.second->GetJobName()));
Dump内部可以加下时间间隔控制，如果小文件采集文件结束的dump已经足够（小于5s）或者是边界值，不需要这个5s兜底

2023-09-20 08:13 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.h
> +
这些接口确认下哪些可以是private的。

一个接口同时private跟public，锁不好控制。

2023-09-20 09:09 UTC, Takuka0311 commented on core/checkpoint/AdhocCheckpointManager.cpp
> +            p.second->Dump(GetJobCheckpointPath(p.second->GetJobName()));
done

2023-09-20 09:38 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +DEFINE_FLAG_STRING(adhoc_check_point_file_dir, "", "/tmp/logtail_adhoc_checkpoint");
ok，正式发布前是要改掉的

2023-09-20 10:19 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +                                                 std::vector<AdhocFileCheckpointPtr> fileCheckpointList) {
分两阶段用两个锁，GetAdhocJobCheckpoint获取到后，可能会被释放掉，再往后访问就有问题了

2023-09-20 10:43 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +                mAdhocJobCheckpointMap[job] = jobCheckpoint;
都不需要锁？

2023-09-20 10:52 UTC, Takuka0311 commented on core/checkpoint/AdhocCheckpointManager.cpp
> +                mAdhocJobCheckpointMap[job] = jobCheckpoint;
Load只在logtail启动的过程中执行一次，这个时候其他部分还没开始工作，不许要加锁

2023-09-20 10:52 UTC, Takuka0311 commented on core/checkpoint/AdhocCheckpointManager.cpp
> +                                                 std::vector<AdhocFileCheckpointPtr> fileCheckpointList) {
没有太明白是什么问题。
这里预期读出来是nullptr，然后新建AdhocJobCheckpoint并返回。如果是读出来有值，进入下面语句前被释放，那还会新建一个AdhocJobCheckpoint并返回。这两种情况都会返回正常的值且jobName一致。

2023-09-20 12:35 UTC, messixukejia commented on core/checkpoint/AdhocCheckpointManager.cpp
> +                                                 std::vector<AdhocFileCheckpointPtr> fileCheckpointList) {
先get出来，被其他线程删掉，然后本线程继续处理之前读出来的

2023-09-21 11:13 UTC, messixukejia commented on core/logtail.cpp
> +    AdhocCheckpointManager::GetInstance()->LoadAdhocCheckpoint();
这里先注释掉，不要有直接的接口调用

2023-09-21 11:23 UTC, Takuka0311 commented on core/logtail.cpp
> +    AdhocCheckpointManager::GetInstance()->LoadAdhocCheckpoint();
done

2023-09-21 11:31 UTC, messixukejia approved these changes

2023-09-21 11:33 UTC, henryzhx8 approved these changes

2023-09-21 12:22 UTC, merged