feat: plugin ProcessorParseJsonNative
alibaba/ilogtail pull request #1124
Opened 2023-09-13 13:11 UTC by quzard

2023-09-14 14:58 UTC, messixukejia commented
@yyuuttaaoo 重点review下吧

2023-09-18 06:13 UTC, yyuuttaaoo requested changes

2023-09-18 06:13 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
> +void ProcessorParseJsonNativeUnittest::TestProcessJson() {
测试一下key里面有__raw__的情况，验证处理结果符合预期

2023-09-18 06:13 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
> +    std::string inJson = R"({
outJson呢？

2023-09-18 06:52 UTC, quzard commented on core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
> +    std::string inJson = R"({
在下面的expectValue

2023-09-19 02:47 UTC, yyuuttaaoo commented on core/processor/ProcessorParseJsonNative.cpp
> +    PipelineConfig config = componentConfig.GetConfig();
使用引用

2023-09-19 02:47 UTC, yyuuttaaoo commented on core/processor/ProcessorParseJsonNative.cpp
> +
不要多余空行

2023-09-19 03:21 UTC, yyuuttaaoo commented on core/processor/ProcessorParseJsonNative.cpp
> +        StringBuffer contentKeyBuffer = sourceEvent.GetSourceBuffer()->CopyString(contentKey);
这个地方有没有可能优化一下，一次性把rapidjson的char* 复制到stringbuffer中

2023-09-19 03:25 UTC, yyuuttaaoo commented on core/processor/ProcessorParseJsonNative.cpp
> +        StringBuffer contentKeyBuffer = sourceEvent.GetSourceBuffer()->CopyString(contentKey);
这个地方有没有可能优化一下，一次性把rapidjson的char* 复制到stringbuffer中

2023-09-19 05:52 UTC, yyuuttaaoo approved these changes

2023-09-19 05:52 UTC, merged