feat: cache incomplete line in memory to avoid repeat read from disk
alibaba/ilogtail pull request #1142
Opened 2023-09-20 15:16 UTC by yyuuttaaoo

2023-09-20 16:08 UTC, messixukejia commented on core/processor/ProcessorParseDelimiterNative.cpp
> +                    memcpy(extraFields, columnValues[i].data(), columnValues[i].size());
拷贝目的是char*，不涉及结尾\0 +1的问题？

2023-09-20 16:11 UTC, messixukejia commented on core/reader/LogFileReader.cpp
> +        memcpy(stringBuffer, mCache.data(), lastCacheSize); // copy from cache
结尾\0 +1问题

2023-09-21 03:10 UTC, yyuuttaaoo commented on core/processor/ProcessorParseDelimiterNative.cpp
> +                    memcpy(extraFields, columnValues[i].data(), columnValues[i].size());
不应该copy \0，是多个字符串接起来的，大小由len或者size控制。buffer申请时已经有\0在尾部保护了，是否越界总是需要程序逻辑自己保证的。

2023-09-21 03:10 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +        memcpy(stringBuffer, mCache.data(), lastCacheSize); // copy from cache
不应该copy \0，是多个字符串接起来的，大小由len或者size控制。buffer申请时已经有\0在尾部保护了，是否越界总是需要程序逻辑自己保证的。

2023-09-21 03:12 UTC, yyuuttaaoo commented on core/reader/LogFileReader.h
> +    bool HasDataInCache() const { return mCache.size(); }
这里函数名称比较明显，应该不会导致看不明白。

2023-09-21 03:42 UTC, messixukejia commented on core/reader/LogFileReader.h
> +    inline int64_t LastReadPos() const { // pos read but may not consumed, used for read needed
函数命名改成前面加个动词

2023-09-21 03:42 UTC, messixukejia commented on core/reader/LogFileReader.cpp
> +        READ_BYTE -= lastCacheSize; // reserve space to copy from cache if needed
防止负数

2023-09-21 03:50 UTC, messixukejia requested changes

2023-09-21 03:50 UTC, messixukejia commented on core/unittest/reader/LogFileReaderUnittest.cpp
> +    }
配置变更场景模拟下用例，在checkpoint中，恢复后继续能够读取，保证数据连续性

2023-09-21 03:53 UTC, messixukejia requested changes

2023-09-21 03:53 UTC, messixukejia commented on core/unittest/reader/LogFileReaderUnittest.cpp
> +        APSARA_TEST_GE_FATAL(reader.mCache.size(), 0UL);
第一次读有缓存，第二次读续上这种是不是没有用例？

2023-09-22 07:55 UTC, messixukejia approved these changes

2023-09-22 08:05 UTC, merged