Add logtail config tag
alibaba/ilogtail pull request #1147
Opened 2023-09-22 08:28 UTC by Takuka0311

2023-09-24 13:28 UTC, messixukejia requested changes

2023-09-24 13:28 UTC, messixukejia commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +	if err == nil {
![image](https://github.com/alibaba/ilogtail/assets/13250519/b40922c0-58df-46f4-b66d-27beecc34150)
err指向不明

2023-09-24 13:31 UTC, messixukejia requested changes

2023-09-24 13:31 UTC, messixukejia commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +			err = o.TagMachineGroup(project, machineGroup, "sls.machinegroup.deploy_mode", "deamonset")
@linrunqi08 确认下是否一定是deamonset机器组

2023-10-03 01:01 UTC, linrunqi08 commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +	for k, v := range config.ConfigTags {
一样的问题，接口改成多个tag

2023-10-08 05:17 UTC, linrunqi08 commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +			err = o.TagMachineGroup(project, machineGroup, "sls.machinegroup.deploy_mode", "deamonset")
一定是的，statefulset不会扫描env的

2023-10-08 05:20 UTC, linrunqi08 commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +				err = o.TagMachineGroup(project, machineGroup, "sls.machinegroup.deploy_mode", "deamonset")
常量抽一下

2023-10-08 05:20 UTC, linrunqi08 commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +	logtailConfigTags["sls.logtail.channel"] = "ENV"
同上

2023-10-08 07:02 UTC, linrunqi08 approved these changes

2023-10-10 12:51 UTC, messixukejia approved these changes

2023-10-10 14:35 UTC, yyuuttaaoo approved these changes

2023-10-10 14:36 UTC, merged