fix: log model bug fix && build script optimize
alibaba/ilogtail pull request #1154
Opened 2023-09-25 02:37 UTC by snakorse

1. do not copy libzstd if target already exists
2. support LDFLAGS when build go plugins
3. fix bug that extract tags error

2023-09-26 06:11 UTC, yyuuttaaoo requested changes

2023-09-26 06:11 UTC, yyuuttaaoo commented on pluginmanager/plugin_runner_v2.go
> +		log.Timestamp = uint64(*in.Log.TimeNs)
这里不太对，timens只有纳秒部分

2023-09-26 06:11 UTC, yyuuttaaoo commented on scripts/plugin_build.sh
> +LDFLAGS=$LDFLAGS'-X "github.com/alibaba/ilogtail/pluginmanager.BaseVersion='$VERSION'"'
是不是应该这样LDFLAGS="${GO_LDFLAGS:-}"' -X "github.com/alibaba/ilogtail/pluginmanager.BaseVersion='$VERSION'"'
引号、空格

2023-09-26 06:11 UTC, yyuuttaaoo commented on scripts/plugin_build.sh
> +if [[ ! -f "$lib_name" ]]; then
这个不要改，不是所有编译机都能用预编译的lib

2023-09-27 08:23 UTC, snakorse commented on pluginmanager/plugin_runner_v2.go
> +		log.Timestamp = uint64(*in.Log.TimeNs)
timeNs是不够1秒的纳秒部分？

2023-09-27 08:54 UTC, snakorse commented on scripts/plugin_build.sh
> +LDFLAGS=$LDFLAGS'-X "github.com/alibaba/ilogtail/pluginmanager.BaseVersion='$VERSION'"'
嗯 我改下

2023-09-27 08:55 UTC, snakorse commented on scripts/plugin_build.sh
> +if [[ ! -f "$lib_name" ]]; then
ok

2023-10-04 15:21 UTC, yyuuttaaoo commented on pluginmanager/plugin_runner_v2.go
> +		log.Timestamp = uint64(*in.Log.TimeNs)
是的

2023-10-04 15:24 UTC, yyuuttaaoo commented on pluginmanager/plugin_runner_v2.go
> +	case in.Log.Time != 0:
是不是还是if else清晰点。。

2023-10-08 08:29 UTC, snakorse commented on pluginmanager/plugin_runner_v2.go
> +	case in.Log.Time != 0:
ok

2023-10-10 13:51 UTC, yyuuttaaoo approved these changes

2023-10-10 13:52 UTC, merged