新增UsingOldContentTag，go插件tag不平铺到 log content里
alibaba/ilogtail pull request #1169
Opened 2023-10-08 12:05 UTC by quzard

2023-10-09 14:04 UTC, messixukejia requested changes

2023-10-09 14:04 UTC, messixukejia commented on core/config/Config.h
>          bool mEnablePreciseTimestamp = false;
需要企业版端到端测试，设计用例给下吧

2023-10-09 14:27 UTC, messixukejia commented on plugins/aggregator/context/aggregator_context.go
1. 对应的send函数，考虑使用PostLogPackageList，多个包合并一个包list发送。 ---这个怎么考虑的，好像没看到相关代码

2023-10-09 14:30 UTC, messixukejia commented on plugins/aggregator/context/aggregator_context.go
>  	nowLogGroup := logGroupList[len(logGroupList)-1]
ut补充

2023-10-10 03:21 UTC, henryzhx8 requested changes

2023-10-10 03:21 UTC, henryzhx8 commented on plugins/aggregator/context/aggregator_context.go
> +	}
这一块的性能需要考虑，建议先去掉，因为同一个source的日志对应的tag会不一致的情况很少见，可以在以后有需要的时候再添加。

2023-10-12 12:03 UTC, quzard commented on core/config/Config.h
> +        bool mUsingOldContentTag = false;
该字段只有新版前端来取时才会有，前端支持更改。

2023-10-19 02:27 UTC, yyuuttaaoo requested changes

2023-10-19 02:27 UTC, yyuuttaaoo commented on pluginmanager/logstore_config.go
> +func extractTagsToLogTags(rawTags []byte, logTags []*protocol.LogTag) []*protocol.LogTag {
ut

2023-10-19 02:27 UTC, yyuuttaaoo commented on plugins/aggregator/context/aggregator_context.go
> +	p.logGroupPoolSize += logSize
144那里发送的-=

2023-10-19 02:27 UTC, yyuuttaaoo commented on plugins/aggregator/context/aggregator_context.go
> +				if err = p.queue.Add(logGroup); err != nil {
retryforever抽取一个函数

2023-10-19 02:27 UTC, yyuuttaaoo commented on pluginmanager/logstore_config.go
> +func extractTagsToLogTags(rawTags []byte, logTags []*protocol.LogTag) []*protocol.LogTag {
说明一下用途

2023-10-19 02:27 UTC, yyuuttaaoo commented on plugins/aggregator/context/aggregator_context.go
> +	// when logGroupPoolMap is full
这里和138的写清楚注释

2023-10-19 02:27 UTC, yyuuttaaoo commented on pluginmanager/plugin_runner_v1.go
> +			if err := loadAggregator("aggregator_default", p.LogstoreConfig, nil); err != nil {
直接把default改成context吧，2.0后面上下文预览就全局修复了

2023-10-23 09:22 UTC, quzard commented on plugins/aggregator/context/aggregator_context.go
>  		logGroupList = make([]*protocol.LogGroup, 0, p.MaxLogGroupCount)
这次改动不影响上下文预览的功能

2023-10-24 02:23 UTC, yyuuttaaoo requested changes

2023-10-24 02:23 UTC, yyuuttaaoo commented on plugins/aggregator/context/aggregator_context.go
> +	p.logGroupPoolMap = make(map[string][]LogGroupWithSize)
更新logGroupPoolSize

2023-10-24 02:23 UTC, yyuuttaaoo commented on plugins/aggregator/context/aggregator_context.go
> +		for _, logGroup := range logGroupList {
这是不是不用改？反正外面会弄

2023-10-24 02:23 UTC, yyuuttaaoo commented on plugins/aggregator/context/aggregator_context.go
> +		logGroupPoolMap:                  make(map[string][]LogGroupWithSize),
*LogGroupWithSize

2023-10-24 02:23 UTC, yyuuttaaoo commented on plugins/aggregator/context/aggregator_context.go
> +func (p *AggregatorContext) newLogGroupWithSize(pack string, topic string) LogGroupWithSize {
*LogGroupWithSize

2023-10-24 11:59 UTC, quzard commented on core/config/Config.h
>          bool mEnablePreciseTimestamp = false;
input_docker_static_file/ilogtail-e2e.yaml 和 input_static_file/ilogtail-e2e.yaml 这两个e2e刚好覆盖到这个场景

2023-10-24 12:03 UTC, quzard commented on plugins/aggregator/context/aggregator_context.go
> +		for _, logGroup := range logGroupList {
这里需要改，传出去的需要为[]*protocol.LogGroup

2023-10-24 12:04 UTC, quzard commented on pluginmanager/plugin_runner_v1.go
>  	if len(p.AggregatorPlugins) == 0 {
https://github.com/alibaba/ilogtail/issues/1198

2023-10-24 12:05 UTC, quzard commented on core/config/Config.h
>          uint16_t mSearchCheckpointDirDepth = 0; // Max directory depth when search checkpoint.
发版前需要更新advanced和global相关文档

2023-10-25 03:44 UTC, yyuuttaaoo approved these changes

2023-10-25 09:25 UTC, messixukejia approved these changes

2023-10-25 09:27 UTC, messixukejia approved these changes

2023-10-25 10:53 UTC, henryzhx8 approved these changes

2023-10-25 10:57 UTC, merged