complete pipeline definition (#1185)
alibaba/ilogtail pull request #1188
Opened 2023-10-18 07:48 UTC by henryzhx8

* add common param extractor

* add input_file

* add input_observer_network

* add flusher_SLS

* add global config module

* improve pipeline def

2023-10-28 13:07 UTC, messixukejia requested changes

2023-10-28 13:07 UTC, messixukejia commented on core/pipeline/PipelineContext.cpp
> +const string& PipelineContext::GetProjectName() const {
Project、logstore这种跟sls强相关的概念，是否有比较简便的方法从pipeline剥离出来？工作量大的话，就还是维持现状吧。

2023-10-28 13:07 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +            detail["SplitChar"] = Json::Value('\0');
为什么pipeline文件，还保留了这么多config解析的逻辑，不都应该在InputFile等文件中吗

2023-10-30 09:16 UTC, henryzhx8 commented on core/reader/LogFileReader.cpp
> -DEFINE_FLAG_INT32(delay_bytes_upperlimit,
这个最后会统一去掉，现在留着是为了方便看哪些代码移动过了

2023-10-30 09:19 UTC, henryzhx8 commented on core/common/ParamExtractor.h
> +                if (!it->isBool()) {
if constexpr是编译期if，模版实例化的时候编译器会只保留命中的分支

2023-10-30 09:19 UTC, henryzhx8 commented on core/config/NewConfig.cpp
> +bool NewConfig::Parse() {
这个最终会替换现有的Config，目前中间阶段先随便起一个名字过渡一下

2023-10-30 09:20 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +            detail["SplitChar"] = Json::Value('\0');
一些pipeline级别的特殊逻辑还是需要放在pipeline里，比如这里额外添加一个内置的processor

2023-10-30 09:22 UTC, henryzhx8 commented on core/pipeline/PipelineContext.cpp
> +const string& PipelineContext::GetProjectName() const {
sls强相关的内容目前直接用flusherSLS结构体放在context里，这里过渡阶段仍然显式指定project等信息，要彻底剥离可能有点难度，需要以后再弄

2023-11-07 11:59 UTC, yyuuttaaoo commented on core/common/ParamExtractor.h
> +bool GetOptionalBoolParam(const Json::Value& config, const std::string& key, bool& param, std::string& errorMsg);
这些为啥就不像GetOptionalListParam一样用个模版了呢？好像也可以是GetOptionalParam<T>

2023-11-07 12:21 UTC, yyuuttaaoo commented on core/config/NewConfig.cpp
> +    if (mHasNativeFlusher && mHasGoFlusher && !ShouldNativeFlusherConnectedByGoPipeline()) {
一个FileInput+一个正则提取+一个slsFlusher+一个stdout行不行

2023-11-07 13:00 UTC, yyuuttaaoo commented on core/file_server/FileDiscoveryOptions.cpp
> +        PARAM_WARNING_DEFAULT(ctx.GetLogger(), errorMsg, false, pluginName, ctx.GetConfigName());
实际运行的时候，此类用default值的warning会不会很多？超过必要吗?

2023-11-07 13:13 UTC, yyuuttaaoo commented on core/plugin/interface/Plugin.h
> +    const PipelineContext& GetContext() const { return *mContext; }
因为context里面有一些logger什么的，要调用的话不能是const的，所以本来也没加const，否则context的用途会大打折扣

2023-11-07 13:26 UTC, yyuuttaaoo commented on core/pipeline/Pipeline.cpp
> +        if (!mGoPipelineWithoutInput.isNull()) {
和上面那段可以复用一下代码

2023-11-07 13:29 UTC, yyuuttaaoo commented on core/pipeline/PipelineContext.h
> +    bool IsFirstProcessorJson() const { return mIsFirstProcessorJson; }
这种多了之后，感觉mContext好像有了config的感觉，pipeline里面要不要有一个config的shared_ptr与context共享一些类似global config的东西

2023-11-08 04:08 UTC, yyuuttaaoo commented
3个未resolve的在后续PR解决

2023-11-08 04:08 UTC, yyuuttaaoo approved these changes

2023-12-08 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1188) <br/>All committers have signed the CLA.

2023-12-18 07:18 UTC, yyuuttaaoo commented on core/file_server/FileServer.cpp
> +    ConfigManager::GetInstance()->RegisterHandlers();
这里可能卡很久，建议前后打关键日志

2023-12-18 08:24 UTC, yyuuttaaoo commented on core/pipeline/PipelineManager.cpp
> +        DecreasePluginUsageCnt(mPipelineNameEntityMap[config.mName]->GetPluginStatistics());
Increase可以从build函数里拿出来，显得对称一些

2023-12-18 08:39 UTC, yyuuttaaoo commented on core/pipeline/PipelineManager.cpp
> +    // 过渡使用
可以说明一下非mUnchanged的，都在BuildPipeline中Load过了

2023-12-23 02:26 UTC, henryzhx8 commented on core/CMakeLists.txt
> -message(STATUS "Git hash: ${LOGTAIL_GIT_HASH}")
这个跑options.cmake里了

2023-12-23 02:26 UTC, henryzhx8 commented on .gitignore
> +CTestTestfile.cmake
cmake的gitignore模版里默认带的

2023-12-23 02:29 UTC, henryzhx8 commented on core/common/LogtailCommonFlags.cpp
> +// 商业版
不删，这个clean工作专门开一个pr，留一个版本万一以后遇到什么事情方便查询

2023-12-23 15:58 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +        AddLog(mCommonParserOptions.mRenamedSourceKey, buffer, sourceEvent, false);
mRenamedSourceKey现在新的key和解析出来数据冲突了，看来是优先的，这个行为是所有插件统一的吗？有地方说明解析出的key和keepSource几个key的优先级么？

2023-12-24 08:39 UTC, messixukejia approved these changes

2023-12-24 08:40 UTC, messixukejia commented
需要加下changlog

2023-12-24 14:48 UTC, merged