Support SPL
alibaba/ilogtail pull request #1193
Opened 2023-10-23 06:15 UTC by linrunqi08

2023-10-23 12:33 UTC, yyuuttaaoo requested changes

2023-10-23 12:33 UTC, yyuuttaaoo commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +    mRowSize = header.rowSize;
直接保留header的ptr

2023-10-23 12:33 UTC, yyuuttaaoo commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        mLogGroupList->at(logGroupKeyIdx).SetTag(StringView(mColumnNames[idxTag].mPtr, mColumnNames[idxTag].mLen), StringView(row[idxTag].mPtr, row[idxTag].mLen));
header.constCols里的tag漏了

2023-10-23 12:33 UTC, yyuuttaaoo commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +                field.compare(0, LENGTH_FIELD_PREFIX_TAG, FIELD_PREFIX_TAG) == 0) { // __tag__:*
这里tag处理有点问题，输入的时候没有给前缀

2023-10-23 12:33 UTC, yyuuttaaoo commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        mLogGroupList->back().SetAllMetadata(mLogGroup->MutableAllMetadata());
用GetAllMetadata

2023-10-24 04:23 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +                field.compare(0, LENGTH_FIELD_PREFIX_TAG, FIELD_PREFIX_TAG) == 0) { // __tag__:*
done

2023-10-24 04:23 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        mLogGroupList->back().SetAllMetadata(mLogGroup->MutableAllMetadata());
done

2023-10-24 04:24 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +    mRowSize = header.rowSize;
done

2023-10-24 04:25 UTC, linrunqi08 commented on core/unittest/sls_spl/SplBenchmark.cpp
> +    std::ostringstream oss;
这里是为了方便生成一定数量event的group，字符串不太好生成

2023-10-24 04:25 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupInput.cpp
> +        header.columnNames.emplace_back(SplStringPiece(kv.first.data(), kv.first.size()));
done

2023-10-24 04:26 UTC, linrunqi08 commented on core/CMakeLists.txt
> +        fuse sls_spl
done

2023-10-24 04:52 UTC, linrunqi08 commented on core/pipeline/Pipeline.cpp
> +    std::string pluginId = "spl";
done

2023-10-24 04:54 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        mLogGroupList->at(logGroupKeyIdx).SetTag(StringView(mColumnNames[idxTag].mPtr, mColumnNames[idxTag].mLen), StringView(row[idxTag].mPtr, row[idxTag].mLen));
这个是输出列模式用的，暂时没有用，已删除

2023-10-24 05:34 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupInput.cpp
> +void PipelineEventGroupInput::getRow(const int32_t rowIndex, std::vector<KV>& pairs, uint32_t& time, uint32_t& timeNsPart,  std::string& err) {
done

2023-10-25 03:09 UTC, yyuuttaaoo commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        LOG_DEBUG(sLogger, ("tag key", StringView(mIOHeader->columnNames[idxTag].mPtr, mIOHeader->columnNames[idxTag].mLen))("tag value", StringView(row[idxTag].mPtr, row[idxTag].mLen)));
这个实现和我想的不太样，我想的不用实际拼字符换，比如
tagHash = hash(tag)
hashv = (hashv + tagHash) ^ (hashv * tagHash);
不过我并不确定哪种方法会更快你可以测试一下。

2023-10-25 03:10 UTC, yyuuttaaoo commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        mLogGroupList->at(logGroupKeyIdx).SetTag(StringView(mColumnNames[idxTag].mPtr, mColumnNames[idxTag].mLen), StringView(row[idxTag].mPtr, row[idxTag].mLen));
输出列模式是怎么确定的？好像没有IsColumn这样的接口？

2023-10-25 13:22 UTC, messixukejia requested changes

2023-11-02 00:47 UTC, linrunqi08 commented on core/sls_spl/LogtailLogger.cpp
> +void LogtailLogger::log(const LOG_LEVEL& level, const std::string& file, const int32_t line, const std::string& content) {
log已按照最新的讨论换了集成方式

2023-11-02 00:47 UTC, linrunqi08 commented on .devcontainer/Dockerfile
> -FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail-build-linux:gcc_9.3.1-1
已升级

2023-11-02 00:48 UTC, linrunqi08 commented on .devcontainer/Dockerfile
> +FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail-toolchain-linux:spl-1.0
done

2023-11-14 01:01 UTC, linrunqi08 commented on core/sls_spl/ProcessorSPL.cpp
> +    initSPL();
这个是void，没有返回值

2023-11-14 01:26 UTC, linrunqi08 commented on core/sls_spl/ProcessorSPL.cpp
> +    return true;
done

2023-11-14 01:27 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupInput.cpp
> +    LOG_DEBUG(sLogger, ("colIndex", colIndex)("columnName", columnName));
done

2023-11-14 03:23 UTC, linrunqi08 commented on core/sls_spl/ProcessorSPL.cpp
> +    PipelineStatsPtr pipelineStatsPtr = std::make_shared<PipelineStats>();
done

2023-11-23 11:08 UTC, linrunqi08 commented on core/sls_spl/ProcessorSPL.cpp
> +    PipelineStatsPtr pipelineStatsPtr = std::make_shared<PipelineStats>();
done

2023-11-27 02:56 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +void PipelineEventGroupOutput::finish(std::string& error) {
done

2023-11-27 03:48 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        LOG_DEBUG(sLogger, ("tag key", StringView(mIOHeader->columnNames[idxTag].mPtr, mIOHeader->columnNames[idxTag].mLen))("tag value", StringView(row[idxTag].mPtr, row[idxTag].mLen)));
done

2023-11-27 03:49 UTC, linrunqi08 commented on core/sls_spl/ProcessorSPL.cpp
> +    // 根据spip->getInputSearches()，设置input数组
SPL语句有多个输出的时候，getInputSearches不是1，对于Logtail来说，基本上都是1

2023-11-27 10:59 UTC, linrunqi08 commented on core/sls_spl/PipelineEventGroupInput.cpp
> +
这个不会有影响，但是__offset__需要在spl中显示保留

2023-11-28 09:17 UTC, messixukejia commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        LOG_DEBUG(sLogger, ("columeName", field));
这个日志信息量有点太小了，虽然是debug。

如果需要保留就补充下上下文，不需要就删掉

2023-11-28 09:17 UTC, messixukejia commented on core/sls_spl/PipelineEventGroupOutput.cpp
> +        LOG_ERROR(sLogger, ("__error__", errorKV.second));
这种日志看看能不能补充更多上下文。整体日志都看下。

2023-11-29 06:46 UTC, henryzhx8 requested changes
这个PR只提交轮子即可，配置相关的可以都删了，尤其是Pipeline目录下的

2023-11-29 06:46 UTC, henryzhx8 commented on .devcontainer/Dockerfile
> +FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/ilogtail-community-edition/ilogtail-build-linux:spl-0.1
以后镜像版本能不能也按照正常的版本来迭代？不要用这种很特殊的记号

2023-11-29 06:46 UTC, henryzhx8 commented on core/CMakeLists.txt
> +        parser pipeline plugin plugin/creator plugin/instance plugin/interface polling processor processor/daemon profile_sender reader sdk sender shennong sls_control sls_spl
这个目录一定要加sls_前缀吗？

2023-11-29 06:46 UTC, henryzhx8 commented on core/sls_spl/ProcessorSPL.h
processorSPL挪到processor目录下，继承Processor接口

2023-11-29 06:46 UTC, henryzhx8 commented on core/sls_spl/ProcessorSPL.h
> +    MetricsRecordRef mMetricsRecordRef;
这个已经在基类了

2023-12-25 01:37 UTC, closed without merging