C++ input_file support utf16
alibaba/ilogtail pull request #1212
Opened 2023-11-01 05:53 UTC by quzard

2023-11-01 05:54 UTC, quzard commented
目前的改动是基于logtail 1.6改动的。留在这可作为之后master的C++ input_file支持utf16参考

2023-11-04 09:18 UTC, quzard commented
行首正则和正则提取测试脚本
```yaml
enable: true
inputs:
  - Type: file_log
    LogPath: C:\\Users\\Administrator\\ilogtail\\bin\\log\\
    FilePattern: utf16.log
    FileEncoding: utf16
processors:
  - Type: processor_regex_accelerate
    Keys:
    - time
    - level
    - msg
    Regex: \[(\S+)]\s\[(\S+)]\s(.*)
    # Regex: (.*)
    LogBeginRegex: \[\d+-\d+-\w+:\d+:\d+.\d+]\s\[\w+]\s.*
    DiscardUnmatch: false
flushers:
  - Type: flusher_sls
    Endpoint: cn-shanghai.log.aliyuncs.com
    ProjectName: xxxxxxxx
    LogstoreName: utf16
```

```python
# coding=utf-8
import os
import codecs

for i in range(0, 1000000):
    log_message = """[2022-07-07T10:43:27.360266763] [INFO] java.lang.Exception: exception happened
"""+str(0)+"""        at com.aliyun.sls.devops.logGenerator.type.RegexMultiLog.f2(RegexMultiLog.java:108)
    at java.base/java.lang.Thread.run(Thread.java:833)
日志采集是整个日志基础设施中最基础最关键的组件之一，影响着企业内部数据的完整性以及实时性。采集器作为数据链路的前置环节，其可靠性、扩展性、灵活性以及资源（CPU 和内存）消耗等，往往是最被关注的核心技术点。目前开源的日志采集器比较多。各采集器官网上关于其产品特性的描述也都比较相似，基本上都包括日志搜集、转换、路由等功能，并且无一例外都会突出其为高性能而设计。如果单纯看产品文档，其实很难在前面提到的核心技术点上得出有区分度的结论，若直接在生产环境上使用，则无疑是高压线上走钢丝。

我所在的公司作为一家通信与信息服务类公司，线上存在海量日志采集的场景，对于采集效率要求极高。前段时间阿里将内部大规模部署的采集引擎 ilogtail 对外开源，其列举的性能数据和技术细节吸引了我的注意。但是如果在外部社区使用，其具体的性能数据如何。本文将 ilogtail 与其他四款广泛使用的日志采集器：filebeat（go 语言）、vector（rust 语言）、fluent-bit（c 语言）、rsyslog（c 语言）进行对比测试，重点关注他们在可靠性、采集、转换性能、以及功能上的差异。
    """ + "\n"

    file_name = "C:\\Users\\Administrator\\ilogtail\\bin\\log\\utf16.log"

    if os.path.exists(file_name):
        with open(file_name, 'ab') as f:
            f.write(log_message.encode('utf-16le'))
    else:
        with codecs.open(file_name, 'w', 'utf-16-le') as f:
            f.write(log_message)


log_message = """[2022-07-07T10:43:27.360266763] [INFO] java.lang.Exception: exception happened
"""+str(0)+"""        at com.aliyun.sls.devops.logGenerator.type.RegexMultiLog.f2(RegexMultiLog.java:108)
    at java.base/java.lang.Thread.run(Thread.java:833)
日志采集是整个日志基础设施中最基础最关键的组件之一，影响着企业内部数据的完整性以及实时性。采集器作为数据链路的前置环节，其可靠性、扩展性、灵活性以及资源（CPU 和内存）消耗等，往往是最被关注的核心技术点。目前开源的日志采集器比较多。各采集器官网上关于其产品特性的描述也都比较相似，基本上都包括日志搜集、转换、路由等功能，并且无一例外都会突出其为高性能而设计。如果单纯看产品文档，其实很难在前面提到的核心技术点上得出有区分度的结论，若直接在生产环境上使用，则无疑是高压线上走钢丝。

我所在的公司作为一家通信与信息服务类公司，线上存在海量日志采集的场景，对于采集效率要求极高。前段时间阿里将内部大规模部署的采集引擎 ilogtail 对外开源，其列举的性能数据和技术细节吸引了我的注意。但是如果在外部社区使用，其具体的性能数据如何。本文将 ilogtail 与其他四款广泛使用的日志采集器：filebeat（go 语言）、vector（rust 语言）、fluent-bit（c 语言）、rsyslog（c 语言）进行对比测试，重点关注他们在可靠性、采集、转换性能、以及功能上的差异。
    """

file_name = "C:\\Users\\Administrator\\ilogtail\\bin\\log\\utf16.log"

if os.path.exists(file_name):
    with open(file_name, 'ab') as f:
        f.write(log_message.encode('utf-16le'))
else:
    with codecs.open(file_name, 'w', 'utf-16-le') as f:
        f.write(log_message)
```


json测试
```yaml
enable: true
inputs:
  - Type: file_log
    LogPath: C:\\Users\\Administrator\\ilogtail\\bin\\log\\
    FilePattern: utf16.log
    FileEncoding: utf16
    logType: json_log
processors:
  - Type: processor_json_accelerate
    DiscardUnmatch: false
flushers:
  - Type: flusher_sls
    Endpoint: cn-shanghai.log.aliyuncs.com
    ProjectName: xxxxxxx
    LogstoreName: utf16
```


```python
# coding=utf-8
import os
import codecs

for i in range(0, 1000000):
    log_message = """{"url": "POST /PutData?Category=YunOsAccountOpLog HTTP/1.1", "ip": "10.200.98.220", "user-agent": "aliyun-sdk-java", "request": {"status": "200", "latency": "18204"}, "time": "07/Jul/2022:10:30:28"}""" + "\n"

    file_name = "C:\\Users\\Administrator\\ilogtail\\bin\\log\\utf16.log"

    if os.path.exists(file_name):
        with open(file_name, 'ab') as f:
            f.write(log_message.encode('utf-16le'))
    else:
        with codecs.open(file_name, 'w', 'utf-16-le') as f:
            f.write(log_message)


log_message = """[2022-07-07T10:43:27.360266763] [INFO] java.lang.Exception: exception happened
"""+str(0)+"""        at com.aliyun.sls.devops.logGenerator.type.RegexMultiLog.f2(RegexMultiLog.java:108)
    at java.base/java.lang.Thread.run(Thread.java:833)
日志采集是整个日志基础设施中最基础最关键的组件之一，影响着企业内部数据的完整性以及实时性。采集器作为数据链路的前置环节，其可靠性、扩展性、灵活性以及资源（CPU 和内存）消耗等，往往是最被关注的核心技术点。目前开源的日志采集器比较多。各采集器官网上关于其产品特性的描述也都比较相似，基本上都包括日志搜集、转换、路由等功能，并且无一例外都会突出其为高性能而设计。如果单纯看产品文档，其实很难在前面提到的核心技术点上得出有区分度的结论，若直接在生产环境上使用，则无疑是高压线上走钢丝。

我所在的公司作为一家通信与信息服务类公司，线上存在海量日志采集的场景，对于采集效率要求极高。前段时间阿里将内部大规模部署的采集引擎 ilogtail 对外开源，其列举的性能数据和技术细节吸引了我的注意。但是如果在外部社区使用，其具体的性能数据如何。本文将 ilogtail 与其他四款广泛使用的日志采集器：filebeat（go 语言）、vector（rust 语言）、fluent-bit（c 语言）、rsyslog（c 语言）进行对比测试，重点关注他们在可靠性、采集、转换性能、以及功能上的差异。
    """

file_name = "C:\\Users\\Administrator\\ilogtail\\bin\\log\\utf16.log"

if os.path.exists(file_name):
    with open(file_name, 'ab') as f:
        f.write(log_message.encode('utf-16le'))
else:
    with codecs.open(file_name, 'w', 'utf-16-le') as f:
        f.write(log_message)
```

2023-11-06 06:24 UTC, messixukejia commented on .github/workflows/e2e-core.yaml
>          run: |
changelog

2023-11-06 08:34 UTC, yyuuttaaoo requested changes

2023-11-06 08:34 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +        char16_t* utf16BOMBuffer = new char16_t[1];
char16_t utf16BOMBuffer[1]

2023-11-06 08:34 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +        ReadFile(mLogFileOp, utf16BOMBuffer, readBOMByte, filePos, &truncateInfo);
如果空文件其实读取会失败

2023-11-06 08:34 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +
too many empty lines

2023-11-06 08:34 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +    if (utf16Buffer[0] == 0xfeff || utf16Buffer[0] == 0xfffe) {
改一下，不用每次都判断

2023-11-06 10:01 UTC, quzard commented on core/common/EncodingConverter.cpp
> +    mUtf16LittleToUtf8Cd = iconv_open("UTF-8", "UTF-16LE");
后面可以在主线分支支持Windows编译后，统一优化

2023-11-06 12:44 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +    if (!mHasReadUtf16Bom || mLastFilePos == 0) {
为什么还需要 || mLastFilePos == 0？

2023-11-06 12:46 UTC, quzard commented on core/reader/LogFileReader.cpp
> +    if (!mHasReadUtf16Bom || mLastFilePos == 0) {
清空日志文件的场景下，需要考虑这个

2023-11-07 08:36 UTC, merged