fix dockerContainer nil
alibaba/ilogtail pull request #1247
Opened 2023-11-20 09:03 UTC by quzard

2023-11-26 14:57 UTC, yyuuttaaoo requested changes

2023-11-26 14:57 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +				if i == 9 {
一个9一个10用个变量替换一下，体现最后一次的关系

2023-11-26 14:57 UTC, yyuuttaaoo commented on pkg/helper/docker_cri_adapter.go
> +			logger.Errorf(context.Background(), "CREATE_CONTAINERD_INFO_ALARM", "Create container info from cri-runtime error, err:%v", err)
这里错误信息太少了，至少需要把container id打印出来

2023-11-27 12:32 UTC, messixukejia approved these changes

2023-11-28 02:27 UTC, yyuuttaaoo approved these changes

2023-11-28 02:27 UTC, merged