fix ProcessorParseDelimiterNative strstr
alibaba/ilogtail pull request #1250
Opened 2023-11-26 06:32 UTC by quzard

2023-11-26 06:36 UTC, quzard commented
修复ProcessorParseDelimiterNative解析了下一行数据的问题

2023-11-26 15:22 UTC, yyuuttaaoo requested changes

2023-11-26 15:22 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
> +void ProcessorParseDelimiterNativeUnittest::TestMultipleLines() {
没看出multiple lines，看到的是mSeparator multiple chars

2023-11-27 12:32 UTC, messixukejia commented on core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
其他的插件多行ut也要加下

2023-11-27 14:04 UTC, quzard commented on core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
> +012@@345@@678
@yyuuttaaoo 这个地方有多行

2023-11-28 02:19 UTC, yyuuttaaoo approved these changes

2023-11-28 02:25 UTC, merged