fix: Correct parsing errors in ProcessorParseApsaraNative with large buffer input
alibaba/ilogtail pull request #1255
Opened 2023-12-04 11:14 UTC by quzard

This commit addresses incorrect parsing outcomes in ProcessorParseApsaraNative when reading a large buffer that contains multiple log entries. New unit tests have been introduced for ProcessorParseApsaraNative, ProcessorParseDelimiterNative, and ProcessorParseJsonNative to verify accurate parsing of log data in scenarios involving large buffer inputs.

2023-12-04 11:28 UTC, messixukejia requested changes

2023-12-04 11:57 UTC, messixukejia requested changes

2023-12-04 11:57 UTC, messixukejia commented on core/processor/ProcessorParseApsaraNative.cpp
>              ++index;
while (index <= buffer.size()); 

index = buffer.size()的时候++index

2023-12-05 16:54 UTC, yyuuttaaoo approved these changes

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    auto buffer = sourceEvent.GetContent(mSourceKey);
这些没必要改动的为啥要改啊

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +bool ProcessorParseApsaraNative::ProcessEvent(const StringView& logPath,
是因为apply了.clang-format导致了这里的变化吗？

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    size_t index = -1;
size_t = -1? 这会让index = 2^32-1。如果是这个意思，一般也会写成(size_t)-1强转，避免编译warning
但这里，是不是int更好？不然3个index类型居然还不一样？

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    if (index < length && buffer.data()[index] != 0) {
用length控制后，buffer.data()[index] != 0之类的代码就可以都不要了，不用再依赖\0作为字符串结尾了

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +            if (index == length || buffer.data()[index] == '\t' || buffer.data()[index] == '\0') {
这里也是类似，不用判定\0了

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +    size_t length = buffer.size();
这个也用int就可以了

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +            LOG_WARNING(sLogger, ("parse apsara log time", "fail")("string", buffer)("timeformat", "%s"));
是不是需要copy一下time字符串再传递给Strptime，这个函数是否依赖\0结尾

2023-12-05 16:54 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseApsaraNativeUnittest.cpp
> +void ProcessorParseApsaraNativeUnittest::TestMultipleLines() {
建议加一个异常测试case，比如
```
[2023-09-04 13:15:50.1] [error] [1[2023-09-04 13:15:33.2]	[info]	[2]	/ilogtail/AppConfigBase.cpp:2		AppConfigBase AppConfigBase:2
[2023-09-04 13:15:22.3]	[warning]	[3]	/ilogtail/AppConfigBase.cpp:3		AppConfigBase AppConfigBase:3
```

2023-12-05 16:57 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseDelimiterNativeUnittest.cpp
> +012@@345@@678",
split后field太多和太少的case是否都有了

2023-12-05 16:58 UTC, yyuuttaaoo requested changes

2023-12-05 16:58 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorParseJsonNativeUnittest.cpp
> +void ProcessorParseJsonNativeUnittest::TestMultipleLines() {
json错误的case是否至少有一个了

2023-12-06 12:42 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +        std::string strTime = buffer.to_string();
找一下]，然后substr中间的

2023-12-06 15:15 UTC, yyuuttaaoo approved these changes

2023-12-07 03:05 UTC, messixukejia approved these changes

2023-12-07 03:38 UTC, merged