fix panic when k8s_event.GetEventRecorder() is nil
alibaba/ilogtail pull request #1264
Opened 2023-12-14 12:31 UTC by quzard

2023-12-14 12:52 UTC, messixukejia approved these changes

2023-12-14 13:42 UTC, messixukejia requested changes

2023-12-14 13:42 UTC, messixukejia commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +	if k8s_event.GetEventRecorder() != nil {
能不能统一判断一次？

2023-12-14 13:42 UTC, messixukejia commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +			k8s_event.GetEventRecorder().SendErrorEventWithAnnotation(k8s_event.GetEventRecorder().GetObject(), GetAnnotationByError(annotations, CustomErrorFromSlsSDKError(err)), k8s_event.CreateTag, "", fmt
![image](https://github.com/alibaba/ilogtail/assets/13250519/4de545c9-0577-417d-961c-69696149a9ad)
引用点是不是也过多了

2023-12-14 13:47 UTC, yyuuttaaoo requested changes

2023-12-14 13:47 UTC, yyuuttaaoo commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +	if k8s_event.GetEventRecorder() != nil {
if k8s_event.GetEventRecorder() != nil这个判断重复代码太多了，能否给k8s_event改造以下，要么总是保证Recorder不为nil，是个mock也行啊。要么弄2个函数SendErrorEventWithAnnotation和SendNormalEventWithAnnotation，在里面if，外面就始终正常调这两个函数。
另外，为什么会nil，是因为不在k8s环境，整个k8s_event都没有init吗？

2023-12-18 06:00 UTC, yyuuttaaoo approved these changes

2023-12-18 06:55 UTC, messixukejia approved these changes

2023-12-19 02:53 UTC, merged