Env
alibaba/ilogtail pull request #1266
Opened 2023-12-15 08:55 UTC by quzard

2023-12-18 11:42 UTC, messixukejia requested changes

2023-12-18 11:42 UTC, messixukejia commented on pkg/helper/docker_center.go
>  func (info *K8SInfo) IsMatch(filter *K8SFilter) bool {
这个应该是比较高频的操作，直接加互斥锁，是不是会影响效率？
改成读写锁？

2023-12-18 11:42 UTC, messixukejia commented on helper/envconfig/aliyun_log_config_define.go
> +	"github.com/alibabacloud-go/tea/tea"
第一次开发容器相关的代码，需要给下设计，找@太业 重点reveiw下测试设计

2023-12-18 11:42 UTC, messixukejia commented on helper/envconfig/aliyun_log_config_define.go
> +			"MaxDirSearchDepth": 20,
MaxDirSearchDepth 这个为什么要加上？

2023-12-18 11:42 UTC, messixukejia commented on helper/envconfig/aliyunlog_client.go
> +	for {
这个代码很关键，要确保能够生效，测试需要测下超时后是否可以真正生效。

2023-12-18 11:42 UTC, messixukejia commented on helper/envconfig/product_logtail_config.go
> +	config.LogtailConfig.Processors = append(config.LogtailConfig.Processors, nginxIngressProcessorDetail)
nginxingress场景是否测试过

2023-12-18 11:42 UTC, messixukejia commented on helper/envconfig/aliyunlog_client.go
> +			return err
假设出了问题，是否有足够信息排查问题？

2023-12-18 11:42 UTC, messixukejia commented on helper/envconfig/aliyunlog_operation_wrapper.go
> -			machineGroups, err = o.logClient.GetAppliedMachineGroups(project, config.LogtailConfig.ConfigName)
GetAppliedMachineGroups 这个没有了？

2023-12-18 11:44 UTC, quzard commented on helper/envconfig/aliyunlog_operation_wrapper.go
> -			machineGroups, err = o.logClient.GetAppliedMachineGroups(project, config.LogtailConfig.ConfigName)
这块逻辑没啥用，不管GetAppliedMachineGroups结果是啥，都会进行apply

2023-12-18 11:44 UTC, henryzhx8 commented on helper/envconfig/aliyun_log_config_define.go
> +			"FilePaths":                []string{logPath + "/**/" + filePattern},
直接把配置的路径放过来，如果有**，那么设置depth和之前一样，如果没有**，则depth为0。具体兼容性自己再检查一下

2023-12-18 11:49 UTC, henryzhx8 commented on helper/envconfig/aliyun_log_config_define.go
> +	// 疑问：新版配置需要支持detail吗
把这块删了吧

2023-12-23 13:55 UTC, quzard commented on helper/envconfig/product_logtail_config.go
> +	config.LogtailConfig.Processors = append(config.LogtailConfig.Processors, nginxIngressProcessorDetail)
k8s-ingress-nginx这个product是不是废弃了？我用老的logtail
使用这个env也创建失败。
aliyun_logs_k8s-ingress-nginx_product=k8s-ingress-nginx

报错提示
ErrorCode: UnRegisterProduct
Message: The product {k8s-ingress-nginx} is not register

2023-12-24 03:27 UTC, messixukejia commented on pkg/helper/docker_center.go
>  	if info.PausedContainer {
改成这样不有变成锁不严格了吗

2023-12-24 03:28 UTC, messixukejia commented on helper/envconfig/aliyun_ecs_meta_data.go
> +	logger.Info(context.Background(), "get role list request", aliyunECSRamURL)
这么个打印法，又走向另外一个极端了。自己的判断是什么？

2023-12-24 03:33 UTC, quzard commented on helper/envconfig/aliyun_ecs_meta_data.go
> +	logger.Info(context.Background(), "get role list request", aliyunECSRamURL)
方便判断用了哪个role的token

2023-12-24 06:56 UTC, messixukejia commented on helper/envconfig/aliyun_ecs_meta_data.go
> +	logger.Info(context.Background(), "get role list request", aliyunECSRamURL)
不能为了方便过度打日志。

2023-12-25 01:44 UTC, yyuuttaaoo commented on helper/envconfig/aliyun_log_config_define.go
> +		maxDirSearchDepth = 100
10

2023-12-25 02:23 UTC, yyuuttaaoo commented on helper/envconfig/docker_env_config_manager.go
> +	var logClient **aliyunlog.Client
2层*能不能避免一下？

2023-12-25 07:43 UTC, quzard commented on helper/envconfig/aliyun_log_config_define.go
> +			"MaxDirSearchDepth": 20,
因为默认0，现在需要规定，path里有/**/才会设置maxDirSearchDepth = 10

2023-12-26 05:47 UTC, yyuuttaaoo commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +				logger.Info(context.Background(), "config not changed", "skip update")
Debug

2023-12-26 05:47 UTC, yyuuttaaoo commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +		logger.Info(context.Background(), "config created, config", *config)
和719行统一一下

2023-12-26 06:02 UTC, yyuuttaaoo approved these changes

2023-12-26 06:42 UTC, merged