add spl processor
alibaba/ilogtail pull request #1268
Opened 2023-12-18 07:58 UTC by linrunqi08

2023-12-18 10:57 UTC, messixukejia commented on core/reader/SourceBuffer.h
> +            mAllocatedChunks.push_back(mem);
mAllocatedChunks 释放也是直接操作，有点不太严格。至少一边需要加上合法性判断。
感觉在这里加上mem申请成功与否的判断比较合适。其他所有new的地方类似

2023-12-18 10:57 UTC, messixukejia commented on core/reader/SourceBuffer.h
> +class BufferAllocator
针对这些改动，SourceBufferUnittest是否需要针对性补充ut？

2023-12-18 10:57 UTC, messixukejia commented on core/spl/ProcessorSPL.cpp
> +    initSPL(&splOptions);
外部依赖需要做好判断，不能假定永远成功

2023-12-18 10:57 UTC, messixukejia commented on core/spl/ProcessorSPL.cpp
> +        inputs.push_back(new PipelineEventGroupInput(colNames, logGroup, *mContext));
new返回值做下判断

2023-12-18 11:58 UTC, henryzhx8 commented on core/config/Config.cpp
> +            if (isSPL) {
加注释

2023-12-18 12:01 UTC, henryzhx8 commented on core/plugin/instance/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} spl)
这个是不是不需要？

2023-12-18 12:01 UTC, henryzhx8 commented on core/plugin/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} spl)
同

2023-12-20 01:33 UTC, henryzhx8 commented on core/processor/ProcessorSPL.h
> +    uint32_t mTimeoutMills;
这两个参数可选的？那默认值是多少？得在这里初始化为默认值

2023-12-20 01:33 UTC, henryzhx8 commented on core/processor/ProcessorSPL.cpp
> +        PARAM_ERROR_RETURN(mContext->GetLogger(),
这里应该是PARAM_WARNING_DEFAULT，下面也是

2023-12-20 01:36 UTC, henryzhx8 commented on core/processor/ProcessorSPL.cpp
> +                                                   mContext->GetRegion());
```suggestion
       PARAM_ERROR_RETURN(mContext->GetLogger(),
                           mContext->GetAlarm(),
                           "failed to parse spl: "+error.msg_,
                           sName,
                           mContext->GetConfigName(),
                           mContext->GetProjectName(),
                           mContext->GetLogstoreName(),
                           mContext->GetRegion());
```

2023-12-20 01:37 UTC, henryzhx8 commented on core/processor/ProcessorSPL.cpp
> +        return false;
```suggestion
```

2023-12-20 01:38 UTC, henryzhx8 commented on core/processor/ProcessorSPL.cpp
> +    }
这一堆放到最上面，然后是spl初始化，最后是开头的指标，顺序换一下

2023-12-20 01:39 UTC, henryzhx8 requested changes
文件末尾的空行问题注意一下

2023-12-20 01:39 UTC, linrunqi08 commented on core/config/Config.cpp
> +            if (isSPL) {
done

2023-12-20 01:39 UTC, linrunqi08 commented on core/plugin/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} spl)
done

2023-12-20 01:40 UTC, linrunqi08 commented on core/spl/ProcessorSPL.cpp
> +    initSPL(&splOptions);
done

2023-12-20 01:40 UTC, linrunqi08 commented on core/plugin/instance/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME} spl)
done

2023-12-22 03:58 UTC, linrunqi08 commented on core/spl/ProcessorSPL.cpp
> +        inputs.push_back(new PipelineEventGroupInput(colNames, logGroup, *mContext));
done

2023-12-25 01:51 UTC, closed without merging