fix: The map is shared, which leads to concurrent read and write issues when reading context in aggregator_context.go:Add and writing context in plugin_runner_v1.go:ReceiveLogGroup
alibaba/ilogtail pull request #1284
Opened 2023-12-26 13:37 UTC by quzard

fatal error: concurrent map read and map write

2023-12-26 14:05 UTC, messixukejia requested changes

2023-12-26 14:09 UTC, quzard commented on pluginmanager/plugin_runner_v1.go
> +		context := map[string]interface{}{}
map在go语言中，是引用类型，当复制的时候，不能用map1 = map2 这样的值类型复制方式。
需要深度copy才行。

2023-12-27 01:54 UTC, linrunqi08 commented on pluginmanager/plugin_runner_v1.go
> +		context := map[string]interface{}{}
!p.LogstoreConfig.GlobalConfig.UsingOldContentTag 只有在进入这个分支的时候，才需要深度copy，是不是可以把判断提前一些

2023-12-27 06:56 UTC, linrunqi08 commented on pluginmanager/plugin_runner_v1.go
> +			context[ctxKeyTopic] = topic
你这里不是还是在写logGroup.Context吗，问题还是会存在

2023-12-27 12:24 UTC, quzard commented on pluginmanager/plugin_runner_v1.go
> +			context[ctxKeyTopic] = topic
不会吧，这个logGroup.Context只有这个地方会用写。

2023-12-29 06:48 UTC, yyuuttaaoo approved these changes

2023-12-29 10:33 UTC, messixukejia approved these changes

2023-12-29 16:39 UTC, merged