Fix apsara time parse nanosecond
alibaba/ilogtail pull request #1285
Opened 2023-12-26 14:50 UTC by Abingcbc

2023-12-27 00:39 UTC, messixukejia commented on core/processor/ProcessorParseApsaraNative.cpp
> +        strptimeResult = Strptime(strptimeResult + 1, "%f", &lastLogTime, nanosecondLength);
要判断下strptimeResult是否还有内容，别搞越界了

ut增加下指导秒，或者各种异常场景的测试

2023-12-27 03:43 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +        strptimeResult = Strptime(strptimeResult + 1, "%f", &lastLogTime, nanosecondLength);
nanosecond part不存在也能解析成功对吗

2023-12-27 03:51 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +        strptimeResult = Strptime(strptimeResult + 1, "%f", &lastLogTime, nanosecondLength);
直接strptimeResult + 1是否没问题

2023-12-27 13:54 UTC, Abingcbc commented on core/processor/ProcessorParseApsaraNative.cpp
> +        strptimeResult = Strptime(strptimeResult + 1, "%f", &lastLogTime, nanosecondLength);
这部分不使用%f解析了，重新采用了之前microtime解析方法

2023-12-28 02:07 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +        if (buffer[begIndex + index] == ']' || buffer[begIndex + index] == '\0') {
为什么不复用原来解析%f的代码了？另外，现在也不可能是]了吧。

2023-12-28 02:07 UTC, yyuuttaaoo commented on core/processor/ProcessorParseApsaraNative.cpp
> +        auto strptimeResult = Strptime(strTime.c_str(), "%Y-%m-%d %H:%M:%S", &lastLogTime, nanosecondLength);
上面279：strTime的地方可以写个注释，这个变量的值是个强prerequisite，strTime一定是[]之间的内容并且以\0结尾。

2023-12-28 03:20 UTC, messixukejia requested changes

2023-12-28 03:26 UTC, messixukejia commented on core/processor/ProcessorParseApsaraNative.cpp
> +int32_t ProcessorParseApsaraNative::GetApsaraLogMicroTimePart(const char* buffer) {
![image](https://github.com/alibaba/ilogtail/assets/13250519/9243f2fc-358e-421c-b181-b49ee6baadc3)

2023-12-28 07:48 UTC, Abingcbc commented on core/processor/ProcessorParseApsaraNative.cpp
> +        auto strptimeResult = Strptime(strTime.c_str(), "%Y-%m-%d %H:%M:%S", &lastLogTime, nanosecondLength);
done

2023-12-28 07:49 UTC, Abingcbc commented on core/processor/ProcessorParseApsaraNative.cpp
> +        strptimeResult = Strptime(strptimeResult + 1, "%f", &lastLogTime, nanosecondLength);
补充了判断逻辑

2023-12-28 09:01 UTC, messixukejia approved these changes

2023-12-28 12:05 UTC, merged