Feature/fix env config
alibaba/ilogtail pull request #129
Opened 2022-04-19 05:03 UTC by linrunqi08

2022-04-19 17:27 UTC, yyuuttaaoo commented on helper/docker_cri_adapter.go
> +				break
这里简化一下？直接return false

2022-04-19 17:34 UTC, yyuuttaaoo requested changes

2022-04-19 17:34 UTC, yyuuttaaoo commented on helper/docker_cri_adapter.go
> +				if strings.Contains(name, "logtail-ds") {
这个感觉固定strings.HasPrefix(name, "k8s_logtail_logtail-ds-")更可靠一些？

2022-04-22 05:15 UTC, linrunqi08 commented on helper/docker_cri_adapter.go
> +				break
fixed

2022-04-22 05:15 UTC, linrunqi08 commented on helper/docker_cri_adapter.go
> +				if strings.Contains(name, "logtail-ds") {
fixed

2022-04-22 08:39 UTC, messixukejia commented on helper/docker_cri_adapter.go
> +	for _, sock := range []string{"/var/run/docker.sock", "/run/docker.sock"} {
cri用了全局变量containerdUnixSocket

建议保持风格一致

2022-04-22 08:39 UTC, messixukejia commented on helper/docker_cri_adapter.go
> +				if strings.HasPrefix(name, "/k8s_logtail_logtail-ds-") {
有没有非name的字段可以判断

2022-04-24 01:41 UTC, EvanLjp requested changes
请修改名称判断

2022-04-24 01:41 UTC, EvanLjp commented on helper/docker_cri_adapter.go
> +				if strings.HasPrefix(name, "/k8s_logtail_logtail-ds-") {
不可以以此作为判断，有自建集群会改名字

2022-04-24 01:44 UTC, EvanLjp commented
1. 使用env 取podname 取不到默认docker
2. 使用docker ps grep podname查看是否存在，存在为docker 否则为假
3. 不使用cri client判断，避免不必要报错

2022-04-24 07:19 UTC, linrunqi08 commented on helper/docker_cri_adapter.go
> +	for _, sock := range []string{"/var/run/docker.sock", "/run/docker.sock"} {
fixed

2022-04-24 07:19 UTC, linrunqi08 commented on helper/docker_cri_adapter.go
> +				if strings.HasPrefix(name, "/k8s_logtail_logtail-ds-") {
fixed

2022-04-24 07:19 UTC, linrunqi08 commented on helper/docker_cri_adapter.go
> +				if strings.HasPrefix(name, "/k8s_logtail_logtail-ds-") {
fixed

2022-04-25 07:12 UTC, EvanLjp approved these changes
LGTM

2022-04-26 03:34 UTC, linrunqi08 commented
rerun

2022-04-26 03:40 UTC, yyuuttaaoo approved these changes
LGTM

2022-04-26 04:04 UTC, messixukejia commented
加下changelog

2022-04-26 11:17 UTC, EvanLjp approved these changes
LGTM

2022-04-26 11:25 UTC, merged