Feature/taiye/add go plugin metric
alibaba/ilogtail pull request #1290
Opened 2023-12-27 08:29 UTC by linrunqi08

2023-12-31 02:26 UTC, messixukejia requested changes

2023-12-31 02:26 UTC, messixukejia commented on pluginmanager/processor_wrapper.go
> +	labels["plugin_id"] = strconv.FormatInt(int64(pluginNum), 10)
这个id一路传下来是做唯一标识的？

目前有了一种机制，不要在引入新的机制
https://github.com/alibaba/ilogtail/discussions/649
https://github.com/alibaba/ilogtail/pull/648
![image](https://github.com/alibaba/ilogtail/assets/13250519/5a94778a-1e88-4abb-abe7-90b328f60a6b)

2023-12-31 02:26 UTC, messixukejia commented on pluginmanager/plugin_runner_helper.go
> +func flushOutStoreV1[T FlushData](lc *LogstoreConfig, store *FlushOutStore[T], flushers []*FlusherWrapperV1, flushFunc func(*LogstoreConfig, *FlusherWrapperV1, *FlushOutStore[T]) error) bool {
FlusherWrapperV1 参数的差异，实现完全一样，用类似继承的方式代码优化下。

2023-12-31 02:26 UTC, messixukejia commented on pluginmanager/plugin_runner_helper.go
> +func flushOutStoreV1[T FlushData](lc *LogstoreConfig, store *FlushOutStore[T], flushers []*FlusherWrapperV1, flushFunc func(*LogstoreConfig, *FlusherWrapperV1, *FlushOutStore[T]) error) bool {
v1、v2差异的地方，放到plugin_runner_v1/v2.go中

2023-12-31 02:26 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +    LOG_INFO(sLogger, ("goLogGroupMap", goLogGroupMap.size()));
日志打印要有更多上下文

2023-12-31 02:26 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +        std::string region = METRIC_REGION_DEFAULT;
给点注释样例说明下这段转换逻辑在干什么

2023-12-31 02:30 UTC, messixukejia requested changes

2023-12-31 02:30 UTC, messixukejia commented on pluginmanager/processor_wrapper.go
> +func (wrapper *ProcessorWrapperV1) Process(logArray []*protocol.Log) []*protocol.Log {
v1、v2的内容是不是应该统一放到plugin_runner_v1/v2中？或者建一个全新的一组文件？

2023-12-31 02:30 UTC, messixukejia commented on pluginmanager/context_imp.go
> +func (p *ContextImp) SetMetricRecord(metricsRecord *pipeline.MetricsRecord) {
这里的实现依赖的是单个LogstoreConfig的所有插件是单线程，顺序init的，否则该实现会有问题 -- 这个假设是否恒成立

线程模型、锁机制拉个会议当面讲下，并讨论下吧

2024-01-02 03:26 UTC, linrunqi08 commented on pluginmanager/context_imp.go
> +func (p *ContextImp) RegisterCounterMetric(metricsRecord *pipeline.MetricsRecord, metric pipeline.CounterMetric) {
done

2024-01-02 03:26 UTC, linrunqi08 commented on plugins/processor/encrypt/processor_encrypt.go
> +	labels := make(map[string]string)
done

2024-01-02 03:42 UTC, linrunqi08 commented on plugins/processor/encrypt/processor_encrypt.go
> +	labels["logstore"] = p.context.GetLogstore()
done

2024-01-17 09:00 UTC, messixukejia requested changes

2024-01-17 09:00 UTC, messixukejia commented on core/go_pipeline/LogtailPlugin.cpp
> +            if (metrics->count > 0) {
大小判断没什么意义，下面for循环都有了

2024-01-17 09:00 UTC, messixukejia commented on core/go_pipeline/LogtailPlugin.cpp
> +                    InnerPluginMetric* innerpm = metrics->metrics[i];
这里再循环一遍释放是不是有点多余，跟上面赋值一起是不是就可以了?

2024-01-17 09:00 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +        SetLogTime(logPtr,
now.tv_sec 是不是时间戳，有时区一说吗？

2024-01-17 09:00 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +    int childPluginID = pluginIndex;
if else？

2024-01-17 09:00 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +        genPluginAndNodeID(pluginIndex, true, pluginMeta);
2.0需要解决下go串联的问题

2024-01-17 09:00 UTC, messixukejia commented on pluginmanager/aggregator_wrapper_v1.go
> +		p.procOutRecordsTotal.Add(int64(len(loggroup.Logs)))
这里再确认下

2024-01-17 09:00 UTC, messixukejia commented on pluginmanager/logstore_config.go
> -			continue
这个条件不需要了？

2024-01-20 07:02 UTC, yyuuttaaoo commented on pkg/helper/self_metric_imp.go
> +func (s *AvgMetric) GetAndReset() int64 {
这个类型比较诡异，0.x怎么表达？

2024-01-20 07:15 UTC, yyuuttaaoo commented on pkg/pipeline/context.go
> +	Labels map[string]string
这个结构会不会label的输出顺序不可控？一般label也应该不需要快速查询，数组是不是更合适？

2024-01-22 01:58 UTC, yyuuttaaoo commented on plugin_main/plugin_export.go
> +        return malloc(sizeof(KeyValue*)*  size);
中间那个是乘号，两边空格

2024-01-22 02:05 UTC, yyuuttaaoo commented on core/monitor/LogtaiMetric.cpp
> +                                             const std::string& childPluginID,
这个是child好还是parent好？child我是觉得分叉到多个下游树形结构会不好表达。
如果只考虑链式那么next比child命名会更好一些

2024-01-22 02:49 UTC, yyuuttaaoo commented on pluginmanager/metric_export.go
> +	for _, config := range LogtailConfig {
这地方要存在多线程竞争吗？

2024-01-22 03:24 UTC, yyuuttaaoo commented on plugins/input/command/VGVzdFNjcmlwdFN0b3JhZ2U=.sh
这是误入的？

2024-01-22 12:52 UTC, messixukejia approved these changes

2024-01-23 06:01 UTC, yyuuttaaoo commented on pluginmanager/logstore_config_test.go
> +		assert.Regexp(t, `testPlugin/_gen_embedded_\d+`, result.PluginTypeWithID)
_gen_embedded_ 不要了吧，和C++保持一致
另外id是0开始，如果和c++在一个pipeline的cgo，应该续下去比如c++ 0 1 go 2 3

2024-01-23 07:11 UTC, yyuuttaaoo approved these changes

2024-01-23 07:21 UTC, merged