fix some memory leaks
alibaba/ilogtail pull request #1298
Opened 2023-12-29 07:25 UTC by quzard

2023-12-29 10:43 UTC, yyuuttaaoo requested changes

2023-12-29 10:43 UTC, yyuuttaaoo commented on .github/workflows/build-core-ut.yaml
> +          # BUILD_TYPE: Debug # TODO: Uncomment when memory management is refined
如果都修好了可以把这个环境变量打开

2023-12-29 10:43 UTC, yyuuttaaoo commented on core/processor/ProcessorParseDelimiterNative.h
> +    ~ProcessorParseDelimiterNative() override { delete mDelimiterModeFsmParserPtr; };
用unique ptr

2023-12-29 10:45 UTC, yyuuttaaoo requested changes

2023-12-29 10:45 UTC, yyuuttaaoo commented on core/unittest/processor/ProcessorFilterNativeUnittest.cpp
> +    ProcessorFilterNative* processor = new ProcessorFilterNative;
这些都不用出现，new直接写instance构造函数里

2023-12-29 15:39 UTC, quzard commented on core/unittest/processor/ProcessorFilterNativeUnittest.cpp
> +    ProcessorFilterNative* processor = new ProcessorFilterNative;
部分地方还是要用到的，需要调用插件的函数和可观测指标

2023-12-30 00:52 UTC, yyuuttaaoo commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    mDelimiterModeFsmParserPtr = std::make_shared<DelimiterModeFsmParser>(mQuote, mSeparatorChar);
这个是不是unique就够了？

2023-12-30 02:33 UTC, quzard commented on .github/workflows/build-core-ut.yaml
> +          # BUILD_TYPE: Debug # TODO: Uncomment when memory management is refined
现在GitHub上的main分支单测流水线跑不起来，要看看是为啥

2024-02-28 02:26 UTC, closed without merging