Fixed the issue where the logGroup pointer was not released when using Golang plugins.
alibaba/ilogtail pull request #1313
Opened 2024-01-05 06:28 UTC by linrunqi08

2024-01-05 08:46 UTC, messixukejia requested changes

2024-01-05 08:46 UTC, messixukejia commented on core/processor/daemon/LogProcess.cpp
> +            for (auto pLogGroup : logGroupList) {
智能指针

2024-01-05 08:46 UTC, messixukejia commented on core/processor/daemon/LogProcess.cpp
> +            logGroupList.clear();
历史修复

2024-01-05 11:03 UTC, linrunqi08 commented on core/processor/daemon/LogProcess.cpp
> +            for (auto pLogGroup : logGroupList) {
done

2024-01-05 11:03 UTC, linrunqi08 commented on core/processor/daemon/LogProcess.cpp
> +            logGroupList.clear();
ASAN扫描出来的都是new Thread的问题，这个单独一个pr去修吧

2024-01-08 01:35 UTC, yyuuttaaoo approved these changes

2024-01-08 06:22 UTC, messixukejia approved these changes

2024-01-08 11:13 UTC, merged