Improve sender log condition to record valuable debug info
alibaba/ilogtail pull request #1359
Opened 2024-02-06 15:17 UTC by yyuuttaaoo

2024-03-22 07:18 UTC, henryzhx8 commented on core/monitor/LogIntegrity.cpp
> +        info->mLastUpdateTime = data->mEnqueueTime;
```suggestion
        info->mLastUpdateTime = data->mEnqueueTime;
        
```

2024-03-22 08:35 UTC, henryzhx8 requested changes

2024-03-22 08:35 UTC, henryzhx8 commented on core/common/LogstoreSenderQueue.h
> +                        ("Network fail, pause ", mSenderInfo.mRegion)("project", item->mProjectName)(
这边pause的都是logstore，不是region

2024-03-22 08:35 UTC, henryzhx8 commented on core/sender/Sender.cpp
> +                "RetryTimes", mDataPtr->mSendRetryTimes)("TotalSendCost", curTime - mDataPtr->mEnqueueTime)(
这里是mLastSendTime吧

2024-03-22 08:35 UTC, henryzhx8 commented on core/sender/Sender.cpp
> +    if (curTime - mDataPtr->mEnqueueTime > INT32_FLAG(discard_send_fail_interval)) {
这里是mLastSendTime还是mEnqueueTime？前者会一直变，后者就一次性，原来那个指的是前者

2024-03-22 08:35 UTC, henryzhx8 commented on core/sender/Sender.cpp
> +                                                 curTime - mDataPtr->mEnqueueTime)("LogLines", mDataPtr->mLogLines)( \
mLastSendTime

2024-03-22 08:35 UTC, henryzhx8 commented on core/sender/Sender.cpp
> -                data->mLastUpdateTime = time(NULL); // set last update time before sending
这个不要了？

2024-03-22 09:28 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> +                "RetryTimes", mDataPtr->mSendRetryTimes)("TotalSendCost", curTime - mDataPtr->mEnqueueTime)(
不是，这里没错。你说的是"ResponseTime", curTime - mDataPtr->mLastSendTime

2024-03-22 09:29 UTC, yyuuttaaoo commented on core/common/LogstoreSenderQueue.h
> +                        ("Network fail, pause ", mSenderInfo.mRegion)("project", item->mProjectName)(
logstore也打印了"logstore", item->mLogstore

2024-03-22 09:43 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> +                                                 curTime - mDataPtr->mEnqueueTime)("LogLines", mDataPtr->mLogLines)( \
It's ResponseTime

2024-03-22 09:44 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> -                data->mLastUpdateTime = time(NULL); // set last update time before sending
不要了，有mLastSendTime了

2024-03-22 10:26 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> +    if (curTime - mDataPtr->mEnqueueTime > INT32_FLAG(discard_send_fail_interval)) {
这是丢弃6小时都发不出去的逻辑，应该用mEnqueueTime

2024-03-22 10:36 UTC, henryzhx8 commented on core/common/LogstoreSenderQueue.h
> +                        ("Network fail, pause ", mSenderInfo.mRegion)("project", item->mProjectName)(
优化一下吧，不然打印出来像是暂停了地域，比如pause：cn-hangzhou

2024-03-22 10:37 UTC, henryzhx8 approved these changes

2024-03-24 10:34 UTC, messixukejia approved these changes

2024-03-25 06:59 UTC, yyuuttaaoo commented on core/common/LogstoreSenderQueue.h
> +                        ("Network fail, pause ", mSenderInfo.mRegion)("project", item->mProjectName)(
顺序调整了一下

2024-03-26 09:06 UTC, merged