add InputContainerStdout
alibaba/ilogtail pull request #1373
Opened 2024-02-27 08:33 UTC by quzard

添加InputContainerStdout插件用于采集stdout

2024-02-29 09:04 UTC, henryzhx8 requested changes

2024-02-29 09:04 UTC, henryzhx8 commented on core/controller/EventDispatcher.cpp
> +    if (inputFile) {
这里拉一下主分支，然后这里不管inputfile还是stdout都要调用，只是在stdout的时候，那个参数直接用0

2024-03-05 12:56 UTC, quzard commented on core/input/InputContainerStdout.cpp
> +    plugin["type"] = Json::Value("metric_docker_file");
直接在现有插件上改，后面一个的pr，会改这个地方

2024-03-05 12:58 UTC, quzard commented on core/file_server/FileDiscoveryOptions.cpp
> +    mAllowingIncludedByMultiConfigs = true;
此处加个开关吧，容器输出重复采集挺常见的

2024-03-06 06:19 UTC, quzard commented on core/pipeline/Pipeline.cpp
> +            detail["Mode"] = Json::Value("custom");
禁止mode为json

2024-03-06 14:04 UTC, henryzhx8 requested changes

2024-03-07 02:21 UTC, quzard commented on core/input/InputContainerStdout.cpp
> +        fileDiscoveryConfig["AllowingCollectingFilesInRootDir"] = true;
避免极端人软连接到了根目录上吧

2024-03-07 03:17 UTC, henryzhx8 commented on core/input/InputContainerStdout.cpp
> +        fileDiscoveryConfig["AllowingIncludedByMultiConfigs"] = true;
那就和文件对齐，默认不允许

2024-03-07 07:13 UTC, henryzhx8 requested changes

2024-03-07 07:13 UTC, henryzhx8 commented on core/input/InputContainerStdout.cpp
>          fileDiscoveryConfig["AllowingIncludedByMultiConfigs"] = true;
这行删了，默认是false了

2024-03-08 01:51 UTC, henryzhx8 approved these changes

2024-03-11 07:50 UTC, henryzhx8 requested changes

2024-03-11 07:50 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +            && inputContainerStreamLog->mMultiline.mMode == MultilineOptions::Mode::CUSTOM) {
后半个条件不要

2024-03-11 07:50 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +
这个应该在插件的init里面

2024-03-18 08:55 UTC, yyuuttaaoo commented on core/controller/EventDispatcher.cpp
>      // now we can be sure that input is file
fix comment

2024-03-18 08:55 UTC, yyuuttaaoo commented on core/pipeline/PipelineManager.cpp
> +                                          bool& isInputStreamChanged,
后面得按照xxServer是否需要pause组织一下，提供xxxServerChanged之类的，否则要改的地方太多了。

2024-03-18 12:10 UTC, yyuuttaaoo approved these changes

2024-03-18 12:11 UTC, merged