Add ProcessorParseContainerLogNative
alibaba/ilogtail pull request #1374
Opened 2024-02-27 08:37 UTC by quzard

ProcessorParseContainerLogNative 插件用于解析containerd的stdout 日志 以及docker的json格式的stdout日志

2024-02-27 16:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1374) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1374) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: quzard<br/>:x: yitao<br/><hr/>**yitao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1374) it.</sub>

2024-02-29 07:19 UTC, henryzhx8 requested changes

2024-02-29 07:19 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    return true;
这里还有可能有其它可能吗？如果没有，直接把前面改成else子句

2024-02-29 07:19 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        sourceEvent.SetContent(ProcessorMergeMultilineLogNative::PartLogFlag,
不用NoCopy？为啥key和value是一样的

2024-02-29 07:19 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +    void AddContainerdTextLog(
```suggestion
    void ResetDockerJsonLogField(char* data, StringView key, StringView value, LogEvent& targetEvent);
    void ResetContainerdTextLog(
```

2024-02-29 07:19 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        std::string errorMsg = "invalid docker stdout json log: " + buffer.to_string();
这里的errormsg和containerd那边我写的保持一致吧

2024-02-29 07:19 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        std::string errorMsg = "invalid docker stdout json log: " + buffer.to_string();
erroMsg同前

2024-02-29 07:19 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        std::string errorMsg = "invalid docker stdout json log: " + buffer.to_string();
errorMsg同前

2024-02-29 07:19 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        errorMsg = "The size of the Docker JSON log file has exceeded the limit. Log: " + buffer.to_string();
```suggestion
        errorMsg = "unexpected error: the original log line length is smaller than the sum of parsed fields\tfirst 1KB log: xxxxxx";
```

2024-03-06 03:16 UTC, henryzhx8 requested changes

2024-03-06 03:16 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        errorMsgStream << "invalid docker stdout json log."
```suggestion
        errorMsgStream << "source field cannot be found in log line."
```

2024-03-06 03:16 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        errorMsgStream << "invalid docker stdout json log."
```suggestion
        errorMsgStream << "time field cannot be found in log line."
```

2024-03-06 03:16 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        errorMsgStream << "invalid docker stdout json log."
```suggestion
        errorMsgStream << "content field cannot be found in log line."
```

2024-03-06 03:16 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    if (content.empty()) {
这里有个小问题，如何区别找不着和本身为空？现在两个是一样处理的，但是在containerd里面，目前空是允许的，不会报错。建议和containerd保持一致。

2024-03-06 03:16 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    if (content.size() > 0 && content[content.size() - 1] == '\n') {
```suggestion
    if (!content.empty() && content.back() == '\n') {
```

2024-03-06 03:16 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    }
```suggestion
        LOG_WARNING(sLogger,
                    ("failed to parse log line, errorMsg",
                     errorMsg)("container runtime", containerType)("processor", sName)("config", mContext->GetConfigName()));

        errorMsg = "failed to parse log line, error: " + errorMsg + "\tcontainer runtime: " + containerType.to_string() + "\tprocessor: " + sName + "\tconfig: " + mContext->GetConfigName();
        LogtailAlarm::GetInstance()->SendAlarm(PARSE_LOG_FAIL_ALARM,
                                               errorMsg,
                                               GetContext().GetProjectName(),
                                               GetContext().GetLogstoreName(),
                                               GetContext().GetRegion());
    }
```

2024-03-06 08:12 UTC, henryzhx8 requested changes

2024-03-06 08:12 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    data = const_cast<char*>(buffer.data());
合一块？

2024-03-07 07:10 UTC, henryzhx8 requested changes

2024-03-07 07:10 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +    CounterPtr mProcDiscardRecordsTotal; // 丢弃条数
```suggestion
```
这个没必要，完全可以从instance的in条数和out条数做差来得到，是个导出字段

2024-03-07 07:10 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        mProcDiscardRecordsTotal->Add(1);
```suggestion
```

2024-03-07 11:09 UTC, henryzhx8 approved these changes

2024-03-08 05:33 UTC, yyuuttaaoo commented on core/processor/ProcessorParseContainerLogNative.h
> +    static const char CONTIANERD_DELIMITER; // 分隔符
CONTAINERD

2024-03-08 06:10 UTC, messixukejia approved these changes

2024-03-08 07:01 UTC, yyuuttaaoo commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        return it != doc.MemberEnd() ? StringView(it->value.GetString()) : StringView();
万一不是string，代码会挂吗？

2024-03-08 07:03 UTC, quzard commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        return it != doc.MemberEnd() ? StringView(it->value.GetString()) : StringView();
嗯

2024-03-10 01:48 UTC, yyuuttaaoo approved these changes

2024-03-11 07:36 UTC, henryzhx8 requested changes

2024-03-11 07:36 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        return false;
return mKeepingSourceWhenParseFail

2024-03-11 07:43 UTC, henryzhx8 approved these changes

2024-03-11 07:44 UTC, merged