Collecting and Processing stdout Information from metric_container_meta via InputContainerStdout Plugin
alibaba/ilogtail pull request #1381
Opened 2024-02-29 07:40 UTC by quzard

2024-03-19 08:36 UTC, henryzhx8 requested changes

2024-03-19 08:36 UTC, henryzhx8 commented on plugins/input/docker/logmeta/metric_container_info.go
> +	idf.lastStreamLogTypeCache = make(map[string]string)
为什么要搞这么多的map？不能合成一个吗？你这导致delte那边会出来一堆重复事件

2024-03-19 08:36 UTC, henryzhx8 commented on plugins/input/docker/logmeta/metric_container_info.go
> +	cmd.DefaultRootPath = path.Clean(helper.GetMountedFilePathWithBasePath(idf.MountPath, path.Clean(defaultRootPath)))
这是干啥用的？

2024-03-19 08:36 UTC, henryzhx8 commented on plugins/input/docker/logmeta/metric_container_info.go
> +			Source:      path.Clean(helper.GetMountedFilePathWithBasePath(idf.MountPath, path.Clean(formatPath(mount.Source)))),
go传给c的path是不是转换后的？为什么要带/logtail_host

2024-03-19 08:36 UTC, henryzhx8 commented on plugins/input/docker/logmeta/metric_container_info.go
> +	sortMounts(mounts)
为什么要sort？

2024-03-19 08:36 UTC, henryzhx8 commented on core/reader/FileReaderOptions.h
> +    enum class Encoding { UTF8, UTF16, GBK, CONTAINERD_TEXT, DOCKER_JSON_FILE };
为什么总是把这两者混起来？encoding和format是两个概念，难道stdout就不允许它是GBK了？

2024-03-19 11:38 UTC, henryzhx8 requested changes
需要做一些封装，不要直接平铺：
1. 利用FileDiscoveryOptions中的mUpdateContainerInfo和mDeleteContainerInfo函数指针来替代DoUpdateContainerPaths函数里的DeleteDockerContainerPath和UpdateDockerContainerPath
2. 函数指针的设置在插件Init函数里，init filediscovery之后
3. input file和stdout的方法分别以static函数的形式放在插件类中
4. pathcmd的string的反序列化可以在接收到的时候就做，直接存json不是存string

2024-03-20 04:00 UTC, quzard commented on plugins/input/docker/logmeta/metric_container_info.go
> +	sortMounts(mounts)
防止虽然mouts一样，但乱序导致不同。统一按照source进行排序，然后再比较

2024-03-20 09:10 UTC, henryzhx8 commented on core/file_server/FileDiscoveryOptions.h
> +    bool (*mIsSameDockerContainerPath)(const Json::Value&, bool, FileDiscoveryOptions*) = nullptr;
把FileDiscoveryOption参数放到第一个，相当于类成员函数的this指针，issame这个可以是const指针

2024-03-20 09:12 UTC, henryzhx8 commented on core/file_server/FileDiscoveryOptions.cpp
>          return false;
这个也都直接放到函数里面去吧，其它几个地方同，这里只是做一层转发，本质上strategy设计模式

2024-03-20 09:18 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +        DockerContainerPathCmd* cmd = new DockerContainerPathCmd(configName, false, jsonParams, false);
一样，直接用JsonUtil的函数

2024-03-20 09:28 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +DECLARE_FLAG_STRING(default_container_host_path);
这个变量的定义从appconfig移到logtailcommonflags

2024-03-20 09:32 UTC, henryzhx8 commented on core/input/InputFile.cpp
> +}
目前看delete两个插件是完全一样的，所以delete不用搞函数指针了，直接把这个函数挪到filediscoveryoptions里

2024-03-20 09:43 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +void SetContainerPath(DockerContainerPath& dockerContainerPath) {
这边要把go那边的软链接转换逻辑搬过来

2024-03-20 10:54 UTC, henryzhx8 requested changes

2024-03-20 10:54 UTC, henryzhx8 commented on core/models/PipelineEventGroup.cpp
> +const std::string EVENT_GROUP_META_DOCKER_JSON_FILE = "json-file";
这里为什么要改？

2024-03-20 10:54 UTC, henryzhx8 commented on core/reader/LogFileReader.h
> +    const FileReaderConfig& GetReaderConfig() const { return mReaderConfig; }
```suggestion
```

2024-03-20 10:54 UTC, henryzhx8 commented on core/reader/LogFileReader.cpp
> +                }
这边直接在reader里面加一个参数mFileLogFormat，不要加在readeroptions里

2024-03-20 10:54 UTC, henryzhx8 commented on core/reader/FileReaderOptions.h
> +    enum class LogFormat { TEXT, CONTAINERD_TEXT, DOCKER_JSON_FILE };
挪到logfile reader里去

2024-03-20 10:54 UTC, henryzhx8 commented on core/processor/daemon/LogProcess.cpp
> +        }
这个挪到下边这个函数里

2024-03-20 10:54 UTC, henryzhx8 commented on pkg/helper/docker_center.go
> +		StdoutLogType:    info.HostConfig.LogConfig.Type,
这边要和C++那边统一，docker的情况最好加上docker_前缀

2024-03-20 10:54 UTC, henryzhx8 commented on plugins/input/docker/rawstdout/input_docker_stdout.go
> +	case "json-file", "journald", "containerd_text":
这里不要随意的改，不要把通用的字段和你自定义的字段放在一起

2024-03-20 11:45 UTC, quzard commented on core/file_server/FileDiscoveryOptions.h
> +    bool (*mIsSameDockerContainerPath)(const Json::Value&, bool, FileDiscoveryOptions*) = nullptr;
issame里也要处理logpath，不能const

2024-03-22 06:47 UTC, yyuuttaaoo commented on core/input/InputFile.cpp
> +static void SetContainerPath(ContainerInfo& containerInfo, const FileDiscoveryOptions* fileDiscovery) {
把这个作为回调，IsSameContainerInfo和UpdateContainerInfoFunc重复度太高了

2024-03-22 07:38 UTC, yyuuttaaoo commented on core/input/InputContainerLog.cpp
> +std::string InputContainerLog::TryGetRealPath(std::string path) {
输入参数使用引用

2024-03-22 07:40 UTC, yyuuttaaoo commented on core/unittest/input/InputContainerLogUnittest.cpp
> +    std::cout << result << std::endl;
测试使用ASSERT，打印一下起不到作用

2024-03-24 05:47 UTC, henryzhx8 requested changes

2024-03-24 05:47 UTC, henryzhx8 commented on core/file_server/ContainerInfo.h
> +    InputType mInputType;
这个不要放在这，把这个信息放在readerconfig里面

2024-03-24 05:47 UTC, henryzhx8 commented on core/reader/LogFileReader.h
> +    ContainerInfo::InputType mInputType = ContainerInfo::InputType::InputFile;
这里就不用额外存了，从readerconfig里拿

2024-03-24 05:47 UTC, henryzhx8 commented on core/reader/LogFileReader.cpp
> +            mFileLogFormat = LogFormat::CONTAINERD_TEXT;
这里应该是先判断有没有读到东西，没有的话是不要把mHasReadContainerBom赋值的，有的话再分类，这样的话你的判断条件就不应该有mLastFilePos这种奇怪的东西

2024-03-24 05:47 UTC, henryzhx8 commented on core/reader/LogFileReader.cpp
> +    }
这段逻辑搞成单独的函数，不要两个地方复制

2024-03-24 05:47 UTC, henryzhx8 commented on core/reader/LogFileReader.h
> +    void checkContainerType();
在哪用到了？

2024-03-24 05:47 UTC, henryzhx8 commented on core/reader/LogFileReader.h
> +    bool mHasReadContainerBom = false;
这个信息要不要存到checkpoint里？

2024-03-24 05:47 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +std::string InputContainerLog::TryGetRealPath(const std::string& path) {
windows的行为没有复制过来

2024-03-24 05:47 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +            std::string subPath = tmpPath.substr(0, index);
这里都可以用stringview

2024-03-24 05:47 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +                std::string partialPath = STRING_FLAG(default_container_host_path).c_str()
c_str()?

2024-03-24 05:47 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +        LOG_ERROR(sLogger, ("failed to get real path", containerInfo.mStdoutPath));
```suggestion
        LOG_ERROR(sLogger, ("failed to set container base dir", "container log path not existed")("container id", containerInfo.mId)("container log path", containerInfo.mLogPath));
        mContext->GetAlram()->SendAlarm(INVALID_CONTAINER_PATH_ALARM, "failed to set container base dir: container log path not existed\tcontainer id: " + ToString(containerInfo.mId) + "\tcontainer log path: " + containerInfo.mLogPath, mContext->GetProjectName(),mContext->GetLogstoreName(), mContext->GetRegion());
```

2024-03-24 05:47 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
>      return true;
这上边的alarm type有问题，是category_config_alarm，拿alarm的方式和前面对齐

2024-03-24 08:14 UTC, quzard commented on core/file_server/ContainerInfo.h
> +    std::string mStdoutPath;
1

2024-03-25 03:00 UTC, quzard commented on core/reader/LogFileReader.h
> +    bool mHasReadContainerBom = false;
应该不需要

2024-03-25 07:32 UTC, henryzhx8 requested changes

2024-03-25 07:32 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +#if defined(__linux__)
宏往里缩一层，别搞两个函数

2024-03-25 07:32 UTC, henryzhx8 commented on core/input/InputContainerLog.cpp
> +    }
windows这些能用？

2024-03-25 12:00 UTC, quzard commented on core/input/InputContainerLog.cpp
> +    }
polling也用的这个

2024-03-26 09:04 UTC, henryzhx8 approved these changes

2024-04-02 10:02 UTC, henryzhx8 requested changes

2024-04-02 10:56 UTC, quzard commented on core/file_server/ContainerInfo.cpp
> +    containerInfo.mJson = params;
之前是mJsonStr。现在换成了mJson，因为最后save时，需要添加logpath进去。

2024-04-02 10:57 UTC, quzard commented on core/reader/LogFileReader.cpp
> +void LogFileReader::checkContainerType(LogFileOperator& op) {
FixLastFilePos和read时的LogFileOperator不是同一个。需要传进来

2024-04-02 11:54 UTC, henryzhx8 approved these changes

2024-04-29 13:07 UTC, yyuuttaaoo approved these changes

2024-04-30 01:24 UTC, merged