support flushing out data rather than stopping immediately on app exit
alibaba/ilogtail pull request #1395
Opened 2024-03-12 07:56 UTC by henryzhx8

2024-03-16 06:19 UTC, messixukejia requested changes

2024-03-16 06:19 UTC, messixukejia commented on core/common/LogtailCommonFlags.cpp
> +DEFINE_FLAG_BOOL(sidecar_mode, "", false);
退出前不存本地，需要发送这种模式可能不太能直接跟sidecar划等号，可能还有其他场景也需要，是不是应该抽象下？

2024-03-16 06:19 UTC, messixukejia commented on core/sender/Sender.cpp
> +    if (!BOOL_FLAG(sidecar_mode) && Application::GetInstance()->IsExiting()) // write local file avoid binary update fail
如果网络不稳定，发送极慢，会有什么影响？影响最终退出时间？

2024-03-18 13:29 UTC, yyuuttaaoo commented on core/event_handler/EventHandler.cpp
> +        if (!it->second.empty()) {
加这个注释？为啥要这么弄一下？

2024-03-18 13:29 UTC, yyuuttaaoo commented on core/event_handler/LogInput.cpp
> +        }
非sidecar_mode在mInteruptFlag+Application::GetInstance()->IsExiting()的时候也可以break出来？

2024-03-18 13:29 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> +            return true;
哪里的改动是修复这里需要额外一把flush的？

2024-03-19 03:56 UTC, henryzhx8 commented on core/event_handler/LogInput.cpp
> +        }
之前的设计里是input的循环是不会主动退出的，只会暂停

2024-03-19 04:00 UTC, henryzhx8 commented on core/sender/Sender.cpp
> +    if (!BOOL_FLAG(sidecar_mode) && Application::GetInstance()->IsExiting()) // write local file avoid binary update fail
常规模式下，一旦开始退出流程，所有缓存队列的数据全部写到本地磁盘，不再通过网络发送，所以网络对退出时间无影响；
新模式下，是强制发完所有数据后退出，如果网络问题导致发不出去，就会一直等着，直到K8s强制kill。这个是迅飞提的要求，发不出去就死等，而不是超时自动退出。

2024-03-19 05:57 UTC, henryzhx8 commented on core/sender/Sender.cpp
> +            return true;
已沟通

2024-03-19 08:16 UTC, yyuuttaaoo approved these changes

2024-03-22 02:14 UTC, messixukejia approved these changes

2024-03-22 02:29 UTC, merged