fix: refactor split state
alibaba/ilogtail pull request #1410
Opened 2024-03-19 11:27 UTC by Abingcbc

2024-03-19 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1410) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1410) before we can accept your contribution.<br/><hr/>**Abingcbc** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1410) it.</sub>

2024-03-20 02:17 UTC, henryzhx8 reviewed
feedlines相关的都删了，这个实际用不到，是个废指标

2024-03-20 02:17 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.h
> +    CounterPtr mProcSplittedEventsCnt;
IgnoreUnmatchWarning参数也要加一下，参照merge那个

2024-03-20 02:17 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.cpp
> +    mProcUnmatchedEventsCnt->Add(discardIndex.size());
118那个分支也加上error，和merge的219行一样。以后的原则就是，像这种是内部插件，用户是不能自己配的，所以一切都应该是预期的，出现预期外的行为，肯定是有什么大问题，所以必须打日志，而且是error级别的。

2024-03-20 03:22 UTC, henryzhx8 requested changes

2024-03-20 03:23 UTC, henryzhx8 reviewed
形式上和merge完全对齐，unmatch的时候就直接打印日志，不用再维护discardIndex之类的。

2024-03-21 02:04 UTC, Abingcbc commented on core/processor/ProcessorSplitRegexNative.cpp
> +                    multiStartIndex = endIndex + 1;
这之前的日志都被处理了，所以multiStartIndex需要向后移

2024-03-21 03:28 UTC, henryzhx8 requested changes
插件名称改成SplitMultilineLogStringNative

2024-03-21 03:28 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.cpp
> +void ProcessorSplitRegexNative::HandleSplittedLogs(const StringView& content,
名字改一下吧，CreateNewEvent

2024-03-21 03:28 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.cpp
>      if (!sourceEvent.HasContent(mSourceKey)) {
在hascontent前面再判断一下sourceEvent.size()是不是等于2，不等于的话，也告警和return

2024-03-21 03:28 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.cpp
> +    long sourceOffset = 0L;
不要使用非类型安全的整形，可以用uint32_t或者uint64_t

2024-03-21 03:28 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.h
> +    char mSplitChar = '\n';
是不是多余了？
```suggestion
```

2024-03-21 09:50 UTC, henryzhx8 requested changes

2024-03-21 09:50 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +                CreateNewEvent(content, sourceOffset, sourceKey, sourceEvent, logGroup, newEvents);
这里startindex不用赋值？万一是最后一行的话，循环外面的那段逻辑就出问题了

2024-03-21 09:50 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +                        // if only end pattern is given, start another log automatically
这里也不用赋值吗？

2024-03-21 09:50 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +    const char* multiStartIndex = sourceVal.data();
这个应该置为nullptr

2024-03-21 09:50 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +        isPartialLog = true;
加上multiStartIndex = sourceVal.data();

2024-03-21 09:50 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +    StringView sourceVal = sourceEvent.GetContent(mSourceKey);
这边等我event模型合进去以后，还要再微调，可以先FindContent，判断存不存在，然后it->second拿到内容。

2024-03-21 09:50 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +                        multiStartIndex = content.data() + content.size() + 1;
这里为什么要赋值？

2024-03-21 09:50 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +                        HandleUnmatchLogs(
这个分支不需要createEvent吗？

2024-03-22 02:22 UTC, henryzhx8 requested changes

2024-03-22 02:22 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.h
> +    bool mIgnoreUnmatchWarning = false;
```suggestion
    bool mIgnoringUnmatchWarning = false;
```
Init里面的参数也对应改下

2024-03-22 02:22 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +    const StringView& logPath = logGroup.GetMetadata(EventGroupMetaKey::LOG_FILE_PATH_RESOLVED);
```suggestion
    StringView logPath = logGroup.GetMetadata(EventGroupMetaKey::LOG_FILE_PATH_RESOLVED);
```

2024-03-22 02:22 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +                                                          const StringView& logPath,
```suggestion
                                                          StringView logPath,
```

2024-03-22 02:22 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +    if (sourceEvent.GetContents().size() != 2 || !sourceEvent.HasContent(mSourceKey)) {
这里写一下注释吧，说明内部插件，必有content和file offset字段

2024-03-22 02:22 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +        int endIndex = sourceVal[sourceVal.size() - 1] == '\n' ? sourceVal.size() - 1 : sourceVal.size();
这边确认一下最后一行是空行的情况是否符合预期

2024-03-22 02:22 UTC, henryzhx8 commented on core/unittest/processor/ProcessorSplitMultilineLogStringNativeUnittest.cpp
> +UNIT_TEST_CASE(ProcessorSplitMultilineLogDisacardUnmatchUnittest, TestLogSplitWithEnd);
这个宏最后不用加分号

2024-03-22 02:22 UTC, henryzhx8 commented on core/unittest/processor/ProcessorSplitMultilineLogStringNativeUnittest.cpp
> +    PipelineContext mContext;
private

2024-03-22 02:22 UTC, henryzhx8 commented on core/unittest/processor/ProcessorSplitMultilineLogStringNativeUnittest.cpp
> +    void SetUp() override { mContext.SetConfigName("project##config_0"); }
这个函数是protected，顺序还是public、protected、private

2024-03-22 02:22 UTC, henryzhx8 commented on core/unittest/processor/ProcessorSplitMultilineLogStringNativeUnittest.cpp
> +UNIT_TEST_MAIN
文件尾巴的空行一般都加上

2024-03-22 03:28 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.h
> +    bool mIgnoreUnmatchWarning = false;
这个参数挪到multilineoptions里去

2024-03-22 06:58 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +    StringView sourceVal = sourceIterator->second;
```suggestion
    // This is an inner plugin, so the size of log content must equal to 2 (sourceKey, __file_offset__)
    if (sourceEvent.Size() != 2) {
        newEvents.emplace_back(std::move(e));
        LOG_ERROR(mContext->GetLogger(),
                  ("unexpected error", "size of event content doesn't equal to 2")("processor", sName)(
                      "config", mContext->GetConfigName()));
        mContext->GetAlarm().SendAlarm(SPLIT_LOG_FAIL_ALARM,
                                       "unexpected error: size of event content doesn't equal to 2.\tprocessor: " + sName
                                           + "\tconfig: " + mContext->GetConfigName(),
                                       mContext->GetProjectName(),
                                       mContext->GetLogstoreName(),
                                       mContext->GetRegion());
        return;
    }
    
    auto sourceIterator = sourceEvent.FindContent(mSourceKey);
    if (sourceIterator == sourceEvent.end()) {
        newEvents.emplace_back(std::move(e));
        LOG_ERROR(mContext->GetLogger(),
                  ("unexpected error", "some events do not have the SourceKey")(
                      "processor", sName)("config", mContext->GetConfigName()));
        mContext->GetAlarm().SendAlarm(SPLIT_LOG_FAIL_ALARM,
                                       "unexpected error: some events do not have the sourceKey.\tprocessor: " + sName
                                           + "\tconfig: " + mContext->GetConfigName(),
                                       mContext->GetProjectName(),
                                       mContext->GetLogstoreName(),
                                       mContext->GetRegion());
        return;
    }
    StringView sourceVal = sourceIterator->second;

    auto offsetIterator = sourceEvent.FindContent(LOG_RESERVED_KEY_FILE_OFFSET);
    if (offsetIterator == sourceEvent.end()) {
        newEvents.emplace_back(std::move(e));
        LOG_ERROR(mContext->GetLogger(),
                  ("unexpected error", "event do not have key __file_ofset__")("processor", sName)(
                      "config", mContext->GetConfigName()));
        mContext->GetAlarm().SendAlarm(SPLIT_LOG_FAIL_ALARM,
                                       "unexpected error: event do not have key __file_ofset__.\tprocessor"
                                           + sName
                                           + "\tconfig: " + mContext->GetConfigName(),
                                       mContext->GetProjectName(),
                                       mContext->GetLogstoreName(),
                                       mContext->GetRegion());
        return;
    }
    uint32_t sourceOffset = atol(offsetIterator->second.data());
    
```

2024-03-22 07:01 UTC, henryzhx8 approved these changes

2024-03-25 07:03 UTC, yyuuttaaoo approved these changes

2024-03-25 09:03 UTC, henryzhx8 requested changes
1. 指标有误，需要完善一下
2. handleunmatch那边，只需打印第一条日志和有多少行不匹配就可以了

2024-03-26 08:16 UTC, henryzhx8 requested changes

2024-03-26 08:16 UTC, henryzhx8 commented on core/processor/ProcessorSplitMultilineLogStringNative.cpp
> +        if (fisrtLogSize <= 0) {
```suggestion
        if (fisrtLogSize == 0) {
```

2024-03-26 10:49 UTC, henryzhx8 approved these changes

2024-03-29 10:03 UTC, merged