feat: rate limit for history file import
alibaba/ilogtail pull request #1449
Opened 2024-04-11 08:20 UTC by Abingcbc

问题：采集后端可能无法处理太大的流量
解决：除了反馈队列之外，还需要给用户提供手动限流的配置。
通过类似于令牌桶的算法：
1. 每次申请token时，计算可用的token数量
2. 如果token足够，则通过
3. 否则计算所需要等待的时间，等待

## 效果
![compare](https://github.com/alibaba/ilogtail/assets/34068205/9dc90c64-ea12-434c-9883-cb9f40ec0a59)

2024-04-12 06:00 UTC, henryzhx8 approved these changes

2024-04-12 06:00 UTC, henryzhx8 commented on core/event_handler/HistoryFileImporter.h
> +    uint32_t mRate;
以后新代码里面类成员基础类型都要初始化

2024-04-12 06:00 UTC, henryzhx8 commented on core/event_handler/HistoryFileImporter.cpp
> +    double rateInBytesPerUs = rate / 1000000;
以后除法尽量少用，除非必要，效率和乘法差的很大

2024-04-12 06:00 UTC, henryzhx8 commented on core/event_handler/HistoryFileImporter.cpp
> +        usleep(waitTime);
以后2.0代码的sleep统一用std::this_thread::sleep

2024-04-13 01:31 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
> +    double rateInBytesPerUs = rate / 1000000;
这里应该能改成乘法吧

2024-04-15 02:15 UTC, Abingcbc commented on core/event_handler/HistoryFileImporter.h
> +    uint32_t mRate;
这个在构造函数里初始化了

2024-04-16 02:43 UTC, henryzhx8 approved these changes

2024-04-17 01:28 UTC, messixukejia requested changes

2024-04-17 01:28 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
> +        auto waitTime = ((bufferSize / rate) - (bufferSize / curRate)) * 1000000;
(bufferSize / curRate)) 这一部分可以改成乘法

2024-04-17 01:28 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
> +    if (curRate > rate) {
131、132行可以改成乘法的比较

2024-04-17 01:28 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
> +    static uint64_t lastPushBufferTime = GetCurrentTimeInMicroSeconds();
这个是不是可以改成成员变量？

2024-04-17 01:28 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
> +void HistoryFileImporter::FlowControl(uint32_t bufferSize, double rate) {
ut

2024-04-17 08:59 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
> +    double limitRateTime = bufferSize / rate * 1000000;
应该可以进一步把/移到 if (乘法){除法}中吧

2024-04-17 11:58 UTC, messixukejia approved these changes

2024-04-19 06:46 UTC, yyuuttaaoo commented on core/event_handler/HistoryFileImporter.cpp
> +        LOG_WARNING(sLogger, ("history wait", limitRateTime - realRateTime));
这句warning根据实测是不是会频繁打印？有无必要？
另外信息不太完整，没有说明wait的原因和wait的单位

2024-04-21 01:53 UTC, merged