fix: infinite retry container discovery
alibaba/ilogtail pull request #1454
Opened 2024-04-15 11:44 UTC by Abingcbc

问题：在某些场景下，容器运行时比iLogtail启动要慢很多。原有的初始化重试时间不够长。
解决：如果容器运行时发现初始化失败，那么后续的发现逻辑也不应该执行。PR中启动了一个独立的goroutine一直重试初始化，直至以下两种情况下成立：
1. 用户指定使用Containerd，且Containerd初始化成功
2. 用户不指定使用Containerd，且任意一种运行时初始化成功

2024-05-23 07:43 UTC, linrunqi08 approved these changes

2024-05-23 13:43 UTC, messixukejia commented on pkg/helper/docker_cri_adapter.go
> +	_, err = client.Status(ctx, &cri.StatusRequest{})
这里循环删掉的原因是？

2024-05-23 13:43 UTC, messixukejia commented on pkg/helper/docker_center.go
> +		}()
由串行改成了并行，getDockerCenterInstance函数return后有没有强依赖containerFindingManager初始化的行为？

2024-05-24 01:54 UTC, messixukejia commented on pkg/helper/docker_center.go
> +		}()
测试怎么测试的？ 至少这里需要加个sleep十分钟，在真实环境上进行下测试。

2024-05-24 01:58 UTC, messixukejia requested changes

2024-05-24 01:58 UTC, messixukejia commented on pkg/helper/docker_center.go
> +		}()
> 由串行改成了并行，getDockerCenterInstance函数return后有没有强依赖containerFindingManager初始化的行为？

并行初看是没有问题的。
1、补充下sleep的测试
2、这里加下注释，说明下 采集任务-容器上下文map-containerFindingManager 之间的关系，containerFindingManager初始化晚了不会应该整体流程。

2024-05-24 13:48 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +			containerFindingManager.SyncContainers()
这个SyncContainers可以顺便改一下名字，明明是StartSyncContainers的意思

2024-05-24 13:53 UTC, yyuuttaaoo requested changes

2024-05-24 13:53 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +			containerFindingManager.Init(3)
这里我感觉整个实现就不太对头，整个实现都应该在ContainerDiscoverManager里面，怎么是外面传进去呢？
Init的参数是重试几次的意思，这与外面无限重试是矛盾的，如果Init 3次失败了，最后还是没有达到目的，应该是Init成功才能结束无限循环。

2024-05-27 08:32 UTC, Abingcbc commented on pkg/helper/docker_center.go
> +		}()
测试的场景
![image](https://github.com/alibaba/ilogtail/assets/34068205/d15a20fc-97e5-440b-9e9b-c3368ade5f09)

2024-05-27 08:33 UTC, Abingcbc commented on pkg/helper/docker_cri_adapter.go
> +	_, err = client.Status(ctx, &cri.StatusRequest{})
因为外部有无限重试了，所以内部的重试可以省去了

2024-05-30 12:24 UTC, messixukejia approved these changes

2024-06-07 03:46 UTC, yyuuttaaoo requested changes

2024-06-07 03:46 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +				if IsCRIRuntimeValid(containerdUnixSocket) {
这段代码为什么不放到ContainerDiscoverManager.Init函数里面？

2024-06-07 05:35 UTC, Abingcbc commented on pkg/helper/docker_center.go
> +				if IsCRIRuntimeValid(containerdUnixSocket) {
这一段还有dockerCenterInstance尝试初始化client。把dockerCenterInstance的初始化放在ContainerDiscoverManager里面感觉也不太好？

2024-06-07 05:56 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +				if IsCRIRuntimeValid(containerdUnixSocket) {
没有吧，后面拆一下这个类把，比如拆分为ContainerRuntimeCenter和dockerRuntimeWrapper等

2024-06-07 08:03 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +			containerFindingManager = NewContainerDiscoverManager(false, false, false)
参数是不是不要了

2024-06-07 08:11 UTC, yyuuttaaoo approved these changes

2024-06-07 09:24 UTC, merged