summer-ospp-2024
alibaba/ilogtail pull request #1461
Opened 2024-04-23 07:30 UTC by Takuka0311

Add community events to docs，and add event summer-ospp-2024

2024-04-23 07:31 UTC, Takuka0311 commented
暂时不合入，待项目审批完成会再添加项目连接

2024-04-26 02:39 UTC, yyuuttaaoo approved these changes

2024-04-26 02:43 UTC, messixukejia requested changes

2024-04-26 02:43 UTC, messixukejia commented on docs/cn/README.md
>  * 知乎：[iLogtail社区](https://www.zhihu.com/column/c_1533139823409270785)
把最近的几篇2.0 spl的文章加到https://github.com/alibaba/ilogtail/blob/main/docs/cn/awesome-ilogtail/use-cases.md 吧

2024-04-26 02:43 UTC, messixukejia commented on docs/cn/README.md
>  * 知乎：[iLogtail社区](https://www.zhihu.com/column/c_1533139823409270785)
在阿里开发者公众号上找下

2024-04-26 02:43 UTC, messixukejia commented on docs/cn/events/summer-ospp-2024/README.md
> +* **04/30-06/04 学生报名、挑选项目、与导师沟通并准备项目申请材料、提交申请**
![image](https://github.com/alibaba/ilogtail/assets/13250519/04296ff7-2dbb-4fa7-b6e4-fa364248b641)
字体

2024-04-26 02:43 UTC, messixukejia commented on docs/cn/events/summer-ospp-2024/projects/ilogtail-io.md
> +普通
之前是不是提过意见把要求提高下，都是进阶？

2024-04-26 02:43 UTC, messixukejia commented on docs/cn/events/summer-ospp-2024/README.md
> +* **04/30-06/04 学生报名、挑选项目、与导师沟通并准备项目申请材料、提交申请**
自己preview页面看看效果

2024-04-28 08:54 UTC, Takuka0311 commented on docs/cn/events/summer-ospp-2024/projects/ilogtail-io.md
> +普通
是进阶，已订正

2024-04-28 08:55 UTC, Takuka0311 commented
补充了宣传视频和项目链接

2024-04-28 11:23 UTC, messixukejia commented on docs/cn/events/summer-ospp-2024/projects/ilogtail-io.md
> +普通
这种较低级的意见以后还是少被提出来

2024-04-28 11:23 UTC, messixukejia approved these changes

2024-04-28 11:23 UTC, merged