fix: support external plugins.
alibaba/ilogtail pull request #1462
Opened 2024-04-23 13:05 UTC by shunjiazhu

2024-04-24 02:24 UTC, henryzhx8 requested changes
这个方法确实可行，不过从通用性的角度，这就变相变成强制加载go插件了，内存上有点得不偿失。
最开始的设想是C++这边维护一份全量的Go插件列表，用于插件编排，不过现在这个能力弱化了，就只剩下判断插件是否有效了。所以我理解干脆把判定权全部下放到Go那边，C++这边不再维护Go插件列表了，这样是最简单的。

2024-04-24 02:29 UTC, shunjiazhu commented
因为考虑到有些场景，比如文件采集，用不到go插件。所以做了一个开关load_plugin_base，这样行为可以和ilogtail 2.0上一个版本保持一致了，然后字节自己打包的产物可以确保这个参数为true。

2024-04-24 02:39 UTC, henryzhx8 commented
> 因为考虑到有些场景，比如文件采集，用不到go插件。所以做了一个开关load_plugin_base，这样行为可以和ilogtail 2.0上一个版本保持一致了，然后字节自己打包的产物可以确保这个参数为true。

嗯，但是出包的时候这个参数值是一定的，不能假定用户用或者用不到Go插件。对于第三方用户，如果他也有自己的私有插件，他还得记得把这个参数给强制打开。这种架构上的设置最好不要分叉。

2024-04-24 02:41 UTC, shunjiazhu commented
> > 因为考虑到有些场景，比如文件采集，用不到go插件。所以做了一个开关load_plugin_base，这样行为可以和ilogtail 2.0上一个版本保持一致了，然后字节自己打包的产物可以确保这个参数为true。
> 
> 嗯，但是出包的时候这个参数值是一定的，不能假定用户用或者用不到Go插件。对于第三方用户，如果他也有自己的私有插件，他还得记得把这个参数给强制打开。这种架构上的设置最好不要分叉。

那完全移动到go之后，c++这边对插件进行编排这个能力是不是会丢失，我们也有预期想共建core的这部分能力

2024-04-24 02:54 UTC, henryzhx8 commented
> > > 因为考虑到有些场景，比如文件采集，用不到go插件。所以做了一个开关load_plugin_base，这样行为可以和ilogtail 2.0上一个版本保持一致了，然后字节自己打包的产物可以确保这个参数为true。
> > 
> > 
> > 嗯，但是出包的时候这个参数值是一定的，不能假定用户用或者用不到Go插件。对于第三方用户，如果他也有自己的私有插件，他还得记得把这个参数给强制打开。这种架构上的设置最好不要分叉。
> 
> 这个问题感觉通过更新一下脚本解决，
> 
> 1. c++还是维护一个默认的插件集合
> 2. 如果检测到external_plugins，脚本注入这个开关。
> 
> 因为完全移动到go之后，c++这边对插件进行编排这个能力是不是会丢失，我们也有预期想共建core的这部分能力，还是蛮重要的

你说的这个方案我觉得也是可行的，编译时注入，可能唯一的小缺点就是Go这边插件列表变了，C++部分也得重新编译，不过我理解iLogtail作为整体的话，全部重新编译也能接受。

2024-04-24 07:31 UTC, shunjiazhu commented
> > > > 因为考虑到有些场景，比如文件采集，用不到go插件。所以做了一个开关load_plugin_base，这样行为可以和ilogtail 2.0上一个版本保持一致了，然后字节自己打包的产物可以确保这个参数为true。
> > > 
> > > 
> > > 嗯，但是出包的时候这个参数值是一定的，不能假定用户用或者用不到Go插件。对于第三方用户，如果他也有自己的私有插件，他还得记得把这个参数给强制打开。这种架构上的设置最好不要分叉。
> > 
> > 
> > 这个问题感觉通过更新一下脚本解决，
> > 
> > 1. c++还是维护一个默认的插件集合
> > 2. 如果检测到external_plugins，脚本注入这个开关。
> > 
> > 因为完全移动到go之后，c++这边对插件进行编排这个能力是不是会丢失，我们也有预期想共建core的这部分能力，还是蛮重要的
> 
> 你说的这个方案我觉得也是可行的，编译时注入，可能唯一的小缺点就是Go这边插件列表变了，C++部分也得重新编译，不过我理解iLogtail作为整体的话，全部重新编译也能接受。

我改了一下构建脚本，辛苦再看一下。

2024-05-06 06:53 UTC, henryzhx8 commented on core/application/Application.cpp
> +    }
这些是不是都不需要了？

2024-05-08 03:19 UTC, closed without merging