refactor process queue element
alibaba/ilogtail pull request #1463
Opened 2024-04-24 09:38 UTC by henryzhx8

2024-05-04 08:47 UTC, messixukejia requested changes

2024-05-04 08:47 UTC, messixukejia commented on core/models/PipelineEventGroup.cpp
>      SetMetadataNoCopy(key, mSourceBuffer->CopyString(val));
CopyString 是否也一样去掉引用？

2024-05-04 08:47 UTC, messixukejia commented on core/models/LogEvent.h
> +    void SetMeta(uint32_t offset, uint32_t size) {
![image](https://github.com/alibaba/ilogtail/assets/13250519/f3e1bed1-4b9e-4883-a999-20ce6767ef1f)
Meta使用相同的结构。现在这种通过参数顺序的方式不便于后续扩展。

2024-05-04 08:47 UTC, messixukejia commented on core/processor/ProcessorSplitLogStringNative.cpp
> +    LOG_ERROR(mContext->GetLogger(),
这段error为什么不是所有的processor都加？如果都加是不是应该做到框架层面？

2024-05-04 08:47 UTC, messixukejia commented on core/event_handler/EventHandler.cpp
> +        PipelineEventGroup group{std::shared_ptr<SourceBuffer>(std::move(logBuffer->sourcebuffer))};
这些pipeline框架的改动，测试好性能影响

2024-05-04 08:47 UTC, messixukejia commented on core/event_handler/EventHandler.cpp
> +        group.SetMetadata(EventGroupMetaKey::LOG_FILE_INODE, ToString(reader->GetDevInode().inode));
把这些逻辑封装成一个函数吧，注释说明下原则

2024-05-04 08:47 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
>                  delete logBuffer;
delete的时机

2024-05-04 08:47 UTC, messixukejia commented on core/models/PipelineEventGroup.h
> -    HOST_IP,
去掉的原因是？

2024-05-04 08:47 UTC, messixukejia commented on core/processor/ProcessorSplitLogStringNative.cpp
> +        targetEvent->SetMeta(offset, length);
是否有对应的ut？

2024-05-04 08:47 UTC, messixukejia commented on core/processor/ProcessorTagNative.cpp
> +    const string& agent_tag = EnterpriseConfigProvider::GetInstance()->GetUserDefinedIdSet();
这个逻辑为什么变了？

2024-05-04 08:47 UTC, messixukejia commented on core/processor/ProcessorTagNative.cpp
> +    StringView filePath = logGroup.GetMetadata(EventGroupMetaKey::LOG_FILE_PATH);
跟这个pr无关的一件事情。最终要实现一套完整的meta、tag管理逻辑，支持选择重命名等，这个事情是不是没有任何地方在记录？这个要排上。

2024-05-04 08:47 UTC, messixukejia commented on core/CMakeLists.txt
> +        profile_sender queue reader sdk sender sls_control fuse
这个pr有些不兼容的变更以及meta tag划分的基本原则，找个时间评审下吧。

2024-05-04 15:27 UTC, linrunqi08 commented on core/models/PipelineEventGroup.h
> +    RangeCheckpointPtr GetExactlyOnceCheckpoint() const { return mExactlyOnceCheckpoint; }
这个现在实际还没有用到？只看到了数据写入

2024-05-04 15:27 UTC, linrunqi08 commented on core/processor/daemon/LogProcess.cpp
> +                                  const std::string& logstore,
这里单单放一个logstore好像也挺尴尬的，且没有什么拓展性

2024-05-04 15:27 UTC, linrunqi08 commented on core/processor/daemon/LogProcess.h
> +    bool PushBuffer(LogstoreFeedBackKey key,
感觉函数名是不是改成PushEventGroupToQueue会好一些，PushBuffer不知道是要向buffer推，还是推的是buffer，而且现在已经没有buffer的概念了

2024-05-04 15:27 UTC, linrunqi08 commented on core/processor/daemon/LogProcess.h
> +    bool ProcessBuffer(const std::shared_ptr<Pipeline>& pipeline,
同理，应该是ProcessEventGroups？

2024-05-06 03:35 UTC, henryzhx8 commented on core/models/PipelineEventGroup.h
> -    HOST_IP,
进程级信息因为是全局唯一的，所以没有必要放到group的metadata里，只需要在输出的地方放置（比如在tag processor里直接放到tag里，不需要tag和metadata存两份，减少压力）

2024-05-06 03:37 UTC, henryzhx8 commented on core/common/LogstoreFeedbackQueue.h
> +        if (mSize == HIGH_SIZE) {
这个没反，和之前逻辑保持一致的，高水位是包含关系，不是排除关系

2024-05-06 03:39 UTC, henryzhx8 commented on core/event_handler/EventHandler.cpp
> +    delete logBuffer;
不论是否为空，都需要把buffer删掉

2024-05-06 03:41 UTC, henryzhx8 commented on core/event_handler/HistoryFileImporter.cpp
> +                    readerSharePtr->GetLogstoreKey(), readerSharePtr->GetConfigName(), 0, std::move(group), 100000000);
这里还没改造完，先临时过渡一下，加个注释说明一下

2024-05-06 03:50 UTC, henryzhx8 commented on core/models/LogEvent.h
> +    void SetMeta(uint32_t offset, uint32_t size) {
这边是之前和迅飞讨论的结果，主要是两点考虑：
1. 目前log event只有这两个元数据，存在扩展的可能性很小
2. 改用通用结构的话，存储成本和查询成本都会上去，而且通用结构的map的值只能是个string，但offset和size又都是int，这就会增加额外的转换开销
具体可以和其它内容评审的时候一起再看一下

2024-05-06 03:55 UTC, henryzhx8 commented on core/models/PipelineEventGroup.h
> +    RangeCheckpointPtr GetExactlyOnceCheckpoint() const { return mExactlyOnceCheckpoint; }
用到了

2024-05-06 04:00 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.cpp
> +        targetEvent->SetMeta(offset, length);
有的，原来的那些ut会覆盖到

2024-05-06 04:02 UTC, henryzhx8 commented on core/processor/ProcessorTagNative.cpp
> +    const string& agent_tag = EnterpriseConfigProvider::GetInstance()->GetUserDefinedIdSet();
因为agent tag属于进程级信息，不再塞到group的metadata里了，而是直接用

2024-05-06 04:03 UTC, henryzhx8 commented on core/processor/daemon/LogProcess.cpp
> +                                  const std::string& logstore,
这个临时性的，flusher改造的时候会删掉的

2024-05-06 04:04 UTC, henryzhx8 commented on core/processor/daemon/LogProcess.h
> +    bool ProcessBuffer(const std::shared_ptr<Pipeline>& pipeline,
一样，中间阶段

2024-05-06 05:11 UTC, henryzhx8 commented on core/processor/daemon/LogProcess.h
> +    bool PushBuffer(LogstoreFeedBackKey key,
第三阶段会改

2024-05-06 05:12 UTC, henryzhx8 commented on core/queue/ProcessQueueItem.h
> +    size_t mInputIndex = 0;
第三阶段会用到，现在暂时没用，是用来标注这个数据包是从流水线的第几个input产生的

2024-05-06 05:13 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.cpp
> +              ("unexpected error", "unsupported log event")("processor", sName)("config", mContext->GetConfigName()));
这个是可以的，但是比较麻烦，涉及enum转string，理论上这个分支是进不去的，可以先放一下

2024-05-06 05:15 UTC, henryzhx8 commented on core/aggregator/Aggregator.cpp
> +                    || (value->mLines > logCountMin || value->mRawBytes > logGroupByteMin
这边等flusher改造的时候会统一加，目前的逻辑只是恢复到以前的状态

2024-05-07 15:42 UTC, yyuuttaaoo commented on core/common/memory/SourceBuffer.h
> +    StringBuffer CopyString(StringView s) { return CopyString(s.data(), s.length()); }
这个改动有什么好处

2024-05-07 16:37 UTC, yyuuttaaoo commented on core/models/LogEvent.h
> +    std::pair<uint32_t, uint32_t> GetMeta() const { return {mFileOffset, mRawSize}; }
这样写语义太模糊了

2024-05-07 16:46 UTC, yyuuttaaoo commented on core/event_handler/EventHandler.cpp
> +    delete logBuffer;
这个看起来原来是写得不太好，应该在外面delete或者直接用unique ptr

2024-05-07 17:03 UTC, yyuuttaaoo commented on core/processor/daemon/LogProcess.cpp
> +            uint64_t readBytes = item->mEventGroup.GetEvents()[0].Cast<LogEvent>().GetMeta().second
这里强转是暂时的，后面的PR会弄成通用的？

2024-05-08 01:35 UTC, henryzhx8 commented on core/common/memory/SourceBuffer.h
> +    StringBuffer CopyString(StringView s) { return CopyString(s.data(), s.length()); }
StringView是引用类型，传值的效率比传引用的效率高

2024-05-08 01:37 UTC, henryzhx8 commented on core/processor/daemon/LogProcess.cpp
> +            uint64_t readBytes = item->mEventGroup.GetEvents()[0].Cast<LogEvent>().GetMeta().second
这要等老的profile给替换成新的才行了，这里其实强转都是错的，其它input根本没有这个概念，所以自监控的优先级必须提上来

2024-05-10 13:59 UTC, messixukejia approved these changes

2024-05-10 13:59 UTC, messixukejia commented on core/event_handler/EventHandler.cpp
> +        time_t logtime = time(nullptr);
跟history的代码是不是一样的？封装一下？

2024-05-10 13:59 UTC, messixukejia commented on core/event_handler/HistoryFileImporter.cpp
>              readerSharePtr->ReadLog(*logBuffer, nullptr);
eventhandler中是unique_ptr<LogBuffer> logBuffer(new LogBuffer); 要不要统一下？

2024-05-10 13:59 UTC, messixukejia commented on core/reader/LogFileReader.cpp
> +    switch (mFileLogFormat) {
跟之前的代码一样引入些临时变量表示下含义吧。否则比较晦涩。

2024-05-13 01:57 UTC, linrunqi08 approved these changes

2024-05-13 02:04 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +    finalLine.fullLine = false;
这个结构申明是可以直接false吗？

2024-05-13 02:12 UTC, yyuuttaaoo requested changes

2024-05-13 02:12 UTC, yyuuttaaoo commented on core/processor/daemon/LogProcess.cpp
> +            if (item->mEventGroup.GetEvents()[0].Is<LogEvent>()) {
如果全部过滤了呢？

2024-05-13 02:12 UTC, yyuuttaaoo commented on core/processor/daemon/LogProcess.cpp
> +                for (auto& item : logGroupList[0]->logtags()) {
考虑全部过滤

2024-05-13 02:12 UTC, yyuuttaaoo commented on core/processor/daemon/LogProcess.cpp
> +                string convertedPath = item->mEventGroup.GetMetadata(EventGroupMetaKey::LOG_FILE_PATH).to_string();
这些是不是log特有的？在下一阶段去通用化吗？

2024-05-13 02:16 UTC, yyuuttaaoo approved these changes

2024-05-13 03:42 UTC, henryzhx8 commented on core/processor/daemon/LogProcess.cpp
> +                for (auto& item : logGroupList[0]->logtags()) {
前面logSize > 0保证有数据

2024-05-13 03:43 UTC, henryzhx8 commented on core/processor/daemon/LogProcess.cpp
> +                string convertedPath = item->mEventGroup.GetMetadata(EventGroupMetaKey::LOG_FILE_PATH).to_string();
不会通用化，这个是shennong profile依赖，要等可观测重构才行

2024-05-13 05:58 UTC, merged