update build image to decrease unittest size
alibaba/ilogtail pull request #1469
Opened 2024-04-29 07:59 UTC by Abingcbc

问题：每个单测用例，都需要静态链接复制一份unittest_base.a，导致整体编译结果达到了107GB。
解决方法：将公共部分unittest_base编译成动态链接库，整体编译结果缩小到了4.7GB。

2024-05-08 03:37 UTC, henryzhx8 requested changes

2024-05-08 03:37 UTC, henryzhx8 commented on core/CMakeLists.txt
> +option(BUILD_SPL_UT "Build spl unit test" ON)
这个改成dependent option

2024-05-08 03:37 UTC, henryzhx8 commented on core/CMakeLists.txt
> +if (BUILD_LOGTAIL_UT AND NOT BUILD_SPL_UT)
这里不需要BUILD_LOGTAIL_UT了

2024-05-08 03:37 UTC, henryzhx8 commented on core/CMakeLists.txt
> +    endif()
能不能用排除法？

2024-05-08 03:37 UTC, henryzhx8 commented on core/processor/CMakeLists.txt
> +if (LINUX AND ((BUILD_LOGTAIL_UT AND BUILD_SPL_UT) OR NOT BUILD_LOGTAIL_UT))
一样优化

2024-05-14 03:10 UTC, Abingcbc commented on docker/Dockerfile.ilogtail-build-linux
> +ENV LD_LIBRARY_PATH=/opt/logtail/deps/lib:$LD_LIBRARY_PATH
这个是解决protoc的报错
```
/opt/logtail/deps/bin/protoc: error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or directory
```
cmake的参数应该没法解决？

2024-05-16 01:57 UTC, henryzhx8 requested changes

2024-05-16 01:57 UTC, henryzhx8 commented on core/unittest/CMakeLists.txt
> +endif()
前边withoutspl都是有unix假设的，这边统一一下吧

2024-05-16 01:57 UTC, henryzhx8 commented on core/unittest/CMakeLists.txt
> +endif ()
一样

2024-05-16 01:57 UTC, henryzhx8 commented on core/dependencies.cmake
> +        if (WITHOUTSPL)
这边3个有特殊性是因为spl依赖吗？

2024-05-16 07:01 UTC, Abingcbc commented on core/dependencies.cmake
> +        if (WITHOUTSPL)
这个是因为编译时候这几个会链接错误

2024-05-16 07:27 UTC, yyuuttaaoo approved these changes

2024-05-16 07:29 UTC, henryzhx8 approved these changes

2024-05-16 08:35 UTC, merged