Feature: Add input_container_stdout C++ plugin
alibaba/ilogtail pull request #1470
Opened 2024-04-29 10:10 UTC by quzard

2024-05-04 14:35 UTC, messixukejia requested changes

2024-05-04 14:35 UTC, messixukejia commented on core/processor/daemon/LogProcess.cpp
> +    if (!eventGroup.HasMetadata(EventGroupMetaKey::LOG_FORMAT)) {
这里这段逻辑隐藏着非stdout的含义，有点太隐晦了。通过引入一些临时变量，让这个逻辑更明确一些吧。

2024-05-04 14:35 UTC, messixukejia commented on core/file_server/ContainerInfo.h
> +    std::vector<sls_logs::LogTag> mTags; // ContainerNameTag
这两个变量名有点歧义。而且跟整体规划的meta、tag也有点分不清。

2024-05-04 14:35 UTC, messixukejia commented on core/file_server/MultilineOptions.cpp
> +        if (mStartPatternRegPtr || mEndPatternRegPtr) {
else if？

2024-05-04 14:35 UTC, messixukejia commented on plugins/input/docker/rawstdout/input_docker_stdout.go
> +	for k, v := range ss.info.ContainerNameTag {
这里增加会有兼容性吗

2024-05-04 14:35 UTC, messixukejia commented on core/container_manager/ContainerDiscoveryOptions.cpp
> +            detail["LogPath"] = Json::Value(fileDiscovery->GetWildcardPaths()[0]);
越界风险

2024-05-04 14:35 UTC, messixukejia commented on core/controller/EventDispatcher.cpp
> +    string name = config->GetInputs()[0]->GetPlugin()->Name();
越界风险评估

2024-05-04 14:35 UTC, messixukejia commented on pkg/helper/docker_center.go
> +				if duration >= ContainerInfoDeletedTimeout {
判断调到其他变量之前？

2024-05-04 14:35 UTC, messixukejia commented on core/input/InputContainerLog.cpp
> +    for (int i = 0; i < 10; i++) {
为什么循环10？

2024-05-06 02:09 UTC, quzard commented on core/models/LogEvent.cpp
> +            SetContent(GetSourceBuffer()->CopyString(key), contents[key].asString());
这个是单测时用的，让每个key有自己的内存空间

2024-05-06 02:12 UTC, quzard commented on core/container_manager/ConfigContainerInfoUpdateCmd.h
> -    bool mUpdateAllFlag; // if this flag is true, clear this config's DockerContainerPath array and load all
mUpdateAllFlag这个逻辑，通过其他方式表达出来了，不需要专门设置个flag
![image](https://github.com/alibaba/ilogtail/assets/30899719/673fde0d-b266-4b18-b188-c3631886af3a)

2024-05-06 02:28 UTC, quzard commented on core/file_server/MultilineOptions.cpp
> +        if (mStartPatternRegPtr || mEndPatternRegPtr) {
mIsMultiline 默认为false 不需要else if

2024-05-06 02:32 UTC, quzard commented on core/container_manager/ContainerDiscoveryOptions.cpp
> +            detail["LogPath"] = Json::Value(fileDiscovery->GetWildcardPaths()[0]);
有个fileDiscovery->GetWildcardPaths().empty()的判断

2024-05-06 02:38 UTC, quzard commented on core/controller/EventDispatcher.cpp
> +    string name = config->GetInputs()[0]->GetPlugin()->Name();
这一步前面有判断

2024-05-06 02:49 UTC, quzard commented on pkg/helper/docker_center.go
> +				if duration >= ContainerInfoDeletedTimeout {
ContainerInfoDeletedTimeout 是由前面的变量算出来的

2024-05-06 02:50 UTC, quzard commented on core/input/InputContainerLog.cpp
> +    for (int i = 0; i < 10; i++) {
这段逻辑是从go里搬过来的。应该是对于软链接只允许递归查找10次

2024-05-06 03:58 UTC, quzard commented on core/input/InputContainerLog.cpp
> +// Licensed under the Apache License, Version 2.0 (the "License");
增加了

2024-05-06 04:00 UTC, quzard commented on plugins/input/docker/rawstdout/input_docker_stdout.go
> +	for k, v := range ss.info.ContainerNameTag {
这块代码原先在GetExternalTags里做的。现在GetExternalTags不做这块工作了，把他迁移出来了

2024-05-08 00:49 UTC, messixukejia commented on core/common/PathUtil.h
> + * Copyright 2024 iLogtail Authors
文档好像没加啊

2024-05-08 00:55 UTC, messixukejia commented on core/input/InputContainerLog.cpp
> +    for (int i = 0; i < 10; i++) {
对于容器普通文件采集的场景也测试下，另外看看门槛用例里是否有软链接的用例。

2024-05-08 01:40 UTC, quzard commented on core/common/PathUtil.h
> + * Copyright 2024 iLogtail Authors
![image](https://github.com/alibaba/ilogtail/assets/30899719/d96467a1-d9db-4424-978f-05b04fed9172)

2024-05-08 02:00 UTC, linrunqi08 commented on core/input/InputContainerLog.cpp
> +    // ParseByJSONObj 确保 mLogPath不会以\\或者/ 结尾
这里好像没有对\\处理？

2024-05-08 02:04 UTC, linrunqi08 commented on core/pipeline/Pipeline.cpp
> +    if (inputContainerLog) {
这种条件分支可以拆成单独的函数吗，感觉这个init函数有点太长了

2024-05-08 03:36 UTC, quzard commented on core/file_server/MultilineOptions.cpp
>  bool MultilineOptions::ParseRegex(const string& pattern, shared_ptr<boost::regex>& reg) {
优化行首正则性能，把尾巴的.*去除

2024-05-08 03:37 UTC, quzard commented on core/file_server/ContainerInfo.h
> +    static bool ParseByJSONObj(const Json::Value&, ContainerInfo&, std::string&);
mJson的m代表成员变量

2024-05-08 05:39 UTC, linrunqi08 approved these changes

2024-05-09 02:11 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +        std::cout << "mStringBuffer.insert" << std::endl;
delete debug code

2024-05-09 02:44 UTC, yyuuttaaoo commented on core/common/memory/SourceBuffer.h
> +    char* data;
可以改回去

2024-05-09 02:46 UTC, yyuuttaaoo commented on core/reader/LogFileReader.h
> +    static std::unique_ptr<SourceBuffer> mSourceBuffer;
不用static，因为类已经是static（相当于单例了）

2024-05-09 02:47 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +ContainerdTextParse LogFileReader::mContainerdTextParse = ContainerdTextParse();
static的应该以static开头

2024-05-09 03:10 UTC, yyuuttaaoo requested changes
见行内评论

2024-05-09 14:26 UTC, yyuuttaaoo approved these changes

2024-05-09 14:32 UTC, merged