support containerd on windows
alibaba/ilogtail pull request #1477
Opened 2024-05-08 07:30 UTC by Abingcbc

2024-05-08 07:39 UTC, linrunqi08 commented on pkg/helper/docker_cri_adapter_windows.go
> +	containerdUnixSocket  = `\\.\pipe\containerd-containerd`
跟windows相关的改动，单独抽出来，这样重复代码太多了

2024-05-08 07:39 UTC, linrunqi08 commented on pkg/helper/docker_cri_adapter_windows.go
> +var criRuntimeWrapper *CRIRuntimeWrapper
部署方面的改动注释里写一下

2024-05-09 06:49 UTC, linrunqi08 requested changes

2024-05-09 06:49 UTC, linrunqi08 commented on pkg/helper/cri_helper_windows.go
> +var containerdUnixSocket = `\\.\pipe\containerd-containerd`
这个可能变吗，用户如果不是这个路径呢

2024-05-09 06:49 UTC, linrunqi08 commented on pkg/helper/mount_windows.go
> +// DockerInstallPath should be set when the runtime is containerd.
注释里给个样例

2024-05-09 06:49 UTC, linrunqi08 commented on pkg/helper/mount_windows.go
> +// DockerInstallPath should be set when the runtime is containerd.
containerd里还依赖一个Docker的环境变量比较奇怪，感觉统一一下比较好

2024-05-09 06:49 UTC, linrunqi08 commented on pkg/helper/mount_windows.go
>  var DockerDataMountPath = flag.String(dockerDataMountPathFlagName, "C:\\ProgramData\\docker", "")
这两个变量的关系梳理一下吧，我们看看怎么把docker和containerd统一一下

2024-05-09 08:57 UTC, Abingcbc commented on pkg/helper/cri_helper_windows.go
> +var containerdUnixSocket = `\\.\pipe\containerd-containerd`
可以的，环境变量 CONTAINERD_SOCK_PATH 可以配置

2024-05-10 14:08 UTC, messixukejia commented on pkg/helper/mount_windows.go
> +		// Case: containerd, filePath is not start with driver letter. e.g. \\var\\logs\\pods\\xxx\\0.log
没有C: 盘符？

2024-05-10 14:08 UTC, messixukejia commented on pkg/helper/cri_helper_windows.go
> +//
除了测试containerd还要测试docker，改动不要影响到docker场景。

2024-05-11 02:07 UTC, Abingcbc commented on pkg/helper/cri_helper_windows.go
> +//
已经测试过，docker也可以正常运行

2024-05-11 02:08 UTC, Abingcbc commented on pkg/helper/mount_windows.go
> +		// Case: containerd, filePath is not start with driver letter. e.g. \\var\\logs\\pods\\xxx\\0.log
logpath这个值是直接保存的kubelet传进来的值，而在windows上启动容器时，会将进程的工作目录hardcode成了C盘。所以，无论是containerd写日志还是logtail读日志，都是在C盘下的。
![image](https://github.com/alibaba/ilogtail/assets/34068205/357a8336-c086-4357-b1f9-581b4ef69915)

2024-05-13 11:21 UTC, messixukejia approved these changes

2024-05-14 02:51 UTC, yyuuttaaoo approved these changes

2024-05-14 02:52 UTC, linrunqi08 approved these changes

2024-05-14 02:53 UTC, merged