refactor: self metric apis
alibaba/ilogtail pull request #1485
Opened 2024-05-14 13:24 UTC by shunjiazhu

重构自监控 API

2024-05-17 02:49 UTC, yyuuttaaoo commented on pkg/helper/self_metrics_vector_imp.go
> +		*buffer = append(*buffer, '|')
如果超过128字节会有问题吗

2024-05-17 03:00 UTC, yyuuttaaoo commented on pkg/helper/self_metrics_vector_imp.go
> +		v.bytesPool.Put(buffer)
如果buffer超过128B，put回去还对吗？

2024-05-17 03:37 UTC, shunjiazhu commented on pkg/helper/self_metrics_vector_imp.go
> +		v.bytesPool.Put(buffer)
没事的，Get方法中取出对象都会清空的。
*res = (*res)[:0]

2024-05-29 01:50 UTC, linrunqi08 requested changes

2024-05-29 01:50 UTC, linrunqi08 commented on pkg/pipeline/self_metrics.go
> +	Get() MetricValue[float64]
这里Get是纯获取语义吗，会重置计数吗

2024-05-29 01:50 UTC, linrunqi08 commented on pkg/pipeline/self_metrics.go
> +	Add(int64) error // return error when WithLabels returns an invalid metric.
WithLabels什么情况下会报错？

2024-05-29 01:50 UTC, linrunqi08 commented on pkg/pipeline/context.go
> +	GetMetricRecord() *MetricsRecord // for v1.8.8 compatible
这里是GetMetricRecord和RegisterMetricRecord放在一起了是吗，我觉得还是分开比较好，这样方便后面合入

2024-05-29 01:50 UTC, linrunqi08 commented on pkg/helper/self_metrics_v2_imp.go
> +func NewErrorMetric(metricType pipeline.SelfMetricType, err error) pipeline.Metric {
我感觉为了error实现一套接口，是不是有点得不偿失。在中间直接返回error会比较好？

2024-05-29 01:50 UTC, linrunqi08 commented on pkg/helper/self_metrics_v2_imp.go
> +func NewGauge(ms pipeline.MetricSet, index []string) pipeline.Gauge {
这个是不是可以替代self_metric_imp的实现了

2024-05-29 01:50 UTC, linrunqi08 commented on pkg/pipeline/context.go
> +			metric.Serialize(log)
Serialize()和Clear()分两步走是有问题的，非原子性。

2024-05-29 09:28 UTC, shunjiazhu commented on pkg/pipeline/self_metrics.go
> +	Add(int64) error // return error when WithLabels returns an invalid metric.
传入一个未定义的Label的时候，比如NewCounterVector的时候声明了[]string{status_code}

WithLabel({"invalid_label_name", "label_value"})就会返回一个ErrorMetric，"invalid_label_name"没有被声明过。

2024-05-30 11:16 UTC, shunjiazhu commented on pkg/pipeline/context.go
> +			metric.Serialize(log)
这是很好的提议，其实我们实践经验，metrics没必要有clear这个API，每次get都会清空状态。

2024-05-31 02:27 UTC, shunjiazhu commented on pkg/pipeline/self_metrics.go
> +	Get() MetricValue[float64]
目前是纯Get，因为对齐了此前的行为，其实改成重置计数会好一点

2024-06-01 14:33 UTC, shunjiazhu commented on pkg/pipeline/self_metrics.go
> +	Get() MetricValue[float64]
已经改好了

2024-06-01 14:33 UTC, shunjiazhu commented on pkg/pipeline/context.go
> +	GetMetricRecord() *MetricsRecord // for v1.8.8 compatible
好的，我加一下

2024-06-01 14:34 UTC, shunjiazhu commented on pkg/helper/self_metrics_v2_imp.go
> +func NewErrorMetric(metricType pipeline.SelfMetricType, err error) pipeline.Metric {
我简化了一下errorMetric的实现

2024-06-01 14:34 UTC, shunjiazhu commented on pkg/pipeline/context.go
> +			metric.Serialize(log)
嗯，已经改好了

2024-06-03 11:06 UTC, shunjiazhu commented on pkg/helper/self_metrics_v2_imp.go
> +func NewErrorMetric(metricType pipeline.SelfMetricType, err error) pipeline.Metric {
errorMetric改为打印日志，不再返回error

2024-06-12 11:01 UTC, shunjiazhu commented on pkg/helper/self_metrics_v2_imp.go
> +func (c *counterImp) Get() pipeline.MetricValue[float64] {
意思是同时保留 Get()和 GetAndReset()接口吗？

2024-06-17 01:34 UTC, linrunqi08 approved these changes

2024-06-17 03:14 UTC, yyuuttaaoo commented on pkg/helper/self_metrics_vector_imp.go
整体感觉层次还是比较多的，调用也有技巧，能否简单附一个开发者说明，比如只有固定label的用NewCounterMetricAndRegister，参考哪里的调用，需要可变label的用NewCounterMetricVectorAndRegister，参考哪里调用

2024-06-17 03:18 UTC, shunjiazhu commented on pkg/helper/self_metrics_v2_imp.go
> +	_ pipeline.CounterMetric = (*cumulativeCounterImp)(nil)
没啥含义，就确保这个特定类型实现了一些接口，方便IDE提示。然后万一后续接口变动，编译期间也能报错检查出问题。

2024-06-17 03:19 UTC, shunjiazhu commented on pkg/helper/self_metrics_v2_imp.go
> +func newMetric(metricType pipeline.SelfMetricType, metricSet pipeline.MetricSet, index []string) pipeline.Metric {
是的，我改成label values吧

2024-06-17 03:19 UTC, shunjiazhu commented on pkg/helper/self_metrics_vector_imp.go
可以，我加一下

2024-06-17 05:32 UTC, yyuuttaaoo commented on pkg/helper/self_metrics_v2_imp.go
> +	_ pipeline.CounterMetric = (*cumulativeCounterImp)(nil)
CounterMetric我看用了好多次其实没关系是吧？如果处于IDE这种特殊目的也在代码上备注一下吧

2024-06-17 05:40 UTC, yyuuttaaoo commented on pkg/helper/self_metrics_v2_imp.go
> +	_ pipeline.CounterMetric = (*cumulativeCounterImp)(nil)
CounterMetric我看用了好多次其实没关系是吧？如果处于IDE这种特殊目的也在代码上备注一下吧

2024-06-17 05:52 UTC, yyuuttaaoo commented on pkg/helper/self_metrics_v2_imp.go
> +	_ pipeline.CounterMetric = (*cumulativeCounterImp)(nil)
CounterMetric我看用了好多次其实没关系是吧？如果处于IDE这种特殊目的也在代码上备注一下吧

2024-06-17 07:48 UTC, shunjiazhu commented on pkg/helper/self_metrics_v2_imp.go
> +	_ pipeline.CounterMetric = (*cumulativeCounterImp)(nil)
嗯，没关系的

2024-06-17 16:39 UTC, yyuuttaaoo commented on docs/cn/developer-guide/plugin-development/plugin-self-monitor-guide.md
为了让文档能被看见，在 docs/cn/SUMMARY.md 中 开发者指南 部分加一下索引

2024-06-17 16:47 UTC, yyuuttaaoo approved these changes

2024-06-18 03:12 UTC, merged