Prevent circular dependency crash in YAML parsing (to #1503)
alibaba/ilogtail pull request #1507
Opened 2024-05-28 11:54 UTC by Takuka0311

解决配置yaml中存在循环依赖导致iLogtail core dump的问题。
解决issue #1503

2024-05-28 12:06 UTC, messixukejia requested changes

2024-05-28 12:17 UTC, Takuka0311 commented on core/common/YamlUtil.cpp
> +            if (std::find(visited.begin(), visited.end(), child.second) != visited.end()) {
不太一样。

从逻辑上来讲，现在yaml转json分两步：

* ParseYamlTable：前置检查、返回错误
* ConvertYamlToJson：检查完成后，把yaml一层层解析到json结构体中

循环依赖属于yaml写的有问题，应该在前置检查ParseYamlTable处把错误报出来，ConvertYamlToJson里不应该有任何报错。

2024-05-28 12:20 UTC, Takuka0311 commented on core/common/YamlUtil.cpp
> +            if (std::find(visited.begin(), visited.end(), child.second) != visited.end()) {
另外，从实现角度，逻辑解耦方便测试、调整。这个逻辑实现到ConvertYamlToJson中，会需要对现有ConvertYamlToJson逻辑做比较大修改

2024-05-28 12:23 UTC, messixukejia commented on core/common/YamlUtil.cpp
> +            if (std::find(visited.begin(), visited.end(), child.second) != visited.end()) {
ConvertYamlToJson 能加个层次的判断吗

2024-05-28 12:24 UTC, messixukejia commented on core/common/YamlUtil.cpp
> +            if (std::find(visited.begin(), visited.end(), child.second) != visited.end()) {
ConvertYamlToJson 能加个层次的判断吗

2024-05-28 12:28 UTC, Takuka0311 commented on core/common/YamlUtil.cpp
> +            if (std::find(visited.begin(), visited.end(), child.second) != visited.end()) {
需要对层数判断吗？

2024-05-28 12:30 UTC, Takuka0311 commented on core/common/YamlUtil.cpp
> +            if (std::find(visited.begin(), visited.end(), child.second) != visited.end()) {
目前循环的配置已经被拦截了，能传下去的配置必定是在有限层数内的

2024-05-29 02:08 UTC, henryzhx8 approved these changes

2024-05-29 03:09 UTC, messixukejia approved these changes

2024-05-29 06:20 UTC, yyuuttaaoo approved these changes

2024-05-29 06:22 UTC, merged