Add UseDecimal parameter to the service_canal plugin. When UseDecimal is set to true, the binlog parsing outputs the original DECIMAL format instead of scientific notation
alibaba/ilogtail pull request #1509
Opened 2024-05-28 14:58 UTC by quzard

参考链接：https://github.com/go-mysql-org/go-mysql/blob/6c99b4bff931a5aced0978b78aadb5867afcdcd3/canal/dump.go#L85

https://github.com/go-mysql-org/go-mysql/issues/475

目前现状，UseDecimal默认为false，当DECIMAL类型数据大于等于100000时，会转成科学计数法 例如 1e6.
看了底层实现，UseDecimal为false时会用fmt.Sprint，所以变成了科学计数法

2024-05-28 23:41 UTC, yyuuttaaoo approved these changes

2024-05-29 01:26 UTC, messixukejia requested changes

2024-05-29 01:26 UTC, messixukejia commented on plugins/input/canal/input_canal.go
> +	// True时 binlog解析DECIMAL输出原格式而非科学计数法, like:https://github.com/go-mysql-org/go-mysql/blob/6c99b4bff931a5aced0978b78aadb5867afcdcd3/canal/dump.go#L85
各种文档

2024-05-29 02:09 UTC, henryzhx8 approved these changes

2024-06-17 01:39 UTC, messixukejia commented on docs/cn/plugins/input/service-canal.md
> +| UseDecimal | Boolean，`false` | binlog解析DECIMAL时，是否输出原格式而非科学计数法。不设置时，默认为false，表示使用科学计数法。|
![image](https://github.com/alibaba/ilogtail/assets/13250519/15d61108-d12f-4bad-9eaf-ebfcd332a4a6)
细节把握

2024-06-17 01:41 UTC, messixukejia approved these changes

2024-06-17 01:45 UTC, quzard commented on docs/cn/plugins/input/service-canal.md
> +| UseDecimal | Boolean，`false` | binlog解析DECIMAL时，是否输出原格式而非科学计数法。不设置时，默认为false，表示使用科学计数法。|
修改了下注释

2024-06-17 03:07 UTC, messixukejia commented on plugins/input/canal/input_canal.go
> +	// True时 binlog解析DECIMAL输出原格式而非科学计数法, like:https://github.com/go-mysql-org/go-mysql/blob/6c99b4bff931a5aced0978b78aadb5867afcdcd3/canal/dump.go#L85
给一个意见是不是应该自己有意识全都检查下？

2024-06-17 07:24 UTC, merged