add ebpf framework
alibaba/ilogtail pull request #1510
Opened 2024-05-29 03:49 UTC by sunym1991

2024-05-29 07:26 UTC, messixukejia commented on core/ebpf/security/SecurityServer.cpp
> +// Licensed under the Apache License, Version 2.0 (the "License");
![image](https://github.com/alibaba/ilogtail/assets/13250519/25ac790f-6be2-4a60-90e3-77553c320c47)
这两个目录是不是有共用的部分？所以感觉不需要分目录了，直接通过文件名区分就可以了

2024-05-29 07:28 UTC, messixukejia approved these changes

2024-05-29 07:49 UTC, sunym1991 commented on core/ebpf/security/SecurityServer.cpp
> +// Licensed under the Apache License, Version 2.0 (the "License");
因为原先observer逻辑要全部重写到ebpf目录下，很多逻辑跟security无关的。所以先用子目录区分下，后期如果发现没有必要再合并

2024-05-30 01:47 UTC, yyuuttaaoo approved these changes

2024-05-30 01:49 UTC, merged

2024-05-30 01:51 UTC, henryzhx8 requested changes

2024-05-30 01:51 UTC, henryzhx8 commented on core/input/InputEbpfFileSecurity.h
> + * Copyright 2023 iLogtail Authors
2024

2024-05-30 01:51 UTC, henryzhx8 commented on core/input/InputEbpfFileSecurity.h
> +}
文件末尾都要有空行

2024-05-30 01:51 UTC, henryzhx8 commented on core/input/InputEbpfFileSecurity.h
> +    std::string mDetail;
整个配置是一个string？

2024-05-30 01:51 UTC, henryzhx8 commented on core/input/InputEbpfNetworkSecurity.h
> +
代码里多余的空行都去掉

2024-05-30 01:51 UTC, henryzhx8 commented on core/ebpf/security/SecurityServer.h
> +    void PauseInner();
```suggestion
```

2024-05-30 01:51 UTC, henryzhx8 commented on core/ebpf/security/SecurityOptions.h
> +    enum class Mode { xxx };
这个Mode如果只在这个类里用，放到private

2024-05-30 01:55 UTC, sunym1991 commented on core/input/InputEbpfFileSecurity.h
> +    std::string mDetail;
> 整个配置是一个string？

这个等具体开发时定，我只是写了个example