test: e2e and regression test
alibaba/ilogtail pull request #1512
Opened 2024-05-30 05:49 UTC by Abingcbc

2024-06-14 02:52 UTC, henryzhx8 approved these changes
目前是新老两套体系并行，老case待迁移至新体系中

2024-06-14 07:56 UTC, messixukejia requested changes

2024-06-14 07:56 UTC, messixukejia commented on test/cases/core/main_test.go
> +	config.TestConfig.KubeConfigPath = os.Getenv("KUBE_CONFIG_PATH")
1、框架统一
2、内外分离

2024-06-14 07:56 UTC, messixukejia commented on docs/cn/developer-guide/test/e2e-test.md
> -# E2E测试
说明后续删除，文件名、目录名具备标识性

2024-06-14 07:56 UTC, messixukejia commented on test/engine/boot/compose.go
> -	"github.com/alibaba/ilogtail/pkg/helper"
放到一级目录，表示后续删除

2024-06-14 07:56 UTC, messixukejia commented on test/engine/boot/compose.go
>  	"github.com/testcontainers/testcontainers-go/wait"
testhub->engine

2024-06-14 07:56 UTC, messixukejia commented on test/cases/core/scenarios/container_filter.feature
> +@input
新老两个目录

新目录
1、用例目录
2、engine目录
3、_test.go

文档：
1、用例开发
2、Engine增强

2024-06-29 14:52 UTC, messixukejia approved these changes

2024-06-29 14:52 UTC, messixukejia commented on docs/cn/developer-guide/test/e2e-test.md
> +# 插件E2E测试
说明下后续会下掉，统一为e2e-core-test

2024-06-29 14:52 UTC, messixukejia commented on scripts/dependency_licenses.sh
> +  	GOOS=${target%%/*} GOARCH=${target##*/} go list -deps -f '{{with .Module}}{{.Path}}@@@{{.Replace}}{{end}}' ./... >> "${output_file}-temp"
这里修改的目的是？

2024-06-29 14:52 UTC, messixukejia commented on test/README.md
> +| 行为类型 | 模板 | 参数 | 说明 |
本文件移到？
![image](https://github.com/alibaba/ilogtail/assets/13250519/584577c2-5fdc-4eba-bcf9-4651ac42ce6e)

2024-06-29 14:53 UTC, messixukejia approved these changes
提的几个意见再处理下即可

2024-06-30 16:23 UTC, Abingcbc commented on scripts/dependency_licenses.sh
> +  	GOOS=${target%%/*} GOARCH=${target##*/} go list -deps -f '{{with .Module}}{{.Path}}@@@{{.Replace}}{{end}}' ./... >> "${output_file}-temp"
之前是因为有个main.go，所以从main出发可以正确的识别所有用到的库。现在没有main了，需要整个包扫描一下。

2024-07-01 01:53 UTC, henryzhx8 requested changes
测试用例每个目录一个，不要拆开来

2024-07-01 01:53 UTC, henryzhx8 commented on docs/cn/developer-guide/test/e2e-test.md
这个文档应该在合适的位置链接另一个文档

2024-07-01 01:53 UTC, henryzhx8 commented on docs/cn/developer-guide/test/e2e-test-step.md
> +- [https://github.com/cucumber/godog](https://github.com/cucumber/godog)
删除

2024-07-03 04:07 UTC, henryzhx8 approved these changes

2024-07-03 04:08 UTC, merged