add config server proto v2
alibaba/ilogtail pull request #1516
Opened 2024-06-03 03:21 UTC by yyuuttaaoo

protobuf定义基本与讨论 #1491 中最后的结论一致。但有以下修改：
1. 放弃与v1版本的兼容，因为tags字段从string变更为AgentGroupTag，必然带来不兼容。
2. 删除了未定义行为的字段，和高度重复的结构，简化proto定义。
后续兼容策略：
1. proto v2与v1在不同命名空间，故可以在1个binary中共存
2. config server v1版本特性depreciated，在半年后彻底删除
3. 当v2版本client和server都完成后，默认切换到v2，使用v1需打开兼容开关

2024-06-03 03:32 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +    RequestFlagsUnspecified = 0;
心跳请求是否需要flag标识当前为压缩心跳or未压缩，比如：ReportFullState？

2024-06-03 03:35 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +// API: /Agent/HeartBeat/
跟README里的API不一致

2024-06-03 03:39 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +    ConfigStatus status = 3; // Config's status
需要上报config error message吗

2024-06-03 03:47 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +    string instance_id = 2;                 // Required, Agent's unique identification
instance_id目前是没有用到的，还需要保留不

2024-06-03 03:59 UTC, yyuuttaaoo commented on config_server/protocol/v2/agent.proto
> +    RequestFlagsUnspecified = 0;
确实会更明确一些，比判断Attributes是否存在更直接。加。

2024-06-03 04:00 UTC, yyuuttaaoo commented on config_server/protocol/v2/agent.proto
> +    ConfigStatus status = 3; // Config's status
我觉得可以在可观测的链路那边加详情，这里只保留状态

2024-06-03 04:01 UTC, yyuuttaaoo commented on config_server/protocol/v2/agent.proto
> +    string instance_id = 2;                 // Required, Agent's unique identification
那就删掉。

2024-06-03 04:28 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +    string instance_id = 2;                 // Required, Agent's unique identification
> 会不会没有的话，不方便定位问题？

所以建议instance_id都放在query里，放body里只有服务端识别，query里整个请求链路都能感知

2024-06-03 04:58 UTC, yyuuttaaoo commented on config_server/protocol/v2/agent.proto
> +    ConfigStatus status = 3; // Config's status
还是加了一个，语义是明确的，可选填充吧。

2024-06-03 09:12 UTC, Takuka0311 commented
这个协议放在了v2的目录下，之前的要不要转移到一个“v1”的目录？

2024-06-03 09:34 UTC, yyuuttaaoo commented
> 这个协议放在了v2的目录下，之前的要不要转移到一个“v1”的目录？

2024-06-03 09:55 UTC, messixukejia requested changes

2024-06-03 09:55 UTC, messixukejia commented on config_server/protocol/v2/README.md
> +
目录的组织跟之前调整成评级？

2024-06-03 09:55 UTC, messixukejia commented on config_server/protocol/v2/README.md
> +
跟V1的差异性

2024-06-03 09:55 UTC, messixukejia commented on config_server/protocol/v2/agent.proto
> +enum ConfigStatus {
PipelineConfig?

命名：AgentConfig、PipelineConfig
如果两者通用共用的，才叫Config？

2024-06-11 08:41 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +option go_package = ".;configserver_proto_v2";
`.;configserver_proto_v2` -> `./configserver_proto_v2` or `/configserver_proto_v2` ?

2024-06-11 08:58 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +enum ResponseFlags {
AgentConfigResponse 里没有ResponseFlags跟ServerCapabilities，不需要了？

2024-06-11 08:59 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +    uint64 flags = 13;                          // Predefined command flag
uint64 flags -> RequestFlags flags ?

2024-06-11 09:01 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +// API: /Agent/GetAgentConfig
感觉还是Heartbeat更贴切点？GetAgentConfig要怎么理解呢

2024-06-11 09:08 UTC, PapaPiya commented on config_server/protocol/v2/README.md
> +        int32 code = 2;
感觉v1里的RespCode意义比较明确。用int32的话可能还需要定义下success/error code?

2024-06-11 09:41 UTC, yyuuttaaoo commented on config_server/protocol/v2/agent.proto
> +enum ResponseFlags {
这里定义的是enum，使用的时候可以多个Flag | Flag起来

2024-06-11 09:41 UTC, yyuuttaaoo commented on config_server/protocol/v2/agent.proto
> +// API: /Agent/GetAgentConfig
可以

2024-06-11 09:51 UTC, yyuuttaaoo commented on config_server/protocol/v2/README.md
> +        int32 code = 2;
我觉得可以约定一个成功的code，错误的行为定义为打印错误并稍后重试？所以也不用太关心具体值

2024-06-11 10:36 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +    uint64 flags = 13;                          // Predefined command flag
> 可以多值，set多个bit

got

2024-06-11 10:38 UTC, PapaPiya commented on config_server/protocol/v2/agent.proto
> +enum ResponseFlags {
AgentConfigResponse里缺少flags跟capabilities字段

2024-06-11 10:40 UTC, PapaPiya commented on config_server/protocol/v2/README.md
> +        int32 code = 2;
> 我觉得可以约定一个成功的code，错误的行为定义为打印错误并稍后重试？所以也不用太关心具体值

对，需要有个约定。

2024-06-11 10:49 UTC, messixukejia approved these changes

2024-06-11 10:49 UTC, messixukejia commented on config_server/protocol/v2/README.md
> +本规范定义了 Agent 管控网络协议以及 iLogtail 和 Config Server 的预期行为。
从全局来看 Config Server 命名不统一，空格，大小写要注意下

2024-06-12 12:28 UTC, PapaPiya approved these changes

2024-06-12 12:38 UTC, merged