improve Android compatibility
alibaba/ilogtail pull request #1518
Opened 2024-06-03 10:45 UTC by alph00

2024-06-07 03:02 UTC, henryzhx8 requested changes

2024-06-07 03:02 UTC, henryzhx8 commented on core/dependencies.cmake
> +if(NOT ANDROID)
这里不需要

2024-06-07 03:02 UTC, henryzhx8 commented on core/logtail.cpp
> +#endif
这里删除，不要写死

2024-07-26 23:03 UTC, messixukejia commented on core/dependencies.cmake
> +        target_link_libraries(${target_name} z)
z的含义是？

2024-07-26 23:03 UTC, messixukejia commented on core/logtail.cpp
> +#if !defined(__ANDROID__)
开源也要加这个条件的必要性是？

2024-07-29 01:35 UTC, alph00 commented on core/dependencies.cmake
> +        target_link_libraries(${target_name} z)
zlib在安卓的ndk里有内置的库，库名就叫 z

2024-07-29 02:40 UTC, alph00 commented on core/logtail.cpp
> +#if !defined(__ANDROID__)
如果是安卓上使用开源版的话，也是需要把运行目录和运行时文件存放目录分开，否则跑不起来

2024-07-30 03:46 UTC, henryzhx8 approved these changes

2024-07-30 03:46 UTC, henryzhx8 commented on core/logtail.cpp
>      STRING_FLAG(logtail_sys_conf_dir) = ".";
那开源这个环境变量的值默认是商业版那个？如果是这样的话，这个值在安卓场景下应该是必填项？不填工作不了

2024-07-30 03:46 UTC, henryzhx8 commented on core/common/RuntimeUtil.cpp
> +#elif defined(__linux__)
注释一下原因

2024-07-30 03:46 UTC, henryzhx8 requested changes
有些问题再看一下

2024-07-30 03:56 UTC, alph00 commented on core/logtail.cpp
>      STRING_FLAG(logtail_sys_conf_dir) = ".";
目前是没有默认值，是要必填的。因为之前是把路径写到/data/data/com.example.logtail_for_android/files这个目录，这个目录直接设成默认值感觉不太合适？
或者再加一下命令行提示告知logtail_sys_conf_dir必填？

2024-07-30 08:49 UTC, alph00 commented on core/common/RuntimeUtil.cpp
> +#elif defined(__linux__)
已经修改

2024-07-30 13:12 UTC, messixukejia commented on core/logtail.cpp
> +#if !defined(__ANDROID__)
这个删掉吧，通过运行时脚本配置解决

2024-08-01 01:52 UTC, alph00 commented on core/logtail.cpp
> +#if !defined(__ANDROID__)
已经修改

2024-08-02 09:06 UTC, henryzhx8 approved these changes

2024-08-06 12:00 UTC, merged