feat: add ebpf input
alibaba/ilogtail pull request #1536
Opened 2024-06-13 04:01 UTC by alph00

Add six inputs, two input servers, and several process-level settings for security and observability with ebpf

2024-06-13 09:56 UTC, henryzhx8 commented on core/common/ParamExtractor.cpp
> +bool GetOptionalDoubleParam(const Json::Value& config, const string& key, double& param, string& errorMsg) {
一样加了，把mandatory的也加了

2024-06-13 09:58 UTC, henryzhx8 commented on core/common/ParamExtractor.h
> +bool IsMapValid(const Json::Value& config, const std::string& key, std::string& errorMsg);
这两个在哪用的？

2024-06-13 11:41 UTC, henryzhx8 requested changes
1. 各个插件的参数之间并没有很明显的复用，完全没有必要统统都放到xxxOptions里去解析，应该直接放在插件类里面自己去解析。
2. 各种filter之间不要强行用继承，更合适的是variant，但是这里必要性不强，直接在server里搞3个map并没有什么不妥。

2024-06-13 11:41 UTC, henryzhx8 commented on core/input/InputEbpfFileSecurity.h
> +    SecurityOptions mSecurityOptions;
外部可配置的参数都是public

2024-06-13 11:41 UTC, henryzhx8 commented on core/ebpf/security/SecurityOptions.h
> +    std::vector<SecurityFileFilterItem*> mFileFilterItem;
为什么要用指针？代码里不允许使用裸指针，可以用类解决的不要用指针。

2024-06-14 01:27 UTC, messixukejia commented on config_server/protocol/README.md
> +ConfigServer管控协议的总贴、V1版本协议说明和翻新至V2的讨论参见
为什么多出怎么多不想关的内容

2024-06-14 01:58 UTC, closed without merging