add ebpf input
alibaba/ilogtail pull request #1540
Opened 2024-06-14 02:28 UTC by alph00

Add six inputs, two input servers, and several process-level settings for security and observability with ebpf

2024-06-14 06:51 UTC, messixukejia requested changes

2024-06-14 06:51 UTC, messixukejia commented on core/CMakeLists.txt
>          aggregator application app_config checkpoint common config config/provider config/watcher config_manager config_server_pb
文档

2024-06-14 06:51 UTC, messixukejia commented on core/app_config/AppConfig.cpp
> +        if (!GetOptionalStringParam(thisConverageConfig, "Strategy", mConverageConfig.mStrategy, errorMsg)) {
string 类型的如果配了取值范围外的字符串，需要考虑下

2024-06-14 06:51 UTC, messixukejia commented on core/app_config/AppConfig.h
> +        std::string mStrategy = "fixedRate";
有效字符串取值用宏或者常量来表示

2024-06-14 06:51 UTC, messixukejia commented on core/input/InputEbpfProcessSecurity.cpp
>  #include "input/InputEbpfProcessSecurity.h"
eBPF 标准大小写

2024-06-14 06:51 UTC, messixukejia commented on core/ebpf/observer/ObserverOptions.cpp
> +            // EnableProtocols (Mandatory)
Mandatory 代码实现上怎么体现的？这里只写了注释。

2024-06-14 06:51 UTC, messixukejia commented on core/ebpf/security/SecurityOptions.cpp
> +                    if (!GetMandatoryStringParam(
![image](https://github.com/alibaba/ilogtail/assets/13250519/b398c262-9f46-4bbe-85d4-cc9f47065291)
 这里的type改个名字？防止不同层面字段重名。

2024-06-14 06:51 UTC, messixukejia commented on core/ebpf/security/SecurityOptions.cpp
> +                if (!GetMandatoryStringParam(fileFilterItem, "FilePath", thisFileFilterItem.mFilePath, errorMsg)) {
这个函数巨长无比，适当切分下

2024-06-14 06:58 UTC, alph00 commented on core/ebpf/observer/ObserverOptions.cpp
> +            // EnableProtocols (Mandatory)
下面一行会根据参数是否Mandatory来使用不同的函数

2024-06-17 06:25 UTC, henryzhx8 requested changes

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverOptions.cpp
> +            if (!GetOptionalBoolParam(
mandatory为啥还是optional？

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverOptions.h
> +class ObserverProcess {
加上Options后缀，直接改用struct，下同

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/security/SecurityOptions.h
> +};
注意空行

2024-06-17 06:25 UTC, henryzhx8 commented on core/pipeline/Pipeline.h
> +    friend class InputEbpfFileSecurityUnittest;
这些为什么要加？

2024-06-17 06:25 UTC, henryzhx8 commented on core/plugin/PluginRegistry.cpp
> +#include "input/InputEbpfProcessSecurity.h"
这些在windows下能用？应该只能linux下吧，android也不行，所以所有相关的内容都应该像以前的observer一样，加上宏控制。

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverServer.h
> +    bool mStop;
系统类型一律要初始化，而且名字要能直观表达意思，一般最好以默认值为false的表述，IsThreadRunning或Stopped

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverServer.h
> +    std::unordered_map<std::string, const ObserverOptions*> mInputMap;
mInputOptionsMap

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverServer.h
> +    std::unordered_map<std::string, const PipelineContext*> mInputContextMap;
两个map合一块吧，像file server一样，这样避免两次查询

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverServer.h
> +    void AddObserverOption(const PipelineContext* context, size_t index, const ObserverOptions* option);
虽然configname可以从ctx里那，但是这个接口设计就和remove不一致了，所以还是显式地把configname参数加上

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverServer.h
> +    std::unordered_map<std::string, const PipelineContext*> mInputContextMap;
这两个数据结构要不要加锁？如果不加锁，意味着你配置变更的时候，是不能发数据的，如果相互不影响的话，肯定得加锁，这个结合具体业务场景决定，但不应该忽视。

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/observer/ObserverServer.cpp
> +        initialized = true;
这两个参数能不能合并？

2024-06-17 06:25 UTC, henryzhx8 commented on core/ebpf/security/SecurityServer.h
> +    bool mStop;
observer那边的问题这里一样，不重复说了

2024-06-18 02:43 UTC, alph00 commented on core/ebpf/observer/ObserverServer.h
> +    std::unordered_map<std::string, const PipelineContext*> mInputContextMap;
目前配置更新时，会停止ebpf探针、重新加载配置并启动ebpf探针，所以不会有影响。后续优化时需要考虑下加锁的问题

2024-06-18 02:48 UTC, alph00 commented on core/app_config/AppConfig.cpp
> +        if (!GetOptionalStringParam(thisConverageConfig, "Strategy", mConverageConfig.mStrategy, errorMsg)) {
这部分取值范围应该是由ebpf端那边确定，他们说是之后再来优化这个点

2024-06-18 04:02 UTC, alph00 commented on core/pipeline/Pipeline.h
> +    friend class InputEbpfFileSecurityUnittest;
目前是因为ebpf input的单测需要给pipeline私有变量赋值，是仿原来的file_input的单测写的，这里要改吗

2024-06-18 09:29 UTC, alph00 commented on core/CMakeLists.txt
>          aggregator application app_config checkpoint common config config/provider config/watcher config_manager config_server_pb
已经新增6个输入插件的文档，内容还不太完善

2024-06-18 11:38 UTC, henryzhx8 commented on core/ebpf/observer/ObserverServer.h
> +    std::unordered_map<std::string, const PipelineContext*> mInputContextMap;
了解，那就不用改了

2024-06-18 11:38 UTC, henryzhx8 commented on core/pipeline/Pipeline.h
> +    friend class InputEbpfFileSecurityUnittest;
了解，那就不用改了

2024-06-18 11:49 UTC, henryzhx8 requested changes

2024-06-18 11:49 UTC, henryzhx8 commented on core/ebpf/observer/ObserverOptions.cpp
> +    if (!GetOptionalStringParam(
这里还是不对啊，mandatory对应的是error_return，optional是warning_default或ignore

2024-06-18 12:32 UTC, messixukejia approved these changes

2024-06-18 12:32 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-file-observer.md
> +
文档目录没有链接。参考：https://github.com/alibaba/ilogtail/commit/1028ee56d8bb04f13bbf959dfeb0f9ccb669d818

2024-06-19 06:08 UTC, sunym1991 approved these changes

2024-06-19 09:23 UTC, henryzhx8 approved these changes

2024-06-19 09:23 UTC, henryzhx8 commented on core/ebpf/observer/ObserverOptions.cpp
> +                              BOOL_DEFAULT,
改成参数默认值

2024-06-19 09:23 UTC, henryzhx8 commented on core/ebpf/observer/ObserverOptions.cpp
> +                              STRING_DEFAULT,
直接ignore

2024-06-21 01:57 UTC, merged