Centralize subdirectory CMakeLists into a centralized file
alibaba/ilogtail pull request #1559
Opened 2024-06-24 08:39 UTC by alph00

2024-06-25 02:16 UTC, messixukejia commented on core/CMakeLists.txt
>      add_definitions(-DNOMINMAX)
PR养成习惯，补充下描述。背景、开发内容简介、收益

2024-06-25 11:48 UTC, yyuuttaaoo commented on core/CMakeLists.txt
> +    file(GLOB TEMP_SOURCE_FILES ${DIR_NAME}/*.c ${DIR_NAME}/*.cc ${DIR_NAME}/*.cpp)
感觉不能foreach (DIR_NAME ${SUB_DIRECTORIES_LIST})不做区分全部加入，还是要分一下，应该都是正向加入source的逻辑，避免出现大量REMOVE_ITEM。

2024-06-25 11:53 UTC, yyuuttaaoo commented on core/CMakeLists.txt
> +    add_definitions(-DPSAPI_VERSION=1)
这为什么新加？

2024-06-25 12:28 UTC, alph00 commented on core/CMakeLists.txt
> +    add_definitions(-DPSAPI_VERSION=1)
这里是在整理子目录CMakeList的时候扒上来的

2024-06-25 12:42 UTC, alph00 commented on core/CMakeLists.txt
> +    file(GLOB TEMP_SOURCE_FILES ${DIR_NAME}/*.c ${DIR_NAME}/*.cc ${DIR_NAME}/*.cpp)
目前这块的逻辑是按照旧的子目录的正向、反向逻辑整理出来的
大部分的REMOVE_ITEM在不同的操作系统里有不同的表现，而且所处的子目录其他未被REMOVE的文件还不少，改成正向的APPEND有点困难
而且这里我理解直接REMOVE掉 os 不匹配的文件更合理一点吧？如果反过来的话那不就每次在相关子目录里新增一个文件就得在CMakeList里加一下

2024-06-26 11:13 UTC, henryzhx8 requested changes
input、processor、flusher、common目录的内容单独放到一个cmake里，include进来，保持主cmake的干净

2024-06-27 06:32 UTC, messixukejia approved these changes

2024-06-27 16:41 UTC, yyuuttaaoo approved these changes

2024-07-01 03:48 UTC, henryzhx8 requested changes

2024-07-01 03:48 UTC, henryzhx8 commented on core/CMakeLists.txt
> +    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/observer)
后边改用target_include_directories

2024-07-01 03:48 UTC, henryzhx8 commented on core/links.cmake
dependency.cmake应该改成add_library(IMPORTED),set_target_options指定路径，然后link这边直接target_link_libraries

2024-07-01 03:48 UTC, henryzhx8 commented on core/CMakeLists.txt
>          set(SUB_DIRECTORIES_LIST ${SUB_DIRECTORIES_LIST} shennong streamlog)
商业版的这些目录怎么处理？是否编译过？

2024-07-01 03:51 UTC, henryzhx8 reviewed
input、processor、flusher目录下面应该还要有一个dependency.cmake，用于指定插件所需要的依赖库，这些信息应该从主cmake里移除。
举个例子，link spl这个操作就应该放到那个文件里

2024-07-02 10:00 UTC, alph00 commented on core/CMakeLists.txt
>          set(SUB_DIRECTORIES_LIST ${SUB_DIRECTORIES_LIST} shennong streamlog)
拷到商业版上编译了一下。已经修复问题，目前可以正常编译

2024-07-02 10:00 UTC, alph00 commented on core/CMakeLists.txt
> +    include_directories(${CMAKE_CURRENT_SOURCE_DIR}/observer)
resolve later

2024-07-02 10:00 UTC, alph00 commented on core/links.cmake
resolve later

2024-07-10 11:06 UTC, henryzhx8 requested changes

2024-07-10 11:06 UTC, henryzhx8 commented on core/CMakeLists.txt
> +    flusher_link(${LOGTAIL_TARGET})
不用再专门搞个宏了，直接在这里include三个文件就行了

2024-07-11 01:59 UTC, henryzhx8 approved these changes

2024-07-11 02:00 UTC, merged