support configServer V2
alibaba/ilogtail pull request #1592
Opened 2024-07-05 07:04 UTC by quzard

2024-07-08 08:52 UTC, PalanQu commented
请问配置同步功能是否可以支持在ilogtail agent启动的时候指定一些环境变量的key，然后将key与环境变量的值作为一组label上传到config server，config server可以通过这些key对group进行管控？

2024-07-10 04:55 UTC, quzard commented
> 请问配置同步功能是否可以支持在ilogtail agent启动的时候指定一些环境变量的key，然后将key与环境变量的值作为一组label上传到config server，config server可以通过这些key对group进行管控？

有个FillAttributes，可以重载该函数来自定义实现这部分

2024-07-16 04:37 UTC, messixukejia requested changes

2024-07-16 04:37 UTC, messixukejia commented on core/config/provider/CommonConfigProvider.cpp
> +    auto HeartbeatResponse = SendHeartbeat(heartbeatRequest);
网络交互都可能失败，得考虑异常情况。特别是偶尔异常时的行为是什么

2024-07-16 05:06 UTC, quzard commented on core/config/provider/CommonConfigProvider.cpp
> +DEFINE_FLAG_INT32(heartbeat_update_interval, "second", 10);
原来的config_update_interval参数在LegacyCommonConfigProvider里。

2024-07-16 05:09 UTC, quzard commented on core/config/provider/CommonConfigProvider.cpp
> +    auto HeartbeatResponse = SendHeartbeat(heartbeatRequest);
异常的时候返回的HeartbeatResponse是empty，不会影响当前的正常运行。

2024-07-16 05:37 UTC, quzard commented on core/config/provider/CommonConfigProvider.cpp
> +    LoadConfigFile();
这个函数内部加载文件时会有一些warning日志打出。他本身不需哟错误码。

2024-07-16 05:41 UTC, messixukejia requested changes

2024-07-16 05:41 UTC, messixukejia commented on core/config/feedbacker/ConfigFeedbackReceiver.cpp
> +    mCommandFeedbackableMap[type + '\1' + name] = feedbackable;
为什么 type + '\1' + name 散落在各处这种描述

2024-07-16 05:54 UTC, quzard commented on core/config/feedbacker/ConfigFeedbackReceiver.cpp
> +    mCommandFeedbackableMap[type + '\1' + name] = feedbackable;
加了个GenerateCommandFeedBackKey

2024-07-16 09:59 UTC, messixukejia commented on core/unittest/config/ConfigUpdatorUnittest.cpp
> +    unordered_map<string, PipelineConfig*>::iterator it = configMap.find("commonreg.com");
![image](https://github.com/user-attachments/assets/cd80503b-06d3-4d78-9b42-385fb62507e6)
这两个文件名？

2024-07-16 10:30 UTC, yyuuttaaoo commented on core/application/Application.cpp
> +    {
这部分代码下一步抽离到LocalProvider的Init里。

2024-07-16 10:54 UTC, messixukejia approved these changes

2024-07-16 10:55 UTC, merged