WIP: e2e performance test
alibaba/ilogtail pull request #1599
Opened 2024-07-10 09:04 UTC by Assassin718

* add ilogtail file-to-blackhole performance test

2024-07-10 09:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1599) it.</sub>

2024-07-23 07:07 UTC, Assassin718 commented
# 新增
- 为test/engine新增了benchmark docker-compose启动流程：基于e2e docker-compose启动流程做出修改，去除掉默认启动ilogtail、goc-server容器，新增默认启动cadvisor容器（可以在benchmark时监控容器资源占用）
- 为test/engine新增了setup/monitor：通过访问cadvisor容器，记录benchmark过程中对应容器的资源占用（目前主要记录了CPU、内存占用的最大值和平均值），统计数据，在benchmark结束后将数据输出到文件中
- 新增benchmark testcases：添加了ilogtail、filebeat、fluentbit、vector在速率为10MB/s的文件输入、json解析的benchmark testcase，为避免下游接收程序对吞吐量的影响，在flusher侧设置了抛弃所有事件
- benmark CI workflow：在pull request时触发，执行所有benchmark testcase后记录数据，在action中输出benmark结果（待完成benmark结果图形可视化）

2024-07-25 05:50 UTC, Abingcbc requested changes

2024-07-25 05:50 UTC, Abingcbc commented on .github/workflows/benchmark.yaml
> +  push:
这个条件改成合入到main的commit才可以触发？要不然对CI集群压力太大了

2024-07-25 05:50 UTC, Abingcbc commented on test/benchmark/benchmark_docker_test.go
> +func TestE2EOnDockerComposePerformance(t *testing.T) {
只保留performance就可以了，其他两个不需要

2024-07-25 05:50 UTC, Abingcbc commented on test/benchmark/test_cases/performance_file_to_blackhole_filebeat/case.feature
> +    When start monitor {e2e-filebeat-1}
这块可以不填具体的容器名吗？比如填个正则，匹配一个容器

2024-07-26 10:28 UTC, messixukejia requested changes

2024-07-26 10:28 UTC, messixukejia commented on test/benchmark/test_cases/performance_file_to_blackhole_filebeat/filebeat.yml
> +filebeat.inputs:
a.log就不要提交了

2024-07-26 10:28 UTC, messixukejia commented on test/engine/trigger/file.go
> +	"fmt"
@Abingcbc 这个生成测试文件的方法没有通用的？还需要新建一个？

2024-07-26 10:28 UTC, messixukejia commented on scripts/benchmark_collect_result.sh
> +
增加下文档说明吧
1、如何使用
2、效果怎么看

2024-08-19 05:40 UTC, yyuuttaaoo requested changes

2024-08-19 07:08 UTC, yyuuttaaoo requested changes

2024-08-19 07:08 UTC, yyuuttaaoo commented on scripts/benchmark_collect_result.sh
> +input_statistic_files=($(find test/benchmark/report -type f -name '*ilogtail_statistic.json'))
*_statistic.json?

2024-08-19 08:15 UTC, Assassin718 commented on scripts/benchmark_collect_result.sh
> +input_statistic_files=($(find test/benchmark/report -type f -name '*ilogtail_statistic.json'))
这里主要是因为其他agent也会生成文件名以{agentname}_statistic.json为后缀的测试统计结果，而benchmark action只需要关注文件名以ilogtail_statistic.json为后缀的测试统计结果

2024-10-15 09:43 UTC, Abingcbc approved these changes

2024-10-15 09:43 UTC, Abingcbc commented on .github/workflows/benchmark.yaml
> +      # - name: Store benchmark result other agents
这些注释代码还有用吗？没的话可以删掉了

2024-10-15 09:43 UTC, Abingcbc commented on test/benchmark/main_test.go
这块代码结构调整了一下，和main同步一下吧

2024-10-15 09:43 UTC, Abingcbc commented on test/engine/setup/docker_compose.go
> +var dockerComposeType = "e2e"
这个和 dockerComposeTypeE2E 是不是重复的

2024-10-15 09:57 UTC, Assassin718 commented
![image](https://github.com/user-attachments/assets/209b397b-a6fb-453f-ad5c-332f20b7b961)
![image](https://github.com/user-attachments/assets/d090db47-868c-44cf-9b59-6fd6b7e9dacf)

2024-10-15 10:03 UTC, Assassin718 commented on .github/workflows/benchmark.yaml
> +      # - name: Store benchmark result other agents
这些是需要开启用来存储和展示结果的分支后需要action

2024-10-17 02:42 UTC, yyuuttaaoo commented on docs/cn/developer-guide/test/benchmark.md
> +- `When start docker-compose {directory}`: `{}`中参数为当前scenario的文件夹名，该行动作会读取`director`文件夹下的docker-compose.yaml文件，通过docker-compose命令启动所有容器
director -> directory

2024-10-17 03:02 UTC, yyuuttaaoo approved these changes

2024-10-17 11:45 UTC, messixukejia commented on test/benchmark/test_cases/performance_file_to_blackhole_ilogtail/case.feature
> +    """
这种完全一样的日志，有点问题，需要引入随机因素。例如url、ip、status、time等。

2024-10-17 11:53 UTC, messixukejia commented on test/engine/setup/monitor/monitor.go
> +func StartMonitor(ctx context.Context, containerName string) (context.Context, error) {
增加一个最后检查项。假设输入10分钟，那就cpu高的持续时间应该不超过10%的偏差，否则失败。

2024-10-21 01:31 UTC, messixukejia commented on test/engine/trigger/file.go
> +	JSONTemplates := []string{
这个内置的几个优先组合的，还是有点问题。

1、需要做成变量，例如ip是20个固定的地址，stats 200/400/401/403/404等，user-agent：aliyun-sdk-java/aliyun-sdk-golang/aliyun-sdk-python， latency：一段范围内的正态分布随机数，时间 当前日志时间。
2、把例子改成标准的Nginx日志，先正则解析。
3、增加一个logtail-spl的对比。

2024-10-24 05:42 UTC, messixukejia approved these changes

2024-10-25 05:43 UTC, merged