feat: plugin metric manager(for plugins like input_file)
alibaba/ilogtail pull request #1605
Opened 2024-07-11 10:08 UTC by Takuka0311

2024-07-14 07:21 UTC, messixukejia requested changes

2024-07-14 07:21 UTC, messixukejia commented on core/monitor/LogtailMetric.cpp
> +Counter* Counter::Collect() {
为什么要改成这么怪的名字？

2024-07-14 07:21 UTC, messixukejia commented on core/monitor/LogtailMetric.cpp
> +    ReadLock lock(mGaugesReadWriteLock);
这个锁有用吗？返回的引用，外面函数如果并发也没啥用吧。

2024-07-14 07:23 UTC, messixukejia requested changes

2024-07-14 07:23 UTC, messixukejia commented on core/monitor/PluginMetricManager.cpp
> +MetricsRecordRefPtr PluginMetricManager::GetOrCreateMetricsRecordRefPtr(MetricLabels labels) {
PluginMetricManager 名字不是特别好。

2024-07-15 01:57 UTC, Takuka0311 commented on core/monitor/LogtailMetric.cpp
> +Counter* Counter::Collect() {
这里的名字是go部分指标之前与字节交流后统一的名字。参见：https://github.com/alibaba/ilogtail/pull/1485/files#diff-559a25dd2b2d5d0ed6941ba5f5add3c78f6a0370cb2f38ddcc8c3295a904503f

2024-07-15 01:58 UTC, Takuka0311 commented on core/monitor/PluginMetricManager.cpp
> +MetricsRecordRefPtr PluginMetricManager::GetOrCreateMetricsRecordRefPtr(MetricLabels labels) {
这个类目前是服务于总线模式的插件，用于管理指标，之前的名字MetricManager太大了一点

2024-07-15 02:55 UTC, Takuka0311 commented on core/monitor/LogtailMetric.cpp
> +    ReadLock lock(mGaugesReadWriteLock);
我疏忽了，没有注意到返回的是引用。外面存在并发，这里返回引用不太好，但是改成返回副本会损耗性能。

由于GetGauges接口仅用于填充LogGroup中的sls_log，与 @linrunqi08 讨论后决定：

* 移除GetGauges与GetCounters接口
* 新增ReportAsSLSLog接口（名字待定），用于生成sls_log上报
* 新增ReportAsMap接口（名字待定），用于生成map格式的数据，用于开源输出测试

2024-07-15 03:19 UTC, Takuka0311 commented on core/monitor/LogtailMetric.cpp
> +    ReadLock lock(mGaugesReadWriteLock);
> 我疏忽了，没有注意到返回的是引用。外面存在并发，这里返回引用不太好，但是改成返回副本会损耗性能。
> 
> 由于GetGauges接口仅用于填充LogGroup中的sls_log，与 @linrunqi08 讨论后决定：
> 
> * 移除GetGauges与GetCounters接口
> * 新增ReportAsSLSLog接口（名字待定），用于生成sls_log上报
> * 新增ReportAsMap接口（名字待定），用于生成map格式的数据，用于开源输出测试

为了便于测试，保留GetGauges与GetCounters接口，改为返回副本。正式应用场景直接使用ReportAsLog

2024-07-16 08:02 UTC, closed without merging