split original CI UT job into two separate jobs
alibaba/ilogtail pull request #1606
Opened 2024-07-11 10:58 UTC by alph00

思路：将原来的CI UT job拆分到只有spl和无spl的2个job，这样其他 UT 就不需要静态链接一个相当大的unittest_base.a
效果：UT job需要的时间从原来的40min以上可以降低到10min左右

2024-07-12 02:47 UTC, henryzhx8 requested changes

2024-07-12 02:47 UTC, henryzhx8 commented on core/CMakeLists.txt
> +option(BUILD_LOGTAIL_SPL_UT "Build SPL unit test for Logtail")
加一下覆盖逻辑，在ut状态，withoutspl是不能取任意值，这和编主程序是不一样的。

2024-07-14 06:41 UTC, messixukejia requested changes

2024-07-14 06:41 UTC, messixukejia commented on core/CMakeLists.txt
> +    set(NOSPL_WINDOWS_SOURCE_FILES ${SOURCE_FILES_LIST} ${NOSPL_SUBDIR_SOURCE_FILES})
命名不太统一，NOSPL跟WITHOUTSPL是一个事情？

2024-07-14 06:41 UTC, messixukejia commented on core/CMakeLists.txt
> +    set(NOSPL_WINDOWS_SOURCE_FILES ${SOURCE_FILES_LIST} ${NOSPL_SUBDIR_SOURCE_FILES})
NOSPL_WINDOWS_SOURCE_FILES NOSPL 用后缀表示更好些？

2024-07-14 06:41 UTC, messixukejia commented on core/dependencies.cmake
> +        if (WITHOUTSPL)
if else 内都是一样的，为什么还需要if else

2024-07-14 06:41 UTC, messixukejia commented on core/unittest/CMakeLists.txt
> +macro(add_nospl_subdir)
这里除spl外所有的目录，用nospl表示不合适吧。如果后面再加个特殊的组件还能表示的了？ 其他地方类似。

从base、spl、另外再有个类似，三个类似的角度来考虑这个问题。
整体的变量命名需要考虑下。所以不应该出现nospl、without这种命名。应该是base 加 增量的关系

2024-07-15 01:39 UTC, alph00 commented on core/dependencies.cmake
> +        if (WITHOUTSPL)
这里是因为临时这样写一下，这几天会把镜像里的依赖库更新一下，这里就都可以改成 .a 了，这里的分支选项也都可以去掉

2024-07-15 01:40 UTC, alph00 commented on core/CMakeLists.txt
> +    set(NOSPL_WINDOWS_SOURCE_FILES ${SOURCE_FILES_LIST} ${NOSPL_SUBDIR_SOURCE_FILES})
NOSPL 是表示生成不含有SPL的单元测试，WITHOUTSPL 表示的是在生成产物过程中是否链接SPL

2024-07-15 02:33 UTC, henryzhx8 approved these changes

2024-07-16 02:37 UTC, alph00 commented on core/unittest/CMakeLists.txt
> +macro(add_nospl_subdir)
修改命名设计如下：
1. 按照不同阶段考虑，涉及到类似变量的阶段主要包括生成主程序时的链接阶段、生成UT base库、链接UT子目录代码。
2. 生成主程序时的链接阶段主要涉及 WITHOUTSPL，用来控制生成主程序时是否链接SPL，将其修改为WITHSPL，默认为ON
3. 生成UT base库时涉及NOSPL_UNIX_SOURCE_FILES等，用来控制生成UT base库有哪些文件，将其修改为UNIX_SOURCE_FILES_UTBASE 和 UNIX_SOURCE_FILES_UTBASE_WITHSPL
4. 链接UT子目录代码时涉及add_nospl_subdir() 和 add_spl_subdir(), 用来控制生成哪些UT，将其修改为add_core_subdir() 和 add_spl_subdir()

2024-07-16 11:10 UTC, alph00 commented on core/CMakeLists.txt
> +    set(NOSPL_WINDOWS_SOURCE_FILES ${SOURCE_FILES_LIST} ${NOSPL_SUBDIR_SOURCE_FILES})
已经重新设计

2024-07-16 15:48 UTC, yyuuttaaoo commented on core/CMakeLists.txt
> +    processor_link(${LOGTAIL_TARGET} ${UT_LINK} ${UT_LINK_NEED_SPL})
add_subdirectory(unittest)应该放在这个文件的最后，以免污染

2024-07-16 15:48 UTC, yyuuttaaoo commented on core/unittest/CMakeLists.txt
> +include(${CMAKE_SOURCE_DIR}/links.cmake)
在父级CMakeList最后被add_dir，是否可以看到父级已经引入的变量和函数？这里是否需要include？

2024-07-17 02:04 UTC, alph00 commented on core/unittest/CMakeLists.txt
> +include(${CMAKE_SOURCE_DIR}/links.cmake)
是可以去掉，已删去

2024-07-17 06:54 UTC, messixukejia commented on core/CMakeLists.txt
> +set(UT_LINK_NEED_SPL OFF)
这里的NEED跟WITHSPL中的with的含义统一下吗

2024-07-17 06:58 UTC, alph00 commented on core/CMakeLists.txt
> +if (BUILD_LOGTAIL_SHARED_LIBRARY AND WITHSPL)
<img width="548" alt="image" src="https://github.com/user-attachments/assets/e30dceb6-a366-496c-b8f5-5335109ad033">
BUILD_LOGTAIL_SHARED_LIBRARY 是用于生成动态库的开关，是原来就有的

2024-07-17 07:30 UTC, alph00 commented on core/CMakeLists.txt
> +set(UT_LINK_NEED_SPL OFF)
已经修改，进行了简化和统一

2024-07-17 09:34 UTC, yyuuttaaoo requested changes

2024-07-17 09:34 UTC, yyuuttaaoo commented on core/unittest/CMakeLists.txt
>  macro(add_core_subdir)
这一段和上面一样，是不是也都不需要重复add_subdirectory，主文件都跑过了按说SOURCE_FILES_CORE和SOURCE_FILES_CORE_WITHSPL都是完整的了，下面
set(SOURCE_FILES_CORE ${SOURCE_FILES_LIST} ${SUBDIR_SOURCE_FILES_CORE})
set(SOURCE_FILES_CORE_WITHSPL ${SOURCE_FILES_CORE} ${SUBDIR_SOURCE_FILES_SPL})
也感觉是重复的

2024-07-17 09:38 UTC, alph00 commented on core/unittest/CMakeLists.txt
>  macro(add_core_subdir)
这里是我把SOURCE_FILES_CORE和SOURCE_FILES_CORE_WITHSPL已到后面来了，主文件里就没有这两个变量了，这两个变量主要是为了后面用起来方便，就是core 和 spl 的一个组合

2024-07-17 09:40 UTC, alph00 commented on core/unittest/CMakeLists.txt
>  macro(add_core_subdir)
主文件里只剩下SRC_FILES了，但是SRC_FILES是受WITHSPL控制的，而UT这里需要两个确定的无spl和有spl的变量

2024-07-17 09:43 UTC, alph00 commented on core/unittest/CMakeLists.txt
>  macro(add_core_subdir)
这里add_subdirectory()加的是UT子目录，不是在加source文件

2024-07-17 11:14 UTC, alph00 commented on core/CMakeLists.txt
> +set(SRC_FILES ${SRC_FILES} ${SOURCE_FILES_LIST} ${SUBDIR_SOURCE_FILES_CORE})
已改为 FRAMEWORK_SOURCE_FILES

2024-07-17 11:19 UTC, yyuuttaaoo approved these changes

2024-07-17 11:21 UTC, alph00 commented on core/CMakeLists.txt
> +set(SUBDIR_SOURCE_FILES_CORE "")
已修改为PLUGIN_SOURCE_FILES_CORE

2024-07-17 11:35 UTC, alph00 commented on core/CMakeLists.txt
> +if (BUILD_LOGTAIL_SHARED_LIBRARY AND WITHSPL)
已修改

2024-07-17 14:12 UTC, messixukejia approved these changes

2024-07-18 01:42 UTC, merged