feat: add prometheus text parser lib
alibaba/ilogtail pull request #1608
Opened 2024-07-12 03:27 UTC by catdogpandas

2024-07-15 06:22 UTC, linrunqi08 requested changes

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.cpp
> +const std::string SAMPLE_RE = R"""(^(?P<name>\w+)(\{(?P<labels>[^}]+)\})?\s+(?P<value>\S+)(\s+(?P<timestamp>\S+))?)""";
(\s+(?P<timestamp>\S+))? 这个需要捕获两次吗？

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.cpp
> +const std::string SAMPLE_RE = R"""(^(?P<name>\w+)(\{(?P<labels>[^}]+)\})?\s+(?P<value>\S+)(\s+(?P<timestamp>\S+))?)""";
(\s+(?P<timestamp>\S+))? 这个需要捕获两次吗？

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.cpp
> +const std::string SAMPLE_RE = R"""(^(?P<name>\w+)(\{(?P<labels>[^}]+)\})?\s+(?P<value>\S+)(\s+(?P<timestamp>\S+))?)""";
叫SAMPLE_RE是不是不太好，应该叫template_re

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.h
> +        : mSourceBuffer(sourceBuffer), mSampleRegex(SAMPLE_RE) {
SAMPLE_RE我建议放在公共的地方吧，应该是有全局const的文件的。放在这里比较奇怪

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.cpp
> +const std::string SAMPLE_RE = R"""(^(?P<name>\w+)(\{(?P<labels>[^}]+)\})?\s+(?P<value>\S+)(\s+(?P<timestamp>\S+))?)""";
timestamp是不是可以更精确一些，全部是数字

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.cpp
> +        double value;
value如果是double，那么前面正则也可以更精确一些

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.cpp
> +        RE2::FullMatch(line,
RE2::FullMatch返回值不判断一下吗

2024-07-15 06:22 UTC, linrunqi08 commented on core/prometheus/TextParser.h
> +            mErr = std::make_shared<std::exception>(std::invalid_argument("invalid regex"));
这个我觉得不太适合放在构造函数里，这个放在OK函数里不是很好吗，Err()函数就不需要了

2024-07-15 08:46 UTC, henryzhx8 requested changes

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.cpp
> +#include "re2/re2.h"
第三方库统一用尖括号

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.h
> +#include "models/PipelineEventGroup.h"
h文件里的头文件请格外注意，不要少，也不要多，不要去依赖隐式依赖，所有用到的标准库和头文件都列出来，比如这里memory，exception，string等等

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.h
> +    std::shared_ptr<SourceBuffer> mSourceBuffer;
这个不是不要了吗？

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.h
> +    std::shared_ptr<std::exception> mErr;
还是保持c++风格，函数返回值用bool表示成功与否，errorMsg通过参数来返回，这个有点rust的风格了。

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.h
> +            mErr = std::make_shared<std::exception>(std::invalid_argument("invalid regex"));
有这种逻辑的，一般都需要加Init函数来显式调用，不要在构造函数里做这些操作。

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.h
> +class TextParser {
这是个单例还是啥？感觉这个类更像单例，没有啥可共用的状态

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.h
> +                             const std::string& instance = "");
这俩函数都会对外暴露吗？如果只暴露一个，另一个是内部实现，请放在private里

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.cpp
> +        boost::algorithm::trim(line);
这个函数一定要用boost吗？std没有吗？或者stringutil看下有没有类似的

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.cpp
> +        double value;
任何原始类型参数都需要初始化

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.cpp
> +            continue;
这种地方不需要加日志吗？是预期内还是预期外？

2024-07-15 08:46 UTC, henryzhx8 commented on core/prometheus/TextParser.cpp
> +                    boost::trim_if(value, boost::is_any_of("\""));
如果一定要要boost，而且是比较通用的，这种逻辑请包一层在stringutil里，不要直接调用

2024-07-15 08:52 UTC, henryzhx8 reviewed
之前提到正则性能不好，这个后续会修改吗？

2024-07-15 09:20 UTC, catdogpandas commented
后面做性能优化时会直接把正则换掉，用纯文本解析和状态机实现解析

2024-07-15 09:58 UTC, catdogpandas commented on core/prometheus/TextParser.cpp
> +const std::string SAMPLE_RE = R"""(^(?P<name>\w+)(\{(?P<labels>[^}]+)\})?\s+(?P<value>\S+)(\s+(?P<timestamp>\S+))?)""";
(\s+(?P<timestamp>\S+))?) 这一部分在暴露的指标中可能不存在，所以需要多写一次
SAMPLE_RE指代更明确，只解析暴露的样本，对注解等不相关的内容不处理

2024-07-15 10:00 UTC, catdogpandas commented on core/prometheus/TextParser.h
> +        : mSourceBuffer(sourceBuffer), mSampleRegex(SAMPLE_RE) {
它是和插件内容相关的代码，放在全局的位置是不是耦合的太严重了？

2024-07-15 11:03 UTC, catdogpandas commented on core/prometheus/TextParser.h
> +class TextParser {
就是个简单的工具类

2024-07-15 11:03 UTC, catdogpandas commented on core/prometheus/TextParser.h
> +                             const std::string& instance = "");
应该是只会暴露第一个

2024-07-15 11:07 UTC, catdogpandas commented on core/prometheus/TextParser.cpp
> +        boost::algorithm::trim(line);
应该可以换成TrimString
ilogtail里面有挺多挺好用的字符串函数，比如ToString，但是想要找到合适的需要一个一个看代码实现，有没有简单的文档可以参考，提高点效率

2024-07-15 12:15 UTC, messixukejia requested changes

2024-07-15 12:15 UTC, messixukejia commented on core/unittest/prometheus/TextParserUnittest.cpp
> +    const auto eGroup = parser.Parse(R"""(test_metric{k1="v1", k2="v2"} 9.9410452992e+10 1715829785083)""");
增加多行用例

2024-07-15 12:15 UTC, messixukejia commented on core/unittest/prometheus/TextParserUnittest.cpp
> +    const auto &parser = TextParser();
这个用例测试的目的是什么？TextParser这种功能单一类，不应该直接从接口测试就可以了吗

2024-07-15 12:15 UTC, messixukejia commented on core/prometheus/TextParser.cpp
> +            e->SetTag(string("job"), jobName);
通用的tag改成宏或者常量，不要直接用字符串

2024-07-16 02:21 UTC, catdogpandas commented on core/unittest/prometheus/TextParserUnittest.cpp
> +    const auto &parser = TextParser();
这个是用来测试写的正则表达式是否能够应对实际比较复杂的情况

2024-07-16 02:39 UTC, catdogpandas commented on core/prometheus/TextParser.cpp
> +            e->SetTag(string("job"), jobName);
ok，这俩个tag是临时在这里实现，后面会移到更合适的位置

2024-07-16 03:44 UTC, catdogpandas commented on core/prometheus/TextParser.cpp
> +        RE2::FullMatch(line,
增加：当返回false时跳过该行

2024-07-16 03:46 UTC, catdogpandas commented on core/prometheus/TextParser.h
> +                             const std::string& instance = "");
两个函数都会用到

2024-07-16 03:52 UTC, catdogpandas commented on core/prometheus/TextParser.cpp
> +        double value;
这个没必要再优化了，后面不会用正则去解析的

2024-07-16 07:06 UTC, messixukejia commented on core/prometheus/TextParser.cpp
> +            LOG_WARNING(sLogger, ("invalid value", argValue));
这么打印知道哪里出错了？ 是不是得把line打出来

2024-07-16 07:06 UTC, messixukejia commented on core/unittest/prometheus/TextParserUnittest.cpp
> +    const auto &parser = TextParser();
不应该用接口来测试吗？不应该把内部实现移除来

2024-07-16 07:06 UTC, messixukejia commented on core/prometheus/TextParser.cpp
> +                    // boost::trim_if(value, boost::is_any_of("\""));
不需要的代码删掉

2024-07-22 11:45 UTC, linrunqi08 approved these changes

2024-07-22 12:04 UTC, henryzhx8 approved these changes

2024-07-22 12:06 UTC, messixukejia approved these changes

2024-07-22 12:07 UTC, merged