fix core caused by concurrent use of non-thread-safe gethostbyname
alibaba/ilogtail pull request #1611
Opened 2024-07-12 09:32 UTC by henryzhx8

2024-07-12 23:59 UTC, messixukejia requested changes

2024-07-12 23:59 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +    ipStr[INET_ADDRSTRLEN] = '\0';
初始化整体赋值为0？

2024-07-12 23:59 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +std::unordered_set<std::string> GetNicIpv4IPList() {
函数名改成IPSet？

2024-07-12 23:59 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +#if defined(__linux__)
宏的嵌套比之前复杂了很多，感觉还是之前linux windows整体分开更清晰些，虽然会多一些外围的循环。

2024-07-12 23:59 UTC, messixukejia commented on core/common/MachineInfoUtil.cpp
> +#if defined(__linux__)
1、windows是怎么测试的
2、这个问题自己是否能复现，并发是怎么测试的

2024-07-15 02:41 UTC, henryzhx8 commented on core/common/MachineInfoUtil.cpp
> +#if defined(__linux__)
1. windows目前没有测试，会记一个todo等windows那边能编译后再测试
2. yitao的机器在特定输入下有大概率复现，lingzhu之前的dns core问题目前看也是这个导致的，两个场景可以复现。代码修复后多次运行没有再出现core。

2024-07-15 08:02 UTC, yyuuttaaoo commented on core/common/MachineInfoUtil.cpp
> +        auto p = inet_ntop(AF_INET, &addrs[i].sin_addr, ipStr, INET_ADDRSTRLEN);
这一段和linux是相同的，如果相同，改一下结构，把if defined放到循环里面来

2024-07-15 08:09 UTC, yyuuttaaoo approved these changes

2024-07-18 11:26 UTC, messixukejia approved these changes

2024-07-19 01:42 UTC, merged