support rollback for local json config
alibaba/ilogtail pull request #1612
Opened 2024-07-12 11:43 UTC by henryzhx8

2024-07-18 07:39 UTC, messixukejia approved these changes

2024-07-18 10:16 UTC, yyuuttaaoo commented on core/controller/EventDispatcherBase.cpp
> +    static bool isFirstUpdate = false;
这个变量是不是意思有点反了？第一次看起来是true啊。另外，关于这个代码的位置，是不是可以单独放到启动里面？或者while (mMainThreadRunning) { 前面，就启动时运行一次。

2024-07-18 10:17 UTC, yyuuttaaoo requested changes
see file review

2024-07-18 11:01 UTC, henryzhx8 commented on core/controller/EventDispatcherBase.cpp
> +    static bool isFirstUpdate = false;
必须得等服务端返回全量配置才行，老代码太复杂，不适合单独一个func

2024-07-18 11:01 UTC, henryzhx8 commented on core/controller/EventDispatcherBase.cpp
> +    static bool isFirstUpdate = false;
必须得等服务端返回全量配置才行，老代码太复杂，不适合单独一个func

2024-07-19 02:01 UTC, yyuuttaaoo approved these changes

2024-07-19 03:25 UTC, merged