Feat: prometheus relabel lib
alibaba/ilogtail pull request #1614
Opened 2024-07-15 03:58 UTC by catdogpandas

2024-07-15 07:04 UTC, linrunqi08 requested changes

2024-07-15 07:04 UTC, linrunqi08 commented on core/unittest/prometheus/LabelsUnittest.cpp
> +    labels.push_back(Label{"host", "172.17.0.3:9100"});
这个就写一个元素稍微有点太简单了

2024-07-15 07:04 UTC, linrunqi08 commented on core/prometheus/Relabel.cpp
> +            printf("relabel: unknown relabel action type %s\n", ActionToString(cfg.action).c_str());
printf改一下吧

2024-07-15 08:41 UTC, catdogpandas commented on core/prometheus/Labels.cpp
> +        if (find_if(
这里是因为go里面的设计 res 和 base 是以数组的逻辑进行的，里面可能包含重复项目，所以需要两种情况都要跳过，然后再把 addLabelList 重新添加

2024-07-15 08:41 UTC, catdogpandas commented on core/prometheus/Labels.cpp
> +    for (auto l : addLabelList) {
遍历的对象不一样，addLabelList 和 base 可能存在差集

2024-07-15 08:50 UTC, henryzhx8 requested changes

2024-07-15 08:50 UTC, henryzhx8 commented on core/prometheus/Labels.h
> +private:
一般都是按照public protected private的顺序

2024-07-15 08:50 UTC, henryzhx8 commented on core/prometheus/Labels.h
> +    LabelMap labels;
注意命名规范

2024-07-15 08:50 UTC, henryzhx8 commented on core/prometheus/Labels.h
> +    // void Has();
不用的函数直接删了，不要注释

2024-07-15 08:50 UTC, henryzhx8 commented on core/prometheus/Labels.h
> +    LabelMap::const_iterator end() const;
除override 标准库的情况，其余函数请一律首字母大写，并驼峰，自己全局check一下，很多地方不符合规范

2024-07-15 08:50 UTC, catdogpandas commented on core/prometheus/Labels.cpp
> +            || find_if(addLabelList.begin(), addLabelList.end(), [&l](Label label) { return label.name == l.first; })
数量级不高，从relabel的配置文件中来的，最多在几十个左右。

2024-07-22 08:59 UTC, linrunqi08 commented on core/prometheus/Labels.cpp
> +uint64_t Labels::Hash() {
是不是可以用HashUtil中的HashCombine，
![image](https://github.com/user-attachments/assets/e98fd1d5-e05c-4bdd-80da-3ca64400ce38)
类似这样，逻辑应该是一样的，没必要单独引入一种实现

2024-07-22 08:59 UTC, linrunqi08 commented on core/prometheus/Relabel.cpp
> +    // if (sourceLabelsJson.isArray() && sourceLabelsJson.size() > 0) {
这段直接删掉？

2024-07-22 08:59 UTC, linrunqi08 commented on core/prometheus/Relabel.cpp
> +        mSeparator = config["separator"].asString();
前面用了GetOptionalListParam ，这里和后面为啥不用GetMandatoryStringParam？

2024-07-22 09:25 UTC, catdogpandas commented on core/prometheus/Labels.cpp
> +uint64_t Labels::Hash() {
这里在后续开发的时候实现了[prometheus label ](https://github.com/prometheus/common/blob/main/model/labelset.go)的hash计算算法。
是和one-operator对应的hash一样的实现。

2024-07-23 00:49 UTC, messixukejia requested changes

2024-07-23 00:49 UTC, messixukejia commented on core/prometheus/Relabel.h
> +    replace,
跟原有代码风格统一，enum都是大写

2024-07-23 00:49 UTC, messixukejia commented on core/prometheus/Relabel.cpp
> +// If you want to avoid issues with the input label set being modified, at the cost of
1、一般文件名（Relabel.cpp）或者类名都是名词，很少有动词的。
2、看上去process、ProcessBuilder、Relabel这几个函数也可以成为已有类的成员函数，而不是以独立函数的形态存在。例如，relabel::Process应该是Labels的成员函数。

2024-07-23 01:51 UTC, catdogpandas commented on core/prometheus/Relabel.cpp
> +// If you want to avoid issues with the input label set being modified, at the cost of
1. 这个名字确实怪，但 Prometheus 和 VMagent 都是以 relabel 命名的，因为 relabel 在 Prometheus 中是一个比较通用的操作。
2. 这三个函数在 Prometheus 中也是以纯函数的方式实现的，这么做比较灵活。如果把它作为 Labels 的成员函数，在多次 Process 的时候反而可能会因为 Labels 的成员状态改变而影响输出结果。

2024-07-23 02:05 UTC, linrunqi08 approved these changes

2024-07-23 02:35 UTC, henryzhx8 requested changes

2024-07-23 02:35 UTC, henryzhx8 commented on core/prometheus/Relabel.h
> +namespace relabel {
这里有必要加个namespace吗？这个信息不能放到函数名里吗？或者，如果只是本文件内用到，完全可以static掉。

2024-07-23 02:35 UTC, henryzhx8 commented on core/prometheus/Relabel.h
> +class RelabelConfig {
建议直接使用struct，都是public的话

2024-07-23 02:35 UTC, henryzhx8 commented on core/prometheus/Relabel.h
> +#include "Labels.h"
这里写全路径：prometheus/Labels.h

2024-07-23 02:35 UTC, henryzhx8 commented on core/prometheus/Relabel.h
> +Action StringToAction(std::string action);
const string& ?

2024-07-23 02:35 UTC, henryzhx8 commented on core/prometheus/Relabel.h
> +std::string ActionToString(Action action);
返回引用，函数里面用static做缓存

2024-07-23 02:58 UTC, catdogpandas commented on core/prometheus/Relabel.h
> +namespace relabel {
避免冲突，使用 namespace 便于管理，这三个函数在其他模块被多次调用，等和其他模块合并后会和常量字符串定义一起使用 prometheus namespace。

2024-07-23 03:06 UTC, catdogpandas commented on core/prometheus/Relabel.h
> +#include "Labels.h"
ok

2024-07-23 03:09 UTC, catdogpandas commented on core/prometheus/Labels.cpp
> +uint64_t Labels::Hash() {
已经把对应的算法同步到这里了

2024-07-23 03:17 UTC, catdogpandas commented on core/prometheus/Relabel.h
> +class RelabelConfig {
后面应该还会增加对 VMagent 中的 relabel 支持，可能用到 private。

2024-07-23 04:10 UTC, messixukejia commented on core/prometheus/Relabel.cpp
> +// If you want to avoid issues with the input label set being modified, at the cost of
这个还是得改下的。代码结构还是得清晰些。

2024-07-23 08:56 UTC, messixukejia approved these changes

2024-07-24 07:12 UTC, henryzhx8 approved these changes

2024-07-26 09:33 UTC, merged