feat: add ReusableMetricsRecord and PluginMetricManager for c++ self monitor
alibaba/ilogtail pull request #1617
Opened 2024-07-16 07:50 UTC by Takuka0311

核心改动在core/monitor，测试在core/unittest/monitor

2024-07-17 08:44 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +    PrintMetricsToLocalFile();
输出到文件便于调试是可以的，但是不太能用编译参数来控制。
可能的输出：1、sls；2、文件；3、Prometheus export等。得考虑通用性。

2024-07-17 08:44 UTC, messixukejia commented on core/monitor/PluginMetricManager.cpp
> +ReusableMetricsRecordRef PluginMetricManager::GetOrCreateReusableMetricsRecordRef(MetricLabels labels) {
是不是提过意见不要叫plugin？

2024-07-17 08:44 UTC, messixukejia commented on core/file_server/FileServer.cpp
> +    auto itr = mPipelineNamePluginMetricManagersMap.find(name);
Lock

2024-07-17 08:44 UTC, messixukejia commented on core/file_server/FileServer.cpp
> +    auto itr = mPipelineNamePluginMetricManagersMap.find(name);
其他的一样, 确认下

2024-07-17 08:44 UTC, messixukejia commented on core/monitor/LogtailMetric.cpp
> +
没有锁的地方说明原因

2024-07-17 08:44 UTC, messixukejia commented on core/input/InputFile.cpp
> +    // INPUT_BATCH_TOTAL,
合成一个，key 指标，value type

2024-07-17 08:55 UTC, messixukejia approved these changes

2024-07-17 08:55 UTC, messixukejia commented on core/CMakeLists.txt
>  option(BUILD_LOGTAIL_UT "Build unit test for Logtail")
把设计图完善好，保持最新的。

2024-07-17 11:51 UTC, Takuka0311 commented on core/monitor/MetricExportor.cpp
> +    PrintMetricsToLocalFile();
改为了ilogtail_config.json中的配置项metrics_report_method

2024-07-17 11:52 UTC, Takuka0311 commented on core/monitor/PluginMetricManager.cpp
> +ReusableMetricsRecordRef PluginMetricManager::GetOrCreateReusableMetricsRecordRef(MetricLabels labels) {
因为是插件级别用于管理细粒度实例指标对象的类，保存位置也在插件内部，所以叫PluginMetricManager

2024-07-18 03:48 UTC, Takuka0311 commented on core/monitor/LogtailMetric.cpp
> +        MetricsRecord* newMetrics = preTmp->Collect();
* pluginmanager/context_imp.go : func (p *ContextImp) ExportMetricRecords()
  * metricsRecord.ExportMetricRecords()
    * metric.Export()，对应的实现在pkg/helper/self_metrics_v2_imp.go: 
      * cumulativeCounterImp/counterImp/gaugeImp/averageImp/latencyImp/strMetricImp.Export()
        * cumulativeCounterImp/counterImp/gaugeImp/averageImp/latencyImp/strMetricImp.Collect()

2024-07-18 06:33 UTC, messixukejia approved these changes

2024-07-19 05:54 UTC, linrunqi08 approved these changes

2024-07-22 08:30 UTC, yyuuttaaoo requested changes

2024-07-22 08:30 UTC, yyuuttaaoo commented on core/monitor/PluginMetricManager.cpp
> +        std::unique_lock lock(mutex);
这里有问题，lock后需要再次find，建议直接用普通mutex，不用读写锁优化

2024-07-22 08:30 UTC, yyuuttaaoo commented on core/monitor/PluginMetricManager.cpp
> +        } else if (it->second.use_count() > 2) {
这里同样有并发问题，直接用普通lock即可。

2024-07-22 09:04 UTC, yyuuttaaoo approved these changes

2024-07-23 01:37 UTC, merged