recover readers exactly from checkpoint
alibaba/ilogtail pull request #1620
Opened 2024-07-17 02:19 UTC by Abingcbc

## 问题
之前在从checkpoint恢复reader时，无论之前reader在哪个位置，都会将reader放置到readerArray中，然后在后续移动到正确的位置。
如果出现日志轮转文件数量大于readArray最大大小时，并且出现inode复用，就会出现readerArray顺序错误（readerArray强要求，reader顺序按照文件轮转降序排列，即 log.2 log.1 log）
目前，已知导致的问题：
1. 错误恢复导致的reader关闭，日志截断
2. 错误恢复导致文件读取位置置为开头，日志采集重复
## 解决方法
在checkpoint中新增字段，保存reader在readerArray中的位置。
-2：不在队列中
-1：默认值，新建的reader，需要放置到readerArray末尾
\>0：在readerArray中的实际位置
在从checkpoint中恢复的时候，根据不同的值，恢复reader到之前准确的位置。

2024-07-17 09:39 UTC, henryzhx8 requested changes
1. checkpoint恢复时不要收到队列长度20的限制；
2. 确认一下升级的那一下，checkpoint里没有idx字段的情况

2024-07-17 09:39 UTC, henryzhx8 commented on core/event_handler/EventHandler.cpp
> +    int32_t idx = readerPtr->GetIdxInReaderArrayFromLastCpt();
这个地方的顺序应该不能随便换的

2024-07-19 14:57 UTC, messixukejia commented
需要针对性的给出e2e测试场景构造，让这些场景都有机会触发。专门记个任务吧。

2024-07-22 02:22 UTC, henryzhx8 requested changes

2024-07-22 02:22 UTC, henryzhx8 commented on core/event_handler/EventHandler.cpp
> +                 "file device", ToString(devInode.dev))("file inode", ToString(devInode.inode)));
这一段日志还是放到原来的地方去，不然会误解

2024-07-22 02:22 UTC, henryzhx8 commented on core/event_handler/EventHandler.cpp
> +        std::sort(readerArray.begin(), readerArray.end(), ModifyHandler::CompareReaderByIdxFromCpt);
sort看下是不是保序

2024-07-22 06:35 UTC, yyuuttaaoo commented on core/event_handler/EventHandler.h
> +        if (right->GetIdxInReaderArrayFromLastCpt() == -1) {
一定不会有2个-1的话才能这样实现，否则2个-1要返回false

2024-07-23 02:23 UTC, yyuuttaaoo approved these changes

2024-07-23 02:27 UTC, henryzhx8 approved these changes

2024-07-23 02:36 UTC, messixukejia approved these changes

2024-07-23 02:59 UTC, merged