feat: prometheus scrape work lib
alibaba/ilogtail pull request #1623
Opened 2024-07-17 10:42 UTC by catdogpandas

2024-07-22 12:14 UTC, linrunqi08 requested changes

2024-07-22 12:14 UTC, linrunqi08 commented on core/prometheus/ScrapeWork.cpp
> +        uint64_t elapsedTime = GetCurrentTimeInNanoSeconds() - lastProfilingTime;
“需要校验花费的时间是否比采集间隔短”这里好像没有检验？

2024-07-22 12:14 UTC, linrunqi08 commented on core/prometheus/ScrapeWork.cpp
> +    uint64_t randSleep = ((double)1.0) * mTarget.mScrapeInterval * (1.0 * h / (double)0xFFFFFFFFFFFFFFFF);
加下注释把，说明下实现逻辑

2024-07-22 12:14 UTC, linrunqi08 commented on core/prometheus/ScrapeWork.cpp
> +    if (!mScrapeLoopThread) {
这里加下TODO吧。应该是要等dumin的改造？否则线程数会比较夸张

2024-07-22 12:28 UTC, catdogpandas commented on core/prometheus/ScrapeWork.cpp
> +    mLabels = labels;
这个URL只是为了计算hash值，我后面在重构这部分代码，中间无关的代码都会删掉的

2024-07-22 12:29 UTC, catdogpandas commented on core/prometheus/ScrapeWork.cpp
> +            LOG_WARNING(sLogger,
mHash中包含了URL

2024-07-22 12:31 UTC, catdogpandas commented on core/prometheus/ScrapeWork.cpp
> +        uint64_t elapsedTime = GetCurrentTimeInNanoSeconds() - lastProfilingTime;
这是个TODO事项，忘记加TODO了

2024-07-22 12:34 UTC, catdogpandas commented on core/prometheus/ScrapeWork.cpp
> +    uint64_t randSleep = ((double)1.0) * mTarget.mScrapeInterval * (1.0 * h / (double)0xFFFFFFFFFFFFFFFF);
已补充

2024-07-23 03:51 UTC, messixukejia requested changes

2024-07-23 03:51 UTC, messixukejia commented on core/prometheus/ScrapeWork.cpp
> +    for (size_t i = 0; i < 1000; ++i) {
这里频繁的重试有点过于暴力了。

数据流的一些典型场景最好拿出来大家一起探讨下。
1、关键环节的异常重试
2、Pipeline各个阶段，原始抓取的数据包的大小，后续处理的聚合 or 拆分，最终发送的大小。
3、https://github.com/alibaba/ilogtail/pull/908 发送需要使用metric特有的方式
4、其他可能的。。。 
@linrunqi08

2024-07-23 05:40 UTC, catdogpandas commented on core/prometheus/ScrapeWork.cpp
> +    for (size_t i = 0; i < 1000; ++i) {
发送需要使用metric特有的方式：这个有没有文档讲一下怎么用

2024-07-23 05:53 UTC, messixukejia commented on core/prometheus/ScrapeWork.cpp
> +    for (size_t i = 0; i < 1000; ++i) {
> metric

自动会识别的，上面908这个pr就是。开发进度可以由 @linrunqi08 来跟进吧，但是最终测试的时候，你也需要关注下，这是一个比较关键的特性。

2024-07-27 09:10 UTC, closed without merging