Add k8s meta module to support k8s meta plugin and k8s meta http server.
alibaba/ilogtail pull request #1630
Opened 2024-07-22 05:43 UTC by linrunqi08

2024-08-02 07:06 UTC, messixukejia requested changes

2024-08-02 07:06 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_manager.go
> +						logger.Error(context.Background(), "ENTITY_PIPELINE_QUEUE_FULL", "pipelineCh is full, discard in current sync")
这个日志会造成大量打印

2024-08-02 07:06 UTC, messixukejia commented on plugins/input/kubernetesmeta/service/meta_collector_pod.go
> +	podCh        chan *k8smeta.K8sMetaEvent
不需要专属channel

2024-08-05 05:11 UTC, linrunqi08 commented on pkg/helper/k8smeta/k8s_meta_processor_pod.go
> +func (m *podProcessor) flushPeriodEvent(events []*K8sMetaEvent) {
这种如果每个processor都要实现的话，建议用接口定义出来

2024-08-05 05:18 UTC, linrunqi08 commented on plugins/input/kubernetesmeta/service/meta_collector_pod.go
> +func (p *podCollector) init() {
这种改成start吧，跟init的语义不太符合了

2024-08-07 06:30 UTC, messixukejia requested changes

2024-08-07 06:30 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_manager.go
> +				for _, pipelineCh := range pipelineChs {
1、input首次注册需要保证全量。
2、首次注册获取完全量再处理普通队列，保证串行。

2024-08-07 06:30 UTC, messixukejia commented on plugins/input/kubernetesmeta_service/meta_collector.go
> +		log.Contents.Add("__keep_alive_seconds__", defaultKeepAliveSeconds)
变成常量定义吧

2024-08-08 06:48 UTC, linrunqi08 commented on plugin_main/flags/flags.go
> +	SingletonFlag    = flag.Bool("ALICLOUD_LOG_SINGLETON_FLAG", false, "alibaba log singleton flag, set true if you want to use it")
换成deploymode吧，改成枚举值Singleton，StatefulSet这样的

2024-08-08 06:48 UTC, linrunqi08 commented on plugin_main/plugin_export.go
> +			err := instance.Init("")
https://code.alibaba-inc.com/sls/alibabacloud-log-controller/commit/cc0a33c34158d36ef3ac29ddfb8aa1d2a8a21cc4 换成这种方式试试，这样后面部署可以更加灵活

2024-08-08 06:48 UTC, linrunqi08 commented on plugins/input/kubernetesmeta_service/meta_collector.go
> +func (m *metaCollector) processPodReplicasetLink(data *k8smeta.K8sMetaEvent, method string) models.PipelineEvent {
这种还是拆分一下文件，资源类型太多了

2024-08-10 07:36 UTC, Abingcbc commented on pkg/helper/k8smeta/k8s_meta_manager.go
> +				for _, pipelineCh := range pipelineChs {
input采用list watch的方式比较合理，定时事件采用list，直接拉取。实时事件采用watch，通过channel通知。两者在同一个select case中进行处理，就可以保证定时事件和实时事件的串行。

2024-08-12 05:21 UTC, Abingcbc commented on pkg/helper/k8smeta/k8s_meta_manager.go
> +		m.ready.Store(true)
这个是一个进程级别的服务，没有Pipeline Context。需要基于 https://github.com/alibaba/ilogtail/pull/1673 合入之后进行开发。

2024-08-15 03:45 UTC, messixukejia requested changes

2024-08-15 03:45 UTC, messixukejia commented on plugin_main/plugin_export.go
> +		if *flags.DeployMode == flags.DeploySingleton {
1、port 给默认值
2、增加一个开关，但是开关关的时候，input得能注册。

2024-08-15 07:23 UTC, Abingcbc commented on plugins/input/kubernetesmetav2/service_meta.go
> +func panicRecover() {
现在就是每个包下面都复制了一个，猜测应该是避免pkg之间循环引用。

2024-08-15 12:33 UTC, messixukejia commented on plugins/input/kubernetesmetav2/meta_collector.go
> +			m.collector.AddRawLog(log)
并发？

2024-08-15 12:33 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_deferred_deletion_cache.go
> +	go func() {
未完全初始化，不要进入全量流程。加入初始化开关依赖。

2024-08-15 12:33 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_deferred_deletion_cache.go
> +							f(&K8sMetaEvent{
注释说明为什么要锁f

2024-08-15 12:33 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_processor_pod.go
> +type podProcessor struct {
podProcessor --> PodCache

2024-08-15 12:33 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_processor_pod.go
> +			m.eventCh <- &K8sMetaEvent{
不要卡主，主动做下丢弃下吧，做好错误统计

2024-08-15 12:33 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_processor_pod.go
> +func (m *podProcessor) podServiceProcess(podList []*ObjectWrapper) []*ObjectWrapper {
podServiceProcess 函数名service

2024-08-15 12:33 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_processor_pod.go
> +		service, ok := data.Raw.(*v1.Service)
用例

2024-08-15 12:40 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_deferred_deletion_cache.go
> +		case event := <-m.eventCh:
定时事件与ADD/Update/Delete统一

2024-08-16 04:08 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_deferred_deletion_cache.go
> +			if !obj.Deleted {
取key，然后发送不加锁

2024-08-16 06:25 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_deferred_deletion_cache.go
> +			obj, ok := m.Items[k]
一次获取50，避免每次都锁

2024-08-16 06:27 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +		port = 9000
连续两个9000?

2024-08-16 06:35 UTC, messixukejia approved these changes

2024-08-16 09:18 UTC, merged