Support config server v2 provider
alibaba/ilogtail pull request #1633
Opened 2024-07-22 12:41 UTC by quzard

2024-07-23 01:56 UTC, henryzhx8 requested changes
1. ProcessConfig的checkconfigdiff不应该和pipelineconfig的checkconfigdiff完全复用，互相之间明显有差异。
2. ProcessConfigManager放在pipeline目录下显然不合适。

2024-07-23 06:26 UTC, quzard commented
> 1. ProcessConfig的checkconfigdiff不应该和pipelineconfig的checkconfigdiff完全复用，互相之间明显有差异。
> 2. ProcessConfigManager放在pipeline目录下显然不合适。

ProcessConfigManager开发时再一起改了

2024-07-23 09:26 UTC, yyuuttaaoo requested changes

2024-07-23 09:26 UTC, yyuuttaaoo commented on core/config/provider/CommonConfigProvider.cpp
> +    string requestID = sdk::Base64Enconde(string("Heartbeat").append(to_string(time(NULL))));
这个是不是应该用libuuid生成？

2024-07-23 09:26 UTC, yyuuttaaoo commented on core/config/provider/CommonConfigProvider.cpp
>      httpResponse.header[sdk::X_LOG_REQUEST_ID] = "ConfigServer";
这个和pb中用一样的吧

2024-07-23 09:26 UTC, yyuuttaaoo commented on core/config/provider/CommonConfigProvider.h
> +    virtual void UpdateRemotePipelineConfig(
这两个UpdateRemote方法为什么要virtual

2024-07-23 10:55 UTC, yyuuttaaoo approved these changes

2024-07-23 10:55 UTC, henryzhx8 commented on core/CMakeLists.txt
> +        add_definitions(-DVIRTUAL= )
linux和windows得通用吧，单独拿出去

2024-07-31 07:48 UTC, henryzhx8 approved these changes

2024-07-31 09:16 UTC, merged