feat: add loong collector monitor
alibaba/ilogtail pull request #1636
Opened 2024-07-24 05:16 UTC by Takuka0311

2024-07-24 06:51 UTC, messixukejia requested changes

2024-07-24 06:51 UTC, messixukejia commented on core/application/Application.cpp
> +    LOG_INFO(sLogger, ("LoongCollectorMonitor", "init"));
不要前后都打日志

2024-07-24 06:51 UTC, messixukejia commented on core/event_handler/LogInput.cpp
>      LogtailMonitor::GetInstance()->UpdateMetric("multi_config", AppConfig::GetInstance()->IsAcceptMultiConfig());
为什么这些不需要？

2024-07-24 06:51 UTC, messixukejia commented on core/monitor/LogtailMetric.cpp
> +    std::lock_guard<std::mutex> lock(mLabelsMutex);
为什么这里有一个锁？

而且还把前几天的错误又重复了一遍，这么加锁有用吗

2024-07-24 06:51 UTC, messixukejia commented on core/processor/daemon/LogProcess.cpp
>              if (ExactlyOnceQueueManager::GetInstance()->GetProcessQueueCnt() > 0) {
为什么这些都没有

2024-07-24 06:51 UTC, messixukejia commented on core/monitor/Monitor.cpp
> +    // init metrics
上报的指标如何整体区分指标类型到底是进程还是插件的？

2024-07-24 07:03 UTC, Takuka0311 commented on core/application/Application.cpp
> +    LOG_INFO(sLogger, ("LoongCollectorMonitor", "init"));
这个忘记删了

2024-07-24 07:05 UTC, Takuka0311 commented on core/event_handler/LogInput.cpp
>      LogtailMonitor::GetInstance()->UpdateMetric("multi_config", AppConfig::GetInstance()->IsAcceptMultiConfig());
先实现了之前设计文档中提到的关键指标

2024-07-24 07:23 UTC, Takuka0311 commented on core/monitor/LogtailMetric.cpp
> +    std::lock_guard<std::mutex> lock(mLabelsMutex);
现在有SetLabels方法了，labels对象可能会改掉。

这里加锁有必要，锁的是labels对象，在GetLabels的时候不能被SetLabels改掉。和之前的错误不一样，之前是一个对象里面的值可能会改变，返回引用是不用加锁的；这次是整个对象会被替换掉

2024-07-24 07:24 UTC, Takuka0311 commented on core/processor/daemon/LogProcess.cpp
>              if (ExactlyOnceQueueManager::GetInstance()->GetProcessQueueCnt() > 0) {
先实现了之前设计文档中提到的关键指标

2024-07-24 07:24 UTC, Takuka0311 commented on core/monitor/Monitor.cpp
> +    // init metrics
通过labels区分。插件指标会有label.plugin_name等字段

2024-07-26 08:31 UTC, messixukejia commented on core/monitor/LogtailMetric.cpp
> +    MetricsRecord* metrics;
增加个string类型吧

2024-07-26 10:23 UTC, messixukejia approved these changes

2024-07-29 02:32 UTC, linrunqi08 approved these changes

2024-07-29 02:32 UTC, linrunqi08 commented on core/monitor/LogtailMetric.cpp
> +            contentPtr->set_key(LABEL_PREFIX + item->first);
这里为啥不是pair.first

2024-07-29 02:47 UTC, Takuka0311 commented on core/monitor/LogtailMetric.cpp
> +            contentPtr->set_key(LABEL_PREFIX + item->first);
写错了，我改一下

2024-07-29 06:23 UTC, yyuuttaaoo commented on core/monitor/LogtailMetric.cpp
> +        for (auto& item : tmp->GetDoubleGauges()) {
Double ToString的精度可能比较长，后续看看是否需要控制一下

2024-07-29 06:23 UTC, yyuuttaaoo approved these changes

2024-07-29 06:25 UTC, yyuuttaaoo commented on core/monitor/LoongCollectorMetricTypes.h
> +using DynamicMetricLabels = std::vector<std::pair<std::string, std::function<std::string()>>>;
这里function的要求是线程安全

2024-07-29 06:25 UTC, yyuuttaaoo approved these changes

2024-07-29 06:26 UTC, merged