refactor flusher runner and http sink
alibaba/ilogtail pull request #1639
Opened 2024-07-24 07:55 UTC by henryzhx8

2024-07-27 00:06 UTC, messixukejia requested changes

2024-07-27 00:06 UTC, messixukejia commented on core/flusher/sls/DiskBufferWriter.cpp
> +SendResult DiskBufferWriter::SendBufferFileData(const sls_logs::LogtailBufferMeta& bufferMeta,
这里跟发送逻辑耦合的有点重，DiskBuffer应该只承载缓存的作用

比如说”(region.find("http://")“及各种错误码的响应都要在这里感知，有点重复的

2024-07-29 08:32 UTC, henryzhx8 commented on core/application/Application.cpp
> +    FlusherRunner::GetInstance()->Stop();
这三个都是框架级的单例，且可枚举，三者之间是上下游的关系，Flusherunner是上游，httpsink和diskbufferwriter是下游

2024-07-29 08:33 UTC, henryzhx8 commented on core/common/SafeQueue.h
> +    bool WaitAndPopAll(std::vector<T>& values, int64_t ms) {
可以混用，一个是阻塞接口，一个是非阻塞接口

2024-07-29 08:35 UTC, henryzhx8 commented on core/common/http/Curl.cpp
> +    curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, method.c_str());
应该是啥都没变，行之间的顺序可能换了换，变量名改了一下

2024-07-29 08:37 UTC, henryzhx8 commented on core/sink/http/HttpResponse.cpp
> +bool caseInsensitiveComp(const char lhs, const char rhs) {
这里是正式版，sdk那个目录里的理论上都应该废弃，但是现在diskbufferwriter和slsclientmanager都依赖，也没时间去重构那两块代码，所以sdk目录就残留在那了

2024-07-29 08:39 UTC, henryzhx8 commented on core/sink/http/HttpRequest.h
> + *
sink是实际执行发送的类，flusher是个插件，二者不在一个维度上，可以看内部文档的模型。

2024-07-29 08:48 UTC, henryzhx8 commented on core/flusher/sls/DiskBufferWriter.cpp
> +SendResult DiskBufferWriter::SendBufferFileData(const sls_logs::LogtailBufferMeta& bufferMeta,
这里都是老代码直接搬，没有做任何逻辑改动。理想状态是还要再拆分的，但这块改动现在必要性不大，只能先维持现状了

2024-07-29 08:52 UTC, henryzhx8 commented on core/flusher/sls/DiskBufferWriter.cpp
> +            if (mIsFlush && mQueue.Empty()) {
mIsFlush只有在stop的时候才会变成true，此时如果队列为空说明所有数据都发完了，就可以退了

2024-07-29 08:52 UTC, henryzhx8 commented on core/flusher/sls/DiskBufferWriter.cpp
> +        if (!mQueue.WaitAndPopAll(res, INT32_FLAG(write_secondary_wait_timeout) * 1000)) {
见下

2024-07-29 08:54 UTC, henryzhx8 commented on core/flusher/sls/DiskBufferWriter.cpp
> +void DiskBufferWriter::Init() {
老代码挪过来的，没有ut

2024-07-29 08:57 UTC, henryzhx8 commented on core/application/Application.cpp
> -    int32_t lastDaemonRunTime = Sender::Instance()->GetLastDeamonRunTime();
这里依赖可观测数据是定期上报的这个特性，个人感觉有点隐式，自杀保护机制需要重新全盘考虑一下，现在这些感觉都有点特殊，所以先把这段删了

2024-08-02 03:57 UTC, yyuuttaaoo commented on core/common/SafeQueue.h
> +        mCond.notify_one();
这个是不是也一样，只有一开始是空的时候notify一下就够了？

2024-08-02 03:58 UTC, yyuuttaaoo commented on core/common/SafeQueue.h
> +class SafeQueue {
safe是指thread safe？

2024-08-02 04:10 UTC, yyuuttaaoo commented on core/sink/http/HttpSink.cpp
> +        if (mQueue.WaitAndPop(request, 500)) {
DoRun和这里职责有点混？感觉这里纯wait更好

2024-08-02 04:20 UTC, yyuuttaaoo commented on core/sink/http/HttpSink.cpp
> +        struct timeval timeout {
从这往下的代码实际有啥用？

2024-08-02 06:04 UTC, yyuuttaaoo approved these changes

2024-08-02 06:41 UTC, henryzhx8 commented on core/sink/http/HttpSink.cpp
> +        struct timeval timeout {
等待有io可用

2024-08-02 10:45 UTC, messixukejia approved these changes

2024-08-02 11:23 UTC, merged