feat: prometheus scrape work, scrape manager, input plugin, and inner processor.
alibaba/ilogtail pull request #1641
Opened 2024-07-25 04:01 UTC by catdogpandas

scrape work: ScrapeWork.h, ScrapeTarget.h
scrape manager: ScrapeJob.h Scraper.h

2024-07-28 00:27 UTC, linrunqi08 requested changes

2024-07-28 00:27 UTC, linrunqi08 commented on core/prometheus/PrometheusInputRunner.cpp
> +                LOG_ERROR(sLogger, ("unregister failed, content is empty", ""));
是register还是unregister？上面的注释里这里应该都是成功的分支，但是这里又是error？

2024-07-28 00:27 UTC, linrunqi08 commented on core/prometheus/PrometheusInputRunner.cpp
> +            // register success
这里预期返回的是什么样的数据，注释一下？

2024-07-28 00:27 UTC, linrunqi08 commented on core/prometheus/PrometheusInputRunner.cpp
> +                ScraperGroup::GetInstance()->mUnRegisterMs = stoll(httpResponse.content);
这里应该要提取下httpResponse.content里的字段吧，不是直接处理

2024-07-28 00:27 UTC, linrunqi08 commented on core/prometheus/PrometheusInputRunner.cpp
> +            break;
如果跳不出循环，建议一定次数要打印一条日志，否则这里卡住没有任何信息

2024-07-28 00:27 UTC, linrunqi08 commented on core/prometheus/PrometheusInputRunner.cpp
> +    mPrometheusInputsMap[inputName] = scrapeJobPtr->mJobName;
mPrometheusInputsMap这个应该要加读写锁的，这个会有并发问题的

2024-07-28 00:27 UTC, linrunqi08 commented on core/prometheus/PrometheusInputRunner.cpp
> +void PrometheusInputRunner::Start() {
这个runner启动的时候还是要加一个判断的，只有在K8s场景才可以启动，非K8s场景启动没有任何意义。我觉得就以mOperatorHost = ToString(getenv(prometheus::OPERATOR_HOST));为标识吧，有了才启动，否则直接初始化失败

2024-07-28 01:13 UTC, linrunqi08 commented on core/prometheus/Scraper.h
> +class ScraperGroup {
这里主类叫ScraperGroup，那文件名也改一下吧

2024-07-28 09:12 UTC, messixukejia requested changes

2024-07-28 09:12 UTC, messixukejia commented on core/prometheus/ScrapeJob.cpp
> +        LOG_INFO(sLogger, ("target relabel keep", mJobName));
数据处理流程不要引入日志，整体都检查下

2024-07-28 09:12 UTC, messixukejia commented on core/prometheus/ScrapeJob.cpp
> +    mScrapeTargetsMap.clear();
锁的使用也不完整

2024-07-28 11:26 UTC, catdogpandas commented on core/input/InputPrometheus.cpp
> +        LOG_ERROR(sLogger, ("scrape config not valid", config.toStyledString()));
具体的字段报错信息在对应解析的位置增加了 Log，然后因为 ScrapeConfig会在本地文件中保存，所以这行日志也就可以删掉了

2024-07-28 11:39 UTC, catdogpandas commented on core/prometheus/TextParser.cpp
> -// TODO: 830移除正则依赖
所有的 TODO 我都以 Aone 进行管理了。

2024-07-28 12:47 UTC, catdogpandas commented on core/prometheus/TextParser.cpp
>                  timestamp = stol(argTimestamp) / 1000;
在 TestParseMetricWithTagsAndTimestamp 单测中增加了 timestamp 溢出的测试用例，结果符合预期（该指标没有被生成）。

2024-07-28 13:05 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +                LOG_ERROR(sLogger, ("unregister failed, content is empty", ""));
抱歉，写错了

2024-07-28 13:47 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +    for (int retry = 0; retry < 3; ++retry) {
这里重试三次应该是在尽快退出（或重启）释放资源和 unregister 之间的平衡。

2024-07-28 13:58 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +void PrometheusInputRunner::Start() {
可以以 mOperatorHost 的状态判断当前的运行环境，如果非 K8s，就跳过与 Operator 的交互，服务发现同样通过静态文件服务发现的方式实现。

2024-07-28 14:05 UTC, catdogpandas commented on core/prometheus/ScrapeJob.cpp
> +        LOG_INFO(sLogger, ("target relabel keep", mJobName));
这一步是解析从 Operator 获取到的 Targets 信息，Info 日志删掉了，Error 日志可以保留吧？

2024-07-28 14:13 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +            mClient->Send(sdk::HTTP_GET,
前者已改。job、worker 中请求头、url、query string 这些信息都不一样，应该不需要再次封装了。

2024-07-29 01:52 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +                ScraperGroup::GetInstance()->mUnRegisterMs = stoll(httpResponse.content);
返回值就只有一个毫秒时间戳字符串，所以就直接处理了。

2024-07-29 02:04 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +    mPodName = ToString(getenv(prometheus::POD_NAME));
2. Scrape 引入的单例 ScraperGroup 多余，已经改掉了。

2024-07-30 08:33 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +    mPodName = ToString(getenv(prometheus::POD_NAME));
在 Global 找一份

2024-07-30 09:03 UTC, catdogpandas commented on core/pipeline/PipelineManager.cpp
> +    if (isInputPrometheusChanged) {
1. 后期，移到 Input 插件的Start中，可重入

2024-08-06 04:48 UTC, linrunqi08 requested changes

2024-08-06 04:48 UTC, linrunqi08 commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +        labels.Push(Label{prometheus::ADDRESS_LABEL_NAME, targets[0]});
这里得判断先长度才能取0

2024-08-06 04:48 UTC, linrunqi08 commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +bool TargetSubscriberScheduler::ParseTargetGroups(const std::string& content, std::vector<Labels>& targetGroups) {
targetGroup？Labels和target是等价的吧？不过这两个名字看上就没什么关联，改个名字吧

2024-08-06 04:48 UTC, linrunqi08 commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +        scrapeScheduler->SetTimer(mTimer);
void ScrapeScheduler::SetTimer(std::shared_ptr<Timer> timer) {
    mTimer = std::move(timer);
}
这里把mTimer move到scrapeScheduler里面，不会有问题吗？ 为啥要move

2024-08-06 04:48 UTC, linrunqi08 commented on core/prometheus/ScraperGroup.cpp
> +    mJobEventMap[targetSubscriber->GetId()] = targetSubscriber;
jobName会重复吗？就是两个不同的job，名字是一样的

2024-08-06 04:48 UTC, linrunqi08 commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +                port = 9100;
解析错了还有必要继续吗？9100是不是大概率就访问不通了

2024-08-06 04:48 UTC, linrunqi08 commented on core/prometheus/async/PromHttpRequest.h
> +    std::chrono::steady_clock::time_point GetNextExecTime() const;
这两个函数没用到也没有实现？

2024-08-06 04:48 UTC, linrunqi08 commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +    future->AddDoneCallback([this](const HttpResponse& response) {
future每次都要新建吗？

2024-08-06 05:33 UTC, catdogpandas commented on core/prometheus/ScraperGroup.cpp
> +    mJobEventMap[targetSubscriber->GetId()] = targetSubscriber;
不会重复，不同job名字应当不一样。

2024-08-06 05:34 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +    mScraperGroup = make_unique<ScraperGroup>();
是要合并的，InputRunner 不是有计划要抽象出一个基类吗，我打算在 PrometheusInputRunner 修改的时候顺便合并了。

2024-08-06 05:37 UTC, catdogpandas commented on core/prometheus/async/PromHttpRequest.h
> +    std::chrono::steady_clock::time_point GetNextExecTime() const;
抱歉，忘记清理掉了。

2024-08-06 05:38 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +uint64_t ScrapeScheduler::GetRandSleep() const {
这个该提取出来成为工具函数。

2024-08-06 06:02 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +    future->AddDoneCallback([this](const HttpResponse& response) {
是的，参考 cpp future 和 python future 设计的 PromTaskFutuer，使用也尽量保持用完即丢的用法。

2024-08-06 06:16 UTC, catdogpandas commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +        scrapeScheduler->SetTimer(mTimer);
move 的只是入参，稍微优化点性能。

2024-08-06 06:21 UTC, catdogpandas commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +            mScrapeMap[work->GetId()] = work;
在 ScraperScheduler 更新时，会通过这个 `mScrapeMap[work->GetId()]->Cancel();` 取消对应的 ScrapeScheduler。

2024-08-06 06:27 UTC, catdogpandas commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +bool TargetSubscriberScheduler::ParseTargetGroups(const std::string& content, std::vector<Labels>& targetGroups) {
原来 Labels 是 ScrapeTarget 的一个成员，现在精简掉了 ScrapeTarget 这个类，信息还是留在 Labels 中。

2024-08-06 06:44 UTC, messixukejia requested changes

2024-08-06 06:44 UTC, messixukejia commented on core/pipeline/PipelineManager.cpp
> +            PrometheusInputRunner::GetInstance()->Start();
isInputPrometheusChanged 暂时想到start里面，保证可重入吧

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +DEFINE_FLAG_STRING(SERVICE_HOST, "service host", "");
环境变量找太业一起规划下

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +sdk::HttpMessage PrometheusInputRunner::SendGetRequest(const string& url) {
函数名有点怪

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +bool PrometheusInputRunner::HasRegisteredPlugin() {
无调用

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +        LOG_ERROR(sLogger, ("curl error", e.what())("url", url)("pod_name", mPodName));
进入异常分支后，httpResponse数据的可用性，后面继续拿着用是否有影响

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +                    LOG_INFO(sLogger, ("register failed, retried", ToString(retry)));
后面日志去掉，改成指标

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +            std::this_thread::sleep_for(std::chrono::seconds(1));
这里会卡主UpdatePipelines，应该是有问题的。
包括下面的stop

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +    return !mPrometheusInputsSet.empty();
mPrometheusInputsSet 这个变量是不是没什么用了

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +        labels.Push(Label{prometheus::ADDRESS_LABEL_NAME, targets[0]});
下标的地方要确保不会越界。整体要检查下

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/Constants.h
> +const char* const PARAM_LABEL_NAME = "__param_";
后面少了一个_?

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +        Labels result = Labels();
result变量辨识性不强，至少要是个label

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/ScraperGroup.cpp
> +        mIsStarted = true;
用原子变量就可以了，不需要锁

2024-08-06 06:44 UTC, messixukejia commented on core/prometheus/ScraperGroup.cpp
> +    future_status s = mThreadRes.wait_for(chrono::seconds(1));
这里是在等什么？好像没看到

2024-08-06 06:51 UTC, catdogpandas commented on core/prometheus/Constants.h
> +const char* const PARAM_LABEL_NAME = "__param_";
没有少，就是这个。附链接：https://prometheus.io/docs/guides/multi-target-exporter/

2024-08-06 06:52 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +bool PrometheusInputRunner::HasRegisteredPlugin() {
这个是 cookbook里 面要求实现的。

2024-08-06 06:53 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +    return !mPrometheusInputsSet.empty();
是为了判断当前是否有 Input Plugin

2024-08-06 06:55 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +sdk::HttpMessage PrometheusInputRunner::SendGetRequest(const string& url) {
改成：SendRegisterMessage

2024-08-06 06:56 UTC, catdogpandas commented on core/prometheus/ScraperGroup.cpp
> +    future_status s = mThreadRes.wait_for(chrono::seconds(1));
这里怕调用 Stop 时，Start 创建的短线程还没跑完

2024-08-06 07:03 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +        LOG_ERROR(sLogger, ("curl error", e.what())("url", url)("pod_name", mPodName));
只有两个位置调用这个函数，在拿到 httpResponse 后，会先判断 statusCode 是否是 200，所以没有影响。

2024-08-06 07:27 UTC, messixukejia commented on core/prometheus/ScraperGroup.cpp
> +    future_status s = mThreadRes.wait_for(chrono::seconds(1));
start跟stop应该是能保证串行的，可以跟笃敏确认下

2024-08-07 05:34 UTC, linrunqi08 commented on core/prometheus/async/PromFuture.cpp
> +    mValidState = false;
应该有几个状态，未执行，执行中，执行结束，如果是未执行或者执行结束，那么cancel可以直接设置成执行结束；如果是执行中，那么cancel需要等待执行结束。
Process那边，要先判断状态是否是未执行，如果是的话，才执行。 状态变化，应该是要加锁，Cancel和Process可能会有冲突。
这里IsCancelled应该是要取消掉，如昨天沟通，应该是scheduler里有一个取消的状态。

2024-08-07 05:42 UTC, catdogpandas commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +        if (m != string::npos) {
这里其实是和 Operator 通信的协议部分， Operator 返回的 target 是符合 [http_sd](https://prometheus.io/docs/prometheus/latest/http_sd/) 协议的，一定是 ip:port 的形式。

2024-08-07 05:54 UTC, catdogpandas commented on core/prometheus/schedulers/TargetSubscriberScheduler.cpp
> +        if (!targets.empty()) {
根据现在和 Operator 的通信内容设计，这里一定不是空，不过从完整性上看，还是优化好吧。

2024-08-09 14:53 UTC, messixukejia approved these changes

2024-08-13 09:23 UTC, linrunqi08 approved these changes

2024-08-13 09:25 UTC, merged