add ebpf input framework
alibaba/ilogtail pull request #1642
Opened 2024-07-25 04:34 UTC by KayzzzZ

2024-07-26 08:03 UTC, henryzhx8 commented on core/input/InputEBPFProcessSecurity.cpp
> +        return ebpf::eBPFServer::GetInstance()->UpdatePlugin(mContext->GetConfigName(), nami::PluginType::PROCESS,mContext, &mSecurityOptions);
这里的update和enable里面调的函数能保持一样吗？就是init还是update能否交给handler自己去判断？因为你这里的update_应该是有假设上一次stop后会紧跟下一次start，这个依赖框架行为，一旦行为变更，你这里就bug了，所以最好是不要这么隐式依赖，比较危险。

如果实在内层做不到，我可以考虑在start里也传个参数给你告诉你是新增还是更新，但是这个行为不太好，不到万不得已不推荐这么弄

2024-07-26 08:05 UTC, henryzhx8 commented on core/ebpf/eBPFServer.h
> +    void Stop() {}
Stop是个空函数？

2024-07-26 08:06 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +    // std::vector<HandlerTypePtr> process_handler;
不要的删了

2024-07-26 08:08 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +void eBPFServer::Init() {
这里可以加一个类成员mHasInited，确保只初始化一次，因为最终这个函数应该是在插件的start函数里去调用的，所以会多次调用，而不是在外围显式调用，目前的写法只是暂时性的。

2024-07-26 08:09 UTC, henryzhx8 commented on core/ebpf/SourceManager.h
> +    enum ebpf_func {
都用enum class把

2024-07-26 08:10 UTC, henryzhx8 commented on core/ebpf/SourceManager.cpp
> +    // remove libs
这个是TODO吗？

2024-07-26 08:11 UTC, henryzhx8 commented on core/ebpf/SourceManager.h
> +    std::string host_path_prefix_;
这几个我怎么感觉和ebpfserver是一样的，需要两边都存一份吗？

2024-07-26 08:13 UTC, henryzhx8 commented on core/ebpf/handler/AbstractHandler.h
> +    uint64_t process_total_count_;
直接初始化为0吧

2024-07-26 08:14 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.h
> +    }
这个挪到cpp里去，头文件里别依赖common里的头文件

2024-07-26 08:14 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.h
> +#include "logger/Logger.h"
这个删了

2024-07-26 08:15 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.h
> +    std::string host_name_;
这俩成员咋又来了。。

2024-07-26 08:15 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.h
> +#include "logger/Logger.h"
```suggestion
```

2024-07-26 08:17 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.cpp
> +    std::shared_ptr<SourceBuffer> mSourceBuffer = std::make_shared<SourceBuffer>();;
多了个分号，普通变量别用m开头

2024-07-26 08:18 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.cpp
> +    PipelineEventGroup mTestEventGroup(mSourceBuffer);
为啥叫testeventgroup？

2024-07-26 08:21 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.cpp
> +            std::unique_ptr<ProcessQueueItem>(new ProcessQueueItem(std::move(mTestEventGroup), 0));
用make_unique；这里不能写0，这里应该写的是input插件在配置里的顺序（从0开始算）

2024-07-26 08:34 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.cpp
> +    }
这里先待定，先确定pull还是push模式

2024-07-26 08:47 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +        std::unique_ptr<ProcessQueueItem> item = std::make_unique<ProcessQueueItem>(std::move(mTestEventGroup), 0);
同另一个地方

2024-07-26 08:47 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(100));
这里的实现为啥和security不一样？

2024-07-26 08:48 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +    auto inner = reinterpret_cast<AppSingleMeasure*>(measure->inner_measure_.get());
这里用reinterpret_cast的原因是？

2024-07-26 08:49 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +        // TODO @qianlu.kk
这里TODO是做什么？

2024-07-26 08:49 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +void GenerateTcpSendPktsTotalMetrics(PipelineEventGroup& group, std::unique_ptr<Measure>& measure, uint64_t ts) {
函数之间空个行吧

2024-07-26 08:54 UTC, KayzzzZ commented on core/input/InputEBPFProcessSecurity.h
> +    static bool update_;
OK 我修改下

2024-07-26 08:56 UTC, KayzzzZ commented on core/input/InputEBPFProcessObserver.cpp
> +        InputEBPFProcessObserver::update_ = false;
我看pipeline代码里面，对于 pipeline update场景，是先 调用 stop(false)，然后会重新创建一个 input对象再调用start方法。所以我想的是在 stop 的时候记录一下 update 的值，用来标记是属于 pipeline update 的场景。那么在调用 input start 方法时，就会调用 ebpfserver 的 updateplugin 方法，而不是 enableplugin

2024-07-26 08:57 UTC, KayzzzZ commented on core/ebpf/security/SecurityOptions.h
> +    std::string mFileName = STRING_DEFAULT;
OK，这个是 cherrypick 的文实的代码  我再整体看下他那部分

2024-07-26 08:58 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +void GenerateTcpSendPktsTotalMetrics(PipelineEventGroup& group, std::unique_ptr<Measure>& measure, uint64_t ts) {
OK

2024-07-29 08:39 UTC, messixukejia requested changes

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +        SecurityOptions* opts = std::get<SecurityOptions*>(options);
怎么都是以SecurityOption来读？

SecurityOptions*, ObserverOptions没有区分度？

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +            std::vector<std::string> names = item.mCallName;
names没有使用

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +            std::transform(filter.mNamespaceFilter.begin(), filter.mNamespaceFilter.end(), ak_filter.mNamespaceFilter.begin(),
std::transform这段代码目的是什么

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +            pconfig.options_.emplace_back(std::move(ak_option));
三个地方emplace_back 的行为都不统一

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/SourceManager.cpp
> +  auto update_f = (init_func)funcs_[(int)ebpf_func::EBPF_INIT];
这一段跟UpdatePlugin有点重复

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/SourceManager.h
> +    std::vector<long> offsets_ = std::vector<long>((int)ebpf_func::EBPF_MAX, 0);
running_固定大小的是不是直接用数据就可以了

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/SourceManager.h
> +    static SourceManager* GetInstance() {
这个单例的必要性是什么？使用单例需要控制下。

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +        config = pconfig;
直接类赋值？

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/handler/ObserveHandler.cpp
> +void ArmsMeterHandler::handle(std::vector<std::unique_ptr<ApplicationBatchMeasure>>&& measures, uint64_t timestamp) {
主流程处理得通用化，不要引入Arms相关的概念或者特有机制

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/handler/SecurityHandler.cpp
> +    PipelineEventGroup mTestEventGroup(source_buffer);
为什么还是test？

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/handler/SecurityHandler.cpp
> +        time_t ts = static_cast<time_t>(x->GetTimestamp() / 1e9);
考虑下非除法方案。

另外ns是否有必要支持

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/handler/ObserveHandler.cpp
> +    event->SetName("arms_npm_recv_packets_total");
arms强相关的都不太能直接这么写

2024-07-29 08:39 UTC, messixukejia commented on core/ebpf/handler/ObserveHandler.cpp
> +void GenerateTcpRecvBytesTotalMetrics(PipelineEventGroup& group, std::unique_ptr<Measure>& measure, uint64_t ts) {
这几个generate函数貌似重复度有点高

2024-07-29 08:42 UTC, messixukejia requested changes

2024-07-29 08:42 UTC, messixukejia commented on core/ebpf/handler/SecurityHandler.cpp
> +    mTestEventGroup.SetTag("host_ip", host_ip_);
Group tag的命名需要统一下，笃敏一起看下吧

2024-07-30 02:45 UTC, messixukejia requested changes

2024-07-30 02:45 UTC, messixukejia commented on core/unittest/input/InputEBPFFileSecurityUnittest.cpp
> +class InputEBPFFileSecurityUnittest : public testing::Test {
UT主要都是针对配置管理的，没有ebpf数据面的，数据面也从应用视角进行下补充

2024-07-30 02:45 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-network-observer.md
> +    ProbeConfig:
这一级貌似不太需要。

2024-07-30 02:45 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-file-security.md
> +    ConfigList:
ConfigList -> FilterList

2024-08-02 14:08 UTC, messixukejia commented on core/ebpf/SourceManager.cpp
> +  if (DynamicLibSuccess()) {
如果部分成功，这个load能重入吗

2024-08-05 03:57 UTC, henryzhx8 requested changes

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.h
> +    std::atomic_bool mInited;
这个用普通的bool就行了，调用点不存在并行的

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +    LOG_INFO(sLogger, ("receive plugin update", "now suspend for a while"));
打日志的话，info级日志要慎重，要打印就得把相关上下文都打出来，要不就别打。配置变更这边我理解都不用打日志，框架层面已经打了足够多的日志了

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +}
所有文件末尾的空行注意下

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/handler/AbstractHandler.h
> +        mPluginIdx = index;
这俩不用加锁吗？更新是logtail的主线程在做，与此同时sysak还会定时调用handler函数吧？

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +    LOG_WARNING(sLogger, ("begin to stop all plugins", ""));
这个是info吧

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +    mInited.store(true);
这一行建议放到最后一行

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +        mProcessSecureCB->update_context(ctx, plugin_index);
这一步是不是应该在startplugin之后再调用？stop的时候置空，这样老数据就不要了，那应该等新配置加载之后再开始接受新数据吧？

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +        pconfig.process_security_cb_ = std::bind(&SecurityHandler::handle, mProcessSecureCB.get(), std::placeholders::_1);
尽量别用bind吧，用lambda函数替代

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +        // nami::ObserverNetworkOption* opts = std::get<nami::ObserverNetworkOption*>(options);
```suggestion
```

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +bool eBPFServer::StartPluginInternal(const std::string& pipeline_name, uint32_t plugin_index,
这里还是强假设每个插件全局只能有一个咯？那假设配了两个，在现阶段应该是什么行为？拒绝加载还是随机挑一个？现在没有任何拒绝机制，容易出问题

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/config.h
> +};
这个是不是没用了？

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/config.h
> +const bool DEFUALT_PROCESS_ENABLE_OOM_DETECT = false;
这些是不是都应该放到cpp里去？这边应该只是声明，如果只有config.cpp会用的话，加上static限定符吧

2024-08-05 03:57 UTC, henryzhx8 commented on core/ebpf/include/export.h
> +//
这个文件的作用要不写个注释说明一下，是给sysak用的意思吗？咋一看会和config.h搞混

2024-08-05 05:00 UTC, henryzhx8 commented on core/ebpf/handler/SecurityHandler.h
> +    std::string mHostName;
基于上述描述，这里注明这两个变量以后会干掉

2024-08-05 06:53 UTC, alph00 commented on docs/cn/plugins/input/input-ebpf-file-security.md
> +    ConfigList:
<img width="305" alt="image" src="https://github.com/user-attachments/assets/9c23e05d-5e43-4ef0-8c19-c0d865e94c1a">
ConfigList 的下级是config ，包括 callname 和 filter ，不只是 filter，这里将 ConfigList 改成 FilterList 是不是不太合适？

2024-08-08 05:24 UTC, closed without merging