add http ping support
alibaba/ilogtail pull request #165
Opened 2022-06-07 03:05 UTC by yonghua-sun

2022-06-10 07:14 UTC, EvanLjp requested changes

2022-06-13 06:49 UTC, yonghua-sun commented on plugins/input/netping/netping.go
> +				realHost := strings.Split(u.Host, ":")
modified

2022-06-13 06:49 UTC, yonghua-sun commented on plugins/input/netping/netping.go
>  	if len(m.ICMPConfigs) > 0 {
modified

2022-06-13 06:49 UTC, yonghua-sun commented on plugins/input/netping/netping.go
>  				helper.AddMetric(collector, "dns_resolve_rt_ms", nowTs, result.Label, result.RTMs)
add failed metric is for query convenient

2022-06-13 06:49 UTC, yonghua-sun commented on plugins/input/netping/netping.go
> +			} else {
add failed metric is for query convenient

2022-06-13 06:49 UTC, yonghua-sun commented on plugins/input/netping/netping.go
>  		helper.AddMetric(collector, fmt.Sprintf("%s_total", result.Type), nowTs, result.Label, float64(result.Total))
add failed metric is for query convenient

2022-06-13 06:50 UTC, yonghua-sun commented on plugins/input/netping/netping.go
> +func (m *NetPing) doICMPing(config *ICMPConfig) {
modified

2022-06-13 06:50 UTC, yonghua-sun commented on plugins/input/netping/netping.go
> +	label.Append("dst", config.Target)
modified

2022-06-13 14:34 UTC, merged