support flusher route for pipeline event group
alibaba/ilogtail pull request #1655
Opened 2024-08-01 11:07 UTC by henryzhx8

2024-08-02 14:52 UTC, messixukejia requested changes

2024-08-02 14:52 UTC, messixukejia commented on core/route/Condition.cpp
> +        mType = Type::TAG_VALUE;
tag不是说先不实现

2024-08-02 14:52 UTC, messixukejia commented on core/route/Condition.cpp
> +        mType = Type::EVENT_TYPE;
增加一个topic类型的过滤项吧。用于entity、link的识别，具体可以找太业交流下

2024-08-06 05:40 UTC, messixukejia commented on core/config/PipelineConfig.cpp
> +    key = "Match";
文档

2024-08-06 05:40 UTC, messixukejia commented on core/route/Condition.cpp
> +    return g.GetEvents()[0]->GetType() == mType;
边界保护

2024-08-06 05:40 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +    static vector<size_t> allFlusherIdx(mFlushers.size());
感觉这里有点多余。

for (size_t i = 0; i < mFlushers.size(); ++i) {
是不是继续用原来的循环，判断下路由i是否在mRouter->Route返回的列表里就可以了

2024-08-06 07:39 UTC, yyuuttaaoo commented on core/pipeline/Pipeline.cpp
> +        auto flusherIdx = mRouter ? mRouter->Route(group) : allFlusherIdx;
allFlusherIdx是static的？这个reload后不需要变化吗？

2024-08-06 10:03 UTC, yyuuttaaoo approved these changes

2024-08-06 13:30 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +                allSucceeded = mFlushers[flusherIdx[i]]->Send(group.Copy()) && allSucceeded;
这里有较多下标范围，做好保护。可以增加个mRouter跟mFlushers.size()的比较？

2024-08-07 02:54 UTC, messixukejia approved these changes

2024-08-07 08:50 UTC, merged