Support MetricEvent serialize to logGroup
alibaba/ilogtail pull request #1656
Opened 2024-08-02 03:53 UTC by linrunqi08

2024-08-02 07:13 UTC, messixukejia commented on core/serializer/SLSSerializer.cpp
> +            logPtr->set_value(std::to_string(metricEvent.GetTimestamp()) + "000000");
不是有ns字段吗？

2024-08-02 08:15 UTC, henryzhx8 requested changes

2024-08-02 08:15 UTC, henryzhx8 commented on core/common/Constants.cpp
> +
这些都挪到slsserializer.cpp文件里，

2024-08-02 08:15 UTC, henryzhx8 commented on core/serializer/SLSSerializer.cpp
> +            for (auto it = metricEvent.TagsBegin(); it != metricEvent.TagsEnd(); it++) {
++it

2024-08-02 08:15 UTC, henryzhx8 commented on core/serializer/SLSSerializer.cpp
> +std::string Uint32ToSixDigitString(uint32_t number) {
这个函数是把纳秒转成微秒？如果是这样的话，是不是放到timeutil比较合适

2024-08-05 01:54 UTC, henryzhx8 approved these changes

2024-08-05 05:40 UTC, merged

2024-08-06 03:26 UTC, yyuuttaaoo commented on core/serializer/SLSSerializer.cpp
> +            std::ostringstream oss;
这里内存分配应该次数会很多，需要提取到for循环外面。如果都是字符串，建议直接用string，然后reserve一个比较大的大小，后面直接append，性能会好很多

2024-08-06 03:27 UTC, yyuuttaaoo commented on core/common/TimeUtil.cpp
> +    if (result.length() > length) {
这里应该直接检查number是否合法