Add ebpf input
alibaba/ilogtail pull request #1668
Opened 2024-08-07 13:34 UTC by alph00

2024-08-08 06:42 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +    mLoadedPipeline[int(type)] = pipeline_name;
加下锁

2024-08-08 06:42 UTC, messixukejia commented on core/ebpf/handler/ObserveHandler.cpp
> +            if (!mCtx) {
@henryzhx8 这里一起看下优化下。不需要存ctx，只需要存GetProcessQueueKey即可。

2024-08-08 06:42 UTC, messixukejia commented on docs/cn/configuration/system-config.md
> +| `ReceiveEventChanCap` | Int |  |
这里有点不搭， @yyuuttaaoo 关注下

2024-08-08 06:50 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +    mLoadedPipeline[int(type)] = pipeline_name;
pipeline 的启停、更新目前应该都是单线程在操作的

2024-08-08 06:52 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +            if (!mCtx) {
OK 那我改成key

2024-08-08 06:53 UTC, messixukejia commented on docs/cn/configuration/system-config.md
> +| `AggregationConfig.AggWindowSecond` | Int |  |
第三列补全

2024-08-08 06:57 UTC, alph00 commented on docs/cn/SUMMARY.md
> +  * [eBPF文件可观测数据](plugins/input/input-ebpf-file-observer.md)
已修改

2024-08-08 08:41 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +            if (!mCtx) {
1. handler 只使用 queuekey
2. 保证在 stop 和 suspend 调用之后，sysak 不再调用 handle

2024-08-08 08:42 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +    mLoadedPipeline[int(type)] = pipeline_name;
加了锁

2024-08-08 09:22 UTC, henryzhx8 requested changes

2024-08-08 09:22 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +            std::lock_guard<std::mutex> lock(mMux);
这里还有锁？

2024-08-08 09:23 UTC, henryzhx8 requested changes

2024-08-08 09:23 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +                LOG_WARNING(sLogger, ("[Otel Metrics] push queue failed!", ""));
这里打日志没有啥信息量，至少要把配置名，插件index等信息，这些都可以从context里拿

2024-08-08 09:25 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +                LOG_WARNING(sLogger, ("[Otel Metrics] push queue failed!", ""));
OK

2024-08-08 09:25 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +            std::lock_guard<std::mutex> lock(mMux);
这个已经删掉了

2024-08-08 09:25 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +            std::lock_guard<std::mutex> lock(mMux);
刚 git push 失败了

2024-08-08 09:25 UTC, KayzzzZ commented on core/ebpf/handler/AbstractHandler.h
> +        mQueueKey = key;
OK 明白 是为了记录日志是吧

2024-08-08 09:27 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +        if (ProcessQueueManager::GetInstance()->PushQueue(mQueueKey, std::move(item))) {
是！吧

2024-08-08 09:40 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +        if (ProcessQueueManager::GetInstance()->PushQueue(mQueueKey, std::move(item))) {
我看pushqueue 正常的话返回0诶

2024-08-08 09:40 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +        if (ProcessQueueManager::GetInstance()->PushQueue(mQueueKey, std::move(item))) {
![Uploading image.png…]()

2024-08-08 11:09 UTC, yyuuttaaoo commented on docs/cn/configuration/system-config.md
> +```json
这个增加点层次吧
{
  "ebpf": {
    "receive_event_chan_cap":4096,
    "admin_config": {
      "debug_mode": false
...

2024-08-08 11:12 UTC, henryzhx8 approved these changes

2024-08-08 11:13 UTC, henryzhx8 reviewed
最后合的时候最好是两个干净的commit在pr里，直接merge了，squash的话只能记到一个人

2024-08-08 12:02 UTC, yyuuttaaoo commented on docs/cn/configuration/system-config.md
> +| `ReceiveEventChanCap` | Int |  |
这里选项与json配置关联起来，比如
```
{ "ebpf": { "receive_event_chan_cap":4096
```
那么这里描述为ebpf.receive_event_chan_cap
实际gflag为ebpf_receive_event_chan_cap
```
{ "ebpf": { "admin_config": { "debug_mode": false ...
```
那么这里描述为ebpf.admin_config.debug_mode
实际gflag为ebpf_admin_config_debug_mode

2024-08-09 05:52 UTC, alph00 commented on docs/cn/configuration/system-config.md
> +| `ReceiveEventChanCap` | Int |  |
已经修改

2024-08-09 06:24 UTC, alph00 commented on docs/cn/configuration/system-config.md
> +| `AggregationConfig.AggWindowSecond` | Int |  |
已经修改

2024-08-09 07:17 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +        } else if (jsonvalue.isArray()){
这个感觉可能实际并不需要，加了反而错，转不了的最后会走到1057行

2024-08-09 07:20 UTC, alph00 commented on core/app_config/AppConfig.cpp
> +        } else if (jsonvalue.isArray()){
已经删掉

2024-08-09 08:58 UTC, yyuuttaaoo approved these changes

2024-08-09 09:21 UTC, yyuuttaaoo approved these changes

2024-08-09 13:08 UTC, messixukejia approved these changes

2024-08-12 09:42 UTC, closed without merging