support circular process queue for input with pull mode
alibaba/ilogtail pull request #1670
Opened 2024-08-08 03:44 UTC by henryzhx8

- 当pipeline的任意一个输入插件是pull模式时，处理队列为ring buffer，否则为高低水位队列。
- 队列参数暂时是写死的，后边再调整为可配的。

2024-08-09 23:01 UTC, messixukejia requested changes

2024-08-09 23:01 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +        for (auto& input : mInputs) {
这里是不是更应该是配置时直接拒绝，商业版需要从API开始。

可以配置多个不同类型插件，但是最多放宽到必须ack类型是同类的。

2024-08-09 23:09 UTC, messixukejia commented on core/input/InputObserverNetwork.h
> +    bool SupportAck() const override { return true; }
go那边如何考虑的

2024-08-13 06:52 UTC, yyuuttaaoo requested changes

2024-08-13 06:52 UTC, yyuuttaaoo commented on core/queue/QueueParam.h
> +    BoundedQueueParam(size_t cap, double ratio = 2 / 3)
2.0/3 ?

2024-08-13 06:52 UTC, yyuuttaaoo commented on core/queue/BoundedProcessQueue.h
> -    void Reset(size_t cap, size_t low, size_t high);
strange, key and cap is passed to 3 Interfaces.

2024-08-13 06:52 UTC, yyuuttaaoo commented on core/unittest/queue/CircularProcessQueueUnittest.cpp
> +    unique_ptr<ProcessQueueItem> GenerateItem() { return make_unique<ProcessQueueItem>(std::move(*sEventGroup), 0); }
这个测试设计不太好，无法验证队列元素正确性

2024-08-13 09:38 UTC, messixukejia approved these changes

2024-08-13 09:38 UTC, messixukejia commented on core/queue/SenderQueueManager.cpp
> +DEFINE_FLAG_INT32(sender_queue_capacity, "", 10);
这部分代码我没什么问题了。但是各种场景下各种队列的参数需要全局设计并讨论下。现在的参数有点散，更多还是从开发视角。

2024-08-15 11:16 UTC, messixukejia commented on core/queue/ProcessQueueManager.cpp
> +bool ProcessQueueManager::CreateOrUpdateQueue(QueueKey key, uint32_t priority, QueueType type, size_t capacity) {
QueueType type, size_t capacity) 这两个参数不配套

2024-08-15 11:16 UTC, messixukejia commented on core/queue/CircularProcessQueue.cpp
> +void CircularProcessQueue::Reset(size_t cap) {
注释下

2024-08-16 06:20 UTC, yyuuttaaoo approved these changes

2024-08-16 08:07 UTC, merged