add go process-level metric
alibaba/ilogtail pull request #1673
Opened 2024-08-08 07:57 UTC by Takuka0311

2024-08-09 07:56 UTC, messixukejia requested changes

2024-08-09 07:56 UTC, messixukejia commented on pluginmanager/metric_export.go
> +	"runtime/metrics"
![image](https://github.com/user-attachments/assets/e6b799c3-68db-4f77-8380-e8bb69ad7298)
太容易重名了，是不是得重命名下

2024-08-09 07:56 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +        if (item.find(processLevelMetricKey) != item.end()) {
把这里改成两个两个函数吧

插件Go指标、进程Go指标

2024-08-09 07:56 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +        metrics.erase(mem);
不要有删除逻辑

2024-08-13 09:49 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +        ProcessGoPluginMetricsListToLogGroupMap(goPluginMetircsList, goPluginMetircsLogGroupMap);
processLevelMetricKey
ProcessGoPluginMetricsListToLogGroupMap

单就这个小小的功能process就两种含义，很容易歧义。

2024-08-15 12:20 UTC, yyuuttaaoo approved these changes

2024-08-15 12:21 UTC, merged