optimization: prometheus text parser
alibaba/ilogtail pull request #1688
Opened 2024-08-15 02:23 UTC by catdogpandas

2024-08-17 08:31 UTC, messixukejia requested changes

2024-08-17 08:31 UTC, messixukejia commented on core/prometheus/labels/TextParser.cpp
> +    lines.reserve(content.size() / 100);
为什么/100

2024-08-17 08:31 UTC, messixukejia commented on core/prometheus/Utils.cpp
> +    value = std::strtod(str, &end);
Prometheus抓取的文本属于外部输入，很容易构造异常，各个分支要保护好，不能做任何正确性假定，需要都有针对性的测试

2024-08-17 08:31 UTC, messixukejia commented on core/prometheus/labels/TextParser.cpp
> +        logEvent->SetTimestamp(defaultNanoTs / 1000000000, defaultNanoTs % 1000000000);
尽量不要用除法

2024-08-19 01:54 UTC, catdogpandas commented on core/prometheus/labels/TextParser.cpp
> +    lines.reserve(content.size() / 100);
这里是假设每行有100个字符，问了 lingzhu 这里经验值为1024

2024-08-19 01:58 UTC, catdogpandas commented on core/prometheus/labels/TextParser.cpp
> +        logEvent->SetTimestamp(defaultNanoTs / 1000000000, defaultNanoTs % 1000000000);
后面不会在 BuildLogGroup 这里保存时间戳，因为还要在 Processor 中取出，然后重新保存到 MetricEvent 中，后面会直接在 Processor 中一次计算完成。

2024-08-19 02:12 UTC, catdogpandas commented on core/prometheus/labels/TextParser.cpp
> +        auto ns = (milliTimestamp % 1000) * 1000000;
这里有两种方法：1. 用 tmpTimestamp 字符串，进行两次转数字计算出 timestamp 和 ns，2. 进行除余计算。实际测试过方法2更快一点。
c++没有直接的带余除法，额外增加带余除法算法也并不会带来很好的优化效果。
因为100M（178万行）的测试数据下，本 if case 下的除余计算只用了 0.01s，所以没必要继续优化这里

2024-08-19 02:13 UTC, catdogpandas commented on core/prometheus/Utils.cpp
> +    value = std::strtod(str, &end);
这里没有写 ut 是因为这个函数不会抛异常，已补充。

2024-08-23 08:07 UTC, messixukejia approved these changes

2024-08-30 06:11 UTC, linrunqi08 commented on core/prometheus/labels/TextParser.cpp
> +void TextParser::HandleStart(MetricEvent& metricEvent) {
我觉得加下注释，一个样例数据，每一个函数要处理那一部分，这样会更清楚一些

2024-08-30 06:22 UTC, catdogpandas commented on core/prometheus/labels/TextParser.cpp
> +    lines.reserve(content.size() / 100);
100是忘记改了，1024是1行指标字节数的经验值。

2024-08-30 07:15 UTC, linrunqi08 approved these changes

2024-08-30 07:25 UTC, merged