modify security eBPF probe parameter for process & file
alibaba/ilogtail pull request #1693
Opened 2024-08-16 03:46 UTC by alph00

1.  修改 file security eBPF probe filter 参数
2. 修改 process security eBPF probe 参数
3. 增加 callname check

2024-08-16 03:58 UTC, sunym1991 reviewed
进程的漏了一个hook点

2024-08-16 03:58 UTC, sunym1991 commented on docs/cn/plugins/input/input-ebpf-file-security.md
>  |  Type  |  string  |  是  |  /  |  插件类型。固定为iuput\_ebpf\_file\_security  |
iuput -> input

2024-08-16 03:58 UTC, sunym1991 commented on docs/cn/plugins/input/input-ebpf-process-security.md
> +        - "wake_up_new_task"
漏了一个sys_enter_clone

2024-08-16 03:58 UTC, sunym1991 commented on core/ebpf/config.cpp
> +        = {"sys_enter_execve", "disassociate_ctty", "acct_process", "wake_up_new_task"};
漏了：sys_enter_clone

2024-08-16 05:27 UTC, alph00 commented on docs/cn/plugins/input/input-ebpf-file-security.md
>  |  Type  |  string  |  是  |  /  |  插件类型。固定为iuput\_ebpf\_file\_security  |
已经修改

2024-08-16 05:28 UTC, alph00 commented on core/ebpf/config.cpp
> +        = {"sys_enter_execve", "disassociate_ctty", "acct_process", "wake_up_new_task"};
已经修改

2024-08-16 05:28 UTC, alph00 commented on docs/cn/plugins/input/input-ebpf-process-security.md
> +        - "wake_up_new_task"
已经修改

2024-08-16 07:09 UTC, messixukejia requested changes

2024-08-16 07:09 UTC, messixukejia commented on core/ebpf/config.cpp
> +        case SecurityProbeType::PROCESS: {
这里是不是重复度有点高，不需要重写3遍

2024-08-16 07:09 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-file-security.md
>        - CallName:
CallName改成CallNameFilter吧，语义跟下面对等。

CallNameFilter可以不配，表示所支持的所有。

2024-08-16 14:42 UTC, alph00 commented on core/ebpf/config.cpp
> +        case SecurityProbeType::PROCESS: {
已经修改

2024-08-16 14:42 UTC, alph00 commented on docs/cn/plugins/input/input-ebpf-file-security.md
>        - CallName:
已经修改

2024-08-17 07:27 UTC, messixukejia requested changes

2024-08-17 07:27 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-network-security.md
> +|  ProbeConfig.AddrFilter.DestAddrList  |  \[string\]  |  否  |  空  |  目的IP地址白名单  |
1、文档所有字段补充完整，有值、无值分别什么含义。不同Filter之间的关系是什么
2、确认下 单个Filter有值、无值及组合关系（或 且）要保持统一。并增加相关的ut

2024-08-17 07:27 UTC, messixukejia commented on core/ebpf/config.cpp
> +    callNames.assign(callNameDict.at(type).begin(), callNameDict.at(type).end());
下标访问要进行合法值判断

2024-08-17 07:27 UTC, messixukejia commented on core/ebpf/config.cpp
> +            SetSecurityProbeDefaultCallName(probeType, thisSecurityOption.call_names_);
SetSecurityProbeDefaultCallName 每个分支一开始都是设置，其实是跟分支无关的

2024-08-17 07:27 UTC, messixukejia commented on core/ebpf/config.cpp
> +                    thisSecurityOption.null_filter_ = true;
thisSecurityOption 在switch分支都没有初始化

2024-08-19 01:55 UTC, alph00 commented on core/ebpf/config.cpp
> +            SetSecurityProbeDefaultCallName(probeType, thisSecurityOption.call_names_);
SetSecurityProbeDefaultCallName 不是在每个分支都会进行，只是在probeconfig 和 callname 用户没有配的时候会补上一个默认值，如果用户配置了正确的probeconfig 或者 callname就不会赋默认值

2024-08-19 01:55 UTC, alph00 commented on core/ebpf/config.cpp
> +                    thisSecurityOption.null_filter_ = true;
这里的 thisSecurityOption 在前面初始化过了

2024-08-22 02:57 UTC, messixukejia requested changes

2024-08-22 02:57 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-file-security.md
> +|  ProbeConfig.FilePathFilter  |  \[string\]  |  否  |  空  |  文件路径过滤器，遵循前缀匹配的原则，不填表示不进行过滤  |
为什么其他地方都在体现白名单，这里就不体现了

2024-08-22 02:57 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-file-security.md
> +|  ProbeConfig  |  \[object\]  |  否  |  /  |  插件配置参数列表  |
ProbeConfig 说明部分，可以加下各Filter之间的关系

2024-08-22 02:57 UTC, messixukejia commented on core/ebpf/config.cpp
> +        if (!GetValidSecurityProbeCallName(probeType, callNames, errorMsg)) {
364执行失败了，这里还能执行？ 包括下面的384行。

这一系列动作应该是有依赖性的

2024-08-22 02:57 UTC, messixukejia commented on core/common/ParamExtractor.h
> +bool GetOptionalListFilterParam(const Json::Value& config,
如果列表值部分正确的行为呢？ 多个错误码也传递不出去。

某个类型错误就当做全部异常处理吧，直接return，退出前清空下vector

这个限制加到开发手册里，list值单个异常直接整体错误

2024-08-22 02:57 UTC, messixukejia commented on core/ebpf/config.cpp
> +    const std::unordered_set<std::string> dic
IsProcessNamespaceFilterTypeValid也不用了，可以直接删除掉

2024-08-22 02:57 UTC, messixukejia commented on core/ebpf/config.cpp
> +        if (callNameDict.at(type).find(callName) == callNameDict.at(type).end()) {
有非有效区间的取值不要认为是错误，还是return true。只需要把错误列表返回供打印即可

2024-08-22 02:57 UTC, messixukejia commented on core/ebpf/config.cpp
> +        InitCallNameFilter(innerConfig, callNames, mContext, sName, probeType);
InitCallNameFilter、InitSecurityFileFilter实现不一致。
1、返回值一个有判断一个没判断
2、内部实现返回错误码不一致

2024-08-22 02:57 UTC, messixukejia commented on core/ebpf/config.cpp
> +        case SecurityProbeType::NETWORK: {
文件场景合并倒还可以，网络不太适合合并。而且这个实现两个list有重复没有很好的考虑。

Merge实现过于复杂，去掉吧。因为都是list，改成第一生效吧，有重复的打印日志。

2024-08-22 02:57 UTC, messixukejia commented on core/unittest/input/InputEBPFFileSecurityUnittest.cpp
> +                    "CallNameFilter": ["security_file_permission"],
这些ut看上去承载不了足够的组合测试，给我讲下怎么保证各种组合的正确性吧

2024-08-23 07:48 UTC, alph00 commented on core/ebpf/config.cpp
> +        if (!GetValidSecurityProbeCallName(probeType, callNames, errorMsg)) {
之前的话这里是不会影响下面的执行逻辑的
但是按照下一个review意见 “某个类型错误就当做全部异常处理”的话，这里就需要修改
已经修改

2024-08-23 08:05 UTC, alph00 commented on core/ebpf/config.cpp
> +        InitCallNameFilter(innerConfig, callNames, mContext, sName, probeType);
返回值已统一格式。由于callname有赋默认值的行为，其他filter没有，所有返回值在行为上会有不同

2024-08-23 08:24 UTC, alph00 commented on core/ebpf/config.cpp
> +        case SecurityProbeType::NETWORK: {
已经删除

2024-08-23 08:52 UTC, alph00 commented on docs/cn/plugins/input/input-ebpf-process-security.md
> +|  ProbeConfig.CallNameFilter  |  \[string\]  |  否  |  该插件支持的所有 callname  |  内核挂载点过滤器，按照白名单模式运行，不填表示配置该插件所支持的所有挂载点  |
必填项没有默认值

2024-08-23 08:52 UTC, alph00 commented on docs/cn/plugins/input/input-ebpf-file-security.md
> +|  ProbeConfig.FilePathFilter  |  \[string\]  |  否  |  空  |  文件路径过滤器，遵循前缀匹配的原则，不填表示不进行过滤  |
已经修改

2024-08-23 11:14 UTC, alph00 commented on core/unittest/input/InputEBPFFileSecurityUnittest.cpp
> +                    "CallNameFilter": ["security_file_permission"],
待调研解决

2024-08-23 15:15 UTC, messixukejia commented on core/ebpf/config.cpp
> +                res = false;
![image](https://github.com/user-attachments/assets/650fb837-602f-4f71-945f-4ac4ab103747)
这里注释不正确，只要有符合的就不是默认

2024-08-23 15:15 UTC, messixukejia commented on core/ebpf/config.cpp
> +                res = false;
![image](https://github.com/user-attachments/assets/3921559e-5916-4a48-90e4-8047ad245f4a)
改成这个形式吧

2024-08-23 15:15 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-process-security.md
>      ProbeConfig:
这种情况直接不用配ProbeConfig

2024-08-26 06:38 UTC, messixukejia approved these changes

2024-08-26 06:58 UTC, sunym1991 approved these changes

2024-08-26 07:39 UTC, merged