Concatenate plugin IDs
alibaba/ilogtail pull request #1694
Opened 2024-08-16 06:14 UTC by Takuka0311

2024-08-19 07:43 UTC, messixukejia requested changes

2024-08-19 07:43 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +            res["type"] = plugin["Type"];
399、402作为异常场景不要加到gopipeline，直接前置过滤掉吧，过滤掉的不要id++。

2024-08-19 07:43 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
>  void Pipeline::AddPluginToGoPipeline(const Json::Value& plugin, const string& module, Json::Value& dst) {
Type可以作为一个参数，不需要频繁从json读了

2024-08-20 05:48 UTC, messixukejia requested changes

2024-08-20 05:48 UTC, messixukejia commented on core/pipeline/Pipeline.h
> +    void AddPluginToGoPipeline(const std::string& name, const Json::Value& plugin, const std::string& module, Json::Value& dst);
name type为什么要混用

2024-08-20 05:48 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
>      unique_ptr<FlusherSLS> SLSTmp = make_unique<FlusherSLS>();
make也可以放到if里面

2024-08-20 05:48 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +        if (!detail.isObject() || !detail.isMember("Type") || !detail["Type"].isString()) {
打warning

2024-08-20 05:48 UTC, messixukejia commented on pluginmanager/logstore_config.go
> +		pluginName, valid := cfg["type"]
name type命名混乱，需要制定下标准

2024-08-20 08:23 UTC, henryzhx8 requested changes

2024-08-20 08:23 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +    if (config.mProject != "") {
```suggestion
    if (!config.mProject.empty()) {
```

2024-08-20 08:23 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +    if (config.mAggregators.size() == 0 && config.ShouldNativeFlusherConnectedByGoPipeline()) {
应该是IsFlushingThroughGoPipelineExisted()

2024-08-20 11:28 UTC, Takuka0311 commented on core/pipeline/Pipeline.cpp
>      unique_ptr<FlusherSLS> SLSTmp = make_unique<FlusherSLS>();
这里需要保证SLSTmp的生命周期持续到Flusher_sls init结束，放if里的话会很快销毁，后面会有问题

2024-08-20 11:33 UTC, Takuka0311 commented on pluginmanager/logstore_config.go
> +		pluginName, valid := cfg["type"]
pluginType=input_{xxxx}/processor_{xxxx}/flusher_{xxxx}等
pluginName=pluginType/pluginID#pluginPriority.

2024-08-22 04:11 UTC, messixukejia requested changes

2024-08-22 04:11 UTC, messixukejia commented on core/container_manager/ContainerDiscoveryOptions.cpp
> +    plugin["type"] = Json::Value("metric_container_info/" + pluginMeta.mPluginID);
组合方式用函数表示

2024-08-22 04:11 UTC, messixukejia commented on pluginmanager/logstore_config.go
> +		pluginName, valid := cfg["type"]
type

typeWithID

2024-08-22 04:11 UTC, messixukejia commented on pluginmanager/logstore_config.go
> +	logger.Info(logstoreConfig.Context.GetRuntimeContext(), "all MetricInputs", pipeline.MetricInputs)
1

2024-08-22 07:06 UTC, messixukejia approved these changes

2024-08-23 01:56 UTC, henryzhx8 requested changes
36个topology的测试用例改一下

2024-08-23 01:56 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +    aggregatorDefault["Type"] = "aggregator_default";
恢复原样

2024-08-23 04:53 UTC, linrunqi08 commented
标题优化一下，信息要完整一些

2024-08-23 05:26 UTC, linrunqi08 requested changes

2024-08-23 05:26 UTC, linrunqi08 commented on core/pipeline/Pipeline.cpp
>  PluginInstance::PluginMeta Pipeline::GenNextPluginMeta(bool lastOne) {
现在如果一个input，一个processor，两个flusher，这里现在是怎么生成的呢？之前是单条pipeline，所以顺序生成没问题。一个processor，两个flusher，现在ebpf已经有这种场景了

2024-08-23 05:30 UTC, Takuka0311 commented on core/pipeline/Pipeline.cpp
>  PluginInstance::PluginMeta Pipeline::GenNextPluginMeta(bool lastOne) {
这边目前还没有处理，对外暂时只展示pluginID

2024-08-23 06:13 UTC, henryzhx8 approved these changes

2024-08-26 03:44 UTC, linrunqi08 approved these changes

2024-08-26 11:10 UTC, yyuuttaaoo commented on core/pipeline/Pipeline.cpp
> +    res["type"] = GenPluginTypeWithID(pluginType, std::to_string(mPluginID.load()));
Pipeline::GetNowPluginID

2024-08-26 11:13 UTC, yyuuttaaoo commented on core/pipeline/Pipeline.cpp
> +void Pipeline::AddPluginToGoPipeline(const string& pluginType, const Json::Value& plugin, const string& module, Json::Value& dst) {
为什么原来不用传pluginType直接用json的，现在改了？

2024-08-27 02:34 UTC, yyuuttaaoo commented on core/aggregator/AggregatorDefault.h
> +class AggregatorDefault {
这个是不是只有Pipeline初始化可能用，那不用一个单独文件，放在cpp的匿名namespace里就好了。另外名字应该是AggregatorDefaultConfig吧

2024-08-28 02:40 UTC, merged