feat: prometheus basic auth and authorization for scrape config
alibaba/ilogtail pull request #1696
Opened 2024-08-16 08:31 UTC by catdogpandas

2024-08-22 03:12 UTC, linrunqi08 requested changes

2024-08-22 03:12 UTC, linrunqi08 commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +    return ReadFile(filePath, content);
这个可以直接写文件测试吧。测试完了把文件删掉就好了

2024-08-22 03:12 UTC, linrunqi08 commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +        type = prometheus::AUTHORIZATION_DEFAULT_TYEP;
type需要校验类型吗？可枚举吗

2024-08-22 03:12 UTC, linrunqi08 commented on core/prometheus/Constants.h
> +const char* const USERNAME_FILE = "username_file";
username也会是文件？这个是auth的规范？

2024-08-22 04:01 UTC, catdogpandas commented on core/prometheus/Constants.h
> +const char* const USERNAME_FILE = "username_file";
虽然 [prometheus 文档](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) 中没有指明 `username_file`，但是 prometheus 和 VMAgent 都支持 `username_file`。所以应该实现这个部分。

2024-08-22 05:41 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +        type = prometheus::AUTHORIZATION_DEFAULT_TYEP;
不需要校验，最终都会以 `Authorization: Type Credential` 的方式放在请求头中。Prom 和 VMAgent 都是以这种方式实现的。

2024-08-23 02:34 UTC, messixukejia requested changes

2024-08-23 02:34 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +    if (!credentials.empty() && !credentialsFile.empty()) {
K8s文件的传递方式需要有明确的方案。

2024-08-23 08:37 UTC, messixukejia approved these changes

2024-08-23 09:00 UTC, linrunqi08 approved these changes

2024-08-23 09:04 UTC, merged