update: PrometheusInputRunner inherits the InputRunner basic class
alibaba/ilogtail pull request #1699
Opened 2024-08-16 09:40 UTC by catdogpandas

2024-08-16 23:00 UTC, messixukejia requested changes

2024-08-16 23:00 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
> +void PrometheusInputRunner::StopIfNotInUse() {
这个函数的目的是什么，跟stop区分度并不是太强。

2024-08-16 23:02 UTC, messixukejia commented on core/prometheus/PrometheusInputRunner.cpp
>      mIsStarted.store(false);
置false是最后还是最前面？

2024-08-19 01:29 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
> +void PrometheusInputRunner::StopIfNotInUse() {
这个函数会在配置更新时调用，仅在没有输入插件（mTargetSubscriberSchedulerMap 为空）时退出

2024-08-19 01:37 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
>      mIsStarted.store(false);
放在前面好些，从 stop 可重入的角度看，放前面可以避免后面资源多次被释放。

2024-08-19 03:56 UTC, henryzhx8 requested changes

2024-08-19 03:56 UTC, henryzhx8 commented on core/prometheus/PrometheusInputRunner.cpp
>      LOG_INFO(sLogger, ("PrometheusInputRunner", "Stop"));
你这个stop是有可能花较长时间的，所以会导致卡住的地方都要打印日志。这边有个问题，如果stop之后马上又init了，这边可能会有问题

2024-08-20 07:11 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.cpp
>      LOG_INFO(sLogger, ("PrometheusInputRunner", "Stop"));
增加了一个 register 的锁，保证在频繁 stop、init 时注册是有序的。

2024-08-23 07:54 UTC, messixukejia approved these changes

2024-08-30 01:39 UTC, henryzhx8 approved these changes

2024-08-30 06:46 UTC, merged