enable stopIfNotInUse
alibaba/ilogtail pull request #1700
Opened 2024-08-16 09:45 UTC by KayzzzZ

2024-08-19 06:01 UTC, henryzhx8 requested changes

2024-08-19 06:01 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +void eBPFServer::StopIfNotInUse() {
拉一下最新分支

2024-08-19 09:51 UTC, KayzzzZ commented on core/ebpf/SourceManager.cpp
> +    delete conf;
可以的，已经修改了

2024-08-19 09:51 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +void eBPFServer::StopIfNotInUse() {
OK

2024-08-19 11:11 UTC, henryzhx8 commented on core/ebpf/eBPFServer.cpp
> +}
这俩是不是可以合并了？

2024-08-19 11:54 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +}
目前来看 功能是一致的，我先合并一起好了。CheckIfInUsed 这个方法最开始是在我另一个分支里面，我本来是想还要用来检查底层的bpf复用的逻辑，所以这个feature中我没删掉。

2024-08-20 07:44 UTC, henryzhx8 approved these changes

2024-08-27 11:17 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +    for (std::size_t i = 0; i < mLoadedPipeline.size(); i ++) {
不需要锁？

2024-08-28 09:01 UTC, messixukejia approved these changes

2024-08-29 06:12 UTC, merged