feat: prometheus self-monitor metrics
alibaba/ilogtail pull request #1702
Opened 2024-08-19 05:18 UTC by catdogpandas

fix: 使用更精确的开始采集数据的时间作为时间戳
兼容开源的7条自监控指标

scrape_duration_seconds
scrape_response_size_bytes
scrape_samples_limit
scrape_samples_post_metric_relabeling
scrape_series_added （无效）
scrape_samples_scraped
scrape_timeout_seconds
up

2024-08-22 08:56 UTC, messixukejia requested changes

2024-08-22 08:56 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +    mScrapeDurationSeconds = 1.0 * (GetCurrentTimeInNanoSeconds() - timestampNanoSec) / 1000000000;
除的地方考虑下其他实现。降低ns访问

2024-08-23 01:33 UTC, messixukejia requested changes

2024-08-23 01:33 UTC, messixukejia commented on core/models/PipelineEventGroup.cpp
> +    return mBaggagedata[key];
判断key是否存在，参考gettag

2024-08-23 01:33 UTC, messixukejia commented on core/models/PipelineEventGroup.cpp
> +void PipelineEventGroup::SetBaggagedata(const string& key, const string& value) {
实现的函数结构与Tag保持对等吧

2024-08-23 01:33 UTC, messixukejia commented on core/processor/inner/ProcessorPromRelabelMetricNative.cpp
> +    if (config.isMember(prometheus::SCRAPE_TIMEOUT) && config[prometheus::SCRAPE_TIMEOUT].isString()) {
没有配置是默认值是什么

2024-08-23 01:33 UTC, messixukejia commented on core/processor/inner/ProcessorPromRelabelMetricNative.cpp
> +    auto timestamp = StringTo<uint64_t>(scrapeTimestampStr.substr(0, scrapeTimestampStr.size() - 3).to_string());
scrapeTimestampStr.size() - 3 避免越界访问

2024-08-23 01:33 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> +void ScrapeScheduler::SetAutoMetricMeta(PipelineEventGroup& eGroup) {
函数名不再是meta了

2024-08-23 01:33 UTC, messixukejia commented on core/processor/inner/ProcessorPromParseMetricNative.cpp
> +        ProcessEvent(e, newEvents, eGroup, timestampMilliSec / 1000, timestampMilliSec % 1000 * 1000000);
每条事件都会除 模一次

关于除 模，之前提过很多次意见了，后面还是得注意下。

两种方案
1、ScrapeScheduler传递的时候就按秒、微妙传递
2、提到for循环外面

2024-08-23 01:37 UTC, linrunqi08 requested changes

2024-08-23 01:37 UTC, linrunqi08 commented on core/processor/inner/ProcessorPromParseMetricNative.cpp
> +    StringView scrapeTimestampStr = eGroup.GetBaggagedata(prometheus::SCRAPE_TIMESTAMP);
prometheus::SCRAPE_TIMESTAMP如果你要限定单位是毫秒，建议在参数名里面加上单位

2024-08-23 01:37 UTC, linrunqi08 commented on core/prometheus/Constants.h
> +const char* const UP = "up";
这个是什么意思

2024-08-23 01:37 UTC, linrunqi08 commented on core/processor/inner/ProcessorPromParseMetricNative.cpp
> +        ProcessEvent(e, newEvents, eGroup, timestampMilliSec / 1000, timestampMilliSec % 1000 * 1000000);
这里不用每次都算一次吧，在for循环外面算好，再传进来就好了

2024-08-23 01:37 UTC, linrunqi08 commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> -        logEvent->SetTimestamp(timestamp);
这个现在不设置时间？

2024-08-23 01:58 UTC, catdogpandas commented on core/models/PipelineEventGroup.h
> +    PROMETHEUS_SCRAPE_TIMESTAMP,
这段已经删掉了，timestamp 单独传是因为我只想在解析指标的时候才赋值，在切分成日志格式的时候就不需要额外操作了。

2024-08-23 01:59 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeScheduler.cpp
> -        logEvent->SetTimestamp(timestamp);
是的，logEvent 只是中间状态，设置时间还需要额外除模操作，可以直接在最后面设置

2024-08-23 02:16 UTC, catdogpandas commented on core/processor/inner/ProcessorPromParseMetricNative.cpp
> +    PipelineEventPtr& e, EventsContainer& newEvents, PipelineEventGroup& eGroup, uint64_t timestamp, uint32_t nanoSec) {
这个是因为优化后的 TextParser 还没合并，现在这个 TextParser 没有必要再改造接收 nanoSec 参数了。

2024-08-23 02:18 UTC, catdogpandas commented on core/processor/inner/ProcessorPromRelabelMetricNative.cpp
> +    if (config.isMember(prometheus::SCRAPE_TIMEOUT) && config[prometheus::SCRAPE_TIMEOUT].isString()) {
已与 ScrapeConfig 中的配置统一

2024-08-23 02:22 UTC, catdogpandas commented on core/prometheus/Constants.h
> +const char* const UP = "up";
up 指标表示每次抓取的状态，如果抓取过程中出现如返回非200的情况就会将 up 设置为0，正常情况为1.

2024-08-23 02:26 UTC, catdogpandas commented on core/processor/inner/ProcessorPromParseMetricNative.cpp
> +        ProcessEvent(e, newEvents, eGroup, timestampMilliSec / 1000, timestampMilliSec % 1000 * 1000000);
抱歉，这个地方我以为改了。。

2024-08-23 07:07 UTC, linrunqi08 approved these changes

2024-08-23 07:23 UTC, messixukejia approved these changes

2024-08-23 08:58 UTC, merged