[FEATURE]: iLogtail的extension新增encoder接口，增加prometheus encoder实现，增加ext_default_encoder插件[通过配置使用prometheus encoder]
alibaba/ilogtail pull request #1704
Opened 2024-08-19 08:41 UTC by aiops1900

1. [FEATURE]: iLogtail的extension新增encoder接口 [ 详见 #1660 ]
2. [FEATURE]: iLogtail 新增 Prometheus Protocol Encoder 实现 [ 详见 #1661 ]
3. [FEATURE]: iLogtail的extension插件新增encoder extension插件[ext_default_encoder] [ 详见 #1662 ]

以[flusher_http](https://github.com/alibaba/ilogtail/tree/main/plugins/flusher/http)的配置为例，集成Prometheus Encoder的配置示例
```YAML
flushers:
- Type: flusher_http
  ...
  Encoder:
    Type: ext_default_encoder/prometheus
    ...
...
extensions:
- Type: ext_default_encoder/prometheus
  Format: 'prometheus'
```

2024-08-20 07:27 UTC, yyuuttaaoo requested changes

2024-08-20 07:27 UTC, yyuuttaaoo commented on pkg/protocol/encoder/protocol.go
这个文件位置和endocoder不太对称，可以统一吗

2024-08-20 07:27 UTC, yyuuttaaoo commented on plugins/extension/encoder/encoder.go
和default_decoder.go统一一下？

2024-08-20 07:27 UTC, yyuuttaaoo commented on plugins/extension/encoder/encoder.go
对应的文档，参考 https://github.com/alibaba/ilogtail/blob/2.0/docs/cn/plugins/extension/ext-default-decoder.md
加入overview docs/cn/plugins/overview.md
顺便把链接加一下（原来整个Extension都漏了）docs/cn/SUMMARY.md

2024-08-20 08:21 UTC, aiops1900 commented on plugins/extension/encoder/encoder.go
ok

2024-08-21 02:18 UTC, yyuuttaaoo approved these changes

2024-08-22 12:29 UTC, merged