support report event data
alibaba/ilogtail pull request #1705
Opened 2024-08-19 09:32 UTC by KayzzzZ

2024-08-20 07:54 UTC, henryzhx8 requested changes

2024-08-20 07:54 UTC, henryzhx8 commented on core/ebpf/config.cpp
> +    if (!GetOptionalBoolParam(probeConfig, "EnableEvent", thisObserverNetworkOption.mEnableEvent, errorMsg)) {
Log，metric，span，这里用event是不是不太好？

2024-08-20 07:54 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +                logEvent->SetTimestamp(seconds.count(), event->GetTimestamp());
这里的前面是秒，后边是纳秒，但是纳秒那个是刨除秒之后的产物，换句话说两个变量转成字符串拼起来才是真的纳秒。

2024-08-20 07:54 UTC, henryzhx8 commented on core/ebpf/handler/ObserveHandler.cpp
> +        for (auto& tag : appEvents->tags_) eventGroup.SetTag(tag.first, tag.second);
代码里最好都用花括号括起来，不要在一行里

2024-08-20 10:20 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +                logEvent->SetTimestamp(seconds.count(), event->GetTimestamp());
okk

2024-08-20 10:20 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +                logEvent->SetTimestamp(seconds.count(), event->GetTimestamp());
明白了 我修改下

2024-08-26 12:18 UTC, KayzzzZ commented on core/ebpf/config.cpp
> +    if (!GetOptionalBoolParam(probeConfig, "EnableEvent", thisObserverNetworkOption.mEnableEvent, errorMsg)) {
okk 我先把这个参数改一下吧 改成log  我最开始想的时候主要是因为从内核拿的数据都是事件，只是目前只支持用 log 这个格式来往上报。事件的 scope 可能更大点。
但是我想了一下，就叫 log 好像也没什么问题，我估计长时间看也不用支持别的方式了。以前的事件中心好像要没了

2024-08-26 12:18 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +        for (auto& tag : appEvents->tags_) eventGroup.SetTag(tag.first, tag.second);
okk

2024-08-27 05:38 UTC, henryzhx8 approved these changes

2024-08-27 11:31 UTC, messixukejia requested changes

2024-08-27 11:31 UTC, messixukejia commented on core/ebpf/config.cpp
> +    if (!GetOptionalBoolParam(probeConfig, "EnableLog", thisObserverNetworkOption.mEnableLog, errorMsg)) {
文档

2024-08-27 11:31 UTC, messixukejia commented on core/ebpf/handler/ObserveHandler.cpp
![image](https://github.com/user-attachments/assets/b9ceb84f-88dd-452a-a2fc-3adfc7fbb2fe)
PipelineEventGroup变量定义位置

2024-08-27 11:31 UTC, messixukejia commented on core/ebpf/handler/ObserveHandler.cpp
> +        PipelineEventGroup eventGroup(sourceBuffer);
变量名event_group 跟其他函数统一

2024-08-27 12:31 UTC, KayzzzZ commented on core/ebpf/handler/ObserveHandler.cpp
> +        PipelineEventGroup eventGroup(sourceBuffer);
ok

2024-08-27 12:31 UTC, KayzzzZ commented on core/ebpf/config.cpp
> +    if (!GetOptionalBoolParam(probeConfig, "EnableLog", thisObserverNetworkOption.mEnableLog, errorMsg)) {
已更新

2024-08-28 09:02 UTC, messixukejia approved these changes

2024-08-28 09:07 UTC, merged