feat: reload Go pipeline config independently
alibaba/ilogtail pull request #1713
Opened 2024-08-22 07:53 UTC by Abingcbc

## 背景
目前加载配置都是全量停止，全量重新加载和全量启动。这会造成一些没有变化的配置的重复加载。

## 方案
修改了CGO接口，提供了新的Go流水线加载接口，命名与C++侧统一。
1. StopAll：用于进程退出
2. Stop：停止指定配置
3. Start：启动指定配置

2024-08-26 05:54 UTC, henryzhx8 requested changes
配置变更的时候是先init新的，然后stop老的，再start新的，目前看代码里是不支持这种模式的

2024-09-19 08:19 UTC, henryzhx8 requested changes

2024-09-19 08:19 UTC, henryzhx8 commented on core/pipeline/Pipeline.h
> +    }
有可能减到0吗？真的担心的话，改成int型，变成负数的时候直接error日志

2024-09-19 08:19 UTC, henryzhx8 commented on core/pipeline/queue/ProcessQueueItem.h
> +            auto p = PipelineManager::GetInstance()->FindConfigByName(configName);
这边相当于每次pop都要调用两次，大部分时间有点浪费，还有一种思路是单纯等所有处理线程都完成一次循环。

2024-09-19 08:19 UTC, henryzhx8 commented on core/pipeline/PipelineManager.cpp
> -    }
ConfigWatcher那边mUnchanged可以删了，相关的代码一并删除

2024-09-20 02:21 UTC, Abingcbc commented on core/pipeline/Pipeline.cpp
> +        }
condition variable要配合unique lock一起。这里只需要保证这一个变量的原子性，用atomic比unique lock更轻量级

2024-09-20 06:49 UTC, Abingcbc commented on pluginmanager/checkpoint_manager.go
> +	runningFlag    bool
因为之前stop只会有一次，现在区分成withinput和withoutinput之后，退出会stop两次。这里改成用sync.Once控制只stop一次了。

2024-09-20 06:50 UTC, Abingcbc commented on plugin_main/plugin_export.go
> +func Stop(configName string, exitFlag int) {
removedFlag

2024-09-20 07:22 UTC, Abingcbc commented on plugin_main/plugin_export.go
> +	pluginmanager.LogtailConfigLock.RLock()
有可能一个配置在变更，写LogtailConfig，另一个配置在正常发送，就会对LogtailConfig产生race

2024-09-20 09:12 UTC, Abingcbc commented on core/pipeline/queue/ProcessQueueItem.h
> +            auto p = PipelineManager::GetInstance()->FindConfigByName(configName);
这块改成只有在配置变更时才计算数量

2024-09-23 11:57 UTC, henryzhx8 requested changes

2024-09-23 11:57 UTC, henryzhx8 commented on plugin_main/plugin_export.go
> +func UnloadPipeline(project string, logstore string, configName string) int {
Unload为啥还要project和logstore？

2024-09-23 11:57 UTC, henryzhx8 commented on pluginmanager/logstore_config.go
> +func UnloadLogstoreConfig(project string, logstore string, configName string) error {
你这个语义不对，应该是UnloadPartiallyLoadedConfig

2024-09-23 11:57 UTC, henryzhx8 commented on pluginmanager/plugin_manager.go
> +	stopBuildinOnce.Do(func() {
我觉得可以专门加一个接口用来停止这些自监控流水线，和C++那边一样，停完普通流水线以后再人工调用这个

2024-09-23 11:57 UTC, henryzhx8 commented on core/go_pipeline/LogtailPlugin.cpp
> +        if (stopCost >= 30 * 1000) {
都改成10秒吧

2024-09-23 11:57 UTC, henryzhx8 commented on core/pipeline/plugin/interface/Flusher.cpp
>      }
把这些内容放到SenderQueueManager里，叫SetPipelineForItems(const std::shared_ptr\<Pipeline>& p)

2024-09-23 11:57 UTC, henryzhx8 commented on core/pipeline/plugin/interface/Flusher.cpp
> +        LOG_ERROR(sLogger, ("failed to get pipeline context", "context not found")("action", "discard data"));
自监控的目前就是会走到这个分支，所以肯定不是error

2024-09-23 11:57 UTC, henryzhx8 commented on core/pipeline/plugin/interface/Flusher.cpp
> +            item->mPipeline = pipeline;
这里得要判断item->pipeline是不是为空，如果不为空就不要覆盖，有可能是上次变更残留的

2024-09-23 11:57 UTC, henryzhx8 commented on core/pipeline/queue/ProcessQueueItem.h
> +            mPipeline->AddInProcessCnt();
这个分支能走进去是否说明这个元素时上一次配置变更残留的

2024-09-23 11:57 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +    WaitAllInProcessFinish();
WaitAllItemsInProcessFinished

2024-09-23 11:57 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +        usleep(1000 * 10); // 10ms
代码里sleep都用this_thread::sleep_for

2024-09-23 12:01 UTC, henryzhx8 requested changes

2024-09-23 12:01 UTC, henryzhx8 commented on pluginmanager/plugin_manager.go
>  		if _, exists := DisabledLogtailConfig[config.ConfigNameWithSuffix]; !exists {
DisabledLogtailConfig的key应该还要带上version，但是实现有困难，注明可能的结果。

2024-09-23 13:47 UTC, messixukejia commented on core/unittest/pipeline/PipelineUnittest.cpp
> +void PipelineUnittest::TestInProcessingCount() const {
UT很弱，没有什么针对性的用例

2024-09-24 05:33 UTC, Abingcbc commented on core/pipeline/queue/ProcessQueueItem.h
> +            mPipeline->AddInProcessCnt();
是的，说明这个元素不属于当前的流水线

2024-09-24 09:48 UTC, henryzhx8 requested changes

2024-09-24 09:48 UTC, henryzhx8 commented on plugin_main/plugin_export.go
> +func StopBuiltIn() {
StopBuiltInPipelines

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/BoundedProcessQueue.h
> +    void SetPipelineForItems(std::shared_ptr<Pipeline>& p) const override;
const std::shared_ptr<Pipeline>& p

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/ExactlyOnceQueueManager.cpp
> +                auto p = PipelineManager::GetInstance()->FindConfigByName(configName);
const auto&

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/ProcessQueueManager.cpp
> +                auto p = PipelineManager::GetInstance()->FindConfigByName(configName);
同上

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/BoundedSenderQueueInterface.h
> +    virtual void SetPipelineForItems(std::shared_ptr<Pipeline>& p) const = 0;
const

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.cpp
> +    for (auto& item : mQueue) {
这个对吗？不是有洞吗？item很有可能是空啊

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.cpp
> +void SenderQueue::SetPipelineForItems(std::shared_ptr<Pipeline>& p) const {
还有extrabuffer里的数据呢？不加吗？

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/ExactlyOnceSenderQueue.cpp
> +        }
pipeline指针有的就不要覆盖了

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueueManager.cpp
> +    ExactlyOnceQueueManager::GetInstance()->SetPipelineForSenderItems(key, p);
这里不用else吗？

2024-09-24 09:48 UTC, henryzhx8 commented on core/pipeline/plugin/interface/Flusher.cpp
>          auto pipeline = PipelineManager::GetInstance()->FindConfigByName(mContext->GetConfigName());
const auto&

2024-09-24 11:52 UTC, Abingcbc commented on core/pipeline/queue/SenderQueueManager.cpp
> +    ExactlyOnceQueueManager::GetInstance()->SetPipelineForSenderItems(key, p);
SenderQueueManager::GetAllAvailableItems 里面也没有加else

2024-09-26 04:01 UTC, henryzhx8 requested changes

2024-09-26 04:01 UTC, henryzhx8 commented on core/pipeline/PipelineManager.cpp
> +    LogtailPlugin::GetInstance()->StopBuiltInModules();
这个放到Exit函数里，应该在LogtailAlarm之后

2024-09-26 05:35 UTC, Abingcbc commented on core/pipeline/PipelineManager.cpp
> +          PrometheusInputRunner::GetInstance(),
最后一个元素有逗号应该不影响

2024-09-27 03:12 UTC, henryzhx8 commented on core/pipeline/PipelineManager.cpp
> +    }
这里不需要判断是不是registred，updatepipelines也要有这段逻辑

2024-09-27 06:31 UTC, henryzhx8 approved these changes

2024-10-12 03:57 UTC, messixukejia commented
1、重点挑选的测试完成
2、指标（1、实际生效的pipeline；2、内存里保存的pipeline，防止泄露）

2024-10-12 03:58 UTC, messixukejia approved these changes

2024-10-12 07:06 UTC, yyuuttaaoo approved these changes

2024-10-12 07:42 UTC, merged