[WIP] feat: add Go input to Cpp processor
alibaba/ilogtail pull request #1715
Opened 2024-08-26 02:18 UTC by Assassin718

### 已实现：
- 实现v1接口LogEvent的转发
- Go InputWrapper对多个LogEvent缓存后打包成PipelineEventGroup发送给Cpp processor
### 待实现：
- Go input不同input mode (push/pull)识别
- v2接口LogEvent转发
- MetricEvent、SpanEvent转发
- 支持对Go侧缓存参数的设置

2024-08-27 08:13 UTC, shunjiazhu commented on core/go_pipeline/LogtailPlugin.cpp
> +    case sls_logs::PipelineEventGroup::EventType::PipelineEventGroup_EventType_METRIC:
这个PR会把Metric也处理吗，还是只是给出定义，后续补齐？

2024-08-27 08:19 UTC, Assassin718 commented on core/go_pipeline/LogtailPlugin.cpp
> +    case sls_logs::PipelineEventGroup::EventType::PipelineEventGroup_EventType_METRIC:
暂时只给出定义

2024-08-27 11:03 UTC, Abingcbc requested changes

2024-08-27 11:03 UTC, Abingcbc commented on pluginmanager/plugin_wrapper_metric_v1.go
> +			tagsCached = event.Context
同一个Input的不同event，可能tag的key相同，但是value不同

2024-08-27 11:03 UTC, Abingcbc commented on pluginmanager/plugin_wrapper_metric_v1.go
> +			}
sleep等待

2024-08-27 11:03 UTC, Abingcbc commented on pluginmanager/plugin_wrapper_service_v1.go
> +		p.ShutdownCachedChan <- struct{}{}
close

2024-09-02 02:05 UTC, Assassin718 commented on core/go_pipeline/LogtailPlugin.cpp
> +    for (auto& tag_pair : eventGroupSrc.tags()) {
目前cpp这边metadata的key是一个int enum，但是go这边metadata的key是string，对应关系不太明确

2024-09-02 02:07 UTC, Assassin718 commented on core/go_pipeline/LogtailPlugin.cpp
> +        auto registerProcessFun = (RegisterLogtailProcessCallBack)loader.LoadMethod("RegisterLogtailProcessCallBack", error);
这个函数用于向adapter动态库中注册pushQueue、IsValidProcess函数，类似于registerLogtailCallbackV2，请问需要与registerLogtailCallbackV2合并为一个函数吗？

2024-09-02 02:08 UTC, Assassin718 commented on core/go_pipeline/LogtailPlugin.cpp
> +    case sls_logs::PipelineEventGroup::EventType::PipelineEventGroup_EventType_METRIC:
cpp这边的metric event暂时只支持untyped single value，go的multivalue以及typed value都无法转换

2024-09-02 03:16 UTC, shunjiazhu commented on pkg/protocol/proto/pipeline_event.proto
> +syntax = "proto2";
这块有测试pb 序列化的开销和反序列化开销吗？另外有没有对比一些其他协议的性能测试，比如flatbuffer，arrow。

2024-09-02 08:45 UTC, Abingcbc requested changes

2024-09-02 08:45 UTC, Abingcbc commented on pluginmanager/plugin_runner_v2.go
> +		interval:      wrapper.Interval,
这里为什么少了time.Millisecond

2024-09-02 08:45 UTC, Abingcbc commented on pluginmanager/plugin_runner_v2.go
> +				ctx = helper.NewNativeProcessPipelineContext(p.LogstoreConfig.ConfigName, service.Input.InputMode())
可以在logstoreConfig的时候就直接创建新的context吗？

2024-09-02 08:45 UTC, Abingcbc commented on core/go_pipeline/LogtailPlugin.cpp
> +        auto registerProcessFun = (RegisterLogtailProcessCallBack)loader.LoadMethod("RegisterLogtailProcessCallBack", error);
不用啊，你的这个不需要区分v1和v2。为什么不可以直接注册pushQueue、IsValidProcess，而是再封装一层？

2024-09-02 08:45 UTC, Abingcbc commented on pluginmanager/plugin_wrapper_metric_v1.go
> +		ctx["tags"] = tags
提成一个常量

2024-09-02 08:45 UTC, Abingcbc commented on pluginmanager/plugin_wrapper_metric_v1.go
> +		case <-timer.C:
time.After来实现，timer有可能导致在临近时间点时产生小的数据包

2024-09-02 08:45 UTC, Abingcbc commented on pluginmanager/plugin_wrapper_service_v1.go
> +		p.ShutdownCachedChan <- struct{}{}
close(p.ShutdownCachedChan)

2024-09-02 08:45 UTC, Abingcbc commented on pluginmanager/plugin_wrapper_service_v1.go
> +		p.LogsCachedChan <- &pipeline.LogEventWithContext{LogEvent: logEvent, Context: nil}
这里为什么不继续传ctx

2024-09-02 08:51 UTC, Assassin718 commented on pluginmanager/plugin_runner_v2.go
> +		interval:      wrapper.Interval,
这里wrapper.Interval本来就是乘过time.Millisecond的，这里再乘一个Millisecond运行过程中不对，应该是之前写错了

2024-09-02 09:25 UTC, Abingcbc commented on pkg/protocol/proto/pipeline_event.proto
> +syntax = "proto2";
这个之前有测试过了，pb序列化和大小都是比较有优势的，但是反序列稍微慢些

2024-09-02 09:37 UTC, Assassin718 commented on pkg/protocol/proto/pipeline_event.proto
> +syntax = "proto2";
还没有测试过，后面会详细测试一下

2024-09-03 02:50 UTC, Assassin718 commented
# 已实现
- v1接口LogEvent的转发
- v2接口LogEvent、MetricEvent转发
- Go InputWrapper对多个LogEvent缓存后打包成PipelineEventGroup发送给Cpp processor
- Go input不同input mode (push/pull)识别
# 待实现
- SpanEvent转发
- 支持对Go侧缓存参数的设置

2024-09-03 07:54 UTC, shunjiazhu commented on pluginmanager/plugin_runner_v2.go
> +		interval:      wrapper.Interval,
这个确定是写错了吗，我们应该有业务用MetricInputV2 的，好像没反馈 interval 不对呀？

2024-09-03 08:44 UTC, Assassin718 commented on pluginmanager/plugin_runner_v2.go
> +		interval:      wrapper.Interval,
这里wrapper.Interval是由metricWrapperV2.Init初始化的，这个Init函数输入参数有一个int类型的inputInterval，在函数中对inputInterval乘time.Millisecond赋给了wrapper.Interval

2024-09-04 04:30 UTC, shunjiazhu commented on pluginmanager/plugin_runner_v2.go
> +		interval:      wrapper.Interval,
好的，这个好像是近期引入的 bug，我们内部会延后一点时间和社区 main 同步，所以上一个版本还没问题

2024-09-11 06:31 UTC, shunjiazhu commented on plugin_main/plugin_export.go
> +struct loadGoPipelineResp {
func GetPipelineMetrics() *C.PluginMetrics也要调整吗？改成 pb协议到core。

2024-09-19 09:00 UTC, Assassin718 commented on core/pipeline/Pipeline.h
> +    bool IsFlushingThroughGoPipeline() const;
这里是因为当流水线配置为go input -> cpp processor -> go processor/aggregator/flusher时，在pipeline::Init()中将go的配置全部添加到了mGoPipelineWithInput，此时mGoPipelineWithoutInput为空，因此这里会返回false，导致cpp无法向go发送数据

2024-10-29 08:59 UTC, Assassin718 commented on pluginmanager/plugin_wrapper_metric_v1.go
> +			case <-wrapper.timer.C:
直接timer.After会有比较大的内存分配性能开销

2024-10-29 11:12 UTC, Assassin718 commented on pluginmanager/plugin_runner_v2.go
> +	p.NativeInputPipeContext = nil
这里InputMode只有在在Init函数执行之后执行AddXXXInput时才能确定下来，但是这个Context又必须传入InputMode，不太好改

2024-10-29 11:18 UTC, Assassin718 commented on pluginmanager/plugin_wrapper_metric_v1.go
> +		if isValidToPushNativeProcessQueue {
这里因为是直接调用cpp的PushQueue接口，cpp的processorQueue::PushQueue不是阻塞的

2024-10-29 11:19 UTC, Assassin718 commented on pluginmanager/plugin_wrapper_metric_v1.go
> +	if len(wrapper.pbBuffer) == 0 && len(wrapper.eventCached) == 0 {
pbBuffer是用来放pb反序列化后的结果，这里是尽量希望内存复用

2024-10-29 11:24 UTC, Assassin718 commented on pluginmanager/plugin_wrapper_metric_v1.go
> +		if isValidToPushNativeProcessQueue {
这里主要逻辑是：检测到ProcessQueue水位高时会停止监听LogCachedChan，以阻塞Input；直到检测到ProcessQueue水位低后才重新监听LogCachedChan，使Input运行

2024-10-29 11:31 UTC, Assassin718 commented on pluginmanager/plugin_wrapper_metric_v1.go
> +	if len(wrapper.pbBuffer) == 0 && len(wrapper.eventCached) == 0 {
并且如果向cpp发送失败，需要保存上次已经反序列化后的结果，否则会重新反序列化

2024-10-29 14:06 UTC, Assassin718 commented on pluginmanager/plugin_wrapper_metric_v1.go
> +	if len(wrapper.pbBuffer) == 0 && len(wrapper.eventCached) == 0 {
- 序列化的对象是PipelineEventGroup，我不太确定Protobuf对于PipelineEventGroup的序列化结果是不是LogEvent序列化结果的简单叠加，这里可能有优化空间
- 如果不保留event、tag、context的buffer的话，在出现tag/context不一致时需要检查更多的边界条件，这里暂时是比较简单的实现，有优化空间

2024-10-31 01:51 UTC, merged