Update/prom zero cost
alibaba/ilogtail pull request #1717
Opened 2024-08-26 08:56 UTC by catdogpandas

2024-08-28 13:27 UTC, messixukejia requested changes

2024-08-29 06:03 UTC, catdogpandas commented on core/processor/inner/ProcessorPromParseMetricNative.cpp
> -    if (eGroup.GetEvents().empty()) {
为了在39行添加一条自监控指标。后面的内容以空 Group 跑也没问题，所以删掉这里逻辑会变的更简单。

2024-08-29 09:48 UTC, messixukejia approved these changes

2024-09-13 07:57 UTC, linrunqi08 approved these changes

2024-09-13 07:57 UTC, merged