feat: support prom scrape protocols
alibaba/ilogtail pull request #1719
Opened 2024-08-27 04:37 UTC by catdogpandas

2024-08-28 13:27 UTC, messixukejia requested changes

2024-08-28 13:27 UTC, messixukejia commented on core/prometheus/Constants.h
> +const char* const PrometheusText0_0_4 = "PrometheusText0.0.4";
这是标准的协议？如果是注释下出处

2024-08-28 13:27 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +bool ScrapeConfig::InitScrapeProtocols(const Json::Value& scrapeProtocols) {
这个函数分支还是很多的，ut不是太够

2024-08-29 07:01 UTC, catdogpandas commented on core/prometheus/Constants.h
> +const char* const PrometheusText0_0_4 = "PrometheusText0.0.4";
这四个是协议名字可以从(链接)[https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config]得到。背后是发送的 text/plain, application/openmetrics-text 这样的请求头。

2024-08-29 09:48 UTC, messixukejia approved these changes

2024-08-30 07:43 UTC, linrunqi08 commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +    tmpScrapeProtocols.push_back("*/*;q=0." + ToString(weight));
这个拼出来的字符串的含义是什么？会影响什么？

2024-08-30 07:56 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +    tmpScrapeProtocols.push_back("*/*;q=0." + ToString(weight));
这里是对不同的协议按照先后顺序设置权重，靠前的权重会高。会放到的请求头的 Accept 中。
比如`text/plain;version=0.0.4;q=0.4,application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited;q=0.3,application/openmetrics-text;version=0.0.1;q=0.2,*/*;q=0.1`这个情况会希望Exporter返回 text/plain 的优先级高。

2024-09-19 02:55 UTC, merged