change go exporter
alibaba/ilogtail pull request #1727
Opened 2024-08-30 07:24 UTC by Takuka0311

修改了Go暴露指标的逻辑，从原本的“插件/进程”级别的区分改为“Go直接输出/C++注册指标”两种类型

2024-08-30 08:33 UTC, messixukejia requested changes

2024-08-30 08:33 UTC, messixukejia commented on pluginmanager/metric_export.go
> +	metrics = append(metrics, GetAgentStat())
这个不太能很好扩展，因为跟下面for循环赋值是耦合的，无法很好区分

2024-08-30 08:33 UTC, messixukejia commented on pluginmanager/metric_export.go
> +	MetricExportLevelAgent = "agent"
这个是不是可以去掉了

2024-09-02 02:09 UTC, Takuka0311 commented on pluginmanager/metric_export.go
> +	MetricExportLevelAgent = "agent"
是的

2024-09-02 11:37 UTC, messixukejia requested changes

2024-09-10 09:58 UTC, messixukejia requested changes

2024-09-10 09:58 UTC, messixukejia commented on pluginmanager/metric_export.go
> +		record[recordName] = recordValueString
recordName 名词统一

2024-09-10 09:58 UTC, messixukejia commented on pluginmanager/metric_export.go
> +// 直接输出的go指标，例如go插件指标
样例加上注释

2024-09-10 09:58 UTC, messixukejia commented on core/file_server/reader/LogFileReader.cpp
> +    mLogFileOp.Open(mHostLogPath.c_str());
去掉

2024-09-10 09:58 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +                goCppProvidedMetircsList.push_back(std::move(goMetrics));
if else

2024-09-10 09:58 UTC, messixukejia commented on core/monitor/MetricExportor.cpp
> +    for (auto metrics : metricsList) {
![image](https://github.com/user-attachments/assets/9c3d1a39-6f82-462a-ab88-556937750237)

2024-09-12 01:43 UTC, messixukejia approved these changes

2024-09-12 01:43 UTC, messixukejia commented on pluginmanager/metric_export.go
> +//	    {
注释的缩进保持一致，包括上面的

2024-09-12 01:43 UTC, messixukejia commented on pluginmanager/metric_export.go
> +		metric[recordName] = recordValueString
不是有个意见 recordName 跟metric的定义对齐吗

2024-09-12 02:31 UTC, Takuka0311 commented on pluginmanager/metric_export.go
> +		metric[recordName] = recordValueString
之前是record、records、recordName这些比较混乱，命名也有歧义。修改之后所有函数统一为：

* metrics：[]map[string]string，内部包含多个metric
* metric：map[string]string，内部包含多个k-v
* k-v：[key:value]，为了避免歧义就不单独命名了，就叫key-value

2024-09-12 03:54 UTC, messixukejia commented on pluginmanager/metric_export.go
> +//			"agent_go_routines_total": "20"
![image](https://github.com/user-attachments/assets/cbae6d47-9feb-4cc8-bf8b-f0f96f6f0dfc)
举一反三

2024-09-12 03:55 UTC, messixukejia commented on pluginmanager/metric_export.go
> +//			"agent_go_routines_total": "20"
![image](https://github.com/user-attachments/assets/8ff33a86-2506-4512-b135-5c990556f171)

2024-09-12 05:47 UTC, Takuka0311 commented on pluginmanager/metric_export.go
> +//			"agent_go_routines_total": "20"
![image](https://github.com/user-attachments/assets/bc75144c-7b5e-4c62-9519-cda824cdba5b)
空格和tab在github这边显示和本地不一致，我改一下

2024-09-12 05:49 UTC, messixukejia commented on pluginmanager/metric_export.go
> +//			"agent_go_routines_total": "20"
这是个开发基本的习惯

2024-09-12 06:25 UTC, yyuuttaaoo approved these changes

2024-09-12 06:26 UTC, merged