add ebpf input e2e related functions
alibaba/ilogtail pull request #1728
Opened 2024-08-30 08:32 UTC by alph00

2024-08-31 08:05 UTC, messixukejia requested changes

2024-08-31 08:05 UTC, messixukejia commented on test/engine/verify/ebpf_file_verify.go
> +func FilePathVerify(ctx context.Context, filePath string) (context.Context, error) {
并不太具备通用性，先给我讲下整体设计思路吧

2024-09-03 07:15 UTC, alph00 commented on test/engine/verify/ebpf_file_verify.go
> +func FilePathVerify(ctx context.Context, filePath string) (context.Context, error) {
已增加一定泛用性

2024-09-04 09:00 UTC, messixukejia requested changes

2024-09-04 09:00 UTC, messixukejia commented on test/engine/trigger/ebpf_file_mmap_test.go
> +func TestMmapCommand(t *testing.T) {
这些额外执行的文件，放到一个统一的目录下吧。不要叫test，叫数据生成器之类的。

2024-09-04 11:31 UTC, Abingcbc commented on test/engine/trigger/trigger.go
> +func BeginTrigger(ctx context.Context) (context.Context, error) {
其他日志的也要修改成统一的形式

2024-09-05 13:07 UTC, alph00 commented on test/engine/trigger/ebpf_file_mmap_test.go
> +func TestMmapCommand(t *testing.T) {
已经放到额外的文件夹
按go语法，函数名和文件名不带test不能脱离main执行

2024-09-05 13:07 UTC, alph00 commented on test/engine/trigger/trigger.go
> +func BeginTrigger(ctx context.Context) (context.Context, error) {
TODO

2024-09-06 01:17 UTC, messixukejia requested changes

2024-09-06 01:17 UTC, messixukejia commented on test/engine/trigger/generator/apsara_test.go
> -package trigger
文件不要叫test后缀，改成apsara_generator

2024-09-06 02:25 UTC, alph00 commented on test/engine/trigger/generator/apsara_test.go
> -package trigger
按go语法，函数名和文件名不带test不能按现在的方式脱离main执行

2024-09-06 05:35 UTC, messixukejia requested changes

2024-09-06 05:35 UTC, messixukejia commented on test/engine/trigger/ebpf_trigger.go
> +	hooks := []string{"security_file_permission", "security_mmap_file", "security_path_truncate"}
遍历触发一遍，下面还用到switch case实现是不是有点多余？

2024-09-06 05:35 UTC, messixukejia commented on test/engine/trigger/generator/apsara_test.go
> -package trigger
那就改成main的方式，这里用go test貌似没有什么收益。因为这里执行的并不是test，只是在构造数据

2024-09-06 05:35 UTC, messixukejia commented on test/engine/trigger/ebpf_trigger.go
> +func TrigerFileSecurityEvents(ctx context.Context, commandCnt int, filenames string) (context.Context, error) {
![image](https://github.com/user-attachments/assets/a9945db9-f8b4-45cc-b5c2-c3ecfa2ec90e)
files还是file？

2024-09-06 05:35 UTC, messixukejia commented on test/engine/trigger/ebpf_trigger.go
> +		for i := 0; i < commandCnt; i++ {
加上touchFileCommand、removeCommand，预期到底产生多少事件？

2024-09-08 17:21 UTC, alph00 commented on test/engine/trigger/ebpf_trigger.go
> +func TrigerFileSecurityEvents(ctx context.Context, commandCnt int, filenames string) (context.Context, error) {
现在这里不需要指定不同hook的情况下，我理解files都放到一次execute里面更简洁，含义也比较清晰？
我在case里把这三行改到一行吧

2024-09-09 02:58 UTC, alph00 commented on test/engine/trigger/ebpf_trigger.go
> +		for i := 0; i < commandCnt; i++ {
目前最新版本sysak采回来是可以符合预期条数的，touch和remove不产生事件，每一次cat、truncate、mmap都是触发一次事件

2024-09-10 01:07 UTC, messixukejia approved these changes

2024-09-10 01:15 UTC, sunym1991 approved these changes

2024-09-10 04:05 UTC, merged