sls flusher support  metricstore
alibaba/ilogtail pull request #1731
Opened 2024-09-01 13:09 UTC by EvanLjp

Logtail 2.0 add sls Metrics support

2024-09-01 13:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1731) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=1731) before we can accept your contribution.<br/><hr/>**shaoxuan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=1731) it.</sub>

2024-09-02 12:13 UTC, henryzhx8 requested changes

2024-09-02 12:13 UTC, henryzhx8 commented on core/sdk/Client.cpp
> +                                                      bool isMetrics) {
这里最好改成enum，可以复用flushersls里的，因为以后可能还有trace

2024-09-02 12:13 UTC, henryzhx8 commented on core/sdk/Client.cpp
> +            return SynPostMetricStoreLogs(project, logstore, compressedLogGroup, httpHeader);
这个没有hashkey吗？

2024-09-02 12:13 UTC, henryzhx8 commented on core/sdk/Client.cpp
> +                                                 int64_t hashKeySeqID,
这俩参数没用？

2024-09-02 12:13 UTC, henryzhx8 commented on core/sdk/CurlImp.cpp
> +            }
搜一下IsLogServiceResponse()，应该在flushersls里面还有一个地方有类似的

2024-09-02 12:13 UTC, henryzhx8 commented on core/flusher/sls/FlusherSLS.h
> +    sls_logs::SlsTelemetryType mTelemetryType = sls_logs::SlsTelemetryType::SLS_TELEMETRY_TYPE_LOGS;
这个为什么要改？

2024-09-19 12:07 UTC, EvanLjp commented on core/flusher/sls/FlusherSLS.h
> +    sls_logs::SlsTelemetryType mTelemetryType = sls_logs::SlsTelemetryType::SLS_TELEMETRY_TYPE_LOGS;
落文件时候，之前这个不记录，recover 时候只能按 log recover

2024-09-20 09:35 UTC, EvanLjp commented on core/sdk/Client.cpp
> +                                                      bool isMetrics) {
这个是存储类型，trace 没有特点存储，都是 logstore

2024-09-20 09:36 UTC, EvanLjp commented on core/sdk/Client.cpp
> +            return SynPostMetricStoreLogs(project, logstore, compressedLogGroup, httpHeader);
metricstore 这个渠道自动 hash

2024-09-20 09:37 UTC, EvanLjp commented on core/sdk/Client.cpp
> +                                                 int64_t hashKeySeqID,
没用删了

2024-09-27 05:39 UTC, linrunqi08 commented on core/sdk/CurlImp.cpp
> +            }
FlusherSLS里面，搜一下IsSLSResponse，这块整体重写了一下，这里也处理一下吧

2024-09-27 07:37 UTC, EvanLjp commented on core/sdk/CurlImp.cpp
> +            }
删除了

2024-09-27 07:38 UTC, linrunqi08 approved these changes

2024-09-27 07:43 UTC, henryzhx8 approved these changes

2024-09-27 07:43 UTC, henryzhx8 commented on core/plugin/flusher/sls/FlusherSLS.h
> +#include "sls_logs.pb.h"
把路径写全

2024-09-27 07:55 UTC, EvanLjp commented
TODO : Logtail 端针对错误码的特殊处理需要需求可以同步 Metricstore , 如 SLS quota 异常 @linrunqi08 @henryzhx8

2024-09-27 10:10 UTC, messixukejia approved these changes

2024-09-27 10:13 UTC, merged