feat: support k8s meta to collect more resources
alibaba/ilogtail pull request #1736
Opened 2024-09-03 16:08 UTC by Abingcbc

1. 增加全部的K8s实体和关系
2. 存储时删减Pod非必要字段
3. 修复http server返回结果中的 workload 字段，在Replicaset时，更进一步推到deployment

**TODO**
1. 可观测指标

2024-09-05 02:04 UTC, messixukejia requested changes

2024-09-05 06:04 UTC, Abingcbc commented on plugins/input/kubernetesmetav2/meta_collector_core.go
> +		m.processEntityCommonPart(log.Contents, obj.Kind, obj.Namespace, obj.Name, method, data.FirstObservedTime, data.LastObservedTime, obj.CreationTimestamp.Unix())
这个是因为原始yaml里就缺少单位
![image](https://github.com/user-attachments/assets/299f0ea1-e3ae-4c41-b4ff-13fd144f68e8)

2024-09-05 06:42 UTC, messixukejia requested changes

2024-09-05 06:42 UTC, messixukejia commented on plugins/input/kubernetesmetav2/meta_collector.go
> +	if m.serviceK8sMeta.Node {
这段代码，是不是也可以改成上面map的形式

2024-09-05 06:42 UTC, messixukejia commented on plugins/input/kubernetesmetav2/meta_collector_app.go
> +		log.Contents.Add("match_labels", string(matchLabelsStr))
match_labels的含义是什么

2024-09-05 06:42 UTC, messixukejia commented on plugins/input/kubernetesmetav2/meta_collector_app.go
> +		log.Contents.Add("annotations", string(annotationsStr))
这里信息有点多，确认下有没有采集的必要性

2024-09-05 06:42 UTC, messixukejia commented on plugins/input/kubernetesmetav2/meta_collector_const.go
> +	k8sEntityTypePrefix = "k8s."
以文档为主，可以后面定下来再改

2024-09-05 07:02 UTC, Abingcbc commented on plugins/input/kubernetesmetav2/meta_collector_app.go
> +		log.Contents.Add("match_labels", string(matchLabelsStr))
deployment管理的pod的label

2024-09-06 10:13 UTC, messixukejia requested changes

2024-09-06 10:13 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_cache_pod.go
> +	m.schema = runtime.NewScheme()
与common融合

2024-09-06 10:13 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_const.go
> +var AllLinkMap = map[string]bool{
？

2024-09-06 10:13 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +					podMetadata.WorkloadName = replicaset.Raw.(*app.ReplicaSet).OwnerReferences[0].Name
越界

2024-09-06 10:13 UTC, messixukejia commented on plugins/input/kubernetesmetav2/service_meta.go
> +	PodNodeLink              bool
自动开关

2024-09-06 10:13 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_link_test.go
> +			Object:    podCache.metaStore.Items["default/test"],
命名service1

2024-09-10 09:38 UTC, Abingcbc commented on plugins/input/kubernetesmetav2/meta_collector.go
> +	if m.serviceK8sMeta.Node {
这些都是配置项，改成map可能需要用反射来获取属性

2024-09-10 10:19 UTC, messixukejia approved these changes

2024-09-10 10:36 UTC, merged