1. support honor_timestamps, 2. support honor_labels, apply global mTags to MetricEvent in serializing phase 3. optimization relabel, manage MetricEvent tags directly
alibaba/ilogtail pull request #1742
Opened 2024-09-06 02:48 UTC by catdogpandas

2024-09-07 01:52 UTC, messixukejia requested changes

2024-09-07 01:52 UTC, messixukejia commented on core/prometheus/Utils.cpp
> +uint64_t SizeToByte(const std::string& size) {
输入是从MAX_SCRAPE_SIZE获取的，那就可能有非法配置

2024-09-07 01:52 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +    if ((int)scrapeConfig.isMember(prometheus::BASIC_AUTH) + scrapeConfig.isMember(prometheus::AUTHORIZATION) > 1) {
把采集配置的内部文档更新下，发出来看看。

后面再有类似pr，都发下吧

2024-09-09 01:44 UTC, catdogpandas commented on core/pipeline/Pipeline.cpp
> +                mContext.GetProcessQueueKey(), priority, 5000000);
500万，是为从上周压测预估出来的最大数字。上周压测的数据是当前的 One-Agent 仅能负担 100万的时间线数量。

2024-09-09 01:46 UTC, catdogpandas commented on core/prometheus/Utils.cpp
> +uint64_t SizeToByte(const std::string& size) {
SizeToByte 里面进行了非法配置的校验，当符合`数字+单位`的格式时才会进行字符串转数字，否则返回0，表示非法。

2024-09-09 04:10 UTC, messixukejia commented on core/pipeline/Pipeline.cpp
> +                mContext.GetProcessQueueKey(), priority, 5000000);
要讲清楚全局的影响，需要评审下

2024-09-12 07:38 UTC, catdogpandas commented on core/pipeline/Pipeline.cpp
> +                mContext.GetProcessQueueKey(), priority, 5000000);
讨论结果是使用反压队列，所以这里就不需要修改了

2024-09-19 02:52 UTC, linrunqi08 commented
apply global mTags to MetricEvent in serializing phase  体现在哪里？

2024-09-19 02:54 UTC, linrunqi08 commented on core/prometheus/Utils.cpp
> +    } else if (EndWith(inputSize, "KiB") || EndWith(inputSize, "K") || EndWith(inputSize, "KB")) {
这些大小写都是固定的吗？会出现kib，k，kb这种数据吗

2024-09-19 05:35 UTC, catdogpandas commented on core/prometheus/Utils.cpp
> +    } else if (EndWith(inputSize, "KiB") || EndWith(inputSize, "K") || EndWith(inputSize, "KB")) {
不会，kib, k, kb 这样的应该算是非法。

2024-09-26 01:13 UTC, linrunqi08 approved these changes

2024-09-27 01:06 UTC, messixukejia approved these changes

2024-10-08 01:31 UTC, merged