remove callname and
alibaba/ilogtail pull request #1745
Opened 2024-09-06 07:22 UTC by alph00

* modify plugin type name

2024-09-06 08:57 UTC, messixukejia requested changes

2024-09-06 08:57 UTC, messixukejia commented on docs/cn/plugins/input/input-ebpf-network-security.md
>  |  Type  |  string  |  是  |  /  |  插件类型。固定为input\_ebpf\_network\_security  |
文件名

2024-09-06 09:43 UTC, alph00 commented on docs/cn/plugins/input/input-ebpf-network-security.md
>  |  Type  |  string  |  是  |  /  |  插件类型。固定为input\_ebpf\_network\_security  |
已经都修改了

2024-09-06 09:56 UTC, sunym1991 commented on docs/cn/plugins/input/input-file-security.md
> +|  ProbeConfig  |  object  |  否  |  ProbeConfig 包含默认为空的 Filter  |  ProbeConfig 内部可以有多个 Filter，Filter 内部是或的关系，Filter 之间是且的关系  |
去除callname后，probeconfig只有一个filter了

2024-09-06 09:58 UTC, alph00 commented on docs/cn/plugins/input/input-file-security.md
> +|  ProbeConfig  |  object  |  否  |  ProbeConfig 包含默认为空的 Filter  |  ProbeConfig 内部可以有多个 Filter，Filter 内部是或的关系，Filter 之间是且的关系  |
已经修改

2024-09-06 10:21 UTC, messixukejia commented on core/plugin/input/InputEBPFFileSecurity.cpp
> -const std::string InputEBPFFileSecurity::sName = "input_ebpf_fileprobe_security";
文件名

修改代码举一反三

2024-09-08 12:23 UTC, alph00 commented on core/plugin/input/InputEBPFFileSecurity.cpp
> -const std::string InputEBPFFileSecurity::sName = "input_ebpf_fileprobe_security";
修改了所有input相关的 *EBPF* 命名

2024-09-09 00:46 UTC, messixukejia approved these changes

2024-09-09 10:29 UTC, merged