check runtime env
alibaba/ilogtail pull request #1749
Opened 2024-09-10 09:29 UTC by KayzzzZ

2024-09-27 03:10 UTC, messixukejia requested changes

2024-09-27 03:10 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +void EnvManager::InitEnvInfo() {
InitEnvInfo 调用点也有点多，IsSupportedEnv、eBPFServer::Init都在调用，感觉有点混乱。

优化方向：
IsSupportedEnv 作为 eBPFServer::Init 的一部分就可以了。不支持一定不会init成功。ebpf::eBPFServer::GetInstance()->IsSupportedEnv 类似的判断也就都也已改成是否init为true了。

2024-09-27 03:10 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
>      Init();
这里的init是不是放到类似InputFileSecurity::Init 更合适些?

2024-09-27 03:10 UTC, KayzzzZ commented on core/ebpf/SourceManager.cpp
> +    LOG_DEBUG(sLogger, ("running in container mode, would set host path prefix to", mHostPathPrefix));
ok

2024-09-27 03:20 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +bool EnvManager::IsSupportedEnv(nami::PluginType type) {
最开始一版实现就是成员函数，改成单独的类有几个原因：
1. 要增加一些 m310Support 之类的成员，跟 ebpf server 中其他的成员变量平铺起来我个人感觉有些冗余；
2. eBPF 的一些 helper function 和 program type 是跟着 kernel version 迭代的。后续扩展插件的过程中，可能每个插件所需要 check 的内容都不一样，甚至能降低到 callname 级别。我觉得这个类后续可能还会做很多扩展。

2024-09-27 03:20 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +    m310Support = true;
我检查一下

2024-09-27 03:22 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +    if (mRelease.empty()) {
同 EnvManager 中的讨论，后续扩展的过程中有可能会用到这些变量，所以我把它放到成员中了，但目前确实是没有用到。

2024-09-27 03:22 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +        return mArchSupport && (mBTFSupport || m310Support);
ok

2024-09-27 09:58 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +void EnvManager::InitEnvInfo() {
okk 看了一下代码确实两个位置都有调用，的确有些乱。
我思考了一下，我之前进行了两次调用主要是因为有些平台和架构，load so 包时可能报错，而 eBPFServer 是在 init() 中对 so 包进行 load 的。所以我当时在插件的 init 方法中，先初始化 EnvManager ，如果环境不合适，直接是 so 包都不进行加载了。

现在修改了一下逻辑，在 eBPFServer::Init 中先进行 InitEnvInfo，然后增加了加载 so 包的环境判断。这样就不冲突了，也收敛了 InitEnvInfo 的调用。

2024-09-27 09:59 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
>      Init();
是的，已经移走了。

2024-09-27 23:09 UTC, messixukejia approved these changes

2024-10-14 00:40 UTC, linrunqi08 approved these changes

2024-10-14 14:15 UTC, merged