feat: support prometheus self monitor, add 9 metrics for prom input plugin
alibaba/ilogtail pull request #1760
Opened 2024-09-13 07:14 UTC by catdogpandas

指标 | 描述| labels | 类型
-- | -- | -- | --
prom_register_state | 注册状态 | pod_name,operator_host,operator_port | IntGauge
prom_register_retry_total | 注册重试 | status,pod_name,... | Counter
prom_job_num | 输入插件（Job）数量 | pod_name,... | IntGauge
prom_subsricbe_targets | 订阅的 Targets 数量 | job,pod_name,... | IntGauge
prom_subsricbe_total | 订阅次数总量 | status,job,pod_name,... | Counter
prom_subsricbe_time_ms | 订阅耗时（分布） | status,job,pod_name,... | IntGauge
prom_scrape_total | 采集次数总量 | status,target,job,pod_name,... | Counter
prom_scrape_bytes_total | 采集总字节数 | status,target,job,pod_name,... | Counter
prom_scrape_time_ms | 采集耗时（分布） | status,target,job,pod_name,... | IntGauge

</article>

2024-09-13 07:57 UTC, Takuka0311 requested changes

2024-09-13 07:57 UTC, Takuka0311 commented on core/prometheus/Constants.h
> +const char* const PROM_REGISTER_STATE = "prom_register_state";
这些指标名、Label的const的定义放在core/monitor/MetricConstants.h里吧

2024-09-13 07:57 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.cpp
> +        for (const auto& [metricName, type] : metricKeys) {
这里用的有点奇怪。pluginManager应该是一个key对应一个，然后里面会初始化填多个metricKeys。你这边的逻辑的话，定义应该是

```cpp
std::map<std::string, PluginMetricManagerPtr> mPromMetricsMap;

if (!mPromMetricsMap.count(key)) {
    mPromMetricsMap[key] = std::make_shared<PluginMetricManager>(mDefaultLabels, metricKeys);
}
```

使用应该是

```cpp
    pluginMetricManagerPtr =  mPromMetricsMap[key];
    labels = .....
    metricRecordRef = PluginMetricManagerPtr->GetOrCreateReentrantMetricsRecordRef(labels);
    counter = metricRecordRef->GetCounter(metricKey);
```

2024-09-13 07:57 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.cpp
> +        for (const auto& [metricName, type] : metricKeys) {
先把这个改好在看下吧

2024-09-14 03:19 UTC, Takuka0311 requested changes

2024-09-14 03:19 UTC, Takuka0311 commented on core/prometheus/PrometheusInputRunner.cpp
> +    dynamicLabels.emplace_back(METRIC_LABEL_PROJECTS, []() -> std::string { return FlusherSLS::GetAllProjects(); });
这边merge main看下，METRIC_LABEL_PROJECTS都统一为METRIC_LABEL_PROJECT了

2024-09-14 03:19 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.h
> +class PromSelfMonitor {
这个类是否需要？各个MetricManager放在自己的类里初始化就可以了吧

2024-09-14 03:19 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.h
> +    CounterAdd(const std::string& key, const std::string& metricName, const MetricLabels& labels, uint64_t val = 1);
![image](https://github.com/user-attachments/assets/2a67c26d-cc55-484d-bd1f-a5c830344b44)
这样做不满足这个原则

2024-09-14 03:19 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.h
> +    void InitMetricManager(const std::string& key,
有考虑过并发调用的情况吗？
mPromMetricsMap这个结构，你目前实现了创建、查询，都是无锁的，但是删除某个key的场景不需要考虑吗？pluginManager如果不销毁，或者不调用ReleaseReentrantMetricsRecordRef，指标会一直发送的

2024-09-14 03:19 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.h
> +class PromSelfMonitor {
要不在文档把现在的自监控数据链路画个图吧，哪个类里面调用了哪个东西初始化了什么、metricRecord、metricManager分别保存在哪里、什么时候初始化、什么时候调用之类的，简单画一下

2024-09-14 03:23 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.h
> +class PromSelfMonitor {
例如每一层指标，它的生命周期，可以画个图看看。例如job、inputRunner、target等的指标通过谁、什么时候初始化，什么时候通过什么类去记录、什么时候销毁这些

2024-09-14 04:19 UTC, catdogpandas commented on core/prometheus/PromSelfMonitor.h
> +    void InitMetricManager(const std::string& key,
并发调用和指标熟练的问题都解决了。

2024-09-14 04:21 UTC, catdogpandas commented on core/prometheus/PromSelfMonitor.h
> +class PromSelfMonitor {
这个类的作用是解决 status 的问题。status 可枚举，但是正常状态下，status 只有200，如果在初始化时就创建对应的所有枚举指标，反而会导致发送的自监控日志变多，所以才用这种方法。生命周期管理我都解决了。

2024-09-14 04:21 UTC, catdogpandas commented on core/prometheus/PromSelfMonitor.h
> +class PromSelfMonitor {
你再看一下

2024-09-14 10:01 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.h
> +class PromSelfMonitor {
GetOrCreateReentrantMetricsRecordRef这个方法，在status没有400的情况下，也不会有400的metricRecord

2024-09-14 10:02 UTC, Takuka0311 commented on core/prometheus/PromSelfMonitor.h
> +class PromSelfMonitor {
mPromMetricsMap中的key，会有释放的情况吗

2024-09-20 08:26 UTC, linrunqi08 commented on core/prometheus/PromSelfMonitor.cpp
> +    mMetricsCounterMap[metricName][status]->Add(val);
就算用map，不用加锁吗

2024-09-20 08:26 UTC, linrunqi08 commented on core/prometheus/PromSelfMonitor.cpp
> +    mMetricsCounterMap[metricName][status]->Add(val);
status 3XX，4XX，5XX这样是不是就好了？不需要具体的code吧

2024-10-10 07:06 UTC, closed without merging