add metric for flusher component
alibaba/ilogtail pull request #1762
Opened 2024-09-14 09:19 UTC by henryzhx8

2024-09-14 09:56 UTC, Takuka0311 requested changes

2024-09-14 09:56 UTC, Takuka0311 commented on core/pipeline/plugin/instance/FlusherInstance.cpp
> +    mInEventsCnt = mPlugin->GetMetricsRecordRef().CreateCounter("in_events_cnt");
指标名字的定义加到MetricConstants里吧

2024-09-14 10:02 UTC, messixukejia approved these changes

2024-09-18 03:13 UTC, Takuka0311 requested changes

2024-09-18 03:13 UTC, Takuka0311 commented on core/pipeline/Pipeline.cpp
> +    mStartTime = mMetricsRecordRef.CreateIntGauge("start_time");
core/monitor/MetricConstants.h

2024-09-18 05:45 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +    mStartTime = mMetricsRecordRef.CreateIntGauge("start_time");
不用什么东西都放在那个文件里，本来这个搞法就不对，只有很多地方引用的公共label才应该放在那。

2024-09-18 06:58 UTC, linrunqi08 approved these changes

2024-09-18 07:21 UTC, yyuuttaaoo commented on core/common/compression/CompressorFactory.h
> +    std::unique_ptr<Compressor> Create(CompressType type);
这个搞成public？

2024-09-18 07:24 UTC, yyuuttaaoo commented on core/pipeline/batch/BatchItem.h
> +                                 .time_since_epoch()
这里什么意思？

2024-09-18 07:29 UTC, yyuuttaaoo commented on core/pipeline/batch/Batcher.h
> +        mEventBatchItemsCnt = mMetricsRecordRef.CreateIntGauge("buffers_cnt");
这个指标和group是什么区别

2024-09-18 07:40 UTC, Takuka0311 approved these changes

2024-09-18 08:16 UTC, henryzhx8 commented on core/common/compression/CompressorFactory.h
> +    std::unique_ptr<Compressor> Create(CompressType type);
压缩组件不一定是pipeline专用的，其他模块也可以用，所以这个函数是给其它模块用的

2024-09-18 08:17 UTC, henryzhx8 commented on core/pipeline/batch/BatchItem.h
> +                                 .time_since_epoch()
入队时间总和，用来计算delay的

2024-09-18 08:18 UTC, henryzhx8 commented on core/pipeline/batch/Batcher.h
> +        mEventBatchItemsCnt = mMetricsRecordRef.CreateIntGauge("buffers_cnt");
group还要包括group级聚合队列里的元素

2024-09-19 01:30 UTC, merged