Reconstruct appconfig to support InstanceConfig.
alibaba/ilogtail pull request #1763
Opened 2024-09-18 09:08 UTC by quzard

2024-09-24 10:45 UTC, messixukejia requested changes

2024-10-15 06:59 UTC, messixukejia approved these changes

2024-10-15 06:59 UTC, messixukejia commented on core/common/Flags.h
> +#define SAFE_SET_DOUBLE_FLAG(name, value) gflags::SetCommandLineOption("SAFE_FLAG_" #name, value)
删了吧

2024-10-15 07:41 UTC, yyuuttaaoo commented on core/config/InstanceConfig.h
>      std::unique_ptr<Json::Value> mDetail;
感觉有点复杂，这里并不性能关键，为啥不直接用Json::Value，不用指针

2024-10-15 09:54 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +    if (BOOL_FLAG(logtail_mode)) {
没用

2024-10-15 11:44 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +Json::Value AppConfig::mergeAllConfigs() {
可以分开直接比较，不需要合并。合并后local的值是否生效其实不一定是按这个顺序覆盖的结果

2024-10-15 11:51 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +    }
放外面

2024-10-15 12:10 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +        for (const auto& callback : mCallbacks) {
这里应该先把callback收集一下，然后才开始调用。

2024-10-15 12:24 UTC, yyuuttaaoo commented on core/runner/FlusherRunner.cpp
> +        "max_bytes_per_sec", [this](auto && PH1) { return LoadModuleConfig(std::forward<decltype(PH1)>(PH1)); });
简化一下，固定传入false

2024-10-16 02:33 UTC, yyuuttaaoo commented on core/runner/FlusherRunner.cpp
> +    if (isInit) {
这里可以改一下if里面是non reloadable configs
else直接放外面

2024-10-16 02:45 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +            MergeJson(localInstanceConfig, config.second->GetConfig(), mLocalInstanceConfigKeyToConfigName, config.second->mDirName+"$"+config.second->mConfigName);
dir和name之间是不是用/比较好

2024-10-16 02:50 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +        ("merge instance config", name)("key", name)("value", res)("defaultValue", defaultValue)("from", configName));
我感觉语义是lastValue，看调用点已经不是default的意思了

2024-10-16 02:51 UTC, yyuuttaaoo commented on core/config/InstanceConfig.h
> +    InstanceConfig(const std::string& name, const Json::Value& detail, const std::string& dirName)
4个全部删掉

2024-10-16 03:21 UTC, quzard commented on core/config/InstanceConfig.h
> +    InstanceConfig(const std::string& name, const Json::Value& detail, const std::string& dirName)
InstanceConfig(const std::string& name, const Json::Value& detail, const std::string& dirName)
需要留着

2024-10-16 03:37 UTC, yyuuttaaoo approved these changes

2024-10-16 08:12 UTC, merged