add K8s meta self metrics
alibaba/ilogtail pull request #1765
Opened 2024-09-18 12:10 UTC by Abingcbc

2024-09-20 11:17 UTC, messixukejia commented on plugins/input/kubernetesmetav2/service_meta.go
>  	Ingress               bool
domain去掉，增加个部署形态参数。

部署形态决定集群类型，以及entity前缀

2024-09-20 11:17 UTC, messixukejia commented on plugins/input/kubernetesmetav2/service_meta.go
>  	Ingress               bool
连边acs.k8s.pod --> acs.ack.cluster

2024-09-20 11:17 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +	m.requestCount.Add(-m.requestCount.Load())
再确认下

2024-09-20 11:17 UTC, messixukejia commented on plugins/input/kubernetesmetav2/meta_collector.go
> +	log.Contents.Add(entityTypeFieldName, m.genEntityTypeKey("cluster"))
container等定义成常量

2024-09-30 08:03 UTC, messixukejia commented on plugins/input/kubernetesmetav2/meta_collector.go
> +		prefix = m.serviceK8sMeta.domain + ".k8s"
这里为什么没有结尾的.

2024-09-30 08:03 UTC, messixukejia commented on plugins/input/kubernetesmetav2/service_meta.go
> +	case ackCluster, oneCluster, asiCluster:
这段逻辑引入domainWithClusterMode有点多余，是不是在genEntityTypeKey根据domain直接处理就好了。变量尽量少，形式尽量统一

2024-10-03 08:35 UTC, Abingcbc commented on pkg/helper/self_metrics_constants.go
> +	MetricPluginCollectEntityTotal = "plugin_collect_entity_total"
都用一个指标名，但是entity和link使用不同的label

2024-10-10 07:21 UTC, linrunqi08 commented on pkg/helper/k8smeta/k8s_meta_manager.go
> +	m.metricRecord = pipeline.MetricsRecord{}
这里直接初始化？label是什么？

2024-10-10 09:46 UTC, Abingcbc commented on pkg/helper/self_metrics_constants.go
> +	MetricPluginCollectEntityTotal = "plugin_collect_entity_total"
这里讨论下来，通用的输入输出没有办法表达两种数据类型的含义，所以这里相当于属于meta的特殊指标。

2024-10-11 06:00 UTC, Abingcbc commented on pkg/helper/k8smeta/k8s_meta_manager.go
> +	m.metricRecord = pipeline.MetricsRecord{}
这个是runner级别的，在导出的时候，会填入cluster id，runner name和project。

2024-10-11 08:03 UTC, linrunqi08 requested changes

2024-10-11 08:03 UTC, linrunqi08 commented on pkg/helper/k8smeta/k8s_meta_manager.go
> +	m.metricRecord = pipeline.MetricsRecord{}
默认的project要带上

2024-10-12 03:28 UTC, linrunqi08 approved these changes

2024-10-12 03:32 UTC, messixukejia approved these changes

2024-10-12 03:32 UTC, merged