Feature/metadata
alibaba/ilogtail pull request #1768
Opened 2024-09-19 05:37 UTC by NameHaibinZhang

add k8s metadata

2024-09-24 11:03 UTC, linrunqi08 commented on core/metadata/k8sMetadata.cpp
> +        SendRequestToOperator(mServiceHost, output, containerInfoType::ContainerIdInfo);
这种情况下获取不到数据，外面是不是就上报原始数据了

2024-09-25 05:43 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +        SendRequestToOperator(mServiceHost, output, containerInfoType::ContainerIdInfo);
这个之前也讨论过，上报原始数据

2024-09-25 05:52 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +        SendRequestToOperator(mServiceHost, output, containerInfoType::ContainerIdInfo);
对host的请求失败 做了重试，其他的不重试直接走，不然会影响性能

2024-09-26 03:56 UTC, linrunqi08 approved these changes

2024-09-27 01:31 UTC, messixukejia requested changes

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/k8sMetadata.cpp
> +            return ip_info;
return nullptr;

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/k8sMetadata.cpp
> +    void K8sMetadata::FromInfoJson(const Json::Value& json, k8sContainerInfo& info) {
需要增加指标

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/ProcessorK8sMetadata.cpp
> +void ProcessorK8sMetadata::Process(PipelineEventGroup& logGroup) {
既然已经是input的一部分了，就不在适合用processor的模式了。

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/k8sMetadata.cpp
> +                        containerCache.insert(pair.first, std::make_shared<k8sContainerInfo>(pair.second));
并发的考虑

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/k8sMetadata.cpp
> +        for (const auto& pair : data->containers) {
containers没有老化机制？直增不删？

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/k8sMetadata.cpp
> +                FromContainerJson(root, data);
FromContainerJson 外部输入都是不可靠的

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/k8sMetadata.cpp
> +        SendRequestToOperator(mServiceHost, output, containerInfoType::ContainerIdInfo);
SendRequestToOperator 失败机制也不统一

2024-09-27 01:31 UTC, messixukejia commented on core/metadata/k8sMetadata.cpp
> +        if (res.mStatusCode != 200) {
success跟res.mStatusCode的顺序是什么

2024-10-17 05:41 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +                        containerCache.insert(pair.first, std::make_shared<k8sContainerInfo>(pair.second));
cache 里面已经添加锁

2024-10-17 05:44 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +                FromContainerJson(root, data);
增加了Member的判断

2024-10-18 08:10 UTC, messixukejia commented on core/metadata/LabelingK8sMetadata.cpp
> +bool LabelingK8sMetadata::ProcessEvent(PipelineEventPtr& e,  std::vector<std::string>& containerVec,  std::vector<std::string>& remoteIpVec) {
这里引入一个类，感觉有点多余，后面开发使用方代码的时候再看看怎么调整吧

2024-10-19 06:34 UTC, NameHaibinZhang commented on core/metadata/LabelingK8sMetadata.cpp
> +            e.SetTag("workloadName", containerInfo->workloadName);
嗯，这个主要是label 看看后面怎么定义

2024-10-19 06:34 UTC, NameHaibinZhang commented on core/metadata/LabelingK8sMetadata.cpp
> +bool LabelingK8sMetadata::ProcessEvent(PipelineEventPtr& e,  std::vector<std::string>& containerVec,  std::vector<std::string>& remoteIpVec) {
ok

2024-10-19 07:49 UTC, NameHaibinZhang commented on core/metadata/K8sMetadata.cpp
> +                FromContainerJson(root, data);
已经加上判断，异常后return

2024-10-19 07:49 UTC, NameHaibinZhang commented on core/metadata/LabelingK8sMetadata.cpp
> +bool LabelingK8sMetadata::AddLabelToMetric(MetricEvent& e, std::vector<std::string>& containerVec, std::vector<std::string>& remoteIpVec) {
已经修改成模版方式，减少重复代码

2024-10-19 07:50 UTC, NameHaibinZhang commented
https://github.com/alibaba/ilogtail/pull/1768#discussion_r1805788601

2024-10-19 08:20 UTC, NameHaibinZhang reviewed
comment 都已经修复

2024-10-21 02:10 UTC, NameHaibinZhang commented on core/metadata/ProcessorK8sMetadata.cpp
> +void ProcessorK8sMetadata::Process(PipelineEventGroup& logGroup) {
已经修改

2024-10-21 02:13 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +                    } else {
ok,setIp里面加上判断

2024-10-21 02:13 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +            delete reader;
已经增加

2024-10-21 02:13 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +                        containerCache.insert(pair.first, std::make_shared<k8sContainerInfo>(pair.second));
已经修改

2024-10-21 02:27 UTC, NameHaibinZhang commented on core/metadata/k8sMetadata.cpp
> +    void K8sMetadata::FromInfoJson(const Json::Value& json, k8sContainerInfo& info) {
这个等合并后一起看下需要加哪些指标，大家一起测试一下，然后看看哪些指标是需要的

2024-10-21 08:37 UTC, messixukejia commented on core/metadata/K8sMetadata.cpp
> +    int K8sMetadata::SendRequestToOperator(const std::string& urlHost, const std::string& output, containerInfoType infoType) {
1、返回值改成true、false
2、错误码传到调用方，失败了就不要往下走了
![image](https://github.com/user-attachments/assets/636b0e5e-e3f8-41bb-bd66-131472f54ddc)

2024-10-21 08:37 UTC, messixukejia commented on core/metadata/K8sMetadata.h
> +    const static std::string appIdKey = "armsAppId";
label的问题正好明天上午一起讨论下

2024-10-21 08:39 UTC, messixukejia approved these changes

2024-10-21 08:40 UTC, messixukejia commented on core/metadata/K8sMetadata.cpp
> +    int K8sMetadata::SendRequestToOperator(const std::string& urlHost, const std::string& output, containerInfoType infoType) {
我先通过了，这个问题修改后再合入代码

2024-10-21 08:47 UTC, NameHaibinZhang commented on core/metadata/K8sMetadata.h
> +    const static std::string appIdKey = "armsAppId";
ok

2024-10-21 09:14 UTC, merged