feat: support go to cpp PipelineEventGroup transfer
alibaba/ilogtail pull request #1771
Opened 2024-09-19 08:51 UTC by Assassin718

# 新增go插件、cpp插件PipelineEventGroup转换
- 新增描述PipelineEventGroup、LogEvent、MetricEvent、SpanEvent的protobuf
- go侧增加由go数据结构创建protobuf数据结构的接口
- cpp侧增加由protobuf数据结构转换成cpp数据结构的接口

2024-09-24 06:07 UTC, henryzhx8 requested changes

2024-09-24 06:07 UTC, henryzhx8 commented on core/protobuf/sls/pipeline_event.proto
> +    optional fixed32 Time_ns = 2;
这边统一成required uint64 Timestamp，3种event一样

2024-09-24 06:07 UTC, henryzhx8 commented on core/protobuf/sls/pipeline_event.proto
> +message LogEvent {
C++的Log需要增加Level字段，Go的Log需要增加RawSize字段

2024-09-24 06:07 UTC, henryzhx8 commented on core/go_pipeline/LogtailPlugin.cpp
> +        if (metaData.first == "source") {
source_id

2024-09-24 07:33 UTC, Assassin718 commented on core/protobuf/sls/pipeline_event.proto
> +    map<string, bytes> Tags = 2;
bytes比string反序列化时少一个检查UTF8格式的步骤，性能更好

2024-09-25 06:02 UTC, Assassin718 commented on core/go_pipeline/LogtailPlugin.cpp
> +        }
这里FileOffset和RawSize是由golang传来的还是在cpp这边直接计算的？

2024-09-25 06:06 UTC, Assassin718 commented on core/protobuf/sls/pipeline_event.proto
> +message LogEvent {
请问Level的类型应该是String还是StringView？Go的Log已经有一个GetSize()函数用于计算content的长度，还需要增加RawSize字段吗？

2024-09-27 08:45 UTC, henryzhx8 requested changes

2024-09-27 08:45 UTC, henryzhx8 commented on core/models/LogEvent.h
> +    void SetLevelNoCopy(StringView level);
这两个不要了

2024-09-27 08:45 UTC, henryzhx8 commented on core/go_pipeline/LogtailPlugin.cpp
> +    time_t tns = static_cast<time_t>(src.timestamp() - static_cast<uint64_t>(ts) * 1e9);
这里有没有更优雅的方法？可以看下std::chrono的实现，除法太暴力了

2024-09-27 08:45 UTC, henryzhx8 commented on core/go_pipeline/LogtailPlugin.cpp
> +    // value
这里用switch，有个方法是以_case结尾的

2024-09-27 08:45 UTC, henryzhx8 commented on core/go_pipeline/LogtailPlugin.cpp
> +    if (src.has_logs()) {
一样，用switch

2024-09-27 08:45 UTC, henryzhx8 commented on core/go_pipeline/LogtailPlugin.cpp
> +
这边还需要一组反过来的，就是event变成PB的，然后这些函数可以单独放到一个cpp和h文件里，名字先暂时叫ProtocolConversion吧，或者有更好的名字也可以

2024-09-27 08:45 UTC, henryzhx8 commented on pkg/helper/pipeline_event_helper.go
> +func CreateLogEvent(t time.Time, enableTimestampNano bool, fields map[string]string) (*protocol.LogEvent, error) {
这个和下面ByArray是用来做什么的？

2024-09-27 08:45 UTC, henryzhx8 commented on pkg/helper/pipeline_event_helper.go
> +	logEvent.FileOffset = uint64(rawSize)
这个值不要设

2024-09-27 08:45 UTC, henryzhx8 commented on pkg/helper/pipeline_event_helper.go
> +func CreateMetricEventByRawMetricV2(metric *models.Metric) (*protocol.MetricEvent, error) {
这里的函数名改一下，V2的都直接把V2去了，V1的改成LegacyRawLog

2024-09-27 08:45 UTC, henryzhx8 commented on pkg/helper/pipeline_event_helper.go
> +	}
这里不对，应该是根据MetricType字段来赋值

2024-09-27 08:48 UTC, Assassin718 commented on core/protobuf/models/metric_event.proto
> +    map<string, bytes> Tags = 4;
不是必须的

2024-09-27 08:51 UTC, Assassin718 commented on pkg/helper/pipeline_event_helper.go
> +func CreateLogEvent(t time.Time, enableTimestampNano bool, fields map[string]string) (*protocol.LogEvent, error) {
go v1 input是以map形式生成数据的，这里用于直接将map转为proto数据结构

2024-10-08 03:28 UTC, henryzhx8 requested changes

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.h
> +bool TransferPBToPipelineEventGroup(const logtail::models::PipelineEventGroup& src, logtail::PipelineEventGroup& dst, std::string& errMsg);
外层已经有了logtail namespace，里边可以不要logtail这一层了

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.h
> +
```suggestion
```

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.h
> +#pragma once
有个头注释给拷贝过来

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.cpp
> +        // timestamp
是不是写错了？这一行是要reserve吧？

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.cpp
> +            errMsg = "error transfer PB to PipelineEventGroup: logs events is empty";
failed to transfer PB to PipelineEventGroup: no log events，下同

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.cpp
> +    dst.SetTimestamp(ts.count(), tns.count() % 1000000000);
tns - ts * 1000000000是不是更好些？取模还是会涉及除法

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.cpp
> +            auto* metricDst = dst.mutable_metrics()->add_events();
这里auto就够了吧，下同

2024-10-08 03:28 UTC, henryzhx8 commented on core/protobuf/models/ProtocolConversion.cpp
> +    }
这里应该不用再绕chrono一层了，直接秒*1000000000+纳秒部分就可以了

2024-10-08 03:28 UTC, henryzhx8 commented on pkg/helper/pipeline_event_helper.go
> +func CreateLogEventByRawLogLegacyRawLog(log *protocol.Log) (*protocol.LogEvent, error) {
```suggestion
func CreateLogEventByLegacyRawLog(log *protocol.Log) (*protocol.LogEvent, error) {
```

2024-10-08 03:28 UTC, henryzhx8 commented on pkg/helper/pipeline_event_helper.go
> +func CreateLogEventByRawLog(log *models.Log) (*protocol.LogEvent, error) {
走PB的标准函数名字改成和C++的函数名一样吧，Tranferxxx

2024-10-08 03:28 UTC, henryzhx8 commented on pkg/helper/pipeline_event_helper.go
> +func CreatePipelineEventGroupLegacyRawLog(logEvents []*protocol.LogEvent, configTag map[string]string, logTags map[string]string, ctx map[string]interface{}) (*protocol.PipelineEventGroup, error) {
```suggestion
func CreatePipelineEventGroupByLegacyRawLog(logEvents []*protocol.LogEvent, configTag map[string]string, logTags map[string]string, ctx map[string]interface{}) (*protocol.PipelineEventGroup, error) {
```

2024-10-08 03:31 UTC, henryzhx8 commented on core/protobuf/models/metric_event.proto
> +    map<string, bytes> Tags = 4;
那内层和外层的编号分开来吧，不然扩展性会有问题

2024-10-11 01:31 UTC, henryzhx8 approved these changes

2024-10-12 03:44 UTC, shunjiazhu commented on core/protobuf/models/span_event.proto
> +    uint64 Timestamp = 1;
这里的时间戳单位是ns吗？

2024-10-12 04:14 UTC, Assassin718 commented on core/protobuf/models/span_event.proto
> +    uint64 Timestamp = 1;
是的

2024-10-15 03:22 UTC, liuhaoyang commented on pkg/protocol/proto/metric_event.proto
> +message UntypedSingleValue {
go的 pkg 下面的 proto 和 core 下面的 proto 定义是一样的吗

2024-10-15 03:32 UTC, Assassin718 commented on pkg/protocol/proto/metric_event.proto
> +message UntypedSingleValue {
是的

2024-10-15 11:14 UTC, merged