rename self monitor metrics
alibaba/ilogtail pull request #1779
Opened 2024-09-24 11:26 UTC by Takuka0311

2024-09-25 01:22 UTC, messixukejia commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_LABEL_CHILD_NODE_ID = "child_node_id";
后续如果支持分叉，是否具备延续性，防止引入不兼容变更

2024-09-25 01:22 UTC, messixukejia commented on core/pipeline/route/Router.cpp
>                                                            {METRIC_LABEL_KEY_COMPONENT_NAME, "router"}});
“router”也统一用常量吧

2024-09-25 01:22 UTC, messixukejia commented on core/monitor/MetricConstants.cpp
> +// processor processor_desensitize cunstom metrics
这个文件要不要拆下，一个是公共的，一个是特有的

或者按照大类别来拆分 --- 这个可能更合适些

2024-09-25 01:22 UTC, messixukejia commented on core/monitor/MetricConstants.cpp
> +    = "plugin_split_multiline_log_unmatched_lines_total";
unmatched_lines_total -- 这个是不是应该是公共的

不同插件的unmatched_lines_total有差别吗

2024-09-25 05:58 UTC, Takuka0311 commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_LABEL_CHILD_NODE_ID = "child_node_id";
目前的child_node_id还未开始使用，只是占位，不会有不兼容变更。

2024-09-25 06:31 UTC, Takuka0311 commented on core/pipeline/route/Router.cpp
>                                                            {METRIC_LABEL_KEY_COMPONENT_NAME, "router"}});
done

2024-09-25 06:31 UTC, Takuka0311 commented on core/monitor/MetricConstants.cpp
> +// processor processor_desensitize cunstom metrics
按大类拆成不同文件了

2024-09-25 06:55 UTC, henryzhx8 requested changes

2024-09-25 06:55 UTC, henryzhx8 commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_PLUGIN_COST_TIME_MS = "plugin_cost_time_ms";
处理类的，都叫total_process_time_ms；缓存类的，都叫total_delay_time_ms。
所以compressor和serializer那边也得把delay改成process

2024-09-25 06:55 UTC, henryzhx8 commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_PLUGIN_IN_BUFFER_TOTAL = "plugin_in_buffer_total";
这是啥

2024-09-25 06:55 UTC, henryzhx8 commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_PLUGIN_IN_EVENTS_SIZE_BYTES = "plugin_in_events_size_bytes";
没有event size

2024-09-25 06:55 UTC, henryzhx8 commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_PLUGIN_ERROR_TOTAL = "plugin_error_total";
这个没有意义

2024-09-25 06:55 UTC, henryzhx8 commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_PLUGIN_READ_FILE_SIZE_BYTES = "plugin_read_file_size_bytes";
加一级吧plugin_source_xxxx

2024-09-25 07:49 UTC, Takuka0311 commented on core/monitor/MetricConstants.cpp
> +const std::string METRIC_PLUGIN_ERROR_TOTAL = "plugin_error_total";
讨论结果：本次保留，后续统一整理

2024-09-25 08:21 UTC, henryzhx8 commented
解析类的公共指标：
plugin_out_key_not_found_events_total
plugin_out_failed_events_total
plugin_out_successful_events_total
plugin_discarded_events_total

2024-09-25 08:23 UTC, Takuka0311 commented on core/monitor/MetricConstants.cpp
> +    = "plugin_split_multiline_log_unmatched_lines_total";
> 先回答问题：从含义上看是公共的，目前只有一个插件用到了
> 
> 类型的问题还有不少，processor插件内部的指标，需要单独整理一下。
> 
> 和笃敏初步分析的结果，processor可以分为“解析类（单个event->单个event）”，“过滤类（单个event->0或1个event）”，“切分类（单个event->多个event）”，解析类内部又可以根据前后key-value的对应关系分成多类。 现在C++与Go的processor插件指标很不统一，表意也不清楚，需要后面单独开PR整理一下下面的内容：
> 
> * 错误统计相关指标（现在C++只有一个粗略的error_total，没有太大意义）
> * 每个processor独有的指标能否合并，合并后的指标项如何定义
> 
> 所以这边暂时先保留原样。

最新讨论结果：

* 解析类：使用下面四个通用指标
  * plugin_out_key_not_found_events_total
  * plugin_out_failed_events_total
  * plugin_out_successful_events_total
  * plugin_discarded_events_total
* 过滤类：旧指标可以删除
* 切分类：暂时不动

2024-09-27 02:10 UTC, henryzhx8 requested changes

2024-09-27 02:10 UTC, henryzhx8 commented on core/pipeline/plugin/instance/ProcessorInstance.cpp
> +    mOutEventGroupsTotal = mPlugin->GetMetricsRecordRef().CreateCounter(METRIC_PLUGIN_OUT_EVENT_GROUPS_TOTAL);
这个不需要统计，group的一些指标都是用来和delay time和process time做除法用的，原始指标很少需要直接给用户看

2024-09-27 02:10 UTC, henryzhx8 commented on core/pipeline/plugin/instance/FlusherInstance.cpp
> +    mInEventGroupsTotal = mPlugin->GetMetricsRecordRef().CreateCounter(METRIC_PLUGIN_IN_EVENT_GROUPS_TOTAL);
这个也不需要

2024-09-27 02:10 UTC, henryzhx8 commented on core/pipeline/plugin/instance/ProcessorInstance.cpp
> +        mInEventGroupsTotal->Add(1);
这个不用每次加一，直接在外面一把加上就行了

2024-09-27 02:10 UTC, henryzhx8 commented on core/pipeline/plugin/instance/ProcessorInstance.cpp
>      for (const auto& logGroup : logGroupList) {
顺带把变量名改了，别叫logGroup了，都叫eventGroup或者直接叫group

2024-09-27 02:30 UTC, messixukejia requested changes

2024-09-27 02:30 UTC, messixukejia commented on core/monitor/metric_constants/CommonMetrics.cpp
> +const std::string METRIC_SLS_LOGSTORE_NAME = "shennong_log_profile";
这个为什么还在common

2024-09-27 02:30 UTC, messixukejia commented on core/monitor/metric_constants/PluginMetrics.cpp
> +const std::string METRIC_LABEL_CHILD_NODE_ID = "child_node_id";
把这些多余的去掉。除非某一类内容很少，单独提出来看看

2024-09-27 02:30 UTC, messixukejia commented on core/monitor/metric_constants/PluginMetrics.cpp
> +const std::string METRIC_PLUGIN_SPLIT_MULTILINE_LOG_MATCHED_RECORDS_TOTAL
SPLIT_MULTILINE  是不是需要的？

是不是只要体现matched、unmached就可以了。而且可以共用。

尽量还是能复用。

2024-09-27 03:42 UTC, Takuka0311 commented on core/monitor/MetricConstants.h
> +extern const std::string METRIC_LABEL_PLUGIN_ID;
pluginID是对外的，甚至可以编辑（例如字节有自定义pluginID的场景），主要用于对外的报表展示

nodeID、childNodeID一定是我们内部生成的，表示插件的拓扑结构，主要用于后续绘制Pileline图等场景内部使用

2024-09-27 03:44 UTC, Takuka0311 commented on core/monitor/MetricConstants.h
> +extern const std::string METRIC_LABEL_PLUGIN_ID;
所以之前flusher那里，绑定用的是nodeID是正确的，nodeID就是用于内部使用场景

2024-09-27 03:53 UTC, Takuka0311 commented on core/monitor/metric_constants/PluginMetrics.cpp
> +const std::string METRIC_PLUGIN_SPLIT_MULTILINE_LOG_MATCHED_RECORDS_TOTAL
SPLIT_MULTILINE确实可以省略，缩短下长度。

matched、unmached这些目前暂时也没有其他地方在用，我先改掉

2024-09-27 07:05 UTC, messixukejia commented on core/monitor/metric_constants/ComponentMetrics.cpp
> +const string METRIC_LABEL_KEY_FLUSHER_NODE_ID = "flusher_node_id";
改成归属plugin_id，跟插件都保持一致。不需要体现flusher

只是插件是指向关系，这里是归属关系

2024-09-27 07:06 UTC, messixukejia commented on pkg/helper/self_metrics_constants.go
> +	MetricLabelKeyNodeID       = "node_id"
del

2024-09-27 07:36 UTC, henryzhx8 requested changes

2024-09-27 07:36 UTC, henryzhx8 commented on core/monitor/LogtailMetric.h
> +                        std::string defaultRegion,
引用

2024-09-27 07:36 UTC, henryzhx8 commented on core/monitor/metric_constants/ComponentMetrics.cpp
> +const string METRIC_COMPONENT_BATCHER_BUFFERED_EVENTS_TOTAL = "component_buffered_events_total";
gauge类型的指标要不要加total？是不是应该叫cnt

2024-09-27 07:36 UTC, henryzhx8 commented on core/monitor/metric_constants/ComponentMetrics.cpp
> +} // namespace logtail
空行

2024-09-27 09:59 UTC, messixukejia approved these changes

2024-09-27 10:04 UTC, henryzhx8 approved these changes

2024-09-29 05:58 UTC, merged