Support concurrency isolation between different sender queues
alibaba/ilogtail pull request #1786
Opened 2024-09-26 00:15 UTC by linrunqi08

2024-09-27 06:29 UTC, henryzhx8 requested changes

2024-09-27 06:29 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueueManager.cpp
> +        }
这个功能外移到调用放自己挨个调用吧，和OnFail对称

2024-10-10 09:01 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.h
> +    CounterPtr mGetItemsCnt;
mFetchedItemsCnt

2024-10-10 09:02 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.h
> +    CounterPtr mGetTimesCnt;
mFetchTimesCnt

2024-10-10 09:04 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.cpp
> +    // TODO:: taiye
这个还有吗？

2024-10-10 09:07 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.cpp
> +    int itemsCnt = 0;
直接用limit--吧

2024-10-10 09:10 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.h
> +    CounterPtr mLimitByReteLimiterCnt;
typo

2024-10-10 09:14 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.h
> +    CounterPtr mLimitByLogstoreLimiterCnt;
先笼统的mRejectedTimesCnt

2024-10-11 11:25 UTC, henryzhx8 requested changes

2024-10-11 11:25 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +    if (mCurrenctConcurrency <= 0) {
<=改成==吧，上同

2024-10-11 11:25 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +        mCurrenctConcurrency = max(0U, static_cast<uint32_t>(mCurrenctConcurrency * mConcurrencyDownRatio));
这里不用max了吧，都是无符号的，乘出来还能是负的？

2024-10-11 11:25 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +    if (mCurrenctConcurrency <= 0) {
这里应该加else，不然前面减成0，这里又会调用一次

2024-10-11 11:25 UTC, henryzhx8 commented on core/pipeline/queue/BoundedSenderQueueInterface.cpp
> +        mConcurrencyLimiters.emplace_back(std::make_pair(pair.second, mMetricsRecordRef.CreateCounter(ConcurrencyLimiter::GetLimiterMetricName(pair.first))));
不需要再调用std::make_pair了，之前的判空操作还是要的

2024-10-11 11:25 UTC, henryzhx8 commented on core/pipeline/queue/ExactlyOnceSenderQueue.cpp
> +        mConcurrencyLimiters.emplace_back(std::make_pair(FlusherSLS::GetRegionConcurrencyLimiter(f->mRegion), mMetricsRecordRef.CreateCounter(ConcurrencyLimiter::GetLimiterMetricName("region"))));
同上

2024-10-11 14:37 UTC, messixukejia commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +                {"region", GetRegionConcurrencyLimiter(mRegion)},
这里是region还是az？

2024-10-12 00:45 UTC, linrunqi08 commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +                if (mNetworkErrorCnt) {
这里自监控数据的发送会没有初始化的情况

2024-10-12 00:58 UTC, linrunqi08 commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +                if (mNetworkErrorCnt) {
这里自监控数据的发送会没有初始化的情况

2024-10-12 01:20 UTC, linrunqi08 commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +                {"region", GetRegionConcurrencyLimiter(mRegion)},
是region的概念，这里是从FlusherSLS的配置中解析的，这里是region

2024-10-12 01:40 UTC, linrunqi08 commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +    mPushHttpCnt = GetMetricsRecordRef().CreateCounter(METRIC_PLUGIN_PUSH_CURL_TOTAL);
修改成http

2024-10-12 01:40 UTC, linrunqi08 commented on core/monitor/metric_constants/ComponentMetrics.cpp
> +const string METRIC_COMPONENT_QUEUE_REJECTED_TOTAL_PREFIX = "component_queue_rejected_by_";
已修复

2024-10-12 01:47 UTC, messixukejia commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +                {"region", GetRegionConcurrencyLimiter(mRegion)},
之前文档里评论的没处理？region不够

2024-10-12 02:14 UTC, linrunqi08 commented on core/plugin/flusher/sls/FlusherSLS.cpp
> +                {"region", GetRegionConcurrencyLimiter(mRegion)},
这里跟dumin确认了一下，我们代码里的region就是az的概念，FlusherSLS的配置中的会被configserver侧重新覆盖掉

2024-10-12 02:18 UTC, henryzhx8 requested changes

2024-10-12 02:18 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.h
>      static std::string GetLimiterMetricName(std::string limiterLabel) {
const std::string& limiter

2024-10-12 02:18 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.cpp
> +    if (limit == -1) {
这里改成<0吧，鲁邦一点

2024-10-12 02:18 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.cpp
> +        }
149到151行应该挪到138行前面，而且判断条件改成limit == 0；
然后148行应该挪到154行后面；
137行应该挪到152行前面

2024-10-12 02:18 UTC, henryzhx8 commented on core/monitor/metric_constants/ComponentMetrics.cpp
> +const string METRIC_COMPONENT_QUEUE_LIMIT_BY_REGION_LIMITER_TOTAL = "component_queue_limit_by_region_limiter_total";
rejected

2024-10-12 02:46 UTC, henryzhx8 requested changes

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.h
>      void OnFail(time_t curTime);
这里的curTime没用到，先删了吧，本来是个预留设计

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.h
> +    std::atomic<uint32_t> mInSendingCnt = 0;
atomic_uint32_t

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.h
> +#include <sstream>
atomic,mutex,cstdint,string,chrono

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +#include "common/TimeUtil.h"
这俩不需要了吧

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +    }
这三行可以删了，第一次进来currentConcurrency不可能是0

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/limiter/ConcurrencyLimiter.cpp
> +    if (mCurrenctConcurrency <= 0) {
==0

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/queue/SenderQueue.h
> +    CounterPtr mFetchItemsCnt;
改成Fetched吧，指标名也改一下

2024-10-12 02:46 UTC, henryzhx8 commented on core/pipeline/queue/BoundedSenderQueueInterface.h
> +    CounterPtr mLimitByRateLimiterCnt;
Rejected

2024-10-12 04:11 UTC, henryzhx8 commented on core/monitor/metric_constants/ComponentMetrics.cpp
> +const string METRIC_COMPONENT_QUEUE_REJECTED_BY_REGION_LIMITER_TOTAL = "component_queue_rejected_by_region_limiter_total";
component_fetch_rejected_by_xxx_times_total

2024-10-12 04:11 UTC, henryzhx8 commented on core/monitor/metric_constants/ComponentMetrics.cpp
> +const string METRIC_COMPONENT_QUEUE_FETCHED_ITEMS_TIMES_TOTAL = "component_queue_fetched_items_times_total";
fetch_times

2024-10-12 05:09 UTC, henryzhx8 approved these changes

2024-10-12 07:10 UTC, messixukejia approved these changes

2024-10-12 09:23 UTC, merged