feat:iLogtail renamed to LoongCollector and directory layout changes
alibaba/ilogtail pull request #1791
Opened 2024-09-29 06:30 UTC by quzard

文档 ：https://github.com/alibaba/ilogtail/discussions/1687

2024-10-08 03:01 UTC, henryzhx8 requested changes

2024-10-08 03:01 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +                      ("failed to init pipeline", "Go pipeline is invalid, see loongcollector_plugin.LOG for detail")(
日志名字不是改了吗？go_plugin.LOG

2024-10-08 05:46 UTC, quzard commented
讨论结果：根目录有关的地方都封装成函数，并设置宏定义，能通过宏定义同时兼容iLogtail和loongcollector

2024-10-08 07:01 UTC, messixukejia requested changes

2024-10-08 07:01 UTC, messixukejia commented on core/logtail.cpp
> +    PROCESSDIRFLAG(loongcollector_lib_dir, "ALIYUN_LOONGCOLLECTOR_LIB_DIR", lib);
不再通过配置文件控制，作为安装、启动参数的一部分

2024-10-09 03:52 UTC, quzard commented on docs/cn/config-server/quick-start.md
> +打开 iLogtail 目录下的 loongcollector_config.json 文件，配置 ConfigServer 相关参数 `ilogtail_configserver_address` 和 `ilogtail_tags`。
文档这个pr先不改了，改的地方很多，单独一个pr改文档吧

2024-10-09 03:52 UTC, quzard commented on core/config/provider/ConfigProvider.cpp
> +    mPipelineSourceDir /= "pipelineconfig";
嗯

2024-10-11 07:07 UTC, yyuuttaaoo commented on pluginmanager/checkpoint_manager.go
>  		dbPath = filepath.Join(logtailConfigDir, *CheckPointFile)
CheckPointFile，这个值改成go_plugin_checkpoint

2024-10-11 07:07 UTC, yyuuttaaoo commented on plugins/input/jmxfetch/jmxfetch.go
> +	m.jvmHome = path.Join(config.LoongcollectorGlobalConfig.LoongcollectorConfDir, "jvm")
exec_dir/jvm

2024-10-11 07:07 UTC, yyuuttaaoo commented on plugins/input/command/input_command.go
> +	in.storageDir = path.Join(config.LoongcollectorGlobalConfig.LoongcollectorConfDir, "/scripts")
补充到文档

2024-10-11 07:07 UTC, yyuuttaaoo commented on plugins/input/telegraf/input_telegraf.go
> +	s.tm = GetTelegrafManager(path.Join(global_config.LoongcollectorGlobalConfig.LoongcollectorConfDir, "telegraf"))
exec_dir/telegraf

2024-10-12 01:26 UTC, yyuuttaaoo commented on core/logger/Logger.cpp
>      LoadConfig(execDir + "apsara_log_conf.json");
config位置不对

2024-10-12 01:29 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +string GetAgentConfigName() {
这个不要吧

2024-10-12 01:41 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +DEFINE_FLAG_STRING(app_info_file, "", "app_info.json");
内容中logtail_version这个key没改

2024-10-12 01:47 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +        dirPath = mLoongcollectorConfDir + dirPath + PATH_SEPARATOR;
这个有了instanceconfig后续也要废弃

2024-10-12 02:08 UTC, yyuuttaaoo commented on core/app_config/AppConfig.cpp
> +    PROCESSDIRFLAG(loongcollector_conf_dir, "ALIYUN_LOONGCOLLECTOR_CONF_DIR");
env名称不用单独搞个，就和flag一样就行了

2024-10-12 02:33 UTC, yyuuttaaoo approved these changes

2024-10-12 02:48 UTC, yyuuttaaoo approved these changes

2024-10-12 03:23 UTC, messixukejia approved these changes

2024-10-12 06:03 UTC, henryzhx8 requested changes

2024-10-12 06:03 UTC, henryzhx8 commented on core/go_pipeline/LogtailPlugin.cpp
>      if (mPluginBasePtr == NULL) {
改成GoPluginBase和GoPluginAdapter

2024-10-12 08:38 UTC, henryzhx8 approved these changes

2024-10-12 08:41 UTC, merged