feat: prometheus self monitor metrics
alibaba/ilogtail pull request #1796
Opened 2024-10-08 09:46 UTC by catdogpandas

指标 | 描述 | labels | 类型
-- | -- | -- | --
prom_register_state | 注册状态 | pod_name,operator_host,operator_port | IntGauge
prom_register_retry_total | 注册重试 | status,pod_name,... | Counter
prom_job_num | 输入插件（Job）数量 | pod_name,... | IntGauge
prom_subsricbe_targets | 订阅的 Targets 数量 | job,pod_name,... | IntGauge
prom_subsricbe_total | 订阅次数总量 | status,job,pod_name,... | Counter
prom_subsricbe_time_ms | 订阅耗时（分布） | status,job,pod_name,... | IntGauge
prom_scrape_total | 采集次数总量 | status,target,job,pod_name,... | Counter
prom_scrape_bytes_total | 采集总字节数 | status,target,job,pod_name,... | Counter
prom_scrape_time_ms | 采集耗时（分布） | status,target,job,pod_name,... | IntGauge
prom_scrape_delay_total | 采集延迟总量  | status,target,job,pod_name,... | Counter

2024-10-11 02:19 UTC, Takuka0311 requested changes

2024-10-11 02:19 UTC, Takuka0311 commented on core/prometheus/PrometheusInputRunner.cpp
> +    dynamicLabels.emplace_back(METRIC_LABEL_KEY_PROJECT, []() -> std::string { return FlusherSLS::GetAllProjects(); });
这里有点小问题，projects应该是，Prometheus相关的所有pipeline发送的目标project，而不是所有的project

2024-10-11 02:19 UTC, Takuka0311 commented on core/prometheus/PrometheusInputRunner.cpp
> +    mIntGauges[METRIC_RUNNER_PROM_REGISTER_STATE] = mMetricsRecordRef.CreateIntGauge(METRIC_RUNNER_PROM_REGISTER_STATE);
这里的指标是可枚举的，是不是不需要再包一层map、直接创建对应的GaugePtr

2024-10-11 02:19 UTC, Takuka0311 commented on core/prometheus/PrometheusInputRunner.h
> +    std::unordered_map<std::string, IntGaugePtr> mIntGauges;
这里是不是不需要map，指标没有几个

2024-10-11 03:51 UTC, catdogpandas commented on core/prometheus/PrometheusInputRunner.h
> +    std::unordered_map<std::string, IntGaugePtr> mIntGauges;
是的，哈哈，我改掉

2024-10-11 07:24 UTC, catdogpandas commented on core/monitor/metric_constants/PluginMetrics.cpp
> +const std::string METRIC_PLUGIN_PROM_SUBSCRIBE_TIME_MS = "plugin_prom_subscribe_time_ms";
plugin_prom_subscribe_time_ms 表示网络延迟，再额外加一条 METRIC_PLUGIN_TOTAL_DELAY_MS 指标，plugin_prom_scrape_bytes_total 与 plugin_prom_scrape_total 已经替换

2024-10-12 01:42 UTC, Takuka0311 approved these changes

2024-10-12 01:43 UTC, Takuka0311 commented
我没什么问题了。可以补充一个实际使用场景、指标的样例在评论一起看下

2024-10-12 06:23 UTC, messixukejia requested changes

2024-10-12 06:23 UTC, messixukejia commented on core/prometheus/PromSelfMonitor.cpp
> +void PromSelfMonitor::InitMetricManager(const std::unordered_map<std::string, MetricType>& metricKeys,
PromSelfMonitor --> 类名增加线程不安全描述

2024-10-12 06:23 UTC, messixukejia commented on core/prometheus/PromSelfMonitor.cpp
> +void PromSelfMonitor::CounterAdd(const std::string& metricName, uint64_t statusCode, uint64_t val) {
CounterAdd -> AddCounter
IntGaugeSet -> SetIntGauge

2024-10-12 06:23 UTC, messixukejia commented on core/monitor/metric_constants/RunnerMetrics.cpp
> +const std::string METRIC_RUNNER_PROM_REGISTER_STATE = "runner_prom_register_state";
改成公共的：runner_client_register_state、runner_register_retry_total、runner_job_num

2024-10-12 07:26 UTC, messixukejia approved these changes

2024-10-12 08:25 UTC, merged