Implemented self-monitoring logic for eBPF-related plugins
alibaba/ilogtail pull request #1799
Opened 2024-10-10 08:46 UTC by KayzzzZ

2024-10-11 03:52 UTC, Takuka0311 requested changes

2024-10-11 03:52 UTC, Takuka0311 commented on core/ebpf/SelfMonitor.cpp
> +    switch (type)
加一个label METRIC_LABEL_KEY_PROJECT，含义是当前这个metricRecord统计的对象的目标project，如果有多个用空格分隔

2024-10-11 03:52 UTC, Takuka0311 commented on core/ebpf/SelfMonitor.cpp
> +    switch (type)
所有的metricRecord都加上这个label吧

2024-10-11 05:44 UTC, KayzzzZ commented on core/monitor/metric_constants/RunnerMetrics.cpp
> +const string METRIC_LABEL_KEY_RUNNER_RECV_EVENT_STAGE = "recv_event_stage";
ok 我挪一下

2024-10-11 07:29 UTC, messixukejia requested changes

2024-10-11 07:29 UTC, messixukejia commented on core/monitor/metric_constants/RunnerMetrics.cpp
> +const string METRIC_LABEL_VALUE_RUNNER_NAME_EBPF_SERVER = "ebpf_server";
没有使用

2024-10-11 07:29 UTC, messixukejia commented on core/ebpf/SelfMonitor.cpp
> +    std::lock_guard<std::mutex> lk(mStatsMtx);
现在指标体系都是无锁的，这里的使用方式有点打破了规律

也不需要自己单独再保存一个状态的变量

2024-10-11 07:46 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +    switch (type)
ok value就是插件的project

2024-10-12 08:06 UTC, KayzzzZ commented on core/monitor/metric_constants/RunnerMetrics.cpp
> +const string METRIC_LABEL_KEY_RUNNER_RECV_EVENT_STAGE = "recv_event_stage";
已经挪走了

2024-10-12 08:06 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +    switch (type)
加上了 METRIC_LABEL_KEY_PROJECT 和 METRIC_LABEL_KEY_RUNNER_NAME

2024-10-12 08:06 UTC, KayzzzZ commented on core/monitor/metric_constants/RunnerMetrics.cpp
> +const string METRIC_LABEL_VALUE_RUNNER_NAME_EBPF_SERVER = "ebpf_server";
加上了 METRIC_LABEL_KEY_RUNNER_NAME 这个 label

2024-10-12 08:11 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +    std::lock_guard<std::mutex> lk(mStatsMtx);
我把计算逻辑放到 sysak 里面，再重新修改下

2024-10-12 10:11 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +    std::lock_guard<std::mutex> lk(mStatsMtx);
已修改

2024-10-14 11:39 UTC, Takuka0311 approved these changes

2024-10-15 07:55 UTC, messixukejia requested changes

2024-10-15 07:55 UTC, messixukejia commented on core/plugin/input/InputNetworkSecurity.cpp
> +    return ebpf::eBPFServer::GetInstance()->EnablePlugin(mContext->GetConfigName(), mIndex, nami::PluginType::NETWORK_SECURITY, mContext, &mSecurityOptions, GetMetricsRecordRef());
file、Prometheus都是只传的label，保持统一吧

2024-10-15 07:55 UTC, messixukejia commented on core/ebpf/SelfMonitor.cpp
> +std::string BaseBPFMonitor::PluginTypeToString(const nami::PluginType pluginType) {
无效代码有点多，不用的就删掉吧。包括依赖的变量

2024-10-15 07:55 UTC, messixukejia commented on core/ebpf/SelfMonitor.cpp
> +        mSelfMonitors[int(type)] = std::make_unique<NetworkObserverSelfMonitor>(name, pluginMetricManager, ref);
确认下并发性，是否需要加锁

2024-10-15 07:55 UTC, messixukejia commented on core/ebpf/SelfMonitor.cpp
> +    labelsPtr->push_back({METRIC_LABEL_KEY_LOGSTORE, logstore});
runner 跟logstore没有什么关系，不能在这里体现

2024-10-15 07:55 UTC, messixukejia commented on core/ebpf/SelfMonitor.cpp
> +        keys.insert({METRIC_RUNNER_EBPF_NETWORK_OBSERVER_PROTOCOL_PARSE_RECORDS_TOTAL, MetricType::METRIC_TYPE_COUNTER});
这里把runner跟plugin的概念混淆在一起了

2024-10-17 13:54 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +    labelsPtr->push_back({METRIC_LABEL_KEY_LOGSTORE, logstore});
ok 我写错label了 我改成 METRIC_LABEL_KEY_PROJECT 了

2024-10-17 13:55 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +        keys.insert({METRIC_RUNNER_EBPF_NETWORK_OBSERVER_PROTOCOL_PARSE_RECORDS_TOTAL, MetricType::METRIC_TYPE_COUNTER});
把这些拆到了 plugin 指标中了， server 目前只记录了 start、suspend、stop 的次数

2024-10-17 13:56 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +        mSelfMonitors[int(type)] = std::make_unique<NetworkObserverSelfMonitor>(name, pluginMetricManager, ref);
这个地方其实目前的架构中是不涉及并发的。考虑到后续的迭代，我也加了个锁来保证安全。

2024-10-17 13:56 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +std::string BaseBPFMonitor::PluginTypeToString(const nami::PluginType pluginType) {
嗯 删掉了。这个是最开始的实现中有用到，后来改了几次之后就没用到这个方法了

2024-10-17 13:57 UTC, KayzzzZ commented on core/plugin/input/InputNetworkSecurity.cpp
> +    return ebpf::eBPFServer::GetInstance()->EnablePlugin(mContext->GetConfigName(), mIndex, nami::PluginType::NETWORK_SECURITY, mContext, &mSecurityOptions, GetMetricsRecordRef());
改成传递 manager 了

2024-10-18 06:18 UTC, Takuka0311 requested changes

2024-10-18 06:18 UTC, Takuka0311 commented on core/ebpf/SelfMonitor.cpp
> +    InitInnerMetric();
命名风格可以跟logtail内部贴近一点：
InitInnerMetric -> InitMetricInner
UpdateInnerMetric -> UpdateMetricInner

2024-10-18 06:18 UTC, Takuka0311 commented on core/ebpf/eBPFServer.cpp
> +    mStartPluginTotal = mRef.CreateCounter(METRIC_RUNNER_EBPF_START_PLUGIN_TOTAL);
mStartPluginTotal、mStopPluginTotal、mSuspendPluginTotal这三个指标，具体是什么含义呢？

是想表示当前统计周期内（1min）启动、停止、暂停插件的次数，还是整个runner级别所有插件的状态呢？

2024-10-18 06:19 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +    InitInnerMetric();
ok

2024-10-18 06:34 UTC, KayzzzZ commented on core/ebpf/SelfMonitor.cpp
> +    InitInnerMetric();
已修改

2024-10-18 06:35 UTC, KayzzzZ commented on core/ebpf/eBPFServer.cpp
> +    mStartPluginTotal = mRef.CreateCounter(METRIC_RUNNER_EBPF_START_PLUGIN_TOTAL);
目前只是记录 启、停、暂停的次数，用来做一个基础的问题定位

2024-10-21 02:25 UTC, KayzzzZ commented
![image](https://github.com/user-attachments/assets/2b74902e-ac29-499b-96de-d229d4563c6c)

2024-10-21 06:52 UTC, Takuka0311 approved these changes

2024-10-28 03:40 UTC, KayzzzZ commented
![image](https://github.com/user-attachments/assets/aa45d96c-b2a3-4347-af4a-c512344596fa)

2024-10-28 03:44 UTC, KayzzzZ commented
![image](https://github.com/user-attachments/assets/020b3262-8a24-4bd1-b9d3-ebe83620d524)

2024-10-28 03:56 UTC, Takuka0311 commented
> ![image](https://private-user-images.githubusercontent.com/33246768/380570469-72aa5752-2a6b-4c6c-8a78-53cf7f5f6493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODc5MDQsIm5iZiI6MTczMDA4NzYwNCwicGF0aCI6Ii8zMzI0Njc2OC8zODA1NzA0NjktNzJhYTU3NTItMmE2Yi00YzZjLThhNzgtNTNjZjdmNWY2NDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAzNTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYjdkYzE5ZGM4YTM2NWM5MjRkYTI4Mzg1Mjc0NGE3MmUwOTUyOGE4NDUyMjQ2NzJjODdiMTIzOTJlOGEyYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8a12Jz8MKSqdq1TtdJiO1LU9qrP9cwNZVsB9o6ifxqM)

runner这里有一个label，metric_category需要补一下

2024-10-28 07:58 UTC, messixukejia commented on core/ebpf/eBPFServer.cpp
> +            res += "";
少了空格

2024-10-28 07:58 UTC, messixukejia commented on core/monitor/metric_constants/RunnerMetrics.cpp
> +const string METRIC_RUNNER_EBPF_START_PLUGIN_TOTAL = "runner_start_plugin_total";
这个指标项看上去更应该是公共的

2024-10-28 08:02 UTC, messixukejia approved these changes

2024-10-28 08:05 UTC, messixukejia commented
CI失败处理下

2024-10-28 08:47 UTC, merged