Optimize metrics reporting
alibaba/ilogtail pull request #1807
Opened 2024-10-15 08:39 UTC by Takuka0311

2024-10-16 01:22 UTC, messixukejia requested changes

2024-10-16 01:22 UTC, messixukejia commented on core/file_server/event_handler/LogInput.cpp
> +    LoongCollectorMonitor::GetInstance()->mAgentOpenFdTotal->Set(openFdTotal);
直接暴露单例变量不是个很好的方式

2024-10-16 01:22 UTC, messixukejia commented on pluginmanager/self_telemetry_statistics.go
> -// Licensed under the Apache License, Version 2.0 (the "License");
兼容模式下这里还需要不？

2024-10-16 01:22 UTC, messixukejia commented on core/runner/FlusherRunner.cpp
> +    mInItemRawDataSizeBytes = mMetricsRecordRef.CreateCounter(METRIC_RUNNER_FLUSHER_IN_RAW_SIZE_BYTES);
跟raw对应的是什么？这个处理流不加raw，这里加raw反而有点不一致。

是不是应该是默认都是raw，比如其他场景例如压缩后的，加其他描述

2024-10-16 01:24 UTC, Takuka0311 commented on pluginmanager/self_telemetry_statistics.go
> -// Licensed under the Apache License, Version 2.0 (the "License");
兼容模式下这里也不需要了

2024-10-16 01:28 UTC, Takuka0311 commented on core/runner/FlusherRunner.cpp
> +    mInItemRawDataSizeBytes = mMetricsRecordRef.CreateCounter(METRIC_RUNNER_FLUSHER_IN_RAW_SIZE_BYTES);
走到flusher runner的数据，已经是压缩后的了，这里的raw size就是event记录的。

2024-10-16 01:32 UTC, Takuka0311 commented on core/file_server/event_handler/LogInput.cpp
> +    LoongCollectorMonitor::GetInstance()->mAgentOpenFdTotal->Set(openFdTotal);
这里的考虑是：进程级指标全局唯一，且数量不多可枚举，统一定义好方便维护，不然会在各处存在一些重复指标定义，还需要用map来维护关联关系

2024-10-17 12:11 UTC, messixukejia requested changes

2024-10-17 12:11 UTC, messixukejia commented on core/file_server/event_handler/LogInput.cpp
> +    LoongCollectorMonitor::GetInstance()->mAgentOpenFdTotal->Set(openFdTotal);
用函数封装一下吧，不要直接暴露单例变量

2024-10-17 12:11 UTC, messixukejia commented on core/runner/FlusherRunner.cpp
> +    mInItemRawDataSizeBytes = mMetricsRecordRef.CreateCounter(METRIC_RUNNER_FLUSHER_IN_RAW_SIZE_BYTES);
那前面input、Processor中为什么不也加raw呢？ 不加应该统一，都是原始的。压缩的特殊加标识。

2024-10-18 07:03 UTC, Takuka0311 commented on core/runner/FlusherRunner.cpp
> +    mInItemRawDataSizeBytes = mMetricsRecordRef.CreateCounter(METRIC_RUNNER_FLUSHER_IN_RAW_SIZE_BYTES);
"in_size_bytes"表示的是进入当前runner/component/plugin的数据量

在input、Processor中，数据还未压缩，"in_size_bytes"就是原始大小，然后到了compressor这里之后，数据被压缩了，进到后续的runner/component/plugin的"in_size_bytes"就是压缩后的数据量了，所以需要多加一个raw的指标，标识原始的数据量

这里其实是，"in_size_bytes"究竟应该表示进入当前runner/component/plugin的数据的真实大小，还是表示这些数据的原始数据量的问题

2024-10-22 08:57 UTC, messixukejia approved these changes

2024-10-22 08:57 UTC, messixukejia commented on core/runner/ProcessorRunner.cpp
> +         {"thread_no", ToString(threadNo)}});
为什么不用常量定义？

2024-10-23 01:39 UTC, merged