fix: return empty group when filter all data
alibaba/ilogtail pull request #1824
Opened 2024-10-22 03:00 UTC by Abingcbc

## 问题
对于包含过滤操作的Processor，当所有数据都被过滤时，应当返回 event 为空的 group。
但是 SPL 比较特殊，采用一种类似回调的方式填充 group。如果没有返回数据，那么不会向返回列表中填充 group。
并且此时，属于解析正常，不会报error。
因此，导致后续 ProcessorRunner 中出现数组越界 core。
https://github.com/alibaba/ilogtail/blob/a13bc6f096da042d780be7c91dc798490e0087ff/core/runner/ProcessorRunner.cpp#L194-L196

## 影响范围
- main分支
- LoongCollector 0.1 版本

## 修复方案
在解析成功的情况中判断 logGroupList 是否为空，如果为空，那么清空输入的 group 的 event，回填进 logGroupList。

2024-10-22 03:10 UTC, messixukejia commented on core/plugin/processor/ProcessorSPL.cpp
> +        // all events have been filtered
从[0]的地方加保护，因为后面难免还会有其他场景可能出现此类情况

2024-10-22 07:37 UTC, henryzhx8 requested changes
要么把profile相关的全删了，要么就在process后面直接判定eventgrouplist是空的

2024-10-22 09:02 UTC, linrunqi08 approved these changes

2024-10-24 05:43 UTC, henryzhx8 approved these changes

2024-10-24 05:45 UTC, merged