fix deadlock on LogInput and Processor Runner thread
alibaba/ilogtail pull request #1825
Opened 2024-10-22 03:28 UTC by henryzhx8

- 问题：在压测的时候小概率出现LogInput和Processor线程同时死锁
- 原因：两个线程获取两把锁的顺序相反
  - 处理线程：先获取处理队列的锁，然后pop数据。如果队列变成低水位了，会调用BlockedEventManager::Feedback函数，该函数会对BlockEventMap加锁；
  - input线程：在定时调用GetTimeoutEvent函数时，首先对BlockEventMap加锁，然后通过ProcessQueueManager::IsValidToPush函数判断event对应的队列是否可用，这个时候会对处理队列加锁。
- 影响范围：仅main分支，2.0旧版实现在启用优先级队列后也有概率触发
- 解决方案：Feedback函数里仅保存信息，在LogInput线程里去消费这些feedback。

2024-10-23 01:23 UTC, messixukejia requested changes

2024-10-23 01:23 UTC, messixukejia commented on core/unittest/reader/ForceReadUnittest.cpp
> +        BlockedEventManager::GetInstance()->mEventMap.clear();
并没有专门的ut承载这个场景，看下是否可以增加

2024-10-23 01:23 UTC, messixukejia commented on core/file_server/event/BlockEventManager.cpp
> +        lock_guard<mutex> lock(mEventMapMux);
这两个{} 会导致两个动作没有原子性。 获取 keys 在第二个{}访问的时候，会不会Eventmap已经变化了。

2024-10-24 01:59 UTC, yyuuttaaoo commented on core/file_server/event/BlockEventManager.h
> +    std::mutex mFeedbackQueueMux;
// 保护mFeedbackQueue，可能有Input线程和多个Process线程同时访问

2024-10-24 02:00 UTC, yyuuttaaoo commented on core/file_server/event/BlockEventManager.h
> +    std::mutex mEventMapMux; // currently not needed
要不要锁都加一下注释理由
// 不需要锁，所有访问来自Input单线程

2024-10-24 03:26 UTC, henryzhx8 commented on core/file_server/event/BlockEventManager.cpp
> +        lock_guard<mutex> lock(mEventMapMux);
这里不需要原子性，只需要获取最新的eventMap里的内容就可以了

2024-10-24 10:00 UTC, messixukejia approved these changes

2024-10-24 12:27 UTC, yyuuttaaoo approved these changes

2024-10-24 12:27 UTC, merged