Feature/add event
alibaba/ilogtail pull request #183
Opened 2022-06-29 01:58 UTC by linrunqi08

2022-07-13 11:46 UTC, messixukejia commented on helper/envconfig/docker_env_config.go
> +var K8sEventInitFlag = flag.Bool("ALICLOUD_LOG_K8S_EVENT_CONFIG", false, "alibaba log k8s event config flag, set true if you want to use it")
change to ALICLOUD_LOG_K8S_FLAG

2022-07-13 11:46 UTC, messixukejia commented on helper/envconfig/docker_env_config.go
> +var K8sEventInitFlag = flag.Bool("ALICLOUD_LOG_K8S_EVENT_CONFIG", false, "alibaba log k8s event config flag, set true if you want to use it")
all K8s env

2022-07-13 11:46 UTC, messixukejia commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +func (o *operationWrapper) createProductLogstore(config *AliyunLogConfigSpec, project, logstore, product, lang string) error {
1、什么时候创建k8s role?
2、存量场景兼容

2022-07-20 04:17 UTC, EvanLjp requested changes

2022-07-20 04:17 UTC, EvanLjp commented on go.sum
> +k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd h1:sOHNzJIkytDF6qadMNKhhDRpc6ODik8lVC6nOur7B2c=
这是增加了新的版本吗?

2022-07-20 04:17 UTC, EvanLjp commented on helper/k8s_event/event_define.go
> +package k8s_event
这个命名好像CI 过不了

2022-07-20 04:17 UTC, EvanLjp commented on helper/k8s_event/event_recorder.go
> +	//"github.com/golang/glog"
remove it

2022-07-20 04:17 UTC, EvanLjp commented on helper/k8s_event/event_recorder.go
> +	//glog.V(4).Info("Creating event broadcaster")
could bind the log to logtail logger?
If hard, cloud print to stdout, the stdout would be cached

2022-07-20 04:17 UTC, EvanLjp commented on helper/k8s_event/event_recorder.go
> +	testPod := &v1.Pod{
could find real pod name by docker center and process id
https://blog.csdn.net/Haulyn5/article/details/123293404

2022-07-20 04:17 UTC, EvanLjp commented on helper/envconfig/custom_error.go
> +func (e *CustomError) CustomError() string {
reformat error again?

2022-07-20 05:23 UTC, linrunqi08 commented on helper/envconfig/docker_env_config.go
> +var K8sEventInitFlag = flag.Bool("ALICLOUD_LOG_K8S_EVENT_CONFIG", false, "alibaba log k8s event config flag, set true if you want to use it")
done

2022-07-20 05:23 UTC, linrunqi08 commented on helper/envconfig/docker_env_config.go
> +var K8sEventInitFlag = flag.Bool("ALICLOUD_LOG_K8S_EVENT_CONFIG", false, "alibaba log k8s event config flag, set true if you want to use it")
done

2022-07-20 05:24 UTC, linrunqi08 commented on helper/envconfig/aliyunlog_operation_wrapper.go
> +func (o *operationWrapper) createProductLogstore(config *AliyunLogConfigSpec, project, logstore, product, lang string) error {
全新安装部署的时候，才会创建role。存量场景升级版本的时候，不会有ALICLOUD_LOG_K8S_FLAG存在，因此不会触发事件的逻辑

2022-07-20 09:40 UTC, messixukejia commented on helper/k8s_event/event_recorder.go
> +	testPod := &v1.Pod{
pod name 没有实际意义，用ip之类的吧

2022-07-21 08:35 UTC, shabicheng commented on helper/envconfig/custom_error.go
> +	compileRegex := regexp.MustCompile(`[\s\S]*ErrorCode: (.*)[\s\S]*RequestId: (.*)[\s\S]*Message: (.*)`)
move to global var

2022-07-21 08:38 UTC, shabicheng commented on helper/k8s_event/event_recorder.go
> +		panic(nil)
不能panic，不是核心路径，最多是不可用而已

2022-08-17 01:45 UTC, linrunqi08 commented on helper/k8s_event/event_define.go
> +package k8s_event
fixed

2022-08-17 01:45 UTC, linrunqi08 commented on helper/k8s_event/event_recorder.go
> +	//"github.com/golang/glog"
fixed

2022-08-17 01:45 UTC, linrunqi08 commented on helper/k8s_event/event_recorder.go
> +	testPod := &v1.Pod{
fixed

2022-08-17 01:45 UTC, linrunqi08 commented on helper/k8s_event/event_recorder.go
> +		panic(nil)
fixed

2022-08-17 01:45 UTC, linrunqi08 commented on helper/envconfig/custom_error.go
> +	compileRegex := regexp.MustCompile(`[\s\S]*ErrorCode: (.*)[\s\S]*RequestId: (.*)[\s\S]*Message: (.*)`)
fixed

2022-08-17 01:55 UTC, linrunqi08 commented on helper/envconfig/custom_error.go
> +func (e *CustomError) CustomError() string {
是把不同的error统一处理了一下，方便放在事件里对外暴露

2022-08-17 02:13 UTC, linrunqi08 commented on go.sum
> +k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd h1:sOHNzJIkytDF6qadMNKhhDRpc6ODik8lVC6nOur7B2c=
是的

2022-08-17 02:13 UTC, linrunqi08 commented on helper/k8s_event/event_recorder.go
> +	//glog.V(4).Info("Creating event broadcaster")
这个好像不太好绑定

2022-08-25 03:35 UTC, messixukejia commented on go.sum
>  k8s.io/klog/v2 v2.5.0/go.mod h1:hy9LJ/NvuK+iVyP4Ehqva4HxZG/oXyIS3n3Jmire4Ec=
changelog

2022-08-25 03:51 UTC, linrunqi08 commented on go.sum
>  k8s.io/klog/v2 v2.5.0/go.mod h1:hy9LJ/NvuK+iVyP4Ehqva4HxZG/oXyIS3n3Jmire4Ec=
done

2022-08-25 04:11 UTC, EvanLjp approved these changes

2022-08-25 04:51 UTC, merged