Feat/prom raw event
alibaba/ilogtail pull request #1870
Opened 2024-11-11 08:33 UTC by catdogpandas

2024-11-18 09:54 UTC, henryzhx8 requested changes

2024-11-18 09:54 UTC, henryzhx8 commented on core/prometheus/PrometheusInputRunner.h
> +    std::shared_ptr<EventPool> mEventPool;
这个没必要用指针了，需要用到的地方直接用裸指针，代表引用关系

2024-11-18 09:54 UTC, henryzhx8 commented on core/runner/ProcessorRunner.cpp
> +        PrometheusInputRunner::GetInstance()->CheckGC();
不要放在在这个线程，放到主线程里

2024-11-18 11:07 UTC, catdogpandas commented on core/runner/ProcessorRunner.cpp
> +        PrometheusInputRunner::GetInstance()->CheckGC();
忘记改了。。

2024-11-19 05:38 UTC, henryzhx8 approved these changes

2024-11-19 07:53 UTC, messixukejia approved these changes

2024-11-20 03:51 UTC, merged