feat: support service and more fields in K8s meta
alibaba/ilogtail pull request #1895
Opened 2024-11-18 10:04 UTC by Abingcbc

1. K8s meta HTTP server 返回结果调整
  - `/metadata/ip`：支持传入service IP查询，返回其中一个对应的Pod信息。新增 podIP、startTime、contianerID 字段。
  - `/metadata/containerid`：修改containerID格式，去除前缀。新增 podIP、startTime 字段。
  - `/metadata/host`：新增 podIP、containerID、startTime 字段。
2. 修复遗漏读锁可能导致race问题。

2024-11-25 01:46 UTC, linrunqi08 commented
修复配置停止时导致的race问题 ： 代码在哪里，说明一下

2024-11-25 01:47 UTC, linrunqi08 commented
"支持传入service IP查询，返回其中一个对应的Pod信息" 什么场景需要？以及返回一个pod信息是否合理？

2024-11-25 01:51 UTC, linrunqi08 requested changes

2024-11-25 01:51 UTC, linrunqi08 commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +	mux.HandleFunc("/metadata/ip", m.handler(m.handlePodMetaByPodIP))
如果这里支持service ip，那函数名就不能叫handleXXByPodIP

2024-11-25 01:51 UTC, linrunqi08 commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +		objs := m.metaManager.cacheMap[POD].Get([]string{key})
这种map访问不用加锁吗？

2024-11-25 06:16 UTC, Abingcbc commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +		objs := m.metaManager.cacheMap[POD].Get([]string{key})
manager初始化时创建，后续都是只读的

2024-11-25 06:26 UTC, Abingcbc commented on pkg/helper/k8smeta/k8s_meta_deferred_deletion_meta_store.go
> +		m.lock.RLock()
之前在遍历sendFunc时，锁的粒度不够。只能保证取到元素时是原子的。
但是取到之后，到实际调用执行之间，可能会出现配置重新加载，unregister，无法保证元素仍是有效的。

2024-11-25 12:31 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +func (m *metadataHandler) findPodByServiceIPPort(ipPort []string) *PodMetadata {
参数不要再用数组了，直接ip、port传，避免都要判断下标越界情况

2024-11-25 12:33 UTC, messixukejia commented on pkg/helper/k8smeta/k8s_meta_http_server.go
> +	podMetadata := &PodMetadata{
ut好像没有

2024-11-27 02:41 UTC, messixukejia approved these changes

2024-11-27 02:45 UTC, linrunqi08 approved these changes

2024-11-27 02:52 UTC, merged