feat: support follow_redirections, tls
alibaba/ilogtail pull request #1896
Opened 2024-11-18 12:08 UTC by catdogpandas

2024-11-19 08:40 UTC, messixukejia requested changes

2024-11-19 08:40 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +        } else {
不配置是直接拒绝加载还是按照没有TLS处理？

2024-11-19 08:40 UTC, messixukejia commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +    if (scrapeConfig.isMember(prometheus::FOLLOW_REDIRECTS) && scrapeConfig[prometheus::FOLLOW_REDIRECTS].isBool()) {
默认值是什么？scrapeconfig才是入口，这里最应该默认false

![image](https://github.com/user-attachments/assets/1d702148-a77d-43a5-b39d-f7bb5d4995cd)

2024-11-19 08:40 UTC, messixukejia commented on core/common/http/Curl.cpp
> +            curl_easy_setopt(curl, CURLOPT_CAINFO, tls->mCaFile.c_str());
tls配置了值，但是不合法。会是什么影响？这里需要有容错能力

2024-11-19 08:40 UTC, messixukejia commented on core/prometheus/async/PromHttpRequest.cpp
> +                                 CurlTLS* tls)
tls 的调用点在哪里？CreateCurlHandler 都没有传这个参数

2024-11-19 09:01 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +        } else {
1. 格式错误会 return false 会拒绝加载
2. 不配置 tls_config 时 mEnableTLS 会是 false，会按照没有 TLS 处理

2024-11-19 09:04 UTC, catdogpandas commented on core/prometheus/schedulers/ScrapeConfig.cpp
> +    if (scrapeConfig.isMember(prometheus::FOLLOW_REDIRECTS) && scrapeConfig[prometheus::FOLLOW_REDIRECTS].isBool()) {
默认值是 true，是根据 Prometheus 的默认设置值来的。https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file
<img width="540" alt="截屏2024-11-19 17 03 19" src="https://github.com/user-attachments/assets/5a1ccfa5-c4ec-4664-ae3c-616a88faaf22">

2024-11-19 09:17 UTC, catdogpandas commented on core/prometheus/async/PromHttpRequest.cpp
> +                                 CurlTLS* tls)
漏了，补上了

2024-11-19 10:12 UTC, catdogpandas commented on core/common/http/Curl.cpp
> +            curl_easy_setopt(curl, CURLOPT_CAINFO, tls->mCaFile.c_str());
增加了一个保证不会出现 core dump 的不合法验证 tls 的 ut

2024-11-20 09:16 UTC, henryzhx8 commented on core/common/http/HttpResponse.h
> +
这个放到HttpRequest文件

2024-11-20 09:16 UTC, henryzhx8 commented on core/common/http/HttpRequest.h
> +    CurlTLS* mTls = nullptr;
这边能保证指针是有效的吗？

2024-11-21 01:51 UTC, catdogpandas commented on core/common/http/HttpResponse.h
> +
这个放到 HttpRequest 会和 HttpResponse 出现相互引用

2024-11-21 02:02 UTC, catdogpandas commented on core/common/http/HttpRequest.h
> +    CurlTLS* mTls = nullptr;
由 Prom 传入的 mTls 生命周期可以保证有效，在 Job 取消时，会首先通过锁把每个采集通过 PromFuture 关闭，然后再是 Job shared_ptr 析构。

2024-11-25 01:43 UTC, linrunqi08 commented on core/common/http/HttpRequest.h
> +    std::string mKeyFile;
k8s场景这几个文件从哪里来？

2024-11-25 02:41 UTC, catdogpandas commented on core/common/http/HttpRequest.h
> +    CurlTLS* mTls = nullptr;
已经修改为通过 std::optional 传数据

2024-11-25 02:45 UTC, catdogpandas commented on core/common/http/HttpRequest.h
> +    std::string mKeyFile;
一般配置是：ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt，这个是 POD 里面自带的
如果用户有额外需求，就自己配置

2024-11-25 03:33 UTC, messixukejia approved these changes

2024-11-25 06:19 UTC, linrunqi08 commented on core/common/http/HttpRequest.h
> +    std::string mKeyFile;
我这里说一下，在ACK组件形态下，肯定不允许客户自己配置的。这块我之前提过固定挂一个configmap到某个路径下，这样客户自己可以去configmap中修改，而不动部署模版

2024-11-25 06:31 UTC, xdatcloud commented on core/common/http/HttpRequest.h
> +    std::string mKeyFile;
> 我这里说一下，在ACK组件形态下，肯定不允许客户自己配置的。这块我之前提过固定挂一个configmap到某个路径下，这样客户自己可以去configmap中修改，而不动部署模版

这里不单是 ACK 组件形态，后面托管探针、集团生产环境（另一套组件）需要用到自定义挂载 CA File 才能采集

2024-11-26 10:41 UTC, merged