feat: support span serializer
alibaba/ilogtail pull request #1903
Opened 2024-11-20 08:48 UTC by KayzzzZ

2024-11-20 09:52 UTC, henryzhx8 requested changes

2024-11-20 09:52 UTC, henryzhx8 commented on core/models/SpanEvent.h
> +    constexpr StringView GetKindString() const {
直接返回const std::string&，case里面可以都用static string str = ‘xxx’，然后整个函数放到类外面，h里定义，cpp里实现

2024-11-20 09:52 UTC, henryzhx8 commented on core/models/SpanEvent.h
> +    constexpr StringView GetStatusString() const {
同Kind

2024-11-20 09:52 UTC, henryzhx8 commented on core/models/SpanEvent.h
> +    std::string SerializeEventsToString() const;
这两个函数放到SLSSerializer里，作为普通函数就行了，入参是SpanEvent

2024-11-20 09:52 UTC, henryzhx8 commented on core/pipeline/serializer/SLSSerializer.cpp
> +                serializer.AddLogTime(spanEvent.GetTimestamp());
提到StartToAddLog后面

2024-11-20 09:52 UTC, henryzhx8 commented on core/unittest/serializer/SLSSerializerUnittest.cpp
> +        LOG_INFO(sLogger, ("begin", "span test"));
这种删掉

2024-11-20 09:52 UTC, henryzhx8 commented on core/unittest/serializer/SLSSerializerUnittest.cpp
> +        APSARA_TEST_EQUAL(1, logGroup.logs_size());
这个验证项全一点，参照metric event那边

2024-11-20 09:52 UTC, henryzhx8 commented on core/pipeline/serializer/SLSSerializer.cpp
> +            for (size_t i = 0; i < group.mEvents.size(); ++i) {
按照现在的写法，确认一下group里面的tag是原封不动地上传的

2024-11-21 01:40 UTC, KayzzzZ commented on core/pipeline/serializer/SLSSerializer.cpp
> +                serializer.AddLogTime(spanEvent.GetTimestamp());
ok

2024-11-21 01:43 UTC, KayzzzZ commented on core/pipeline/serializer/SLSSerializer.cpp
> +            for (size_t i = 0; i < group.mEvents.size(); ++i) {
目前是这样子的。
之前说加个resource字段，后来跟服务端的同学聊了下，现在的方式就直接把resource 的字段打平到 group tags 了

2024-11-21 01:48 UTC, KayzzzZ commented on core/models/SpanEvent.h
> +    std::string SerializeEventsToString() const;
好的

2024-11-21 01:59 UTC, KayzzzZ commented on core/models/SpanEvent.h
> +    constexpr StringView GetKindString() const {
ok

2024-11-21 01:59 UTC, KayzzzZ commented on core/unittest/serializer/SLSSerializerUnittest.cpp
> +        LOG_INFO(sLogger, ("begin", "span test"));
好的

2024-11-21 07:25 UTC, henryzhx8 approved these changes

2024-11-21 08:05 UTC, messixukejia commented on core/constants/TagConstants.cpp
> +    const std::string DEFAULT_TRACE_TAG_TRACE_ID = "traceId";
该文件是tag的，即attributes、resource相关的

2024-11-21 09:11 UTC, KayzzzZ commented on core/constants/TagConstants.cpp
> +    const std::string DEFAULT_TRACE_TAG_TRACE_ID = "traceId";
拆到 SpanConstants 文件中了
trace 相关的 tag 我在 K8sMetadata 相关的 PR 提上来

2024-11-21 09:13 UTC, messixukejia approved these changes

2024-11-21 09:42 UTC, merged