Feat: MetricEvent support UntypedMultiValues
alibaba/ilogtail pull request #1908
Opened 2024-11-22 08:32 UTC by Takuka0311

2024-11-22 09:13 UTC, henryzhx8 requested changes

2024-11-22 09:13 UTC, henryzhx8 commented on core/models/MetricValue.h
> +    std::shared_ptr<SourceBuffer> mSourceBuffer;
这是啥？

2024-11-22 09:13 UTC, henryzhx8 commented on core/models/MetricValue.h
> +struct UntypedMultiValues {
改名叫UntypedMultiFloatValues

2024-11-22 09:13 UTC, henryzhx8 commented on core/models/MetricEvent.h
> +    void DelMultiKeyValue(StringView key);
这些都应该放到MetricValue里面，MetricEvent不要感知这些，MetricEvent提供一个MutableValue接口，通过这个接口去改

2024-11-22 09:16 UTC, Takuka0311 commented on core/models/MetricValue.h
> +    std::shared_ptr<SourceBuffer> mSourceBuffer;
测试的时候调用FromJson方法，需要在map里填StringView类型的Key，所以需要一个临时的SourceBuffer来存一下

2024-11-24 11:27 UTC, messixukejia requested changes

2024-11-24 11:27 UTC, messixukejia commented on core/models/MetricValue.h
> +    UntypedMultiFloatValues(std::map<StringView, double> values, PipelineEvent* ptr): mValues(values), mMetricEventPtr(ptr) {}
类型是double，类名叫float？

2024-11-24 11:27 UTC, messixukejia commented on core/models/MetricValue.cpp
>  Json::Value MetricValueToJson(const MetricValue& value) {
MetricValueToJson、JsonToMetricValue都需要ut覆盖

2024-11-24 11:27 UTC, messixukejia commented on core/models/MetricValue.cpp
> +MetricValue JsonToMetricValue(const string& type, const Json::Value& detail, PipelineEvent* mMetricEventPtr) {
新增的第三个参数明显不合理

2024-11-25 01:55 UTC, Takuka0311 commented on core/models/MetricValue.cpp
> +MetricValue JsonToMetricValue(const string& type, const Json::Value& detail, PipelineEvent* mMetricEventPtr) {
![image](https://github.com/user-attachments/assets/36d06042-d90e-4ed6-86ee-80f88917ca6e)

MetricValue归属于MetricEvent，MetricEvent归属于PipelineEventGroup。

MetricEvent所有的StringView的内存都是在PipelineEventGroup的SourceBuffer中存储的，MetricValue里的StringView的内存是通过它归属的MetricEvent、从PipelineEventGroup的SourceBuffer获取的。JsonToMetricValue函数是在创造一个MetricValue，它需要有归属的MetricEvent才能给内部的StringView分配到内存，这个参数没有问题

2024-11-25 02:36 UTC, yyuuttaaoo commented on core/models/MetricValue.cpp
> +MetricValue JsonToMetricValue(const string& type, const Json::Value& detail, PipelineEvent* mMetricEventPtr) {
可以是MetricEvent的一个成员方法吗

2024-11-25 02:44 UTC, yyuuttaaoo commented on core/models/MetricValue.h
> +    double GetMultiKeyValue(StringView key) const;
这些方法名里的MultiKeyValue是不是都省略掉反而更好

2024-11-25 02:50 UTC, Takuka0311 commented on core/models/MetricValue.cpp
> +MetricValue JsonToMetricValue(const string& type, const Json::Value& detail, PipelineEvent* mMetricEventPtr) {
为了减少歧义，把JsonToMetricValue放在了MetricEvent内

2024-11-25 02:53 UTC, Takuka0311 commented on core/models/MetricValue.h
> +    UntypedMultiFloatValues(std::map<StringView, double> values, PipelineEvent* ptr): mValues(values), mMetricEventPtr(ptr) {}
原本叫UntypedMultiValues，是根据上面意见修改的。个人倾向于使用UntypedMultiValues：

* 跟另一个类型UntypedSingleValue对应
* UntypedSingleValue内部的Value也是double，没必要在MultiValues这里再强调一次

2024-11-25 02:57 UTC, Takuka0311 commented on core/models/MetricValue.h
> +    double GetMultiKeyValue(StringView key) const;
已省略

2024-11-25 02:58 UTC, henryzhx8 requested changes

2024-11-25 02:58 UTC, henryzhx8 commented on core/models/MetricValue.h
> +    mutable std::map<StringView, double> mValues;
这个为啥要mutable？

2024-11-25 02:58 UTC, henryzhx8 commented on core/models/MetricValue.cpp
> +    return 0;
这里返回0合理吗？

2024-11-25 02:58 UTC, henryzhx8 commented on core/models/MetricValue.h
> +    PipelineEvent* mMetricEventPtr;
这里如果是指向event的指针，那显然copy的时候这个指针得换，但你这里又没有认为定义复制构造和移动构造函数，肯定会出问题

2024-11-25 09:23 UTC, henryzhx8 commented on core/models/MetricEvent.h
> +    constexpr std::add_pointer_t<T> GetMutableValue() noexcept {
名字去掉Get

2024-11-25 09:23 UTC, henryzhx8 commented on core/models/MetricEvent.cpp
> +    } else if (value["type"].asString() == "untyped_multi_values") {
字符串和类名一致

2024-11-25 09:23 UTC, henryzhx8 commented on core/models/MetricValue.h
> +struct UntypedMultiValues {
这个咋又改回去了

2024-11-25 09:23 UTC, henryzhx8 commented on core/models/MetricValue.h
> +    bool Get(StringView key, double& val) const;
xxxValue

2024-11-25 11:04 UTC, henryzhx8 approved these changes

2024-11-25 11:55 UTC, messixukejia approved these changes

2024-11-25 12:10 UTC, merged