Add self monitor metric inner pipeline
alibaba/ilogtail pull request #1913
Opened 2024-11-25 19:09 UTC by Takuka0311

- [x] 移除旧指标发送流程（MetricExportor）
- [x] 自监控Input：input_self_monitor_metric
  - [x] 插件本体
  - [x] 修改Go指标上报格式
  - [x] 新增SelfMonitorServer
  - [x] 支持SelfMonitorServer输出MultiValues MetricEvent
- [x] 本地文件Flusher：flusher_local_file
  - [x] 插件本体
  - [x] Serializer
- [x] 内置Pipeline

2024-11-26 07:49 UTC, messixukejia requested changes

2024-11-26 07:49 UTC, messixukejia commented on core/monitor/SelfMonitorServer.cpp
> +        unique_lock<mutex> lock(mThreadRunningMux);
之前提的锁使用的问题，记得给我解答下

2024-11-26 07:49 UTC, messixukejia commented on core/pipeline/serializer/JsonSerializer.cpp
> +        case PipelineEvent::Type::SPAN:
log、span等暂时不需要实现这些无关的类型

2024-11-26 07:49 UTC, messixukejia commented on core/pipeline/serializer/JsonSerializer.cpp
> +const string JSON_KEY_CONTENTS = "contents";
不要在引入content，直接一级平铺字段

2024-11-26 07:49 UTC, messixukejia commented on core/pipeline/serializer/JsonSerializer.cpp
> +                eventJson[JSON_KEY_TAGS] = Json::Value();
处理好为空的场景

2024-11-26 07:49 UTC, messixukejia commented on core/pipeline/serializer/JsonSerializer.cpp
> +                eventJson[JSON_KEY_TAGS] = Json::Value();
跟大打印到后端一个格式就可以了

2024-11-26 07:49 UTC, messixukejia commented on core/pipeline/serializer/SLSSerializer.cpp
> +                } else if (e.Is<UntypedMultiDoubleValues>()) {
把样例回复下

2024-11-26 07:49 UTC, messixukejia commented on core/pipeline/serializer/SLSSerializer.cpp
> -std::string SerializeSpanLinksToString(const SpanEvent& event) {
不要改无关的代码。改动都需要说明合理性

2024-11-26 07:49 UTC, messixukejia commented on core/pipeline/serializer/Serializer.cpp
> +std::string SerializeSpanTagsToString(const SpanEvent& event) {
SLS专有的就不要移到这里来，保持原样

2024-11-26 07:49 UTC, messixukejia commented on core/plugin/input/InputSelfMonitorMetric.cpp
> +        rule.mEnable = GetEnabled(ruleJson[ruleKey]);
不配置的要赋默认值

2024-11-26 07:52 UTC, Takuka0311 commented on core/plugin/input/InputSelfMonitorMetric.cpp
> +        rule.mEnable = GetEnabled(ruleJson[ruleKey]);
这里有默认值

2024-11-26 07:52 UTC, Takuka0311 commented on core/pipeline/serializer/SLSSerializer.cpp
> +                } else if (e.Is<UntypedMultiDoubleValues>()) {
https://sls.console.aliyun.com/lognext/project/xuanyang-test/logsearch/loongcollector-self-monitor?encode%3Dbase64%26queryString%3D%26filterInfo%3DeyJmamNvZGUiOiIoKSIsImZxIjoiIn0%3D%26queryTimeType%3D99%26startTime%3D1732602900%26endTime%3D1732603800

2024-11-26 07:56 UTC, Takuka0311 commented on core/monitor/SelfMonitorServer.cpp
> +        unique_lock<mutex> lock(mThreadRunningMux);
mStopCV.wait_for(lock, std::chrono::seconds(1), [this]() { return !mIsThreadRunning; })

这里wait_for的过程中锁是释放的，可以认为是：

* 释放锁等待一秒
* 检查一次mIsThreadRunning的状态，如果为false就退出
* 如果mIsThreadRunning为true，锁被继续加上，走后面的发送流程

2024-11-26 08:01 UTC, messixukejia requested changes

2024-11-26 08:05 UTC, Takuka0311 commented on core/pipeline/serializer/JsonSerializer.cpp
> +        case PipelineEvent::Type::SPAN:
log还是先实现了，毕竟是最常用的、也不复杂（几行就行）

2024-11-26 08:05 UTC, Takuka0311 commented on core/pipeline/serializer/JsonSerializer.cpp
> +        case PipelineEvent::Type::SPAN:
span去掉了

2024-11-26 08:07 UTC, Takuka0311 commented on core/plugin/flusher/local_file/FlusherLocalFile.cpp
> +        mFileWriter->info(serializedData);
1. 多行。
2. batcher是标准流程的一环，在自监控指标场景用处不大，但是从通用性角度来说可以把很多tag一致的group聚合到一起，减少不必要开销，还是有必要的。

2024-11-26 12:09 UTC, messixukejia requested changes

2024-11-26 12:17 UTC, yyuuttaaoo commented on core/monitor/SelfMonitorServer.cpp
> +    LOG_INFO(sLogger, ("send self-monitor metrics", "start"));
del

2024-11-26 12:19 UTC, yyuuttaaoo commented on core/monitor/SelfMonitorServer.cpp
> +    if (pipeline != nullptr) {
.get()

2024-11-27 01:56 UTC, messixukejia approved these changes

2024-11-27 02:02 UTC, henryzhx8 commented on core/plugin/input/InputSelfMonitorMetric.cpp
> +const std::string InputSelfMonitorMetric::sName = "input_self_monitor_metric";
vector叫input_internal_metrics，可以参考

2024-11-27 02:25 UTC, yyuuttaaoo approved these changes

2024-11-27 02:26 UTC, merged