to #249, Contribution process specification for CN
alibaba/ilogtail pull request #250
Opened 2022-07-30 10:53 UTC by messixukejia

2022-07-30 13:34 UTC, yyuuttaaoo requested changes

2022-07-30 13:34 UTC, yyuuttaaoo commented on docs/cn/contributing/CONTRIBUTING.md
> +iLogtail 自从开源以来，受到了很多社区同学的关注。社区的每一个 Issue、每一个 pull request (PR)，都是在为 iLogtial 的发展添砖加瓦。衷心地希望越来越多的社区同学能参与到 iLogtail 项目中来，跟我们一起把 iLogtall 做好。
最后2个iLogtail拼错了

2022-07-30 13:34 UTC, yyuuttaaoo commented on docs/cn/contributing/CONTRIBUTING.md
> +# 如何贡献
用markdownlint处理一下，这种标题都应该空一行的

2022-07-30 13:34 UTC, yyuuttaaoo commented on docs/cn/contributing/CONTRIBUTING.md
> +* Announcements：iLogtail官方公告。
列表上方也要加个回车

2022-07-30 13:34 UTC, yyuuttaaoo commented on docs/cn/contributing/developer.md
> +## 社区角色
后面加回车

2022-07-30 13:34 UTC, yyuuttaaoo commented on docs/cn/contributing/developer.md
> +* shabicheng([@shabicheng](https://github.com/shabicheng))
这个名字是不是改一下？是元乙吧？

2022-07-30 14:41 UTC, EvanLjp requested changes

2022-07-30 14:41 UTC, EvanLjp commented on .github/ISSUE_TEMPLATE/ask-a-question.md
> +- 查看 [中文文档](https://ilogtail.gitbook.io/ilogtail-docs/about/readme)
为什么这个地方双语，其他又都英文，格式不同意

2022-07-30 14:41 UTC, EvanLjp commented on .github/ISSUE_TEMPLATE/bug-report.md
> +- logtail_plugin.LOG:
改一下日志的文件吧，都统一ilogtail开头

2022-07-30 14:41 UTC, EvanLjp commented on .github/ISSUE_TEMPLATE/enhancement.md
> +**Concisely describe the proposed feature**
考虑下格式，渲染后比较乱

2022-07-30 14:56 UTC, messixukejia commented on .github/ISSUE_TEMPLATE/bug-report.md
> +- logtail_plugin.LOG:
这个涉及企业版的兼容性，后面单独考虑吧

2022-07-31 15:25 UTC, yyuuttaaoo approved these changes

2022-08-01 06:04 UTC, EvanLjp approved these changes

2022-08-01 10:15 UTC, merged