Provide a  plugin doc template
alibaba/ilogtail pull request #272
Opened 2022-08-02 07:47 UTC by Takuka0311

2022-08-02 08:54 UTC, messixukejia commented on docs/cn/data-pipeline/templete.md
> +```
file_name -> plugin-doc-templete

2022-08-02 08:54 UTC, messixukejia commented on docs/cn/data-pipeline/templete.md
> +在完成文档后，以插件英文名命名文件，“_”改为“-”，
path: docs/cn/developer-guide/plugin-development

2022-08-02 08:55 UTC, messixukejia commented on docs/cn/data-pipeline/templete.md
> +```
``` 不需要吧

2022-08-02 09:29 UTC, Takuka0311 commented on docs/cn/data-pipeline/templete.md
> +```
done

2022-08-02 09:29 UTC, Takuka0311 commented on docs/cn/data-pipeline/templete.md
> +在完成文档后，以插件英文名命名文件，“_”改为“-”，
done

2022-08-03 01:08 UTC, messixukejia requested changes

2022-08-03 01:08 UTC, messixukejia commented on docs/cn/developer-guide/plugin-doc-templete.md
> +可用于参考的[正式文档链接](https://github.com/alibaba/ilogtail/blob/main/docs/cn/data-pipeline/input/service-journal.md)。
[service-journal插件文档]

2022-08-03 01:08 UTC, messixukejia commented on docs/cn/developer-guide/plugin-doc-templete.md
> +### 文件命名
正文跟汇总页分下层次

### 正文
#### 标题
。。。
#### 简介

### 汇总页
文档完成后，需要修改`docs/cn/data-pipline`中的`overview.md`和`docs/cn`中的`SUMMARY.md`。。。。。

2022-08-03 01:08 UTC, messixukejia commented on docs/cn/developer-guide/plugin-doc-templete.md
> +这是一份ilogtail插件的中文文档的模版及格式说明。
ilogtail 英文前后加下空格

2022-08-03 01:08 UTC, messixukejia commented on docs/cn/developer-guide/plugin-doc-templete.md
> +## 文档模版
在https://github.com/alibaba/ilogtail/issues/279 留言，增加下文档贡献指南

2022-08-03 01:10 UTC, messixukejia requested changes

2022-08-03 01:10 UTC, messixukejia commented on docs/cn/developer-guide/plugin-doc-templete.md
> +2. 根据具体插件差异，可以有多组样例，每组样例也并不一定要有输入。
md format工具的链接，改好PR前发起formt

https://ilogtail.gitbook.io/ilogtail-docs/v/pre-release/developer-guide/codestyle#ge-shi-hua-markdown

2022-08-03 01:25 UTC, Takuka0311 commented on docs/cn/developer-guide/plugin-doc-templete.md
> +### 文件命名
done

2022-08-03 01:25 UTC, Takuka0311 commented on docs/cn/developer-guide/plugin-doc-templete.md
> +可用于参考的[正式文档链接](https://github.com/alibaba/ilogtail/blob/main/docs/cn/data-pipeline/input/service-journal.md)。
done

2022-08-03 01:29 UTC, Takuka0311 commented on docs/cn/developer-guide/plugin-doc-templete.md
> +这是一份ilogtail插件的中文文档的模版及格式说明。
done

2022-08-03 01:30 UTC, Takuka0311 commented on docs/cn/developer-guide/plugin-doc-templete.md
> +2. 根据具体插件差异，可以有多组样例，每组样例也并不一定要有输入。
done

2022-08-03 01:36 UTC, Takuka0311 commented on docs/cn/developer-guide/plugin-doc-templete.md
> +## 文档模版
链接pr，还是等合入之后连接文档？

2022-08-03 01:45 UTC, messixukejia commented on docs/cn/developer-guide/plugin-doc-templete.md
> +可用于参考的`service_journal`插件文档 [service-journal.md](https://github.com/alibaba/ilogtail/blob/main/docs/cn/data-pipeline/input/service-journal.md) 。
这个是正文参考吧，放到正文部分吧

2022-08-03 01:46 UTC, Takuka0311 commented on docs/cn/developer-guide/plugin-doc-templete.md
> +可用于参考的`service_journal`插件文档 [service-journal.md](https://github.com/alibaba/ilogtail/blob/main/docs/cn/data-pipeline/input/service-journal.md) 。
done

2022-08-03 05:54 UTC, messixukejia commented on docs/cn/developer-guide/plugin-doc-templete.md
> +## 文档模版
PR吧

2022-08-03 05:55 UTC, messixukejia approved these changes

2022-08-03 05:56 UTC, merged