add support for hot reloading
alibaba/ilogtail pull request #282
Opened 2022-08-03 13:25 UTC by henryzhx8

2022-08-03 23:30 UTC, messixukejia requested changes

2022-08-03 23:30 UTC, messixukejia commented on core/config_manager/ConfigManager.cpp
> +            GetRemoteConfigUpdate(configSuccessFlag);
configSuccessFlag 没有使用？

2022-08-03 23:30 UTC, messixukejia commented on core/config_manager/ConfigManager.cpp
> +            if (!IsUpdate() && LoadMountPaths()) {
容器模式要测试下

2022-08-03 23:30 UTC, messixukejia commented on core/config_manager/ConfigManager.cpp
> +
所有判断一起汇总下，最后一次性判断UpdateConfig？

2022-08-04 04:39 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +            GetRemoteConfigUpdate(configSuccessFlag);
已删去

2022-08-04 04:40 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +DEFINE_FLAG_INT32(local_config_update_interval, "second", 5);
这个功能点的文档加在哪个文件里？

2022-08-04 05:50 UTC, messixukejia commented on core/config_manager/ConfigManager.cpp
> +DEFINE_FLAG_INT32(local_config_update_interval, "second", 5);
https://ilogtail.gitbook.io/ilogtail-docs/configuration/system-config

标注下，社区版专有，企业版不适用吧

2022-08-05 02:40 UTC, messixukejia commented on core/config_manager/ConfigManager.cpp
> +//
k8s configmap change

2022-08-07 12:19 UTC, messixukejia commented on docs/cn/configuration/system-config.md
> +| `config_update_interval`    | Int | 本地配置热加载的更新间隔，单位为秒。<br>**注意：热加载功能仅限社区版，商业版暂不支持配置文件热加载。**
注意：热加载功能仅限社区版，商业版暂不支持配置文件热加载。 -- 去掉。

config_update_interval 参数仅对企业版生效

2022-08-07 12:20 UTC, messixukejia commented on docs/cn/configuration/system-config.md
> +    "config_update_interval": 10
config_update_interval -- 不需要推荐配置

2022-08-07 12:20 UTC, messixukejia commented on docs/cn/configuration/collection-config.md
> +**注意：热加载功能仅限社区版，商业版暂不支持配置文件热加载。**
同样

2022-08-09 11:28 UTC, messixukejia approved these changes

2022-08-09 11:28 UTC, merged