Add a log-context-based Aggregator
alibaba/ilogtail pull request #325
Opened 2022-08-18 06:57 UTC by henryzhx8

To solve #324

2022-08-19 07:46 UTC, yyuuttaaoo requested changes

2022-08-19 07:46 UTC, yyuuttaaoo commented on helper/local_collector.go
> +func (p *LocalCollector) AddDataWithContext(tags map[string]string, fields map[string]string, ctx map[string]interface{}, t ...time.Time) {
老的测试接口，后续重构成统一的mock collector

2022-08-19 07:46 UTC, yyuuttaaoo commented on plugins/aggregator/defaultone/aggregator_default.go
> +		p.packID[pack] = id
想想怎么清理，不能只增不减

2022-08-22 03:18 UTC, henryzhx8 commented on plugins/aggregator/defaultone/aggregator_default.go
> +		source = ctx["source"].(string)
加在NewDockerStdoutProcessor那边了

2022-08-22 07:43 UTC, henryzhx8 commented on pkg/util/util.go
> +//	n >= 0: at most n lines
保存时会自动format

2022-08-22 07:45 UTC, henryzhx8 commented on plugins/aggregator/defaultone/aggregator_default.go
> +		p.logGroupPool[pack] = make([]*protocol.LogGroup, 0, p.MaxLogGroupCount)
直接`delete(p.logGroupPool[pack], pack)`

2022-08-22 07:45 UTC, henryzhx8 commented on plugins/aggregator/defaultone/aggregator_default.go
> +		if len(logGroupList[len(logGroupList)-1].Logs) != 0 {
已删去

2022-08-22 07:45 UTC, henryzhx8 commented on plugins/aggregator/defaultone/aggregator_default.go
> +	if len(logGroup.LogTags) == 0 || logGroup.LogTags[len(logGroup.LogTags)-1].GetKey() != util.PackIDTagKey {
已删去

2022-08-22 07:48 UTC, henryzhx8 commented on plugins/aggregator/defaultone/aggregator_default.go
> +		p.packID[pack] = id
在`Flush`函数里每隔10分钟去把所有已经很长时间没有新日志产生的`packID`删去`，具体超时时间根据map的大小来决定：map的size小雨10MB时，超时时间为30天，否则为1天。

2022-08-25 16:10 UTC, yyuuttaaoo approved these changes

2022-08-31 11:23 UTC, messixukejia commented on pluginmanager/logstore_config.go
> +	lc.LogsChan <- &ilogtail.LogWithContext{Log: log, Context: map[string]interface{}{"source": packID}}
no topic？

2022-08-31 11:50 UTC, messixukejia commented on plugins/aggregator/defaultone/aggregator_default.go
> -	MaxLogCount     = 1024
add ut

2022-09-01 09:42 UTC, merged