[WIP]feature: add support for otlp log flusher
alibaba/ilogtail pull request #418
Opened 2022-09-20 15:02 UTC by liuhaoyang

2022-09-23 01:32 UTC, messixukejia commented on plugins/flusher/otlplog/flusher_otlp_log.go
> +type FlusherOTLPLog struct {
版本v1要不要体现下？ 后面出了v2，如何扩展？

2022-09-23 01:32 UTC, messixukejia commented on helper/envconfig/docker_env_config.go
> +	if *flags.DockerConfigInitFlag && *flags.DockerConfigPluginInitFlag {
DockerConfigInitFlag的init移到了flags中，这种依赖包导入顺序的初始化是否是可靠的？

2022-09-23 01:32 UTC, messixukejia commented on pkg/protocol/converter/converter.go
> +	ProtocolOtlpLog      = "otlp_log"
要不要体现v1？

2022-09-23 01:32 UTC, messixukejia commented on pkg/protocol/converter/otlp_log.go
> +	for _, t := range logGroup.LogTags {
LogTags 是不是分别加到 Resource.Attributes 及 LogRecords.Attributes中了？

2022-09-23 01:32 UTC, messixukejia commented on pkg/protocol/converter/otlp_log.go
> +			Body:         &commonv1.AnyValue{Value: &commonv1.AnyValue_StringValue{StringValue: contents["content"]}},
跑到这一步可能content字段已经被前序的processor给干掉了，是不是得判断下？

2022-09-23 01:32 UTC, messixukejia commented on pkg/protocol/converter/otlp_log.go
> +	attrs = append(attrs, c.convertToOtlpKeyValue("source", logGroup.Source), c.convertToOtlpKeyValue("topic", logGroup.Topic), c.convertToOtlpKeyValue("machine_uuid", logGroup.MachineUUID))
用GetMachineUUID访问？

2022-09-23 02:43 UTC, henryzhx8 commented on pkg/protocol/converter/otlp_log.go
> +	}
29到33行可以删了，现在loggroup里除content字段其它字段没有实际意义，resourcelog里的attributes直接置空就行。

2022-09-23 02:47 UTC, henryzhx8 commented on pkg/protocol/converter/otlp_log.go
> +	desiredValues := make([][]string, len(logGroup.Logs))
desiredValues需要有实际意义，直接调用findTargetValues，可参考single_log的实现

2022-09-23 02:49 UTC, henryzhx8 commented on pkg/protocol/converter/converter.go
>  	default:
这里必须要加一个ConvertToOtlpStream，编码格式支持json和protobuf

2022-09-23 02:49 UTC, henryzhx8 commented on pkg/protocol/converter/converter.go
>  func (c *Converter) ToByteStreamWithSelectedFields(logGroup *protocol.LogGroup, targetFields []string) (stream [][]byte, values [][]string, err error) {
如果觉得返回值[][]byte不合适的话，也可以改成interface{}

2022-09-23 02:51 UTC, henryzhx8 requested changes
需要做些微调

2022-09-23 03:17 UTC, liuhaoyang commented on helper/envconfig/docker_env_config.go
> +	if *flags.DockerConfigInitFlag && *flags.DockerConfigPluginInitFlag {
我认为go 提供的 init 的顺序还是可靠的

2022-09-23 07:31 UTC, liuhaoyang commented on plugins/flusher/otlplog/flusher_otlp_log.go
> +type FlusherOTLPLog struct {
我倾向于加一个version配置，而不是写多个 flusher

2022-09-23 07:45 UTC, liuhaoyang commented on pkg/protocol/converter/otlp_log.go
> +	for _, t := range logGroup.LogTags {
LogRecords 的Attributes使用了新的 logAttrs 来填充

2022-09-27 03:02 UTC, merged

2023-01-18 09:01 UTC, h0cheung commented
配置了 gzip 后会报错缺少对应的 compressor
需要导入 google.golang.org/grpc/encoding/gzip
另外几个压缩方式在 https://pkg.go.dev/github.com/mostynb/go-grpc-compression