feature : Support for add  _file_offset_ tag to go plugins
alibaba/ilogtail pull request #474
Opened 2022-10-18 11:49 UTC by liuhaoyang

- 在`file_log`插件中添加`EnableLogPositionMeta`，表示在日志中添加该日志所属原始文件的元数据信息，即新增__tag__:__inode__字段和__file_offset__字段，默认值为false 。
- 在 go 的`processor_split_log_string`和`processor_split_log_regex`插件中做多行日志切分时支持修正 file_offset 值

2022-10-23 17:03 UTC, yyuuttaaoo requested changes
除了offset计算可能有点问题，更重要的是2个地方导致这个代码不能全局合入
1. 这个功能缺少开关，而受限于数据结构，修改__tag__:__file_offset__是O(n)时间的，对性能影响可能较大。C++生成plugin配置的地方要处理一下，把开关带过来。
2. 缺少对应的UT用例

2022-10-24 15:01 UTC, liuhaoyang commented on plugins/processor/split/logstring/split_log_string.go
> +				offset += int64(len(strArray[i]))
> 除了offset计算可能有点问题，更重要的是2个地方导致这个代码不能全局合入
> 
> 1. 这个功能缺少开关，而受限于数据结构，修改__tag__:__file_offset__是O(n)时间的，对性能影响可能较大。C++生成plugin配置的地方要处理一下，把开关带过来。
> 2. 缺少对应的UT用例

1. offset 计算已修复，补充UT
2. `processor_split_log_string` 和 `processor_split_log_regex` 插件都添加 `EnableLogPositionMeta` 开关
3. 在日志采集模式是`file_log`时，自动传递`file_log`插件配置的`EnableLogPositionMeta`值到`processor_split_log_string` 中 。生成的json config 如下
```
{
	"processors" : 
	[
		{
			"detail" : 
			{
				"EnableLogPositionMeta" : true,
				"SplitKey" : "content"
			},
			"type" : "processor_split_log_string"
		}
	]
}
```

2022-10-24 15:15 UTC, liuhaoyang commented
> 除了offset计算可能有点问题，更重要的是2个地方导致这个代码不能全局合入
> 
> 1. 这个功能缺少开关，而受限于数据结构，修改__tag__:__file_offset__是O(n)时间的，对性能影响可能较大。C++生成plugin配置的地方要处理一下，把开关带过来。
> 2. 缺少对应的UT用例

1. offset 计算已修复，补充UT
2. `processor_split_log_string` 和 `processor_split_log_regex` 插件都添加 `EnableLogPositionMeta` 开关
3. 在日志采集模式是`file_log`时，自动传递`file_log`插件配置的`EnableLogPositionMeta`值到`processor_split_log_string` 中 。生成的json config 如下
```
{
	"processors" : 
	[
		{
			"detail" : 
			{
				"EnableLogPositionMeta" : true,
				"SplitKey" : "content"
			},
			"type" : "processor_split_log_string"
		}
	]
}
```

2022-10-25 12:06 UTC, messixukejia commented on plugins/processor/split/logregex/split_log_regex.go
> +				helper.ReviseFileOffset(copyLog, int64(lastLineIndex), p.EnableLogPositionMeta)
regex建议也加下ut吧

2022-10-25 12:15 UTC, messixukejia commented on helper/split_log_helper.go
> +func GetFileOffsetTag(log *protocol.Log) *protocol.Log_Content {
![image](https://user-images.githubusercontent.com/13250519/197770368-7cc70921-0c8d-4a30-b27a-64f0ded570ae.png)
看上去tag是在content后面的，可以考虑下从后往前遍历

2022-10-25 14:46 UTC, liuhaoyang commented on helper/split_log_helper.go
> +func GetFileOffsetTag(log *protocol.Log) *protocol.Log_Content {
在 c++ 部分 EnableLogPositionMeta tag 是追加到最后的，倒叙遍历tags是合理的。理想情况下这里可以是O(1)

2022-10-26 02:59 UTC, yyuuttaaoo requested changes

2022-10-26 02:59 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.cpp
> +            if (pluginConfig.empty() || !jsonReader.parse(pluginConfig, pluginConfigJson)) {
empty的时候不用打warning吧，比如极简模式，啥都不处理并且输出到SLS的时候
warning可以把invalid plugin config增加一些信息，plugin config json parse error

2022-10-26 02:59 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.cpp
> +                            for (int i = 0; i < pluginConfigJson["processors"].size(); i++) {
这个应该不用for循环，就第一个插件可能是split插件吧，后面的不需要吧。第一个是自动加的，split content，计算offset语义正确，后面假设还split算offset，语义不一定正确吧。

2022-10-26 02:59 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.cpp
> +                        if (value["advanced"] && value["advanced"]["enable_log_position_meta"]) {
这一段拉出去做一个函数，叫CheckPluginProcessor？和CheckPluginFlusher先统一一下

2022-10-26 02:59 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.cpp
> +                                Json::Value procrssorConfigJson = pluginConfigJson["processors"][i];
procrssorConfigJson拼写错误

2022-10-26 02:59 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.cpp
> +                if (!pluginConfigJson.isNull()) {
这里也需要处理split processor的配置

2022-10-26 03:03 UTC, liuhaoyang commented on core/config_manager/ConfigManagerBase.cpp
> +                            for (int i = 0; i < pluginConfigJson["processors"].size(); i++) {
处理一次之后break出循环吧

2022-10-26 09:33 UTC, yyuuttaaoo approved these changes

2022-10-26 09:36 UTC, merged