ConfigServer adapt new pb
alibaba/ilogtail pull request #506
Opened 2022-11-03 09:10 UTC by Takuka0311

2022-11-14 03:20 UTC, henryzhx8 commented on core/app_config/AppConfigBase.cpp
> +const char* DEFAULT_ILOGTAIL_REMOTE_YAML_CONFIG_DIR_FLAG_VALUE = "user_remote_yaml_config.d";
这个目录名是之前已经约定了吗？如果还没约定的话，把开头的user去掉吧

2022-11-14 03:26 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "format error")("wrong address", TrimString(confJson["ilogtail_configserver_address"][*it].asString())));
如果格式错误还继续往下吗？是不是应该直接continue？

2022-11-14 03:28 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "format error")("wrong address", TrimString(confJson["ilogtail_configserver_address"][*it].asString())));
这里WARNING就够了，config server地址不对logtail也能运行，error一般都是那种比较大的错误

2022-11-14 03:29 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +            boost::regex reg_ip = boost::regex(" (?:(?:1[0-9][0-9]\\.)|(?:2[0-4][0-9]\\.)|(?:25[0-5]\\.)|(?:[1-9][0-9]\\.)|(?:[0-9]\\.)){3}(?:(?:1[0-9][0-9])|(?:2[0-4][0-9])|(?:25[0-5])|(?:[1-9][0-9]
写一下注释，这个pattern到底是代表什么，不然很难理解

2022-11-14 03:29 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "parse fail")("exception", exception));
一样，改WARNING

2022-11-14 03:30 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "illegal port")("port", port));
一样，改WARNING

2022-11-14 03:31 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +            int32_t port = atoi(configServerAddress[1].c_str());
这里也缺错误处理，atoi不成功怎么办？

2022-11-14 03:33 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +    if (0 == mConfigServerAddress.size()) return AppConfig::ConfigServerAddress("", -1);
为什么要返回-1？

2022-11-14 03:34 UTC, henryzhx8 commented on core/app_config/AppConfig.h
> +protected:
这两个成员为什么要定义为protected？

2022-11-14 03:45 UTC, henryzhx8 commented on core/config_manager/ConfigManager.h
> +    google::protobuf::RepeatedPtrField<configserver::proto::ConfigCheckResult> SendHeartbeat(AppConfig::ConfigServerAddress configServerAddress);
返回值和入参需不需要加&？以及入参能加const的都加吧

2022-11-14 03:45 UTC, henryzhx8 commented on core/config_manager/ConfigManager.h
> +    google::protobuf::RepeatedPtrField<configserver::proto::ConfigDetail> FetchPipelineConfig(
同上

2022-11-14 03:48 UTC, henryzhx8 commented on core/app_config/AppConfig.h
> +    std::vector<ConfigServerAddress> mConfigServerAddress;
vector类的，变量名都改复数吧
```suggestion
    std::vector<ConfigServerAddress> mConfigServerAddresses;
```

2022-11-14 03:50 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +const AppConfig::ConfigServerAddress& AppConfig::GetConfigServerAddress() const {
加一下注释，表明只返回一个地址

2022-11-14 03:58 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +        LOG_ERROR(sLogger, ("SendHeartBeat", "fail")("reqBody", reqBody)("errCode", e.GetErrorCode())("errMsg", e.GetMessage()));
改WARNING

2022-11-14 03:59 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +                checkResults = SendHeartbeat(configServerAddress);
需不需要换个地址重试？还是说目前就是能运行就行？

2022-11-14 04:00 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +        LOG_ERROR(sLogger, ("GetConfigUpdateInfos", "fail")("reqBody", reqBody)("errCode", e.GetErrorCode())("errMsg", e.GetMessage()));
同上

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "format error")("wrong address", TrimString(confJson["ilogtail_configserver_address"][*it].asString())));
这里疏漏了

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "format error")("wrong address", TrimString(confJson["ilogtail_configserver_address"][*it].asString())));
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +            int32_t port = atoi(configServerAddress[1].c_str());
atoi无论成功失败都会返回数字，所以就在下面判断port范围（1024～65535）来验证了；另外要是port不对，会在建立连接时报错。

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +            boost::regex reg_ip = boost::regex(" (?:(?:1[0-9][0-9]\\.)|(?:2[0-4][0-9]\\.)|(?:25[0-5]\\.)|(?:[1-9][0-9]\\.)|(?:[0-9]\\.)){3}(?:(?:1[0-9][0-9])|(?:2[0-4][0-9])|(?:25[0-5])|(?:[1-9][0-9]
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "parse fail")("exception", exception));
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +                LOG_ERROR(sLogger, ("ilogtail_configserver_address", "illegal port")("port", port));
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +const AppConfig::ConfigServerAddress& AppConfig::GetConfigServerAddress() const {
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +    if (0 == mConfigServerAddress.size()) return AppConfig::ConfigServerAddress("", -1);
方便验证 没有符合要求的地址 的情况

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.h
> +    std::vector<ConfigServerAddress> mConfigServerAddress;
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/app_config/AppConfig.h
> +protected:
定义错了，应该是private

2022-11-18 08:57 UTC, Takuka0311 commented on core/config_manager/ConfigManager.cpp
> +                checkResults = SendHeartbeat(configServerAddress);
目前是能运行就行

2022-11-18 08:57 UTC, Takuka0311 commented on core/config_manager/ConfigManager.cpp
> +        LOG_ERROR(sLogger, ("SendHeartBeat", "fail")("reqBody", reqBody)("errCode", e.GetErrorCode())("errMsg", e.GetMessage()));
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/config_manager/ConfigManager.cpp
> +        LOG_ERROR(sLogger, ("GetConfigUpdateInfos", "fail")("reqBody", reqBody)("errCode", e.GetErrorCode())("errMsg", e.GetMessage()));
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/config_manager/ConfigManager.h
> +    google::protobuf::RepeatedPtrField<configserver::proto::ConfigCheckResult> SendHeartbeat(AppConfig::ConfigServerAddress configServerAddress);
done

2022-11-18 08:57 UTC, Takuka0311 commented on core/config_manager/ConfigManager.h
> +    google::protobuf::RepeatedPtrField<configserver::proto::ConfigDetail> FetchPipelineConfig(
done

2022-12-18 12:20 UTC, henryzhx8 commented on core/app_config/AppConfig.h
> +#include <map>
这个哪用到了？

2022-12-18 12:39 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +        Json::Value::Members members = confJson["ilogtail_configserver_address"].getMemberNames();
ilogtail_configserver_address是什么格式？看起来是个一组kv？那key代表什么？

2022-12-18 12:40 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +            else if (1024 <= port && port <= 65535)
port范围不应该在1024～65535之间吗？

2022-12-18 12:41 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_tags") && confJson["ilogtail_tags"].isObject()) {
ilogtail_tags是什么格式？其它同上

2022-12-18 12:41 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +const AppConfig::ConfigServerAddress& AppConfig::GetConfigServerAddress() const {
改成GetOneConfigServerAddress吧

2022-12-18 12:42 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_configserver_address") && confJson["ilogtail_configserver_address"].isObject()) {
这个参数只能配在ilogtail_config.json里吗？环境变量似乎不可以？如果K8s用该怎么用？

2022-12-18 12:49 UTC, henryzhx8 commented on core/config_manager/ConfigManager.h
> +    google::protobuf::RepeatedPtrField<configserver::proto::ConfigCheckResult> SendHeartbeat(
类型太长，可以考虑typedefine一下

2022-12-18 12:51 UTC, henryzhx8 commented on core/config_manager/ConfigManager.h
> +        google::protobuf::RepeatedPtrField<configserver::proto::ConfigCheckResult> checkResults,
参数是否引用类型统一一下吧，这边和上边又不太一样

2022-12-18 13:04 UTC, henryzhx8 requested changes

2022-12-18 13:04 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +                if (configDetails[j].name() == configName) {
configDetails和checkResults长度相同吗？这边看起来有重复查找的情况？

2023-01-29 14:30 UTC, closed without merging

2023-02-02 10:49 UTC, Takuka0311 commented on core/app_config/AppConfig.h
> +#include <map>
已删除

2023-02-02 10:52 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +        Json::Value::Members members = confJson["ilogtail_configserver_address"].getMemberNames();
是字符串数组，每个元素代表一个可选的configserver地址

2023-02-02 10:52 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +            else if (1024 <= port && port <= 65535)
已更正

2023-02-02 10:54 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_tags") && confJson["ilogtail_tags"].isObject()) {
也是字符串数组，是ilogtail的tag

2023-02-02 10:54 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +const AppConfig::ConfigServerAddress& AppConfig::GetConfigServerAddress() const {
已改

2023-02-02 10:55 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_configserver_address") && confJson["ilogtail_configserver_address"].isObject()) {
这个版本暂时不考虑k8s场景

2023-02-02 10:57 UTC, Takuka0311 commented on core/config_manager/ConfigManager.h
> +    google::protobuf::RepeatedPtrField<configserver::proto::ConfigCheckResult> SendHeartbeat(
用到的不多，google::protobuf::RepeatedPtrField<configserver::proto::ConfigCheckResult>里，看最后的ConfigCheckResult就可以对应到pb，就不typedef了

2023-02-02 11:13 UTC, Takuka0311 commented on core/config_manager/ConfigManager.cpp
> +                if (configDetails[j].name() == configName) {
不同，configDetails包含详细信息，checkResults只有更新状态。确实有一点重复查找

2023-02-02 11:14 UTC, Takuka0311 commented on core/config_manager/ConfigManager.h
> +        google::protobuf::RepeatedPtrField<configserver::proto::ConfigCheckResult> checkResults,
已统一