feat: add http flusher supporting influxdb protocol & add group aggregator supproting group logs by keys
alibaba/ilogtail pull request #521
Opened 2022-11-17 04:27 UTC by snakorse

1. add http flusher supporting influxdb protocol 
2. add group aggregator supproting group logs by keys

2022-11-17 04:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=521) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=521) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=521) it.</sub>

2022-11-17 08:27 UTC, liuhaoyang reviewed
补充 `aggregator_group ` `flusher_http` `httpserver_input` 的文档

2022-11-18 07:30 UTC, liuhaoyang commented on plugins/flusher/http/flusher_http.go
> +	TagFieldsRename      map[string]string // Rename one or more fields from tags.
重复的定义 https://github.com/alibaba/ilogtail/blob/63df2679797d442d4acf069e5a4ef3c1d9e26237/plugins/flusher/kafkav2/flusher_kafka_v2.go#L146

2022-11-18 07:34 UTC, liuhaoyang commented
还可以给`input_http_server` `flusher_http` 插件添加 e2e case

2022-11-18 14:46 UTC, snakorse commented on plugins/flusher/http/flusher_http.go
> +	TagFieldsRename      map[string]string // Rename one or more fields from tags.
每个flusher相对独立吧，跨flusher去引用定义不太好

要么抽出来？但抽到哪里比较合适呢

2022-11-18 15:01 UTC, liuhaoyang commented on plugins/flusher/http/flusher_http.go
> +	TagFieldsRename      map[string]string // Rename one or more fields from tags.
helper 或者 pkg

2022-11-19 13:50 UTC, messixukejia requested changes

2022-11-19 14:14 UTC, henryzhx8 commented on pkg/protocol/converter/converter.go
> +		EncodingNone: true,
改个名字吧，例如EncodingCustom之类的，这里的none显然和otlp的none不是一个意思

2022-11-19 14:17 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/http.md
> +| Convert.Protocol             | String             | 否       | ilogtail数据转换协议，kafka flusher 可选值：`custom_single`,`otlp_log_v1`,`influxdb`。默认值：`custom_single` |
kafka flusher？

2022-11-19 14:18 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/http.md
> +| Convert.Encoding             | String             | 否       | ilogtail flusher数据转换编码，可选值：`json`、`none`、`protobuf`，默认值：`json`                              |
和实际对应吧

2022-11-19 14:38 UTC, henryzhx8 commented on plugins/flusher/http/flusher_http.go
> +	default:
http flusher应该还是属于通用型flusher吧，不允许[]byte吗？比如otlp的编码完就是[]byte

2022-11-19 14:39 UTC, henryzhx8 reviewed
influx协议的doc加一下

2022-11-20 12:40 UTC, messixukejia commented on plugins/aggregator/group/aggregator_group.go
> +func (q *groupQueue) Add(logGroup *protocol.LogGroup) error {
@henryzhx8 重点review这个文件，并测试下sls场景是否正常工作

2022-11-20 12:59 UTC, messixukejia commented on plugins/flusher/http/flusher_http.go
> +func (f *FlusherHTTP) Description() string {
问下往influxdb发送，db选择是在哪里实现的？

2022-11-29 01:58 UTC, snakorse commented on plugins/flusher/http/flusher_http.go
> +func (f *FlusherHTTP) Description() string {
Query 参数里可以自己配置 kv

2022-11-29 02:07 UTC, snakorse commented on plugins/flusher/http/flusher_http.go
> +	default:
允许[]byte，当前otlp也没实现stream接口，目前没有返回[]byte的实现，就没写
我补充一下吧

2022-11-29 02:11 UTC, snakorse commented on pkg/protocol/converter/converter.go
> +		EncodingNone: true,
otlp的none什么含义呢

2022-11-29 02:40 UTC, snakorse commented on helper/decoder/influxdb/decoder.go
> +			log.Contents = append(log.Contents, &protocol.Log_Content{Key: tagDB, Value: db})
因为parsePointsToLogs原来没有参数传入 req，我改一下这个函数的签名传进去

2022-11-29 02:54 UTC, snakorse commented on helper/decoder/influxdb/decoder.go
> +	typeKey       = "__type__"
type 字段可以管理起来   tag:db 也管理起来是不是语义上不太合适

2022-11-29 03:38 UTC, snakorse commented on helper/decoder/influxdb/decoder.go
> +	typeKey       = "__type__"
要么再加个参数 QueryAsTags 来控制是否将某些key放到tag中

2022-11-29 12:31 UTC, snakorse commented on helper/decoder/influxdb/decoder.go
> +	typeKey       = "__type__"
改名 FieldsExtend，同时将 type、tag:db管理起来

2022-12-01 14:35 UTC, liuhaoyang commented
LGTM

2022-12-04 08:07 UTC, EvanLjp commented on plugins/aggregator/group/aggregator_group.go
> +	groupAggs sync.Map
哪里有并发问题吗？

2022-12-04 08:07 UTC, EvanLjp commented on pkg/protocol/converter/influxdb_metric.go
> +		reader, err := newMetricReader(log)
是不是可以用sync.pool 重用一下，这种对象创建比较频繁

2022-12-06 03:24 UTC, henryzhx8 commented on plugins/aggregator/group/aggregator_group.go
> +			groupKey += groupKeyConnector + val
+=的效率是不是不太好？

2022-12-06 03:26 UTC, henryzhx8 commented on plugins/aggregator/group/aggregator_group.go
> +	groupKVs := g.getGroupKVs(log)
上边的buildGroupKey和getGroupKVs逻辑上看基本是一样的，能不能整合一下，虽然getGroupKVs可能只有初始化的时候会调，但冗余逻辑最好避免

2022-12-06 03:28 UTC, henryzhx8 commented on plugins/aggregator/group/aggregator_group.go
> +			logger.Warning(g.context.GetRuntimeContext(), "AGG_GROUP_NOT_FOUND_KEY", key)
错误信息最好上下文再详细一点，上同

2022-12-06 03:30 UTC, henryzhx8 requested changes

2022-12-06 03:30 UTC, henryzhx8 commented on plugins/aggregator/group/aggregator_group.go
> +	ilogtail.Aggregators["aggregator_group"] = func() ilogtail.Aggregator {
agg名字最好再改一下，一眼能看出来是根据什么聚合的，比如agg_content/value/keygroup这种

2022-12-08 04:26 UTC, snakorse commented on plugins/aggregator/group/aggregator_group.go
> +	groupAggs sync.Map
Add 跟 Flush 之间有并发可能

2022-12-08 08:07 UTC, snakorse commented on plugins/flusher/http/flusher_http.go
> +	queryVarKeys []string
是说 keep-alive header吗，这个golang 的httpclient 默认会添加的

2022-12-08 09:42 UTC, snakorse commented on plugins/flusher/http/flusher_http.go
> +	Delay    time.Duration // Delay time before next retry, default is 100 ms
已调整

2022-12-08 09:43 UTC, snakorse commented on plugins/flusher/http/flusher_http.go
> +	Concurrency int                  // How many requests can be performed in concurrent
已调整

2022-12-08 09:44 UTC, snakorse commented on plugins/aggregator/group/aggregator_group.go
> +			groupKey += groupKeyConnector + val
已调整为 strings.Builder

2022-12-08 09:47 UTC, snakorse commented on plugins/aggregator/group/aggregator_group.go
> +	groupKVs := g.getGroupKVs(log)
抽了下从logcontents中查找指定key的逻辑

buildGroupKey是hot-path，希望尽量减少这个路径上不必要的逻辑，因此并没有完全整合成一个函数

2022-12-08 09:47 UTC, snakorse commented on plugins/aggregator/group/aggregator_group.go
> +			logger.Warning(g.context.GetRuntimeContext(), "AGG_GROUP_NOT_FOUND_KEY", key)
已调整

2022-12-08 09:47 UTC, snakorse commented on plugins/aggregator/group/aggregator_group.go
> +	ilogtail.Aggregators["aggregator_group"] = func() ilogtail.Aggregator {
调整为了 aggregator_content_value_group

2022-12-08 11:19 UTC, henryzhx8 commented on docs/cn/SUMMARY.md
> +  * [按Key分组](data-pipeline/aggregator/aggregator-group.md)
链接地址更新一下

2022-12-09 01:50 UTC, snakorse commented on docs/cn/SUMMARY.md
> +  * [按Key分组](data-pipeline/aggregator/aggregator-group.md)
done

2022-12-09 03:28 UTC, henryzhx8 commented on docs/cn/developer-guide/log-protocol/README.md
> +| 自定义协议 | [Influxdb协议](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/) | custom |
influxdb协议是不是标准协议？

2022-12-09 05:31 UTC, snakorse commented on docs/cn/developer-guide/log-protocol/README.md
> +| 自定义协议 | [Influxdb协议](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/) | custom |
influxdb是开源标准协议，看这个标准自定义的参照是什么吧，我以为是除sls以外的都是自定义。。
如果这个标准和自定义指的是开源社区共识，那influxdb应该认为是标准

2022-12-09 05:56 UTC, EvanLjp approved these changes
LGTM

2022-12-09 09:47 UTC, henryzhx8 approved these changes

2022-12-09 10:53 UTC, messixukejia approved these changes

2022-12-09 10:54 UTC, merged