improve user agent info
alibaba/ilogtail pull request #523
Opened 2022-11-18 03:36 UTC by henryzhx8

2022-11-20 13:16 UTC, messixukejia requested changes

2022-11-20 13:16 UTC, messixukejia commented on core/sls_control/SLSControl.cpp
> +        env = "ACK Daemonset";
中间用_或-连一下？否则后面空格承载了太多意义，不好进行后续分析

2022-11-20 13:16 UTC, messixukejia commented on core/sls_control/SLSControl.cpp
> +    } else if (getenv("ACK_NODE_LOCAL_DNS_ADMISSION_CONTROLLER_SERVICE_HOST")) {
这些环境变量来源、场景，都注释描述下

2022-11-20 13:16 UTC, messixukejia commented on core/sls_control/SLSControl.cpp
> +std::string SLSControl::GetRunningEnvironment() {
之前 @linrunqi08 加过ALICLOUD_LOG_K8S_FLAG，这里为什么不用这个环境变量判断？

2022-11-20 13:16 UTC, messixukejia commented on core/sls_control/SLSControl.cpp
> +    LOG_WARNING(sLogger,
为什么是warning？

2022-11-28 02:47 UTC, henryzhx8 commented on core/sls_control/SLSControl.cpp
> +std::string SLSControl::GetRunningEnvironment() {
已加，因为目前这个变量还未上线

2022-11-28 02:47 UTC, henryzhx8 commented on core/sls_control/SLSControl.cpp
> +    LOG_WARNING(sLogger,
因为curl启动不了可能存在ua误判的情况

2022-11-29 07:59 UTC, yyuuttaaoo approved these changes

2022-11-29 12:35 UTC, messixukejia approved these changes

2022-11-30 03:22 UTC, merged