feat: add clickhouse flusher (#554)
alibaba/ilogtail pull request #580
Opened 2022-12-16 14:34 UTC by kl7sn

2022-12-16 14:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=580) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=580) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=580) it.</sub>

2022-12-20 09:13 UTC, henryzhx8 requested changes

2022-12-20 09:13 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/clickhouse.md
> +| Database          | String    | 是    | 插入数据目标 buffer 表所在数据库名称 |
代码里也是一个整体，可以像kafka那样打包成一个struct

2022-12-20 10:06 UTC, henryzhx8 commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +			Method: clickhouse.CompressionLZ4,
是否允许提供其它压缩类型？

2022-12-21 04:20 UTC, kl7sn commented
上面的问题我尽快解决，最近🐑了，有点耽误进度，实在抱歉。

2022-12-21 06:56 UTC, messixukejia commented
> 上面的问题我尽快解决，最近🐑了，有点耽误进度，实在抱歉。

好好休息，保重身体，祝早日康复。

2022-12-21 08:58 UTC, henryzhx8 requested changes
另外需要加一下E2E测试，详见https://github.com/alibaba/ilogtail/blob/main/docs/cn/developer-guide/test/e2e-test.md

2022-12-21 08:58 UTC, henryzhx8 commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +		}
这里的逻辑建议完善一下，目前是写死的状态，应当能够做的更加通用和灵活一点，比如：
1. 表中的列名能够由用户指定，不指定时提供默认值；
2. 具体写入数据的编码格式可以多样化一些（现在是人工拼出来的），我们已经在pkg.converter这个包里（https://github.com/alibaba/ilogtail/blob/main/docs/cn/developer-guide/log-protocol/converter.md) 提供了一些现成的日志协议及编码方式，可以对loggroup进行不同的转换，可以把这些灵活性放到参数里。（参考kafka的Convert结构）。

2022-12-21 08:58 UTC, henryzhx8 commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +	return batch.Send()
这边发送失败的时候是什么行为？需不需要加一些简单的错误重试逻辑？（不太清楚sdk里是否已包含相关逻辑）

2022-12-21 08:58 UTC, henryzhx8 commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +	flusher FlusherFunc
不对外暴露的放到struct的最后吧

2023-01-16 07:05 UTC, henryzhx8 requested changes
1. 必要的license加一下
2. e2e测试没通过，需要修改一下

2023-01-16 16:03 UTC, kl7sn commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +		}
![image](https://user-images.githubusercontent.com/2037801/212720693-4a7febe2-4ba7-40ab-88f5-36f227ece35c.png)

https://github.com/alibaba/ilogtail/discussions/554

目前的版本会自动创建 buffer 表和 null 表，用户可以自定义物化视图解析 null 表中的数据。

用户指定列名和编码格式的问题，这边再调研下，继续开发。

2023-01-16 16:16 UTC, kl7sn commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +				logger.Debug(f.context.GetRuntimeContext(), string(buf))
| 参数                                | 类型       | 是否必选 | 说明                                          |
|-----------------------------------|----------|------|---------------------------------------------|
| BufferNumLayers                   | Int   | 否    | Buffer 缓冲区数量，默认 16                          |
| BufferMinTime                     | Int   | 否    | 缓冲区数据刷新限制条件 min_time，默认 10                  |
| BufferMaxTime                     | Int   | 否    | 缓冲区数据刷新限制条件 max_time，默认 100                 |
| BufferMinRows                     | Int   | 否    | 缓冲区数据刷新限制条件 min_rows，默认 10000               |
| BufferMaxRows                     | Int   | 否    | 缓冲区数据刷新限制条件 max_rows，默认 1000000             |
| BufferMinBytes                    | Int   | 否    | 缓冲区数据刷新限制条件 min_bytes，默认 10000000           |
| BufferMaxBytes                    | Int   | 否    | 缓冲区数据刷新限制条件 max_bytes，默认 100000000          |
| Compression                       | String   | 否    | 压缩方式，默认 lz4，可选 none/gzip/deflate/lz4/brzstd |

这里使用了 Buffer Engine 的特性，相关参数可以进行配置。

2023-01-18 02:48 UTC, kl7sn commented
今天晚上我再提交一个支持 tls config 的版本。

2023-02-06 03:16 UTC, kl7sn commented
我在本地执行`make check-dependency-licenses`，提示需要增加如下内容

![image](https://user-images.githubusercontent.com/2037801/216875599-fadc586f-2ead-4110-9022-c45188796481.png)

但是该依赖是由 https://github.com/alibaba/ilogtail/pull/603 合并到主分支产生的

![image](https://user-images.githubusercontent.com/2037801/216876029-b36bc5bd-5fe0-4188-ae24-49c84d5fbe6c.png)

我这边是有什么操作不对吗？执行`make check-dependency-licenses`的时候还有别的前置条件吗

2023-02-06 03:57 UTC, henryzhx8 commented
> 我在本地执行`make check-dependency-licenses`，提示需要增加如下内容
> 
> ![image](https://user-images.githubusercontent.com/2037801/216875599-fadc586f-2ead-4110-9022-c45188796481.png)
> 
> 但是该依赖是由 #603 合并到主分支产生的
> 
> ![image](https://user-images.githubusercontent.com/2037801/216876029-b36bc5bd-5fe0-4188-ae24-49c84d5fbe6c.png)
> 
> 我这边是有什么操作不对吗？执行`make check-dependency-licenses`的时候还有别的前置条件吗

test目录下go mod tidy一下先

2023-02-07 02:26 UTC, kl7sn commented
本地运行 `TEST_SCOPE=flusher_clickhouse make e2e` 未出现报错。

当前报错
![image](https://user-images.githubusercontent.com/2037801/217131913-b03a0b82-4c1c-47e2-945b-433c89146e45.png)

在增加 converter 之前未出现该报错，现有的 init 方法这边有什么写错的地方吗？

https://github.com/kl7sn/ilogtail/blob/flusher-clickhouse/test/engine/subscriber/clickhouse.go#L185

2023-02-07 03:28 UTC, henryzhx8 requested changes
麻烦问下你本地的go版本是多少？

2023-02-07 03:28 UTC, henryzhx8 commented on test/engine/subscriber/clickhouse.go
> +	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
这里似乎没有叫clickhouse的包

2023-02-07 04:06 UTC, kl7sn commented on test/engine/subscriber/clickhouse.go
> +	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
本地使用的是 1.19，我之前开发的时候是在，test的go mod里面增加了

> github.com/aliyun/alibaba-cloud-sdk-go/services/sls_inner => ../external/github.com/aliyun/alibaba-cloud-sdk-go/services/sls_inner

如果不增加这个依赖解析会一直报错

2023-02-07 07:43 UTC, henryzhx8 approved these changes

2023-02-07 12:12 UTC, yyuuttaaoo commented on docs/cn/data-pipeline/flusher/clickhouse.md
> +| Addrs                             | String数组 | 是    | ClickHouse 地址                                                                      |
写Addresses/Hosts吧，其他参数没有用缩写的

2023-02-07 12:17 UTC, yyuuttaaoo commented on docs/cn/data-pipeline/flusher/clickhouse.md
> +| Compression                       | String   | 否    | 压缩方式，默认 lz4，可选 none/gzip/deflate/lz4/brzstd                                        |
brzstd 这个是什么压缩方式？漏了/

2023-02-07 12:30 UTC, yyuuttaaoo commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +	if err = createNullBufferTable(f); err != nil {
确认一下，这个flusher多个logtail一起启动，并发创建、写一张表没问题吧？

2023-02-07 12:31 UTC, yyuuttaaoo commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +			return err
不用print err？

2023-02-07 12:31 UTC, yyuuttaaoo commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +			logger.Error(f.context.GetRuntimeContext(), "FLUSHER_FLUSH_ALARM", "flush clickhouse convert log fail, error", err)
不用return err?

2023-02-07 12:32 UTC, yyuuttaaoo commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +				return err
不用print err？

2023-02-08 02:47 UTC, kl7sn commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +	if err = createNullBufferTable(f); err != nil {
写入的表是 clickhouse 的缓冲表具有一定的多线程多小包数据的承载能力。

2023-02-08 02:53 UTC, kl7sn commented on plugins/flusher/clickhouse/flusher_clickhouse.go
> +			logger.Error(f.context.GetRuntimeContext(), "FLUSHER_FLUSH_ALARM", "flush clickhouse convert log fail, error", err)
这里参考的是 main 分支下面类似的逻辑
https://github.com/alibaba/ilogtail/blob/main/plugins/flusher/pulsar/flusher_pulsar.go#L179
https://github.com/alibaba/ilogtail/blob/main/plugins/flusher/kafkav2/flusher_kafka_v2.go#L280

2023-02-13 08:53 UTC, yyuuttaaoo approved these changes

2023-02-13 09:00 UTC, messixukejia approved these changes

2023-02-13 15:46 UTC, merged

2023-10-26 06:57 UTC, starriesWEB commented
为什么会创建一个 null 表，和一个 buffer 表
https://github.com/alibaba/ilogtail/blob/main/plugins/flusher/clickhouse/flusher_clickhouse.go#L271

查看源码发现只有 insert 了 buffer 库，并没有 insert 配置的 table
https://github.com/alibaba/ilogtail/blob/main/plugins/flusher/clickhouse/flusher_clickhouse.go#L194

配置的表数据一直是空的。buffer 表有数据，但是数据会减少，查看源码并没有发现 delete 语句，什么原因呢？
![image](https://github.com/alibaba/ilogtail/assets/73122677/f108c453-9a27-4e9b-a33a-4f1b851416bd)

---

![image](https://github.com/alibaba/ilogtail/assets/73122677/3e1172f1-c634-4365-bfed-d36922e7e1c1)