feat: flusher pulsar
alibaba/ilogtail pull request #603
Opened 2023-01-10 02:06 UTC by shalousun

iLogtail supports outputting data to pulsar  #https://github.com/alibaba/ilogtail/issues/540

2023-01-16 03:58 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/pulsar.md
> +| HashingScheme                         | Int      | 否    | 消息push分区的分发方式：0表示JavaStringHash,1表示Murmur3_32Hash                                  |
这个参数能否直接用String，然后代码里再做一层转换？

2023-01-16 03:58 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/pulsar.md
> +| ClientID                              | String   | 否    | 写入Pulsar的Client ID，默认取值：`LogtailPlugin`。                                           |
默认值改成iLogtail？

2023-01-16 03:58 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/pulsar.md
> +| Url                                   | String   | 是    | Pulsar url                                                                         |
URL的格式再说明一下吧，比如可支持多个url，逗号分隔

2023-01-16 03:58 UTC, henryzhx8 commented on plugins/flusher/pulsar/producers.go
> +	return p.getOrCreateProducer(topic, client, producerOptions)
为何不直接调用getorcreateproducer？

2023-01-16 03:58 UTC, henryzhx8 commented on plugins/flusher/pulsar/flusher_pulsar.go
> +func (f *FlusherPulsar) hashPartitionKey(valueMap map[string]string, defaultKey string) string {
这个函数是说，如果日志里没有partionkey，就用logstore做key；如果存在部分，就用那一部分作key？
我的感觉如果partionkey没有全部出现的话，是不是加个warning（一次性的）？

2023-01-16 03:58 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/pulsar.md
> +| MaxCacheProducers                     | int      | 否    | 动态topic情况下采用lru缓存的最大Producer数量 ，默认最大数量：8                                           |
加一下说明：使用动态topic功能时必选，另外lru这里可以不用体现

2023-01-16 04:47 UTC, henryzhx8 requested changes
可以的话，再加一下e2e测试吧

2023-01-16 08:02 UTC, shalousun commented on plugins/flusher/pulsar/flusher_pulsar.go
> +func (f *FlusherPulsar) hashPartitionKey(valueMap map[string]string, defaultKey string) string {
可以加warning，但是这个hash也是动态的，一次性的warning不行

2023-01-16 11:43 UTC, shalousun commented
> 可以的话，再加一下e2e测试吧

这个后面研究下，添加测试了能跑再提上来，现在是直接编译本地测试无认证条件是可以用的

2023-02-02 13:33 UTC, henryzhx8 approved these changes

2023-02-02 14:12 UTC, merged