feat: support oltp grpc/http input for trace and metrics (v2)
alibaba/ilogtail pull request #611
Opened 2023-01-29 05:40 UTC by shunjiazhu

2023-01-29 05:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=611) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=611) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=611) it.</sub>

2023-01-30 03:11 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-oltp-grpc.md
> +## 配置参数
![image](https://user-images.githubusercontent.com/13250519/215379545-4b719146-ccac-4018-830d-a17618ed1e17.png)

关于input的实现，对于input_http_server定位为一些通用场景。

对于一些重要协议，可以专有input插件，例如这里的service_otlp，可以同时支持http、grpc。

两种插件只是一个接入方式，解析是公用的。

回到代码：
input_http_server.go -- 扩展http的otlp log、metric、trace
新增一个otlp_service，实现全量的场景支持。这个完全对等到tpentelemetry-collector的 otlp input

2023-01-30 03:29 UTC, shunjiazhu commented on docs/cn/data-pipeline/input/service-oltp-grpc.md
> +## 配置参数
可以的

2023-01-30 08:59 UTC, messixukejia requested changes

2023-01-30 13:06 UTC, messixukejia commented on plugins/input/oltp_grpc/input_grpc_server.go
> +	s.metricsReceiver = newMetricsReceiver(ctx)
v1的接口也预留下吧，可以不实现。

2023-02-03 05:17 UTC, shunjiazhu commented on docs/cn/data-pipeline/input/service-oltp-grpc.md
> +
好，我加一下

2023-02-06 05:45 UTC, messixukejia requested changes

2023-02-06 05:45 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-otlp.md
> +不接收gGRPC和HTTP请求
这个配置项存在的价值是？

2023-02-06 05:45 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-otlp.md
> +
service_http_server 的文档

2023-02-06 05:45 UTC, messixukejia commented on helper/decoder/opentelemetry/constant.go
> +	TagKeyUnit                   = "_unit"
都是tag，span、metric命名不是太统一，这里为什么要加_？

2023-02-06 05:57 UTC, messixukejia commented on pkg/models/span.go
>  type SpanEvent struct {
pkg/logtail/libPluginAdapter.so 这个别合了，如果很容易误合，加个ignore吧

2023-02-06 07:55 UTC, shunjiazhu commented on docs/cn/data-pipeline/input/service-otlp.md
> +不接收gGRPC和HTTP请求
我清理一下，这个样例确实不合适，一般opentelemetry collector至少也会开一个协议。

2023-02-06 08:30 UTC, shunjiazhu commented on helper/decoder/opentelemetry/constant.go
> +	TagKeyUnit                   = "_unit"
重新修改了这些tag的命名，用otlp前缀。

2023-02-06 08:30 UTC, shunjiazhu commented on docs/cn/data-pipeline/input/service-otlp.md
> +
已经更新

2023-02-06 08:37 UTC, shunjiazhu commented on pkg/models/span.go
>  type SpanEvent struct {
ok

2023-02-08 03:35 UTC, messixukejia commented
建一个issue关联下吧

2023-02-08 04:04 UTC, yyuuttaaoo approved these changes
LGTM
It seems input_http_server doesn't support format version well. Maybe refectory is required later.

2023-02-08 04:45 UTC, shunjiazhu commented
iLogtail supports otlp metrics/traces input: #637

2023-02-08 15:33 UTC, merged