feat: config server
alibaba/ilogtail pull request #613
Opened 2023-01-29 15:07 UTC by Takuka0311

2023-02-02 13:38 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +            vector<string> configServerAddress = SplitString(TrimString(confJson["ilogtail_configserver_address"][*it].asString()), ":");
为什么要先getMembers？不能直接循环访问吗？

2023-02-02 13:49 UTC, henryzhx8 requested changes

2023-02-02 13:49 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +            else if (1024 < port && port < 65535)
port范围应该是多少？

2023-02-02 13:49 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +        }
问题同前

2023-02-02 13:49 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +            vector<string> configServerAddress = SplitString(TrimString(confJson["ilogtail_configserver_address"][*it].asString()), ":");
为什么要先getMembers？不能直接循环访问吗？

2023-02-02 13:49 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
>  } // namespace logtail
加一个空行

2023-02-02 13:49 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_configserver_address") && confJson["ilogtail_configserver_address"].isObject()) {
注释一下目前不支持k8s，避免遗忘

2023-02-02 13:49 UTC, henryzhx8 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_tags") && confJson["ilogtail_tags"].isObject()) {
注释同前

2023-02-06 04:59 UTC, henryzhx8 requested changes

2023-02-06 04:59 UTC, henryzhx8 commented on core/config_manager/ConfigManagerBase.cpp
> +    updateFlag |= CheckYamlDirConfigUpdate(serverConfigDirPath, true, filepathes, yamlConfigMTimeMap);
CheckYamlDirConfigUpdate加一个bool参数，用来控制是否在path不存在的时候创建改目录，local那个是true，remote那个是false。

2023-02-06 05:00 UTC, messixukejia requested changes

2023-02-06 05:00 UTC, messixukejia commented on core/config_manager/ConfigManager.cpp
> +            AppConfig::ConfigServerAddress configServerAddress = AppConfig::GetInstance()->GetOneConfigServerAddress();
每次调用地址都是变的？

2023-02-06 05:57 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +            vector<string> configServerAddress = SplitString(TrimString(confJson["ilogtail_configserver_address"][*it].asString()), ":");
因为内容未知不能直接循环访问，这样写也更清晰

2023-02-06 05:58 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +        }
回复同上

2023-02-06 05:59 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
>  } // namespace logtail
done

2023-02-06 06:01 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_configserver_address") && confJson["ilogtail_configserver_address"].isObject()) {
done

2023-02-06 06:01 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +    if (confJson.isMember("ilogtail_tags") && confJson["ilogtail_tags"].isObject()) {
done

2023-02-06 06:23 UTC, Takuka0311 commented on core/config_manager/ConfigManagerBase.cpp
> +    updateFlag |= CheckYamlDirConfigUpdate(serverConfigDirPath, true, filepathes, yamlConfigMTimeMap);
done

2023-02-06 07:34 UTC, Takuka0311 commented on core/config_manager/ConfigManager.cpp
> +            AppConfig::ConfigServerAddress configServerAddress = AppConfig::GetInstance()->GetOneConfigServerAddress();
修改了一下，每次调用地址不变，当请求失败时换地址

2023-02-06 07:44 UTC, Takuka0311 commented on core/app_config/AppConfig.cpp
> +            else if (1024 < port && port < 65535)
已更正

2023-02-06 11:27 UTC, henryzhx8 approved these changes

2023-02-12 02:44 UTC, messixukejia commented on core/app_config/AppConfig.cpp
> +    // configserver path, does not support k8s
不支持k8s怎么理解？补充清楚描述吧

2023-02-14 02:37 UTC, henryzhx8 approved these changes

2023-02-14 03:14 UTC, messixukejia approved these changes

2023-02-15 01:18 UTC, merged