Add pyroscope input new
alibaba/ilogtail pull request #614
Opened 2023-01-30 07:46 UTC by EvanLjp

2023-01-30 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=614) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=614) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: linrunqi08<br/>:white_check_mark: EvanLjp<br/>:x: liujiapeng.ljp<br/><hr/>**liujiapeng.ljp** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=614) it.</sub>

2023-02-01 11:05 UTC, messixukejia commented on pluginmanager/plugin_runner_v2.go
> +	if len(p.FlusherPlugins) == 0 {
这个作用是？

2023-02-03 09:37 UTC, EvanLjp commented
Notice: 为http_server 增加了dump功能协助后续系统双写验证, 目前使用场景为验证sls 端与Pyroscope 端 计算结果是否一致

2023-02-03 09:51 UTC, EvanLjp commented on plugins/input/httpserver/input_http_server.go
> +	} else if s.Format != common.ProtocolPyroscope {
fixed

2023-02-03 09:51 UTC, EvanLjp commented on plugins/input/httpserver/input_http_server.go
> +	if strings.Contains(s.Address, "SELF_ADDR") {
removed

2023-02-03 09:53 UTC, EvanLjp commented on pluginmanager/plugin_runner_v2.go
> +	if len(p.FlusherPlugins) == 0 {
增加默认flusher

2023-02-14 04:50 UTC, yyuuttaaoo commented on plugins/input/httpserver/input_http_server.go
> +	DumpDataKeepFiles  int
这里日志dump是什么行为？每小时一个文件，最多保存最近DumpDataKeepFiles个？
要单独搞到dump目录里吗，放外面是不是有点污染？
这个功能是相当与二进制的access.log吗？好像没有看到dump response。
此外，对应的解包tool在哪？不然感觉有点难用啊。

2023-02-14 04:50 UTC, yyuuttaaoo commented on plugins/input/httpserver/input_http_server.go
> +	Endpoint           string
增加自定义路径能力？可能叫path是不是更合理？
ref：https://www.rfc-editor.org/rfc/rfc3986

   The following are two example URIs and their component parts:

         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
          |   _____________________|__
         / \ /                        \
         urn:example:animal:ferret:nose

2023-02-14 04:50 UTC, yyuuttaaoo commented on plugins/input/httpserver/input_http_server.go
> +	fileName := strings.Join([]string{s.context.GetProject(), s.context.GetLogstore(), s.context.GetConfigName()}, "_") + ".dump"
放到单独dump目录，这里dump就不要加了，看上去会清楚点，结合下面时间后缀，统一以_划分各个语义单元。

2023-02-14 05:02 UTC, yyuuttaaoo commented on plugins/input/httpserver/input_http_server.go
> +		s.dumpDataChan <- &dumpData{
ch大小才10个。。是不是应该在返回response后面一把把request和response打印出来，如果满了就doDump？

2023-02-14 09:39 UTC, liuhaoyang commented on plugins/aggregator/metadatagroup/aggregator_metadata_group.go
> +	bytesAndLengthChecker := func(group *models.PipelineGroupEvents) {
感觉写个新的 aggregator for profile 会更清晰？

2023-02-14 12:44 UTC, EvanLjp commented on plugins/input/httpserver/input_http_server.go
> +	fileName := strings.Join([]string{s.context.GetProject(), s.context.GetLogstore(), s.context.GetConfigName()}, "_") + ".dump"
fixed

2023-02-14 12:44 UTC, EvanLjp commented on plugins/input/httpserver/input_http_server.go
> +	Endpoint           string
fixed

2023-02-14 12:45 UTC, EvanLjp commented on helper/unittest.go
> +func PickLogs(logs []*protocol.Log, pickKey string, pickVal string) (res []*protocol.Log) {
fixed

2023-02-14 12:47 UTC, EvanLjp commented on helper/profile/meta.go
> +	Key             *segment.Key
fixed

2023-02-15 01:57 UTC, messixukejia requested changes

2023-02-15 01:57 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-http-service.md
> +  | Agent | 协议         | 是否兼容 |
格式有问题

2023-02-15 01:57 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-http-service.md
> +version: v2
v1、v2分别应用于什么场景

2023-02-15 01:59 UTC, messixukejia requested changes

2023-02-15 01:59 UTC, messixukejia commented on plugins/input/httpserver/input_http_server.go
> +	if s.Format == common.ProtocolOTLPLogV1 {
上面pr已经合入了，同步下主干吧

2023-02-15 01:59 UTC, messixukejia commented on plugins/input/httpserver/input_http_server.go
> +	if strings.Contains(s.Address, "SELF_ADDR") {
SELF_ADDR 这个怎么还在？

2023-02-15 02:26 UTC, EvanLjp commented on docs/cn/data-pipeline/input/service-http-service.md
> +version: v2
v1 只是保留了最开始的, 纯sls 格式. 或者就删除

2023-02-19 12:52 UTC, messixukejia approved these changes

2023-02-19 12:52 UTC, messixukejia commented on plugins/input/httpserver/input_http_server.go
> +			_ = os.Remove(s.dumpDataKeepFiles[0])
超过个数后，只删一个，再极端场景下可能不是不够的，应该直接删到DumpDataKeepFiles - 1个

2023-02-19 12:52 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-http-service.md
> +| DumpDataKeepFiles  | Int               | 否    | [开发使用] Dump文件保留文件数目, 文件按小时滚动, 此参数默认值为5, 表示保留5小时Dump 参数
![image](https://user-images.githubusercontent.com/13250519/219947183-fe3ce186-8de8-44c6-8949-25841d6667af.png)

input插件跟协议解析应该是一个分层的结构，各类协议不应该先定在http场景下。pyscope接入是一个相对比较大的功能，最好是有独立的iput。如果暂时不提供也没关系，但是需要考虑好未来扩展的可能。

基于上述描述，http input并不是唯一的入口，所以dump应该是一个通用的功能，不应该被http input绑定，代码需要提取到公共代码部分

2023-02-19 12:52 UTC, messixukejia commented on plugins/input/httpserver/input_http_server.go
> +	fileName := strings.Join([]string{s.context.GetProject(), s.context.GetLogstore(), s.context.GetConfigName()}, "_") + ".dump"
对于sls来说，project+config已经是唯一了，不需要再增加logstore。可以考虑加上input插件类型，可读性更强些。


需要看下开源场景下，project+config的取值，不要出现一个很怪的文件命名。

2023-02-19 12:52 UTC, messixukejia commented on plugins/flusher/sls/flusher_sls.go
> +func (p *SlsFlusher) Export(events []*models.PipelineGroupEvents, context pipeline.PipelineContext) error {
events -> groups，命名要保持一致，其他地方类似要改下

2023-02-19 12:52 UTC, messixukejia commented on plugins/input/httpserver/input_http_server.go
> +		case d := <-s.dumpDataChan:
批量操作可能更合适些

2023-02-19 12:53 UTC, messixukejia requested changes

2023-02-19 12:53 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-http-service.md
> +| Path               | String            | 否    | <p>接收端点, 如Format 为 `otlp_logv1` 时, 默认端点为`/v1/logs` 。</p><p></p>
为什么要加这个配置？ 新增的配置项周一，一起交流下吧。

配置变更还是得慎重点，参数过多且控制项不正交的话会很影响用户体验，后面建议提前评审讨论下，以防返工。

2023-03-17 07:01 UTC, closed without merging