feat: support private plugin integration
alibaba/ilogtail pull request #638
Opened 2023-02-08 09:27 UTC by snakorse

solve #618 

changes:
1. add tools/builder executable code, to help generate plugins code
2. docker build with DOCKER_BUILDKIT enabled, and Dockerfile_build add --mount=type=ssh to proxy host ssh-agent when build with private repositoy
3. plugin_build.sh add import_plugins.sh before the go build
4. add plugins.yml and  delete plugins/all/*

2023-02-10 10:14 UTC, liuhaoyang commented
还需要补充一下构建文档

2023-02-12 02:43 UTC, messixukejia requested changes

2023-02-12 02:43 UTC, messixukejia commented on .gitignore
> -# local plugins
change log

2023-02-14 03:22 UTC, liuhaoyang approved these changes

2023-02-21 14:35 UTC, messixukejia approved these changes

2023-02-21 14:41 UTC, merged