feat: http flusher support variable config in Header
alibaba/ilogtail pull request #643
Opened 2023-02-10 03:56 UTC by snakorse

2023-02-10 10:19 UTC, liuhaoyang commented
这个改动 需要更新用户文档吗

2023-02-12 02:37 UTC, messixukejia requested changes

2023-02-12 02:37 UTC, messixukejia commented on docs/cn/data-pipeline/flusher/http.md
> +| Headers                      | Map<String,String> | 否       | 发送时附加的http请求header，如可添加 Authorization、Content-Type等信息，支持动态变量写法，如`{"x-db":"%{tag.db}"}`<p>v2版本支持从Group的Metadata或者Group.Tags中获取动态变量，如`{"x
下方文档补充下，动态变量写法的样例吧

2023-02-12 02:43 UTC, messixukejia requested changes

2023-02-12 02:43 UTC, messixukejia commented on docs/cn/data-pipeline/flusher/http.md
> +| 参数                           | 类型                 | 是否必选 | 说明
关键改动需要有changelog

2023-02-14 03:15 UTC, messixukejia approved these changes

2023-02-14 05:23 UTC, liuhaoyang approved these changes

2023-02-14 05:34 UTC, merged