Grok processor report match errors by default
alibaba/ilogtail pull request #645
Opened 2023-02-10 18:19 UTC by yyuuttaaoo

2023-02-12 02:23 UTC, messixukejia requested changes

2023-02-12 02:23 UTC, messixukejia commented on pluginmanager/global_config.go
> -	if runtime.GOOS == "windows" {
windows、liux都测试影响了吗

2023-02-12 02:23 UTC, messixukejia commented on pluginmanager/plugin_manager.go
> +var BaseVersion = "1.3.1"
这个要不要放到一个单独文件里？

2023-02-13 03:35 UTC, yyuuttaaoo commented on pluginmanager/global_config.go
> -	if runtime.GOOS == "windows" {
linux无问题

2023-02-13 03:35 UTC, yyuuttaaoo commented on plugins/processor/grok/processor_grok.go
> +			NoMatchError:        true,
ok

2023-02-13 04:17 UTC, yyuuttaaoo commented on pluginmanager/plugin_manager.go
> +var BaseVersion = "1.3.1"
Refined as described in this article: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications

2023-02-13 08:42 UTC, messixukejia approved these changes

2023-02-13 08:49 UTC, merged