feat: flusher_oltp supports metrics/traces pipelineEvents (v2)
alibaba/ilogtail pull request #646
Opened 2023-02-13 11:08 UTC by shunjiazhu

2023-02-14 03:24 UTC, shunjiazhu commented
solve #650

2023-02-14 04:01 UTC, liuhaoyang requested changes

2023-02-14 04:01 UTC, liuhaoyang commented on docs/cn/data-pipeline/flusher/otlp.md
> +```
在 v2 模式，能单独只发送其中一种或者2种数据吗

2023-02-14 04:19 UTC, shunjiazhu commented on docs/cn/data-pipeline/flusher/otlp.md
> +      Retry:
是丢弃的。目前sls log只有转到otlp log的逻辑。

2023-02-14 04:20 UTC, shunjiazhu commented on docs/cn/data-pipeline/flusher/otlp.md
> +```
可以的，pipelineEvent转出来的logs/metrics/traces，只会发非空的数据。

2023-02-14 05:42 UTC, liuhaoyang commented on docs/cn/data-pipeline/flusher/otlp.md
> +      Retry:
好的

2023-02-14 07:20 UTC, shunjiazhu commented on docs/cn/data-pipeline/flusher/otlp.md
> +```
已经支持

2023-02-14 07:22 UTC, shunjiazhu commented
flusher_oltp需要显式地配置Logs/Metrics/Traces的输出，如果没有配置，则不会输出相应的数据。
如果logs/metrics/traces都没配置，Init阶段会返回error。

2023-02-15 01:16 UTC, messixukejia requested changes

2023-02-15 01:16 UTC, messixukejia commented on pkg/protocol/converter/otlp.go
> +	rsLogs.Resource().Attributes().PutStr("topic", logGroup.GetTopic())
判断下是否为空？

2023-02-15 01:16 UTC, messixukejia commented on pkg/protocol/converter/otlp.go
> +				logRecord.Attributes().PutStr(k, v)
这里也会包含levelKey？

2023-02-15 01:16 UTC, messixukejia commented on pkg/protocol/converter/otlp.go
> +	_ = setScope(scopeLog, groupTags)
这些是不是应该放到hasLogs置为true之后？

2023-02-15 01:16 UTC, messixukejia commented on plugins/flusher/opentelemetry/flusher_otlp.go
> +	if f.logClient.grpcConn == nil {
为什么这里只对logclient进行了判断？

2023-02-15 01:16 UTC, messixukejia commented on docs/cn/data-pipeline/flusher/otlp.md
> +## 简介
changelog麻烦也加下

2023-02-15 01:24 UTC, messixukejia commented on pkg/protocol/converter/otlp.go
> +	"github.com/alibaba/ilogtail/pkg/protocol"
otlp目前是v1，适当考虑下后续如果有v2如何扩展

2023-02-15 02:43 UTC, shunjiazhu commented on pkg/protocol/converter/otlp.go
> +				logRecord.Attributes().PutStr(k, v)
这里我是和上一版flusher_otlp_log对齐的，logAttrs确实会包含levelKey。
https://github.com/alibaba/ilogtail/blob/main/pkg/protocol/converter/otlp_log.go#L50

2023-02-15 03:10 UTC, shunjiazhu commented on plugins/flusher/opentelemetry/flusher_otlp.go
> +	if f.logClient.grpcConn == nil {
这里确实是实现有误，我改一下

2023-02-15 06:08 UTC, shunjiazhu commented on pkg/protocol/converter/otlp.go
> +	rsLogs.Resource().Attributes().PutStr("topic", logGroup.GetTopic())
ok，但是上一个版本好像没有做这个判断。
https://github.com/alibaba/ilogtail/blob/main/pkg/protocol/converter/otlp_log.go#L35

2023-02-15 06:50 UTC, shunjiazhu commented on pkg/protocol/converter/otlp.go
> +	_ = setScope(scopeLog, groupTags)
ok

2023-02-15 06:57 UTC, shunjiazhu commented on pkg/protocol/converter/otlp.go
> +	"github.com/alibaba/ilogtail/pkg/protocol"
好的，可以基于Protocol和泛型支持一下，先留个口子

2023-02-15 07:17 UTC, messixukejia commented on pkg/protocol/converter/otlp.go
> +				logRecord.Attributes().PutStr(k, v)
要不要考虑去掉？

2023-02-15 07:18 UTC, messixukejia approved these changes

2023-02-15 08:03 UTC, shunjiazhu commented on pkg/protocol/converter/otlp.go
> +				logRecord.Attributes().PutStr(k, v)
ok

2023-02-15 09:28 UTC, liuhaoyang approved these changes

2023-02-15 10:02 UTC, merged