feat: suppprt log event model
alibaba/ilogtail pull request #647
Opened 2023-02-13 11:49 UTC by liuhaoyang

支持 log model for pipeline v2 

```
type Log struct {
	Name              string
	Level             string
	SpanID            string
	TraceID           string
	Tags              Tags
	Timestamp         uint64
	ObservedTimestamp uint64
	Body              []byte
}
```

body 使用 []byte 数组存储，提供了和 string zero-copy 转换的函数

2023-02-15 01:29 UTC, messixukejia commented on pkg/models/logs.go
> +	Tags              Tags
这个是不是叫 attributes 更好些，这个字段的意义其实是结构化的日志

2023-02-15 02:29 UTC, liuhaoyang commented on pkg/models/logs.go
> +	Tags              Tags
v2 model 中结构化的数据统一命名 Tags 了。如果改的话，几个数据类型要一起修改了

2023-02-15 13:19 UTC, messixukejia approved these changes

2023-02-15 13:28 UTC, messixukejia requested changes

2023-02-15 13:28 UTC, messixukejia commented on pluginmanager/plugin_runner_v2.go
> +	logger.Info(context.Background(), "time", in.Log.Time, "timestamp", uint64(time.Second*time.Duration(in.Log.Time)))
数据流上日志不要打印吧

2023-02-21 11:23 UTC, liuhaoyang commented
参考 https://ilogtail.gitbook.io/ilogtail-docs/installation/quick-start 测试。
采集配置如下 
```
enable: true
version: v2
inputs:
  - Type: file_log          # 文件输入类型
    LogPath: .              # 文件路径Glob匹配规则
    FilePattern: simple.log # 文件名Glob匹配规则
flushers:
  - Type: flusher_stdout    # 标准输出流输出类型
    OnlyStdout: true
```
1. 构造单行日志 `echo 'Hello, iLogtail!' >> simple.log`
2. 构造多行日志 `echo $'Hello\niLogtail' >> simple.log`
3. 输出结果
```
023-02-21 19:16:56 {"eventType":"log","name":"","timestamp":1676978216450879568,"observedTimestamp":0,"tags":{":__path__":"./simple.log"},"level":"","traceID":"","traceID":"","spanID":"","body":"Hello,iLogtail"}
2023-02-21 19:17:02 {"eventType":"log","name":"","timestamp":1676978222019108820,"observedTimestamp":0,"tags":{":__path__":"./simple.log"},"level":"","traceID":"","traceID":"","spanID":"","body":"Hello"}
2023-02-21 19:17:02 {"eventType":"log","name":"","timestamp":1676978222019108820,"observedTimestamp":0,"tags":{":__path__":"./simple.log"},"level":"","traceID":"","traceID":"","spanID":"","body":"iLogtail"}

```

2023-02-27 13:59 UTC, liuhaoyang commented on pkg/models/logs.go
> +type Log struct {
文档已加

2023-03-07 03:55 UTC, yyuuttaaoo approved these changes

2023-03-07 06:45 UTC, messixukejia approved these changes

2023-03-08 07:58 UTC, merged