feat: add Extension type plugin && http flusher support Authenticator
alibaba/ilogtail pull request #648
Opened 2023-02-13 12:44 UTC by snakorse

changes:
1. add Extension type plugin
2. pipeline.Context add interface GetExtension(name string) Extension
3. http flusher support use custom ClientAuthenticator registered though Extension

2023-02-15 13:29 UTC, messixukejia requested changes

2023-02-15 13:29 UTC, messixukejia commented on plugins/flusher/http/flusher_http.go
> +	Concurrency   int                  // How many requests can be performed in concurrent
1、更新下文档？
2、changelog

2023-02-27 02:29 UTC, liuhaoyang commented on pluginmanager/logstore_config.go
> +	pluginConfig, ok := plugins["extensions"]
extension 的加载为啥不放在下面跟其他类型一起处理

2023-02-27 02:34 UTC, liuhaoyang requested changes

2023-02-27 02:34 UTC, liuhaoyang commented on pkg/pipeline/extension.go
> +type Extension interface {
添加一下extension插件和下面四种实现的文档

2023-03-01 02:46 UTC, snakorse commented on pluginmanager/logstore_config.go
> +	pluginConfig, ok := plugins["extensions"]
因为 其他插件可能在其Init函数中依赖 extension，所以extension需要先加载

2023-03-01 09:00 UTC, snakorse commented on pkg/pipeline/extension.go
> +type Extension interface {
已添加

2023-03-01 09:01 UTC, snakorse commented on plugins/flusher/http/flusher_http.go
> +	Concurrency   int                  // How many requests can be performed in concurrent
已补充

2023-03-01 11:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=648) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=648) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=648) it.</sub>

2023-03-23 02:44 UTC, snakorse commented on licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
> +- [github.com/snakorse/handy](https://pkg.go.dev/github.com/snakorse/handy?tab=licenses)
哦 在ilogtail下fork一份也可以 那你帮忙fork一下吧

2023-03-24 02:30 UTC, snakorse commented on licenses/LICENSE_OF_ILOGTAIL_DEPENDENCIES.md
> +- [github.com/snakorse/handy](https://pkg.go.dev/github.com/snakorse/handy?tab=licenses)
已调整到ilogtail org

2023-03-24 02:48 UTC, messixukejia commented on pluginmanager/context_imp.go
> +	exists, ok := p.logstoreC.PluginRunner.GetExtension(name)
本函数有两个调用GetExtension，注释说明下差异吧

我看了下应该是第一处使用pipeline级别的Extension，下一处是插件阴式使用的场景

2023-03-24 02:48 UTC, messixukejia commented on docs/cn/data-pipeline/overview.md
> +| `ext_basicauth`<br> Basic认证 | 社区<br>[`snakorse`](https://github.com/snakorse) | 为 http_flusher 插件提供 basic 认证能力 |
汇总这里，新增的简介也改成超链接吧。

2023-03-24 03:33 UTC, snakorse commented on docs/cn/data-pipeline/extension/ext-basicauth.md
> +## 简介
已调整

2023-03-24 03:34 UTC, snakorse commented on docs/cn/data-pipeline/overview.md
> +| `ext_basicauth`<br> Basic认证 | 社区<br>[`snakorse`](https://github.com/snakorse) | 为 http_flusher 插件提供 basic 认证能力 |
已调整

2023-03-24 03:34 UTC, snakorse commented on pluginmanager/context_imp.go
> +	exists, ok := p.logstoreC.PluginRunner.GetExtension(name)
嗯 已添加注释

2023-03-24 06:34 UTC, liuhaoyang requested changes

2023-03-24 06:34 UTC, liuhaoyang commented on helper/extension_helper.go
> +type ExtensionConfig struct {
ExtensionConfig 为啥不定义在 pkg/extensions 下面

2023-03-24 06:34 UTC, liuhaoyang commented on helper/extension_helper.go
> +package helper
新加的代码文件需要添加 Copyright header

2023-03-24 06:34 UTC, liuhaoyang commented on pkg/pipeline/extensions/decoder.go
> +package extensions
新的代码文件需要加Copyright Header

2023-03-27 02:51 UTC, snakorse commented on helper/extension_helper.go
> +type ExtensionConfig struct {
已调整

2023-03-27 02:52 UTC, snakorse commented on helper/extension_helper.go
> +package helper
所有新增文件已添加header

2023-03-27 04:45 UTC, messixukejia approved these changes

2023-03-27 06:21 UTC, liuhaoyang approved these changes
LGTM

2023-03-27 06:21 UTC, merged