Feat: Support elasticsearch flusher
alibaba/ilogtail pull request #681
Opened 2023-02-23 16:30 UTC by joeCarf

2023-02-24 06:27 UTC, liuhaoyang commented
是否考虑实现 flusher v2 https://github.com/alibaba/ilogtail/blob/main/pkg/pipeline/flusher.go#L68

2023-02-24 07:38 UTC, joeCarf commented
> 是否考虑实现 [flusher v2](https://github.com/alibaba/ilogtail/blob/main/pkg/pipeline/flusher.go#L68) v2 可以处理 log / metrics / trace 等不同的[数据类型](https://github.com/alibaba/ilogtail/tree/main/pkg/models) ，这些数据都是可以写入ES进行存储的。

您的意思是我进行修改还是后续新增v2的支持呢？

2023-03-01 07:00 UTC, henryzhx8 requested changes
changelog的conflict麻烦先修正一下，这样能够触发流水线

2023-03-01 07:25 UTC, henryzhx8 requested changes

2023-03-01 07:25 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/elasticsearch.md
> +| Addresses                                       | String数组 | 是    | ElasticSearch 地址                                                                   |
加一下Type参数，可参考其它flusher的md

2023-03-01 07:25 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +func (f *FlusherElasticSearch) NormalFlush(projectName string, logstoreName string, configName string, logGroupList []*protocol.LogGroup) error {
这里除了normalflush，还有其它什么可能性吗？

2023-03-01 07:25 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				Index:   f.Authentication.PlainText.Index,
index这个放在authentication下边是不是有问题？如果不用plaintext的话，这里的index是什么？空吗？

2023-03-01 07:25 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				Refresh: "true",
refresh参数的含义是什么？

2023-03-01 07:25 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				logger.Error(f.context.GetRuntimeContext(), "FLUSHER_FLUSH_ALARM", "[%s] Error indexing logs", res.Status())
这里的error仅仅是index log吗？这边的error和162行的err != nil有什么区别？是否需要考虑重试？

2023-03-01 07:25 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/elasticsearch.md
> +| Authentication.HTTPConfig.MaxIdleConnsPerHost   | Int      | 否    | 每个host的连接池最大空闲连接数                                                                  |
httpconfig这个归在authentication下边感觉不是太准确

2023-03-02 01:54 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				Refresh: "true",
刷新es，使其能在下次请求时看到已更新的内容。不过对于这里的场景应该不需要，会带来es额外的资源消耗

2023-03-02 01:58 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +func (f *FlusherElasticSearch) NormalFlush(projectName string, logstoreName string, configName string, logGroupList []*protocol.LogGroup) error {
暂时还没有想到其他的操作方法

2023-03-02 02:00 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				Index:   f.Authentication.PlainText.Index,
es里的index类似于其他数据库的database概念，因此我参考其他数据库的实现，放在了authentication下。我理解这里的index不能为空

2023-03-02 02:18 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				logger.Error(f.context.GetRuntimeContext(), "FLUSHER_FLUSH_ALARM", "[%s] Error indexing logs", res.Status())
我理解两个判断没有区别，应该是重复代码忘记删除了。go-elasticsearch会自动提供三次的重试

2023-03-02 10:36 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				Index:   f.Authentication.PlainText.Index,
authentication的plaintext和tls是互斥的吗？

2023-03-02 10:38 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +func (f *FlusherElasticSearch) NormalFlush(projectName string, logstoreName string, configName string, logGroupList []*protocol.LogGroup) error {
那看一下是否需要这种可扩展性，之前其它flusher有这个是因为确实存在多种模式，并不是一个通用的必须项

2023-03-03 04:31 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +func (f *FlusherElasticSearch) NormalFlush(projectName string, logstoreName string, configName string, logGroupList []*protocol.LogGroup) error {
好的

2023-03-03 04:38 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				Index:   f.Authentication.PlainText.Index,
哦哦 之前没有考虑到互斥的问题，那我index拿出来放到anthentication下还是直接在flushserElasticsearch下合适呢

2023-03-03 10:13 UTC, shalousun commented on docs/cn/data-pipeline/flusher/elasticsearch.md
> +| Authentication.PlainText.Index                  | String   | 是    | 插入数据目标索引                                                                           |
这个是指es的索引吗？ 索引放认证配置下应该不太合适

2023-03-03 10:19 UTC, shalousun commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +
flusher es这里建议新增一个索引配置，类似flusher Kafka v2，支持动态的index。当然es的使用常见动态规则更加复杂，需要支持更具时间日期来生成，可以参考filebeat或者logstash这些组件提供的index配置规则

2023-03-07 08:42 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +				Index:   f.Authentication.PlainText.Index,
放外边合适些

2023-03-07 12:32 UTC, joeCarf commented on docs/cn/data-pipeline/flusher/elasticsearch.md
> +| Authentication.PlainText.Index                  | String   | 是    | 插入数据目标索引                                                                           |
好的

2023-03-07 14:12 UTC, joeCarf commented on docs/cn/data-pipeline/flusher/elasticsearch.md
> +| Authentication.HTTPConfig.MaxIdleConnsPerHost   | Int      | 否    | 每个host的连接池最大空闲连接数                                                                  |
ok

2023-03-08 14:33 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +
添加了一个接口在fmtstr.FormatIndex下，但没写出具体的实现。es的动态索引我不太熟悉，可能需要以后进一步调研

2023-03-09 01:55 UTC, shalousun commented on docs/cn/data-pipeline/flusher/elasticsearch.md
> +        Index: default
index变更了。样例没有变更过来

2023-03-09 09:03 UTC, henryzhx8 requested changes

2023-03-09 09:08 UTC, joeCarf commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +		if err != nil || errConvert != nil {
ok

2023-03-09 09:20 UTC, henryzhx8 requested changes

2023-03-09 09:20 UTC, henryzhx8 commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
>  		serializedLogs, err := f.converter.ToByteStream(logGroup)
这个是不是重复了？169行可以直接获得serializedlog

2023-03-10 03:32 UTC, henryzhx8 approved these changes

2023-03-20 06:51 UTC, messixukejia approved these changes

2023-03-20 07:16 UTC, merged