feat: add loki flusher
alibaba/ilogtail pull request #685
Opened 2023-02-28 02:48 UTC by Abingcbc

## What does this PR do?
1. Add loki flusher

## How to use?
```
enable: true
inputs:
  - Type: file_log
    LogPath: .
    FilePattern: simple.log
flushers:
  - Type: flusher_loki
    URL: http://<loki address>:3100/loki/api/v1/push
    ExternalLabels:
      source: ilogtail
```

2023-02-28 02:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=685) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=685) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=685) it.</sub>

2023-02-28 08:04 UTC, henryzhx8 requested changes
需要加一下ut和e2e测试

2023-02-28 08:48 UTC, liguozhong commented
👍，太棒了，loki也能使用 logtail 高性能agent了。可以在loki 的agent support 列表里增加一个 logtail

2023-02-28 08:58 UTC, liguozhong commented on plugins/flusher/loki/flusher_loki.go
> +				model.LabelSet{}, time.Now(), string(log),
```go
err = f.lokiClient.Handle(
				model.LabelSet{}, time.Now(), string(log),
```

`model.LabelSet{}`如果我理解得没错，这样是空label，这里的 label 对loki 很重要，如果有一种机制能从 logGroup 里提取出一些label 给loki将对loki的帮助很大，也许我理解错了。当然不改也可以，这个PR 可以作为一个非常好的初始pr。

2023-02-28 09:05 UTC, Abingcbc commented on plugins/flusher/loki/flusher_loki.go
> +				model.LabelSet{}, time.Now(), string(log),
嗯嗯，后续准备加上解析label

2023-02-28 09:09 UTC, liguozhong commented on plugins/flusher/loki/flusher_loki.go
> +				model.LabelSet{}, time.Now(), string(log),
👍，非常期待

2023-03-07 07:35 UTC, liguozhong commented on docs/cn/data-pipeline/flusher/loki.md
> +  "contents": {
@Abingcbc 👏 进度神速，动态label 这么快就提交了一个版本，太棒了。 非常期待能用logtail写loki。

这里是 contents,但是下面动态的 label是 content. application.  多了一个s ，我对logtail 不熟悉，不是很清楚这里是什么意思，我比较了解 loki ，隐约感觉这里文档有点模糊。

tag 和 tags 也是一样的。

2023-03-07 08:33 UTC, Abingcbc commented on docs/cn/data-pipeline/flusher/loki.md
> +  "contents": {
这里是参考了现有的 [Kafka flusher](https://ilogtail.gitbook.io/ilogtail-docs/data-pipeline/flusher/kafka_v2#dong-tai-topic)，利用 ilogtail 的 converter 提取日志里的标签。
`conent.` 前缀表示从 `contents` 字段里提取标签，`tag.` 前缀表示从 `tags` 字段里提取标签。我再补充一下这部分的文档

2023-03-07 08:40 UTC, henryzhx8 requested changes
loki的ut需要补充

2023-03-07 08:40 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +## 进阶配置
既然作为一个例子，最好将完整的配置写一下，方便其他用户对照

2023-03-07 08:40 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +- message
这里的字段和下边日志里的字段似乎不对应？

2023-03-07 08:40 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +针对上面写入的这种日志格式，如果想在 Loki 中根据`application`名称进行查询，那么需要进行如下的配置。
这里的文字说明最好再详细一些，不看代码看这段不太能理解

2023-03-07 08:40 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +| ExternalLabels                    | Map      | 否    | 需要添加到每条日志上的静态标签 |
这两个参数的命名最好再斟酌一下，能一看就知道大概作用是什么，第一个Labels太泛了，第二个可能还行

2023-03-07 08:40 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
> +	return f.lokiClient != nil
这里直接return true吧

2023-03-07 08:40 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +| MaxRetries                        | Int      | 否    | 发送是的最大重试次数，默认 `10` |
这三个可以打包

2023-03-07 08:40 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
> +			logger.Error(f.context.GetRuntimeContext(), "FLUSHER_FLUSH_ALARM", "flush loki convert log fail, error", err)
这里还要继续下去吗？

2023-03-07 08:40 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
> +		key = converter.TrimPrefix(key)
这个放在converter里是不是不太好？

2023-03-07 08:40 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
> +			err = f.lokiClient.Handle(labels, time.Now(), string(log))
这里的time.Now()的作用是什么？

2023-03-07 08:40 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
> +	if len(f.ExternalLabels) == 0 && len(f.Labels) == 0 {
这个要求是必须的吗？

2023-03-07 08:40 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
> +		MaxBackoff:     time.Duration(5) * time.Minute,
这边的参数和文档里的有出入，需要检验一下

2023-03-07 08:40 UTC, henryzhx8 commented on test/case/behavior/flusher_loki/loki-config.yaml
> +#  reporting_enabled: false
这一段是不是用不到？可以删了

2023-03-08 03:17 UTC, liguozhong commented on plugins/flusher/loki/flusher_loki.go
> +			err = f.lokiClient.Handle(labels, time.Now(), string(log))
👍，已经review到这么细节的阶段了，看来很快就要进入merge阶段了。

第二个参数是loki里每一行日志的时间戳，是非常重要的。目前的实现看起来是系统时间。

**q1**：logtail 里的流水线里`logGroupList []*protocol.LogGroup`的每一行日志里有时间戳吗（采集时间，系统时间，事件时间）如果能传入 logtail里的日志的时间是最好的。

2023-03-08 03:20 UTC, liguozhong commented
👍赞，用户文档+测试+实现+设计文档，非常完整高质量的一个PR

2023-03-08 07:04 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
> +			err = f.lokiClient.Handle(labels, time.Now(), string(log))
了解，loggroup里面已经有采集时间了，可以用那个时间来代替这里的time.Now()

2023-03-10 05:04 UTC, Abingcbc commented on docs/cn/data-pipeline/flusher/loki.md
> +| ExternalLabels                    | Map      | 否    | 需要添加到每条日志上的静态标签 |
第一个叫做 DynamicLabels 可以吗

2023-03-10 05:06 UTC, Abingcbc commented on docs/cn/data-pipeline/flusher/loki.md
> +| TenantID                          | String   | 否    | Loki 的租户 ID（需要 Loki 开启该功能）如果为空，则表示单租户模式 |
是的

2023-03-13 02:45 UTC, liguozhong commented on docs/cn/data-pipeline/flusher/loki.md
> +| ExternalLabels                    | Map      | 否    | 需要添加到每条日志上的静态标签 |
太棒了，进展很快，👍感谢 @Abingcbc 的积极反馈，关于命名留了一个小建议。
1: ExternalLabels  
在现代化的监控系统里大多叫做 resource 或者 target ，这两个会更加容易被未来的监控系统理解，表示一个 host级别的上下文信息。 我比较建议叫做 resource ，未来agent侧会比较靠近开源社区。ExternalLabels 也不错就是了，如果非要还个名字

2: Labels
如果ExternalLabels 被改成 resource 后，事实上Labels 并不会和谁有冲突。可以保留叫做Labels ，挺好的一眼就能看出来。

2023-03-13 03:17 UTC, liguozhong commented on docs/cn/data-pipeline/flusher/loki.md
> +| Cardinality                       | String数组 | 否    | 需要从日志中动态解析的标签列表，例如：`content.field1` |
👍，看起来 Cardinality 这个配置是这里最为重要的配置，也许可以先合并一个版本，打个 beta 标签，看下用户的反应。Cardinality 的设计定下来是一个漫长的过程，也许分成2个 PR 是个不错的主意

2023-03-13 16:44 UTC, Abingcbc commented on plugins/flusher/loki/flusher_loki.go
> +		key = converter.TrimPrefix(key)
有两个常量 `targetTagPrefix` `targetContentPrefix` 是 converter 下私有的，所以才把 `TrimPrefix` 放在 converter 里。

2023-03-14 08:04 UTC, liguozhong commented
resource 来自这里的描述
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md

2023-03-14 08:12 UTC, liguozhong commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
非常感谢如此快速的响应。文档越来越完善了，从这个配置我已经大概能了解如何配置了。非常棒👍。

有一个小小的建议。这里的Labels 是不是参考 Resource的配置使用Map会更清晰更不迷惑。
同时这样也更能解决 .-_ 等两个系统特殊符号的差异问题，并且可以消除content前缀出现在loki的label里。满多系统都是通过Map来完成Label的配置，因为是2个系统的映射，很多时候需要转换。
 
据我所知，loki的里的label的name 是不能带 小数点.的。 那么  
```yaml
Labels:
  name:    content._name
  level:     content.level
  app:       content.app
  status:    content.status
```

这样将会非常的清晰，并且也和loki原来的大多设计是一致的。同时也能避免在loki里看到context.xxx 这样奇怪的字符。未来排查问题的时候，输入的时候会更加清晰。
```yaml
pipeline_stages:
- json:
    expressions:
      level:
      app_rename: app
- labels:
    level:
    app: app_rename
```
![image](https://user-images.githubusercontent.com/9583245/224936254-6722194c-3ce1-4a75-895f-dedf5ed8727b.png)

2023-03-14 08:15 UTC, Abingcbc commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
好滴，我改一下

2023-03-14 08:40 UTC, Abingcbc commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
或许可以把 key 和 value 互换一下？这样用`content._name` 来解析label，可以通过这个 map，获取到存入 loki 的值，相当于对 label 进行 rename。
反过来的话，通过 `content._name` 解析后，不太方便反查。
e.g.
```yaml
Labels:
  content._name: name
  content.level: level
```

2023-03-14 09:03 UTC, liguozhong commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
这是个非常棒的想法，可以再等一下其他人一起讨论一下，我用 loki 用习惯了，我会比较习惯app放左边。

2023-03-14 09:10 UTC, Abingcbc commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
嗯嗯，那还是符合loki习惯，放在左边吧

2023-03-14 09:29 UTC, henryzhx8 commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
这个label提取出来以后，原始日志里面还有必要保留这个label吗？比如提取了content.name，那日志里还需不需要存在name这个字段？

2023-03-14 09:42 UTC, Abingcbc commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
我理解是需要的？这个 label 在 loki 里的作用是相当于索引，设置的索引应该不影响所存储的日志本身。cc @liguozhong

2023-03-14 09:47 UTC, henryzhx8 requested changes

2023-03-14 09:47 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +| Resource                           | Map      | 否    | 需要添加到每条日志上的静态标签 |
Convert参数是漏掉了吗？

2023-03-14 09:47 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +| MinBackoff, MaxBackoff, MaxRetries | Int      | 否    | 重试之间的最短，最长退避时间和最大重试次数，分别默认 `500`毫秒，`5`分钟和`10` |
这个还是分开来写吧

2023-03-14 09:47 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +| BatchSize                          | Int      | 否    | 发送积累的最大的 batch 大小，默认 `1024 * 1024` |
这边参数名字可以尽可能和kafka的对齐，比如MaxMessageBytes，如果在kafka中找不到对应的，可以自定义命名

2023-03-14 09:47 UTC, henryzhx8 commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
> 非常感谢如此快速的响应。文档越来越完善了，从这个配置我已经大概能了解如何配置了。非常棒👍。
> 
> 有一个小小的建议。这里的Labels 是不是参考 Resource的配置使用Map会更清晰更不迷惑。 同时这样也更能解决 .-_ 等两个系统特殊符号的差异问题，并且可以消除content前缀出现在loki的label里。满多系统都是通过Map来完成Label的配置，因为是2个系统的映射，很多时候需要转换。
> 
> 据我所知，loki的里的label的name 是不能带 小数点.的。 那么
> 
> ```yaml
> Labels:
>   name:    content._name
>   level:     content.level
>   app:       content.app
>   status:    content.status
> ```
> 
> 这样将会非常的清晰，并且也和loki原来的大多设计是一致的。同时也能避免在loki里看到context.xxx 这样奇怪的字符。未来排查问题的时候，输入的时候会更加清晰。
> 
> ```yaml
> pipeline_stages:
> - json:
>     expressions:
>       level:
>       app_rename: app
> - labels:
>     level:
>     app: app_rename
> ```
> 
> ![image](https://user-images.githubusercontent.com/9583245/224936254-6722194c-3ce1-4a75-895f-dedf5ed8727b.png)

这个确实是比较通用的形式，但是logtail这边有点特殊，日志内容是分成content和tag两大类的，content就是业务日志的内容，tag是一些元信息（例如主机名，pod名等等），我理解label信息一般是不是以元信息为主？Convert那边已经提供了重命名tag的功能，如果label不涉及content，这边Labels就没必要用map的形式，list足够了（已经在convert里做了重命名这件事）；如果有可能用到content，那这里就需要用map

2023-03-14 09:52 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
github.com/grafana/loki-client-go/loki，这个组件似乎写着experimental，do not use，这个还有其它替代品吗？

2023-03-15 01:44 UTC, liguozhong commented on plugins/flusher/loki/flusher_loki.go
`Please note that the Loki API is not stable yet, so breaking changes might occur when using or writing a third-party client.
`
https://grafana.com/docs/loki/latest/clients/
据我所知，目前没有官方支持的client. 其他包的代码可靠性看起来，不如现在选择的这个包，也许这个包是一个初版本不错的选择，官方正式出包的时候可以先这样。

另外的一个选择是依赖loki本体，本体里面的promtail 有一个 client，那个是最新的有人维护的，bug少，但是缺点接口一直也在改。并且 mod会引入太多无用的依赖变化。可以选择一下

```
	                "github.com/grafana/loki/clients/pkg/promtail/client"

                         client:= client.New(metrics, cfg.clientConfig, 0, 0, false, logger)
                         client.Chan() <- api.Entry{
				Labels: lbs,
				Entry: logproto.Entry{
					Timestamp: ts,
					Line:      fmt.Sprintf("%v", v),
				},
			}
```

2023-03-15 01:47 UTC, liguozhong commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
事实上都是可以的，配置的修改一次性的，以logtail的习惯和建议为主。TAG 如何用于转化成 label，期望留下一个yaml demo看一眼。

2023-03-15 01:51 UTC, liguozhong commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
> 我理解是需要的？这个 label 在 loki 里的作用是相当于索引，设置的索引应该不影响所存储的日志本身。cc @liguozhong

从我的经验来看，不应该删除。
为什么呢？
因为即便一个json的key被提取了也需要在原文里保留这个key，因为loki期望提供的功能事实上定位是 linux的grep。效果是给开发看到和他代码里打出来是一样的文本，label的配置仅仅是为了查询时候加速过滤，不应该影响开发，让开发看到和代码里不一样的日志。

2023-03-15 08:07 UTC, henryzhx8 commented on plugins/flusher/loki/flusher_loki.go
了解，那可以先使用现有的包，后边根据loki api的发展来动态调整

2023-03-15 08:08 UTC, henryzhx8 commented on test/case/behavior/flusher_loki/ilogtail-e2e.yaml
> +                - content._name
理解，loki的这个lebel更类似于一种索引

2023-03-15 08:41 UTC, henryzhx8 requested changes

2023-03-15 08:41 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +| Resource                           | Map      | 否    | 需要添加到每条日志上的静态标签 |
Resources？

2023-03-15 08:41 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +| Labels                             | String数组 | 否    | 需要从日志中动态解析的标签列表，例如：`content.field1` |
这边Labels和Resources最终都是存放在labelset里的，是不是可以考虑叫DynamicLabels，StaticLabels这样的？现在的命名是从物理意义出发的，不知道是不是不太直观？

2023-03-20 03:33 UTC, liguozhong commented on plugins/flusher/loki/flusher_loki.go
> +	f.lokiClient = client
有一个扩展需求，也是目前我们使用promtail 遇到的比较实际的问题，当 loki服务端性能较差时，是否有必要使用 多个http client，另外的 vector agent 是提供这种功能的。可以使用多个 client 提高写loki的吞吐，也许我们可以在下一个优化的PR 里聊这个。但是这个是目前遇到的很实际的问题。服务端的能力不如sls

2023-03-20 06:27 UTC, liguozhong commented on plugins/flusher/loki/flusher_loki.go
> +	f.lokiClient = client
可以下个优化PR里考虑这种问题，引入并发会让代码变得很复杂

2023-03-28 07:45 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +    BatchSize: 16
这俩名字还是不对

2023-03-28 07:48 UTC, henryzhx8 requested changes
最后在changelog里补充一下；
lint的问题需要解决一下

2023-03-28 07:48 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/loki.md
> +    BatchSize: 16
这俩名字还是不对

2023-03-28 09:15 UTC, messixukejia commented on plugins/flusher/loki/flusher_loki.go
> +	f.lokiClient = client
这个麻烦先提个issue吧

2023-03-28 09:16 UTC, messixukejia commented on plugins/flusher/loki/flusher_loki.go
> +	f.lokiClient = client
> 可以下个优化PR里考虑这种问题，引入并发会让代码变得很复杂

这个麻烦先提个issue吧，后面单独讨论下

2023-03-28 09:24 UTC, liguozhong commented on docs/cn/data-pipeline/flusher/loki.md
> +    MinBackoff: 100000000000
看起来PR快完成了，非常感谢@Abingcbc 的贡献。关于MinBackoff 和 MaxBackoff ，有个小小的建议可以参考一下。
loki 那边的代码，时间相关的一般是2种用法，如果变量不带 _s 或者 second 结尾 那么默认认为是文本形式，如需要填写一个时间字符串，如：5s， 1m，10m，2d 。
```suggestion
    MinBackoff: 5s
```

2023-03-28 12:04 UTC, Abingcbc commented on docs/cn/data-pipeline/flusher/loki.md
> +    MinBackoff: 100000000000
好的，我在下一个PR里增加这个解析

2023-03-29 01:17 UTC, messixukejia approved these changes

2023-03-29 01:22 UTC, henryzhx8 approved these changes

2023-03-29 01:49 UTC, liguozhong commented
恭喜，PR终于通过了。👍

2023-03-31 05:58 UTC, merged

2023-04-01 02:52 UTC, liguozhong commented
恭喜合并支持了，在loki client文档里也指向了 ilogtail了。
```yaml
[docs/sources/clients/_index.md](https://github.com/grafana/loki/pull/8970/files#diff-c43e280923401ffd77b399d09f41258b8c26323e585018d6c8a1bce2b38dbe04)
Marking files as viewed can help keep track of your progress, but will not affect your submitted reviewViewed
Comment on this file
@@ -77,3 +77,4 @@ when using or writing a third-party client.
- [mjaron-tinyloki-java](https://github.com/mjfryc/mjaron-tinyloki-java) (Java)
- [LokiLogger.jl](https://github.com/JuliaLogging/LokiLogger.jl) (Julia)
- [winston-loki](https://github.com/JaniAnttonen/winston-loki) (JS)
- [ilogtail](https://github.com/alibaba/ilogtail) (Go)
```