Add ecs meta
alibaba/ilogtail pull request #692
Opened 2023-03-07 04:00 UTC by EvanLjp

2023-03-07 04:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=692) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=692) before we can accept your contribution.<br/><hr/>**liujiapeng.ljp** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=692) it.</sub>

2023-03-08 02:12 UTC, yyuuttaaoo requested changes

2023-03-08 02:12 UTC, yyuuttaaoo commented on helper/platformmeta/ecs/export.go
> +	manager.mutex.Lock()
这方法感觉是高频调用的，用锁是不是有点代价过高？主机meta插件filebeat/otel collector是如何实现的？

2023-03-09 05:01 UTC, yyuuttaaoo requested changes

2023-03-13 04:15 UTC, yyuuttaaoo commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +`processor_cloudmeta`插件可以添加为日志增加云平台元数据信息。
cloudmeta是包括主机和K8s全部吗？还是只是cloudhost？

2023-03-13 04:15 UTC, yyuuttaaoo commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +| AddMetas | map[string]string | 否    | 增加元信息配置。                                                                                                                                                  |
有这个参数了，感觉Mode有点多余了，因为完全可以用JSONPath为空 + AddMetas的rename表达顶层key为xxx.yyy的意思

2023-03-13 04:15 UTC, yyuuttaaoo commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +| JSONPath | String            | 否    | Mode为json模式生效，支持多层结构增加云平台元信息，最内层结构需要为json结构                                                                                                               |
将JSONPath的第一级当做JSONKey，可以少一个参数。而且在V2下也更合理一些。

2023-03-13 04:15 UTC, yyuuttaaoo commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +| `B:{}`             | ""       | {"cloud_zone":"zone"} | A       | 选中A字段，但无具体字段，因此跳过追加，输出`B:{}`                                                    |
这个行为可能不太合理，除非类型不匹配，比如A已经是个string了，那么跳过，否则应该增加A，并添加meta。因为我们现在的JSON处理并没有那么强大，如果原来日志中缺少key，那么也没有办法补充一个value为object的。

2023-03-13 06:31 UTC, EvanLjp commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +| `B:{}`             | ""       | {"cloud_zone":"zone"} | A       | 选中A字段，但无具体字段，因此跳过追加，输出`B:{}`                                                    |
有add_fields 插件负责这个职责，所以没这么加

2023-03-13 06:33 UTC, EvanLjp commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +`processor_cloudmeta`插件可以添加为日志增加云平台元数据信息。
这个没看懂，这个只是取cloud instance 元信息

2023-03-13 06:44 UTC, messixukejia requested changes

2023-03-13 06:44 UTC, messixukejia commented on plugins/processor/appender/processor_appender.go
> +	case "__ip__":
__host__ 为什么不定义到platformmeta中？

2023-03-13 06:44 UTC, messixukejia commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +`processor_cloudmeta`插件可以添加为日志增加云平台元数据信息。
这个插件如果定位是主机的元信息的话，processor_cloudmeta-> processor_cloud_hostmeta

2023-03-13 06:44 UTC, messixukejia commented on plugins/processor/cloudmeta/platformmeta/interface.go
> +	FlagInstanceID         = "__cloud_instance_id__"
[semantic conventions for Resources](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/)

[semantic conventions for Log Attributes](https://opentelemetry.io/docs/reference/specification/logs/semantic_conventions/)、
﻿[semantic conventions for Span Attributes](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/)

后续我们的字段定义，统一默认按照otel定义的规范吧。

2023-03-13 06:44 UTC, messixukejia commented on plugins/processor/cloudmeta/platformmeta/aliyun_ecs.go
> +// global var
platformmeta下的代码应该是跟processor公用的，是不是放到helper下跟docker目录并列？

2023-03-13 06:45 UTC, messixukejia commented on plugins/processor/cloudmeta/platformmeta/aliyun_ecs.go
> +	e.ecsMinimumFetchInterval = time.Second * time.Duration(val)
@yyuuttaaoo 提个aone后续整改下C++/go的控制变量传递机制吧。

2023-03-13 07:14 UTC, yyuuttaaoo commented on docs/cn/data-pipeline/processor/processor-cloudmeta.md
> +| AddMetas | map[string]string | 否    | 增加元信息配置。                                                                                                                                                  |
rename单独出来吧。默认不建议rename了，map行为和converter一致

2023-03-14 08:01 UTC, yyuuttaaoo requested changes

2023-03-14 08:44 UTC, yyuuttaaoo approved these changes

2023-03-15 08:26 UTC, merged