Standardize ConfigServer's code format.
alibaba/ilogtail pull request #743
Opened 2023-03-23 14:49 UTC by Takuka0311

2023-03-27 03:43 UTC, henryzhx8 requested changes

2023-03-27 03:43 UTC, henryzhx8 commented on core/config_manager/ConfigManager.cpp
> +            LOG_ERROR(sLogger, ("create directory failed", serverConfigDirPath));
加一下，failed之后的行为，例如retry later还是stop using remote了

2023-03-28 04:21 UTC, Takuka0311 commented on core/config_manager/ConfigManager.cpp
> +            LOG_ERROR(sLogger, ("create directory failed", serverConfigDirPath));
添加了stop using remote

2023-04-03 08:08 UTC, henryzhx8 approved these changes

2023-04-03 08:17 UTC, messixukejia approved these changes

2023-04-03 08:25 UTC, merged