Fix/tag fields rename
alibaba/ilogtail pull request #746
Opened 2023-03-25 16:08 UTC by shalousun

fix https://github.com/alibaba/ilogtail/issues/744

Enable enable_env_ref_in_config configuration to support system variable binding [discussion 724](https://github.com/alibaba/ilogtail/discussions/724)

2023-03-25 16:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=746) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=746) before we can accept your contribution.<br/><hr/>**shalousun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=746) it.</sub>

2023-03-26 11:27 UTC, messixukejia requested changes

2023-03-26 11:27 UTC, messixukejia commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
> +- `${env_name}`生效依赖于`ilogtail`的`enable_env_ref_in_config`配置，从`ilogtail 1.5.0`开始支持。
是不是还少了%{content.xxx}

2023-03-26 11:27 UTC, messixukejia commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
> +   service: ${env_name}
锁进？

2023-03-26 11:27 UTC, messixukejia commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
> +在使用`daemonset`或者`sidecar`部署`ilogtail`容器的`env`配置部分添加自己的想要添加的系统变量，配置参考如下：
![image](https://user-images.githubusercontent.com/13250519/227772480-9c480172-d52e-43c5-90c5-e2cd7f305fa1.png)
这一段是不是不需要了？

2023-03-26 11:27 UTC, messixukejia commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
> +    Topic: ilogtail_${app_name}
${env_name}？？

2023-03-26 11:28 UTC, messixukejia commented on core/logtail.cpp
> +DECLARE_FLAG_BOOL(enable_env_ref_in_config);
changelog

2023-03-27 03:34 UTC, henryzhx8 requested changes

2023-03-27 03:34 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
> +- 将自定义的变量`_app_`添加到`ALIYUN_LOG_ENV_TAGS`后日志的`tags`中就会看到自定义的变量。
这里应该是`_app_`还是`_app_name_`？有点乱

2023-03-27 03:34 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
> +#### 动态topic中使用系统变量
这里的逻辑有点混乱，我理解应该是以这种组织方式：
1. 先描述一个场景，目标是将某个环境变量用到动态topic里，扣题
2. 然后分两种场景：
- 最直接的方式是直接在converter配置里用${}这种符号
- 如果日志里也需要存放环境变量，也可以用%{tag/content.xx}的方式，然后讲怎么将环境变量放到tag里，包括直接在env里配或者add_fields加。

2023-03-27 03:34 UTC, henryzhx8 commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
vscode开发环境装一个markdownlint插件，保持风格一致（比如空行等）

2023-03-27 03:34 UTC, henryzhx8 commented on pkg/protocol/converter/converter.go
这里建议不要这么改（还漏了一个地方），源代码还是保留，然后新增一个函数：
```go
func addTagIfRequired(tags, tagKeyRenameMap map[string]string, key, value string) {
	if newKey, ok := tagKeyRenameMap[key]; ok && len(newKey) != 0 {
		tags[newKey] = value
	} else if !ok {
		tags[key] = value
	}
}
```
然后把225-229以及247-251行用这个函数替换掉，然后在205、254和256行添加该函数

2023-03-27 07:41 UTC, shalousun commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
> +#### 动态topic中使用系统变量
嗯，这个文档也是提上来大家看下意见，Kafka的改好了pulsar也要对应的修改

2023-03-28 06:31 UTC, henryzhx8 requested changes

2023-03-28 06:31 UTC, henryzhx8 commented on pkg/protocol/converter/converter.go
> +		addTagIfRequired(tags, tagKeyRenameMap, tagLogTopic, src)
src应该是topic

2023-03-29 11:56 UTC, shalousun commented on docs/cn/data-pipeline/flusher/flusher-kafka_v2.md
这个目前主要是用goland搞的，后面搞一个试下

2023-03-31 02:18 UTC, henryzhx8 approved these changes

2023-03-31 05:48 UTC, messixukejia approved these changes

2023-03-31 05:55 UTC, yyuuttaaoo approved these changes

2023-03-31 05:57 UTC, merged