Processor regex replace
alibaba/ilogtail pull request #757
Opened 2023-04-01 13:15 UTC by pj1987111

to support #402
https://github.com/alibaba/ilogtail/discussions/402

2023-04-03 02:34 UTC, linrunqi08 requested changes

2023-04-03 02:34 UTC, linrunqi08 commented on docs/cn/data-pipeline/processor/processor-regex-replace.md
> +`processor_regex_replace processor`插件可以通过正则匹配的模式实现文本日志的替换。
非常好的设计，能够补充之前https://github.com/alibaba/ilogtail/blob/main/docs/cn/data-pipeline/processor/processor-desensitize.md这个插件在某些条件下的不足。

2023-04-03 02:34 UTC, linrunqi08 commented on docs/cn/data-pipeline/processor/processor-regex-replace.md
> +| Fields       | Field   | 是    | 正则匹配与替换的字段集合                                                            |
按照我们现在比较通用的插件格式设计，这里是不需要Fields字段的，如果需要针对多个sourceKey的配置，那么直接配置多个processor_regex_replace的配置就好了

2023-04-03 02:34 UTC, linrunqi08 commented on docs/cn/data-pipeline/processor/processor-regex-replace.md
> +| Replacement   | String  | 否    | 正则表达式匹配后替换的字符串                               |
这里跟脱敏插件的字段命名保持一致会比较好，ReplaceString

2023-04-03 02:34 UTC, linrunqi08 commented on docs/cn/data-pipeline/processor/processor-regex-replace.md
> +| DestKey | String  | 否    | 正则表达式匹配并替换后的值存储的新字段，默认不存储新字段。                         |
这个字段的话，我个人感觉不是很有必要的

2023-04-03 02:34 UTC, linrunqi08 commented on plugins/processor/regexreplace/processor_regex_replace.go
> +	"regexp"
我们在做GROK正则选型的时候，比较过regexp2和regexp https://github.com/alibaba/ilogtail/blob/main/plugins/processor/grok/processor_grok_benchmark_test.go
结论是regexp2的性能会更好，这里建议也使用regexp2

2023-04-03 02:34 UTC, linrunqi08 commented on plugins/processor/regexreplace/processor_regex_replace_test.go
> +
很完整的测试。不过我们之前的开发者使用regex2的时候，混用了rune和string导致数据中包含中文的时候处理有问题，这里也建议补充一下中文的case。

2023-04-03 02:40 UTC, pj1987111 commented on docs/cn/data-pipeline/processor/processor-regex-replace.md
> +| Fields       | Field   | 是    | 正则匹配与替换的字段集合                                                            |
那这边就不用数组，而是平铺吗？

2023-04-03 06:03 UTC, messixukejia requested changes

2023-04-03 06:03 UTC, messixukejia commented on docs/cn/data-pipeline/processor/processor-regex-replace.md
> +    ReplaceString: ${1}0/24
${} 在采集配置中是有特殊含义的。https://github.com/alibaba/ilogtail/blob/4fa2d6f35c9aca73adf2de22b21395c547fae51b/docs/cn/data-pipeline/flusher/flusher-kafka_v2.md

这里要考虑下怎么解决

可以同步下最新代码https://github.com/alibaba/ilogtail/commit/4fa2d6f35c9aca73adf2de22b21395c547fae51b#diff-2b0aa71052a51bf54bd56e95552811dad5e3acb1ca98522f2a682bc927e565fd

2023-04-03 06:03 UTC, messixukejia commented on docs/cn/data-pipeline/processor/processor-regex-replace.md
> +    Regex: (\d.*\.)\d+
多个匹配什么效果？

2023-04-04 00:52 UTC, messixukejia requested changes

2023-04-04 00:52 UTC, messixukejia commented on docs/cn/SUMMARY.md
> +  * [字符串替换](data-pipeline/processor/processor-string-replace.md)
changelog

2023-04-04 00:52 UTC, messixukejia commented on docs/cn/SUMMARY.md
>  * [聚合](data-pipeline/aggregator/README.md)
https://github.com/alibaba/ilogtail/blob/main/docs/cn/developer-guide/plugin-development/how-to-write-processor-plugins.md
![image](https://user-images.githubusercontent.com/13250519/229658286-b4db8926-1b09-4c04-9d9e-6724be271aac.png)
这一步没有？

2023-04-04 00:52 UTC, messixukejia commented on plugins/processor/stringreplace/processor_string_replace.go
> +// Copyright 2021 iLogtail Authors
2023

2023-04-04 00:52 UTC, messixukejia commented on plugins/processor/stringreplace/processor_string_replace_test.go
> +func TestProcessorRegexChinessCharacters(t *testing.T) {
加下benchmark看看效果

2023-04-04 01:11 UTC, messixukejia requested changes

2023-04-04 01:11 UTC, messixukejia commented on plugins/processor/stringreplace/processor_string_replace_test.go
> +			ipRecord := `10.10.239.16`
这个用例改成多匹配项吧。

换成regex2后，是不是变成只替换单匹配项了？

2023-04-04 01:11 UTC, messixukejia commented on docs/cn/data-pipeline/processor/processor-string-replace.md
> +| Match           | String，无默认值 | 匹配指定数据。<br>如果是字符串全文替换输入需要匹配的字符串。<br>如果是正则替换输入需要匹配的正则表达式。<br>unquote去除转义符不需要输入 |
文档里体现下，如果多个子串符合条件时的处理原则吧。

2023-04-04 01:11 UTC, messixukejia commented on docs/cn/data-pipeline/processor/processor-string-replace.md
> +    "content": "{\"UNAME\":\"\",\"GID\":\"\",\"PAID\":\"\",\"UUID\":\"\",\"STARTTIME\":\"\",\"ENDTIME\":\"\",\"UID\":\"2154212790\",\"page_num\":1,\"page_size\":10}",
UID 是有效值吗？建议改成随机的数字吧

2023-04-04 01:21 UTC, messixukejia requested changes

2023-04-04 01:21 UTC, messixukejia commented on plugins/processor/stringreplace/processor_string_replace.go
> +				newContVal, _ = strconv.Unquote(strings.ReplaceAll(strconv.Quote(cont.Value), "\\\\", "\\"))
这里转换有点多，需要看下有没有性能问题。

2023-04-04 11:43 UTC, messixukejia commented on plugins/processor/stringreplace/processor_string_replace.go
> +					newContVal, _ = strconv.Unquote(cont.Value)
处理失败错误不处理，有可能出现newvalue为空，导致数据丢失。
1、打一下错误日志
2、错误的保持原值不变

2023-04-04 11:43 UTC, messixukejia commented on plugins/processor/stringreplace/processor_string_replace.go
> +			if cont.Value != newContVal {
这个字符串比较可能开销比较大，这个是不是可以去掉？
DestKey如果指定了，不管是否相等都设置。

2023-04-04 12:07 UTC, linrunqi08 approved these changes

2023-04-05 01:42 UTC, messixukejia approved these changes

2023-04-05 15:42 UTC, merged