Feature support goprofile pull
alibaba/ilogtail pull request #764
Opened 2023-04-03 06:10 UTC by EvanLjp

2023-04-03 06:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=764) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=764) before we can accept your contribution.<br/><hr/>**liujiapeng.ljp** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=764) it.</sub>

2023-04-03 06:30 UTC, EvanLjp commented on pkg/helper/profile/meta.go
> +	ExceptionType = Type{Name: "block", Kind: "profile_exception"}
exception

2023-04-03 06:30 UTC, EvanLjp commented on plugins/input/goprofile/discovery_kubernetes.go
> +	IncludeContainerLabelRegex map[string]*regexp.Regexp
to inner field

2023-04-03 06:30 UTC, EvanLjp commented on plugins/input/goprofile/discovery_kubernetes.go
> +	lastClearTime time.Time
remove

2023-04-05 13:01 UTC, messixukejia requested changes

2023-04-06 06:56 UTC, messixukejia commented on docs/cn/data-pipeline/input/service-goprofile.md
> +| Labels | map[string]string，`{}` | 具体实例性能数据追加标签 |
Labels 增加区分度吧

2023-04-06 07:38 UTC, linrunqi08 commented on plugins/input/goprofile/discovery_static.go
> +
这个文件是不是叫discovery_host比较好

2023-04-10 05:01 UTC, messixukejia approved these changes

2023-04-10 09:15 UTC, EvanLjp commented on plugins/input/goprofile/discovery_static.go
> +
和prometheus 一致

2023-04-10 09:16 UTC, merged