Feature add support of quote in processor_split_key_value plugin
alibaba/ilogtail pull request #766
Opened 2023-04-04 14:35 UTC by pj1987111

#762

2023-04-05 11:08 UTC, messixukejia requested changes

2023-04-05 11:40 UTC, messixukejia commented on plugins/processor/split/keyvalue/key_value_splitter.go
> +	Quote                string
参数尽量精简些吧

2023-04-06 00:48 UTC, linrunqi08 requested changes

2023-04-06 00:48 UTC, linrunqi08 commented on plugins/processor/split/keyvalue/key_value_splitter_test.go
> +// slice-index 150987              7647 ns/op            5272 B/op        109 allocs/op
这里我在想是不是10s的时间不够长，因为可能是程序准备的时间有些差异；可以放到30s试一下，是不是波动会小一些

2023-04-06 00:48 UTC, linrunqi08 commented on docs/cn/data-pipeline/processor/processor-split-key-value.md
> +| Quote                        | String | 否       | 引用符，当设定后若值被引用符包含，就提取引用符内的值。 默认不开启引用符功能。  |
例如双引号，需要加\，文档里需要说明一下，否则配置的时候可能就配错了

2023-04-06 02:19 UTC, messixukejia approved these changes

2023-04-07 01:11 UTC, linrunqi08 approved these changes

2023-04-07 04:01 UTC, yyuuttaaoo commented on plugins/processor/split/keyvalue/key_value_splitter.go
> +		if strings.Index(pair, s.Separator+s.Quote) > 0 || strings.HasPrefix(pair, s.Quote) {
1. 似乎没有必要用2个if，全部&&起来是不是就好了
2. 能处理a:"b \" c" d:e =>
    a: b " c
    d: e
    这样的用例吗

2023-04-07 04:44 UTC, pj1987111 commented on plugins/processor/split/keyvalue/key_value_splitter.go
> +		if strings.Index(pair, s.Separator+s.Quote) > 0 || strings.HasPrefix(pair, s.Quote) {
第一个done
第二个由于算法是前向匹配，所以解析出来，是a: b(空格) 、 c"  、 d:e
case 添加到测试里了。

2023-04-07 16:12 UTC, yyuuttaaoo commented on plugins/processor/split/keyvalue/key_value_splitter.go
> +				} else { // nerver hit
never？
if else 里的内容是否反了？

2023-04-08 01:55 UTC, pj1987111 commented on plugins/processor/split/keyvalue/key_value_splitter.go
> +				} else { // nerver hit
已修正

2023-04-10 02:49 UTC, yyuuttaaoo approved these changes

2023-04-10 02:50 UTC, merged