add support for proxy through env
alibaba/ilogtail pull request #790
Opened 2023-04-14 07:22 UTC by henryzhx8

2023-04-18 02:04 UTC, messixukejia approved these changes

2023-04-18 02:04 UTC, messixukejia commented on core/app_config/AppConfigBase.cpp
> +bool AppConfigBase::CheckProxyEnv() {
新增场景ut覆盖下

2023-04-18 14:37 UTC, yyuuttaaoo requested changes

2023-04-18 14:37 UTC, yyuuttaaoo commented on core/app_config/AppConfigBase.cpp
> +    }
不为空的话，应该总是覆盖大写的吧，这样才能保证小写任何情况下优先

2023-04-20 02:21 UTC, yyuuttaaoo approved these changes

2023-04-26 03:09 UTC, merged