feat: support dynamic tag
alibaba/ilogtail pull request #810
Opened 2023-04-23 04:09 UTC by liukezhi2

* read dynamic tag from env ALIYUN_LOG_FILE_TAGS or default path ilogtail_file_tags.json

2023-04-23 04:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=810) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=810) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=810) it.</sub>

2023-04-23 12:48 UTC, EvanLjp approved these changes
LGTM

2023-04-26 10:12 UTC, yyuuttaaoo requested changes

2023-04-27 13:15 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.cpp
> +        mFileFlag = false;
这里可能和我说的意思有点不一样，我的意思是这个函数第一行直接判断flag是空就return掉

2023-04-27 13:15 UTC, yyuuttaaoo commented on core/aggregator/Aggregator.cpp
> +    if (ConfigManager::GetInstance()->mFileFlag) {
这里也一样，用gflag是否为空就行了

2023-04-27 13:15 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.h
> +    T& getAlternateBuffer() {
这两个名字要不还是改成ReadBuffer和WriteBuffer吧，我第一眼进来感觉current是用来read的。为了避免后续复用这个代码有的人用current当read有的人用alternative当read不如就明确点。

2023-04-28 18:05 UTC, yyuuttaaoo approved these changes

2023-04-30 15:15 UTC, merged