otlp decoder for metrics(v1)
alibaba/ilogtail pull request #813
Opened 2023-04-23 08:32 UTC by Takuka0311

Further testing required

2023-04-25 01:56 UTC, qiansheng91 commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSData.go
> +		dataPoint := data.At(i)
需要添加以下逻辑： 如果DataPoint.Exemplars中的TraceID和SpanID如果不为空，则将该值添加到Label中

2023-04-25 01:57 UTC, qiansheng91 commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSData.go
> +		labels := defaultLabels.Clone()
需要添加以下逻辑： 如果DataPoint.Exemplars中的TraceID和SpanID如果不为空，则将该值添加到Label中

2023-04-25 02:50 UTC, messixukejia requested changes

2023-04-25 02:50 UTC, messixukejia commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSData.go
> +package opentelemetry
文件名变一下，不是ToSLS

2023-04-28 03:43 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSData.go
> +		dataPoint := data.At(i)
done

2023-04-28 03:43 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSData.go
> +		labels := defaultLabels.Clone()
done

2023-04-28 03:43 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/decoder.go
>  	"fmt"
done

2023-04-28 03:43 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSData.go
> +package opentelemetry
done

2023-05-04 02:13 UTC, closed without merging