feat: upgrade kafka sarama client
alibaba/ilogtail pull request #824
Opened 2023-05-02 08:03 UTC by shalousun

#https://github.com/alibaba/ilogtail/issues/600
1. upgrade upgrade kafka sarama client to 1.38.1 and rewrite service_kafka input plugin
2. Optimize flusher kafka v2 to improve performance in static topic scenarios

2023-05-06 02:18 UTC, messixukejia requested changes

2023-05-06 02:18 UTC, messixukejia commented on plugins/input/kafka/input_kafka.go
> +func (k *InputKafka) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
问下相对于之前的实现方式的好处是什么？是否有兼容问题？

2023-05-06 03:00 UTC, shalousun commented on plugins/input/kafka/input_kafka.go
> +	switch strings.ToLower(k.Assignor) {
默认是range

2023-05-06 03:03 UTC, shalousun commented on plugins/input/kafka/input_kafka.go
> +	k.context = pipContext
方法里面用了go本身context的方法，所以换了名称

2023-05-06 03:05 UTC, shalousun commented on plugins/input/kafka/input_kafka.go
> +func (k *InputKafka) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
这里是client升级后消费端直接实现它的ConsumeClaim接口，都是消费数据，最终数据处理没变

2023-05-15 07:40 UTC, messixukejia commented
@linrunqi08 尽快测试下InputKafka对企业版的影响，测试通过后即可合入。

2023-05-18 09:21 UTC, linrunqi08 approved these changes

2023-05-22 02:01 UTC, yyuuttaaoo approved these changes

2023-05-22 02:04 UTC, messixukejia approved these changes

2023-05-22 06:26 UTC, merged