otlp decoder for metrics(v1)
alibaba/ilogtail pull request #827
Opened 2023-05-04 02:16 UTC by Takuka0311

2023-05-06 01:33 UTC, messixukejia requested changes

2023-05-06 01:33 UTC, messixukejia commented on pkg/protocol/decoder/opentelemetry/decoder.go
> +	resMetrics := otlpMetricReq.Metrics().ResourceMetrics()
既然分了otlpDataToILogtail.go、otlpDataToILogtailV2.go 两个文件，为什么不把这些代码移过去？

2023-05-06 01:33 UTC, messixukejia commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtailV2.go
> +package opentelemetry
文件名
otlpDataToSLSProto
otlpDataToPielineGroupEvents

2023-05-06 01:33 UTC, messixukejia commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtail.go
> +		attributeMap := dataPoint.Attributes()
这个代码应该抽成函数

2023-05-06 01:33 UTC, messixukejia commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtail.go
> +		exemplar := exemplars.At(i)
exemplar2Labels先不加吧

2023-05-06 01:53 UTC, messixukejia commented on plugins/input/opentelemetry/service_oltp.go
![image](https://user-images.githubusercontent.com/13250519/236591969-424d7639-c0c2-4200-b7da-7c555b1c6106.png)
这个没有实现

要做端到端测试，能够成功写入sls。
service_otlp、service_http_server都需要测试

2023-05-06 02:07 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/decoder.go
> +	resMetrics := otlpMetricReq.Metrics().ResourceMetrics()
done

2023-05-06 02:08 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtailV2.go
> +package opentelemetry
done

2023-05-06 02:16 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtail.go
> +		attributeMap := dataPoint.Attributes()
done

2023-05-06 02:16 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtail.go
> +		exemplar := exemplars.At(i)
done

2023-05-06 03:21 UTC, linrunqi08 requested changes

2023-05-06 03:21 UTC, linrunqi08 commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtail.go
> +		if (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9') || b == '_' || b == ':' {
这个逻辑抽一个公共的函数比较好

2023-05-06 03:21 UTC, linrunqi08 commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtail.go
> +			logs = append(logs, newMetricLogFromRaw(name+"_sum", labels, int64(dataPoint.Timestamp()), dataPoint.Sum()))
"_sum","_min","_max"等等都抽成const吧

2023-05-08 05:55 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/decoder.go
> +		err = errors.New("Invalid ContentType: " + req.Header.Get("Content-Type"))
done

2023-05-08 06:13 UTC, Takuka0311 commented on pkg/protocol/decoder/opentelemetry/otlpDataToILogtail.go
> +			logs = append(logs, newMetricLogFromRaw(name+"_sum", labels, int64(dataPoint.Timestamp()), dataPoint.Sum()))
done

2023-05-15 05:00 UTC, linrunqi08 approved these changes

2023-05-15 08:09 UTC, qiansheng91 approved these changes

2023-05-16 05:36 UTC, messixukejia approved these changes

2023-05-16 12:32 UTC, merged