add tags to profile log
alibaba/ilogtail pull request #840
Opened 2023-05-09 08:36 UTC by linrunqi08

2023-05-10 12:22 UTC, yyuuttaaoo requested changes

2023-05-10 12:22 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
> +        LogStoreStatistic* statistic;
初始化为null

2023-05-10 12:22 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
> +        if (filename.size() == (size_t)0) {
这个为啥不用empty？

2023-05-10 12:22 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
> +        LogStoreStatistic* statistic;
初始化为null

2023-05-10 12:22 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
> +        if (filename.size() == (size_t)0) {
empty

2023-05-10 12:22 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
>      if (filename.size() > (size_t)0) {
这个也改成!empty()吧

2023-05-10 12:22 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
>      if (filename.size() > (size_t)0) {
!empty()

2023-05-10 12:22 UTC, yyuuttaaoo commented on core/profiler/LogFileProfiler.cpp
> +        if (filename.size() == (size_t)0) {
empty

2023-05-10 13:18 UTC, messixukejia commented on core/profiler/LogFileProfiler.cpp
> +            //logTagPtr = logGroup.add_logtags();
不需要的代码删掉

2023-05-11 04:55 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +        LogStoreStatistic* statistic;
done

2023-05-11 04:55 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +        if (filename.size() == (size_t)0) {
done

2023-05-11 04:55 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +        LogStoreStatistic* statistic;
done

2023-05-11 04:55 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
>      if (filename.size() > (size_t)0) {
done

2023-05-11 04:55 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +        if (filename.size() == (size_t)0) {
done

2023-05-11 04:55 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +            //logTagPtr = logGroup.add_logtags();
done

2023-05-11 04:56 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +        if (filename.size() == (size_t)0) {
done

2023-05-11 04:56 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
>      if (filename.size() > (size_t)0) {
done

2023-05-11 08:06 UTC, yyuuttaaoo approved these changes

2023-05-11 08:23 UTC, merged