kubernetes add support kruise
alibaba/ilogtail pull request #878
Opened 2023-05-27 13:53 UTC by EvanLjp

2023-05-27 23:40 UTC, messixukejia requested changes

2023-05-27 23:40 UTC, messixukejia commented on go.mod
> +	github.com/openkruise/kruise-api v1.4.0
文档、changelog加下

2023-05-27 23:40 UTC, messixukejia commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
在meta这个维度，openkruise跟标准k8s是二选一 的关系还是补充关系？

2023-05-28 02:07 UTC, EvanLjp commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
补充，自定义crd，有些crd 是对标准版本的增强

2023-05-28 13:13 UTC, messixukejia commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
EnableOpenKruise是不是设置成扩展的字符串数组更好些，防止后面还增加其他扩展。

2023-05-29 06:58 UTC, yyuuttaaoo commented on plugins/input/kubernetesmeta/optional_kruise.go
文件名为啥叫optional？不应该叫open kruise？即使是必选、可选不应该体现到文件名上，应该是代码逻辑而已。

2023-05-29 07:11 UTC, yyuuttaaoo commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
潜在需要扩展的似乎不算太多，如KubeSphere、Argo、KubeFlow这些比较热门的不知道是否后面有必要加

2023-05-29 08:49 UTC, messixukejia commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
这里已经列举了三个了，感觉是得考虑下后续的扩展性。不能每个都加一个enable开关

2023-05-30 02:01 UTC, EvanLjp commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
这个只是目前的方案，后续会提供一个hpa 资源加载，可以cover 所有hpa 模式资源

2023-05-30 02:02 UTC, EvanLjp commented on plugins/input/kubernetesmeta/optional_kruise.go
fix

2023-05-30 08:16 UTC, yyuuttaaoo approved these changes

2023-05-30 14:22 UTC, messixukejia commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
后面怎么扩展？EnableOpenKruise这个参数加了也就没法去掉了，还是得考虑好未来怎么发展

2023-05-31 01:34 UTC, EvanLjp commented on plugins/input/kubernetesmeta/input_kubernetes_meta.go
> +	EnableOpenKruise       bool
1. 默认是关的，后面我们也不会随意加crd 资源
2. 目前提供Deployment、Deamonset、等很多标准资源，后续会新增一个资源叫hpa ，这个可以更有普适性，很多crd 目的是增强动态扩缩容能力，这个是更下层的标准，所以仅仅会支持这个标准

2023-05-31 02:15 UTC, messixukejia approved these changes

2023-05-31 02:39 UTC, merged