support send medata to config server
alibaba/ilogtail pull request #885
Opened 2023-05-30 03:57 UTC by dragonYang200

- 新增支持火山top网关加签算法BytedanceSign.h/BytedanceSign.cpp
- 新增元数据上报接口
- 心跳上报接口新增agent_machine_id字段
- 新增ConfigServiceClientBase基类，用以扩展字节火山configServer api调用接口

2023-05-30 06:15 UTC, Takuka0311 commented on core/config_manager/BytedanceConfigService.cpp
> +		sdk::AsynRequest request(sdk::HTTP_POST, configServerAddress.host, configServerAddress.port, "", "Action=SendMetadata&Version=2018-08-01", httpHeader, reqBody, INT32_FLAG(sls_client_send_timeout),
如果要实现启动时发送metadata，ConfigServer那边也需要修改，新增对应的接口

2023-05-30 06:20 UTC, dragonYang200 commented on config_server/protocol/agent.proto
> +message MetadataRequest {
当时跟yutao他们对的结论是原heartbeat接口就先不动了，新增一个metadata接口，因为metadata这现在就火山上需要使用

2023-05-30 06:40 UTC, dragonYang200 commented on core/common/LogtailCommonFlags.h
> +DECLARE_FLAG_INT32(config_update_interval);
在LogtailCommonFlags.h中声明的目的是为了在BytedanceConfigService.cpp中也能使用INT32_FLAG(sls_client_send_timeout)这个变量。一开始没有在LogtailCommonFlags.h中声明，BytedanceConfigService.cpp中使用编译失败了

2023-05-30 06:43 UTC, dragonYang200 commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mServiceRoleUri, confJson, "service_role_uri", "SERVICE_ROLE_URI");
ok

2023-05-30 06:43 UTC, liuhaoyang requested changes

2023-05-30 06:43 UTC, liuhaoyang commented on core/config_manager/ConfigManager.cpp
> +        this->mConfigServiceClient = new BytedanceConfigServiceClient();
不能使用Bytedance，需要使用 volce

2023-05-30 06:45 UTC, dragonYang200 commented on core/config_manager/BytedanceConfigService.cpp
> +		sdk::AsynRequest request(sdk::HTTP_POST, configServerAddress.host, configServerAddress.port, "", "Action=SendMetadata&Version=2018-08-01", httpHeader, reqBody, INT32_FLAG(sls_client_send_timeout),
configserver火山这边是另外实现的一套，未使用ilogtail的社区版本，就没有加

2023-05-30 06:52 UTC, dragonYang200 commented on core/config_manager/ConfigManager.cpp
> +        this->mConfigServiceClient = new BytedanceConfigServiceClient();
ok，把bytedance字样都改一下

2023-05-30 08:25 UTC, yyuuttaaoo requested changes

2023-05-30 08:27 UTC, yyuuttaaoo commented on core/config_manager/ConfigManager.h
> +class ConfigServiceClient: public ConfigServiceClientBase {
把这个抽取到独立文件和VolceConfigService并列是否结构更好

2023-05-31 03:29 UTC, dragonYang200 commented on config_server/protocol/agent.proto
> +    string agent_id = 2;                        // Required, Agent's instance unique identification, it will be changed when restart
对的。有2点不确定的地方，所以heartbeat接口先没改，只改了火山现在需要的metadata接口：
- configserver中创建group等操作是用agent_id还是agent_session_id，两者的定位是什么（火山config server当前是使用固定的id去管理agent的升级和创建group等操作）
- 固定id的默认生成方式（火山现在策略是根据hostname+ip+安装路径生成）

2023-05-31 03:41 UTC, Takuka0311 commented on config_server/protocol/agent.proto
> +    string agent_id = 2;                        // Required, Agent's instance unique identification, it will be changed when restart
configserver的group管理仅与logtail的tag有关，和id无关

2023-05-31 03:54 UTC, dragonYang200 commented on config_server/protocol/agent.proto
> +    string agent_id = 2;                        // Required, Agent's instance unique identification, it will be changed when restart
如果把agent_id定义为一个不变的ID，agent_session_id定义为可变的（每次重启发生变化）。configserver是使用agent_id还是agent_session_id当作key进行存储

2023-05-31 03:57 UTC, Takuka0311 commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mEnvironmentCategory, confJson, "environment_category", "ENVIROMENT_CATEGORY");
这个是忘记移到AppConfig了吗

2023-05-31 03:57 UTC, Takuka0311 commented on core/config_manager/ConfigManager.cpp
> +#include "sdk/VolcengineSign.h"
sdk/VolcengineSign.h好像不需要加在这里

2023-05-31 04:06 UTC, dragonYang200 commented on core/config_manager/ConfigManager.cpp
> +#include "sdk/VolcengineSign.h"
yes，有些多余依赖忘记删掉了，我统一处理下

2023-05-31 04:08 UTC, dragonYang200 commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mEnvironmentCategory, confJson, "environment_category", "ENVIROMENT_CATEGORY");
mEnvironmentCategory是一个公共参数，用来标识一些特定环境才需要执行的代码逻辑，所以我把它保留在AppConfigBase中

2023-05-31 06:18 UTC, Takuka0311 commented on config_server/protocol/agent.proto
> +    string agent_id = 2;                        // Required, Agent's instance unique identification, it will be changed when restart
agent_id

2023-05-31 06:19 UTC, Takuka0311 commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mEnvironmentCategory, confJson, "environment_category", "ENVIROMENT_CATEGORY");
怎样的特定环境，可以举一些例子吗？

2023-05-31 06:26 UTC, dragonYang200 commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mEnvironmentCategory, confJson, "environment_category", "ENVIROMENT_CATEGORY");
比如“volcengine”，字节火山环境。通过这个字段判断来判断是使用VolcengineConfigServiceClient还是默认的ConfigServiceClient

2023-05-31 06:41 UTC, dragonYang200 commented on config_server/protocol/agent.proto
> +    string agent_id = 2;                        // Required, Agent's instance unique identification, it will be changed when restart
那sendheartbeat的时候还需要带上可变的agent_session_id不？不带的话我理解就改动agent_id的生成方式就行了？（ilogtail原有的heartbeat request我想先不改。因为用的不是同一个configserver，我这边只为新增的VolcengineConfigServiceClient定义了agent_id和agent_session_id。另外，VolcengineConfigServiceClient中heartbeat request跟原有的也不一样，我们是把绝大多数字段放到了metadata中发送一次）

2023-06-01 07:43 UTC, Takuka0311 commented on config_server/protocol/agent.proto
> +    string agent_id = 2;                        // Required, Agent's instance unique identification, it will be changed when restart
不带了吧

2023-06-02 01:46 UTC, messixukejia requested changes

2023-06-02 01:46 UTC, messixukejia commented on core/app_config/AppConfig.cpp
> +        LoadStringParameter(mGatewayService, confJson, "gateway_service", "GATEWAY_SERVICE");
下面这些参数需要确认下是否火山特有的，如果是的话建议放到VolcengineConfigServiceClient init中，因为这些都是client的内部参数

![image](https://github.com/alibaba/ilogtail/assets/13250519/a1cbafff-915e-4794-90bf-74ab89b05002)
AppConfigti提供一个解析接口，供clinet调用

2023-06-02 01:46 UTC, messixukejia commented on core/config_manager/ConfigManagerBase.h
> +    ConfigServiceClientBase() = default;
https://blog.csdn.net/iicy266/article/details/11906457

需要析构函数

2023-06-02 01:46 UTC, messixukejia commented on config_server/protocol/agent.proto
>      repeated ConfigInfo pipeline_configs = 9;   // Information about the current PIPELINE_CONFIG held by the Agent
文档、changelog

2023-06-02 01:46 UTC, messixukejia commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mEnvironmentCategory, confJson, "environment_category", "ENVIROMENT_CATEGORY");
environment_category -> config_server_provider

2023-06-02 01:52 UTC, messixukejia requested changes

2023-06-02 01:52 UTC, messixukejia commented on core/config_manager/ConfigManagerBase.h
> +    virtual void initClient() = 0;
这个有点Go风格，C++应该是私有的用private。命名统一首字母大写吧

2023-06-02 01:52 UTC, messixukejia commented on core/config_manager/ConfigManagerBase.h
> +    virtual void signHeader(sdk::AsynRequest& request) = 0;
这几个作用需要注释说明下

2023-06-02 01:52 UTC, messixukejia commented on core/config_manager/ConfigServiceClient.cpp
> +sdk::AsynRequest ConfigServiceClient::GenerateHeartBeatRequest(const AppConfig::ConfigServerAddress& configServerAddress, const std::string requestId) {
这些函数都是平移过来的？有逻辑改动吗

2023-06-02 03:12 UTC, dragonYang200 commented on core/config_manager/ConfigManagerBase.h
> +    virtual void initClient() = 0;
私有的用private -> 私有的用小写吧？

2023-06-02 03:13 UTC, dragonYang200 commented on core/config_manager/ConfigServiceClient.cpp
> +sdk::AsynRequest ConfigServiceClient::GenerateHeartBeatRequest(const AppConfig::ConfigServerAddress& configServerAddress, const std::string requestId) {
对的，平移过来的。request的设置没有变化

2023-06-02 03:39 UTC, dragonYang200 commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mEnvironmentCategory, confJson, "environment_category", "ENVIROMENT_CATEGORY");
我是想着以后可能还会有些特殊的逻辑需要用到一个参数配置来控制，所以没有把它命名成跟configserver相关的。

2023-06-02 06:11 UTC, dragonYang200 commented on core/app_config/AppConfig.cpp
> +        LoadStringParameter(mGatewayService, confJson, "gateway_service", "GATEWAY_SERVICE");
读取ilogtail_config.json文件内容需要在GetStringParameter这个接口里面额外额外实现吗？还是在LoadAppConfig的时候用一个变量将ilogtail_config.json文件内容保存下来

2023-06-03 02:34 UTC, messixukejia requested changes

2023-06-03 02:34 UTC, messixukejia commented on core/app_config/AppConfigBase.cpp
> +    LoadStringParameter(mEnvironmentCategory, confJson, "environment_category", "ENVIROMENT_CATEGORY");
base里面不能加太特殊的逻辑。
config_server_provider 意思是跟管控相关的提供者，可以用来区分管控相关的内容，并不仅限于configserver。

2023-06-03 02:34 UTC, messixukejia commented on core/config_manager/ConfigManager.cpp
> +                mConfigServiceClient->SignHeader(request);
SignHeader FlushCredential 为什么对异常的处理方式不一样?

2026-04-27 07:14 UTC, Takuka0311 commented
经百炼自动化审查后，按「重复或已被替代」关闭本项。

本 PR 旨在为火山引擎环境扩展 ConfigServer 客户端与元数据上报，但自 2023 年 6 月起已停滞且存在合并冲突。当前 ConfigServer 管控链路已全面演进至 V2 协议架构（#1793 已合并），且 V2 Provider 扩展支持正由 #1710 专项推进。本 PR 基于旧版架构的实现已被新方案替代，审查反馈中的架构调整与 C++ 规范问题亦未解决，故予以关闭。.

最佳落地路径：

建议关注或参与 #1710（ConfigServer V2 Provider 支持）的后续开发。若火山引擎集成仍需合入，请基于 V2 架构与最新 main 分支重新实现，并将环境特有逻辑封装于独立 Provider/Client 实现中，避免侵入核心 AppConfigBase。.

已核对内容：

- **superseded_by_v2_architecture:** ConfigServer 管控协议已升级至 V2（#1793 已合并），V2 Provider 扩展支持正由 #1710 推进。本 PR 基于旧版架构的 VolcengineConfigServiceClient 实现已被新方案替代。. ([`config_server/protocol/agent.proto`](https://github.com/alibaba/loongcollector/blob/a7bb70befb2d/config_server/protocol/agent.proto), [a7bb70befb2d](https://github.com/alibaba/loongcollector/commit/a7bb70befb2d))
- **stale_and_conflicted:** 本 PR 最后提交于 2023-06-03，GitHub 显示 mergeable: false，存在合并冲突且长期未更新。. ([eb1defc996bf](https://github.com/alibaba/loongcollector/commit/eb1defc996bf))
- **unresolved_architectural_feedback:** 代码审查指出火山特有参数应移至 Client 内部、需规范 C++ 命名与析构、ConfigServiceClientBase 不应包含特殊逻辑等架构问题，作者未提交后续修复。. ([`core/config_manager/VolcengineConfigServiceClient.h`](https://github.com/alibaba/loongcollector/blob/eb1defc996bf/core/config_manager/VolcengineConfigServiceClient.h), [eb1defc996bf](https://github.com/alibaba/loongcollector/commit/eb1defc996bf))

后续讨论请以已链接的规范工单为准。

百炼审查备注：模型 qwen3.6-max-preview；对照提交 [7099f790b8a3](https://github.com/alibaba/loongcollector/commit/7099f790b8a38e6bf00b30a2a49b54a230791577)。

<!-- loongsweeper-review item=885 -->

2026-05-02 14:59 UTC, closed without merging