user_contrib
alibaba/ilogtail pull request #888
Opened 2023-05-30 22:44 UTC by messixukejia

2023-06-04 10:34 UTC, yyuuttaaoo requested changes

2023-06-04 10:34 UTC, yyuuttaaoo commented on example_config/user_contrib/linux-bash-history.md
> +为了适配 iLogtail 文件采集的机制，需要在 .bash_profile 中做如下配置：
如果要全局生效，一个方式是在/etc/profile.d中创建一个.sh文件，比如
sudo vi /etc/profile.d/bash_history.sh

2023-06-04 10:34 UTC, yyuuttaaoo commented on example_config/user_contrib/linux-bash-history.md
> +2023-06-03 22:51:49 {"__tag__:__path__":"/root/.bash_history","cmd":"cat user_log_config.json","__time__":"1685803902"}
这个建议格式化一下，示例主要目的是一眼能看清json字段，倒并不是一定要和输出一模一样。

2023-06-04 15:40 UTC, yyuuttaaoo commented on example_config/user_contrib/linux-bash-history.md
> +    LogPath: /root/
只记录root的吗？是否需要再增加一个/home/*/

2023-06-05 01:26 UTC, messixukejia commented on example_config/user_contrib/linux-bash-history.md
> +    LogPath: /root/
下面增加了一段说明，用户根据情况自行添加吧。后面支持多路径了，这里再改下。

2023-06-05 07:15 UTC, henryzhx8 commented
样例文件命名规范是怎样的？看现在的命名是“系统-文件位置-类型”？感觉这样不方便找

2023-06-05 09:15 UTC, Takuka0311 commented on plugins/input/debugfile/input_debug_file.go
> +	collector.AddData(nil, log)
这里改成多行日志会对plugin_main的file to file 测试有影响，那边用的是这个插件

2023-06-05 12:05 UTC, messixukejia commented on plugins/input/debugfile/input_debug_file.go
> +	collector.AddData(nil, log)
测试限定行数吧。要不然多行就失效了。

2023-06-05 14:45 UTC, yyuuttaaoo approved these changes

2023-06-06 01:06 UTC, messixukejia commented
> 样例文件命名规范是怎样的？看现在的命名是“系统-文件位置-类型”？感觉这样不方便找

这个等积攒一批后调整下吧，现在样例太少。

2023-06-06 01:08 UTC, Takuka0311 approved these changes

2023-06-07 06:41 UTC, merged