fix shennong log key
alibaba/ilogtail pull request #905
Opened 2023-06-05 14:26 UTC by linrunqi08

之前profile的日志key为projectName + "_" + category + "_" + filename，如果用户有两个采集配置采集同一个文件，那么profile数据始终会显示第一个采集配置的名字，造成信息展示错误

2023-06-05 23:19 UTC, messixukejia requested changes

2023-06-05 23:19 UTC, messixukejia commented on core/profiler/LogFileProfiler.cpp
> +    string key = projectName + "_" + category + "_" + configName + "_" + filename;
以后合代码增加下原因描述

2023-06-07 01:40 UTC, linrunqi08 commented on core/profiler/LogFileProfiler.cpp
> +    string key = projectName + "_" + category + "_" + configName + "_" + filename;
done

2023-06-07 02:08 UTC, messixukejia approved these changes

2023-06-07 06:21 UTC, merged