fix static container
alibaba/ilogtail pull request #906
Opened 2023-06-05 15:00 UTC by linrunqi08

2023-06-06 03:52 UTC, EvanLjp approved these changes
LGTM

2023-06-06 04:32 UTC, yyuuttaaoo requested changes

2023-06-06 04:32 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +	if forceFlush || changed {
加一下为什么要这么干多注释

2023-06-06 04:32 UTC, yyuuttaaoo commented on pkg/helper/docker_center_test.go
> +		dc.updateContainer("c1", newContainer("c1", "normalContainer", normalContainerLabels2))
这个测试想说明什么？

2023-06-07 06:25 UTC, yyuuttaaoo approved these changes

2023-06-07 06:26 UTC, merged