Support V1 DataType in GO
alibaba/ilogtail pull request #908
Opened 2023-06-06 06:47 UTC by EvanLjp

2023-07-09 13:48 UTC, messixukejia requested changes

2023-07-09 13:48 UTC, messixukejia commented on core/plugin/LogtailPluginAdapter.cpp
> +                    int shardHashSize,
cgo接口变动要慎重些，尽早找余韬评估下。

2023-07-09 13:48 UTC, messixukejia commented on plugins/input/opentelemetry/service_oltp.go
> +func (s *Server) GetDataType() pipeline.DataType {
这个实现是有问题的，input插件并不是单一的类型。

这种新引入场景的改动，建议一起先设计讨论下再开发吧。

2023-07-10 02:03 UTC, yyuuttaaoo commented on core/sdk/Client.cpp
> +    void Client::SetOpensource(const bool opensource) {
这里是做什么的？

2023-08-08 12:21 UTC, messixukejia commented on core/sender/Sender.cpp
> +    LOG_INFO(sLogger, ("send failed, error code", errorCode)("error msg", errorMessage)("retry times", mDataPtr->mSendRetryTimes));
debug

2023-08-08 12:21 UTC, messixukejia commented on core/common/LogstoreSenderQueue.h
> +#include "Config.h"
changelog

2023-08-08 12:21 UTC, messixukejia commented on core/sender/Sender.cpp
> +        }else if (hashKey.empty()) {
}else 加空格

2023-08-08 12:21 UTC, messixukejia commented on core/sender/Sender.cpp
> +void MetricsSendClosure::OnFail(sdk::Response* response, const string& errorCode, const string& errorMessage) {
SendClosure::OnFail 这两个函数还是重复度极高，能合成一个吗

2023-08-08 12:21 UTC, messixukejia commented on core/plugin/LogtailPluginAdapter.cpp
> +    return gAdapterSendPbFun(configName, configNameSize, logstore, logstoreSize, pbBuffer, pbSize, lines,dataType);
datatype是不是要删掉

2023-08-08 12:41 UTC, yyuuttaaoo commented on core/config_manager/ConfigManagerBase.cpp
> +        LOG_ERROR(sLogger, ("not supported log type, use default log telemetry type", telemetryType));
不致命的用WARNING

2023-08-08 12:41 UTC, yyuuttaaoo commented on core/sdk/CurlAsynInstance.cpp
> +            if (request->mCallBack->mHTTPMessage.statusCode ==401) {
401也是LOGE_INTERNAL_SERVER_ERROR？

2023-08-08 12:41 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> +        if (sendToMetricStore){
format code

2023-08-08 15:20 UTC, EvanLjp commented on core/sender/Sender.cpp
> +        if (sendToMetricStore){
fixed

2023-08-09 06:36 UTC, henryzhx8 approved these changes

2023-09-19 03:33 UTC, yyuuttaaoo requested changes

2023-09-19 03:33 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> +        operation = METRICSTORE_CHANGE_LOGSOTER;
拼写修正一下

2023-09-19 03:33 UTC, yyuuttaaoo commented on core/sender/Sender.cpp
> +            mDataPtr->mTelemetryType = sls_logs::SLS_TELEMETRY_TYPE_LOG;
这个后面我记得好像服务端都叫XXX_LOGS和XXX_METRICS了？确认统一一下

2023-09-25 02:54 UTC, yyuuttaaoo approved these changes

2023-09-25 03:16 UTC, messixukejia commented on core/sender/Sender.cpp
> +        case METRICSTORE_CHANGE_LOGSTORE:
后端不具备时，所有请求会发送两次。等后端发差不多了，再带入logtail版本吧。

2023-09-25 03:16 UTC, messixukejia approved these changes

2024-09-01 13:11 UTC, closed without merging