fix too long log split alarm
alibaba/ilogtail pull request #915
Opened 2023-06-08 05:39 UTC by Abingcbc

超长日志被截断可以分为两种情况：
* 单行：e.g. xxxxxx。
在 ReadUTF8 中，`moreData` 为 true，`nBytes` 为 0。在 ReadGBK 中，`moreData` 为 true，`readCharCount` 为 0。
* 多行：e.g. Begin Reg\nxxxx\nxxxxx
在 ReadUTF8 中，`moreData` 为 true，`readCharCount` 为 0（因为之前的日志被 `LastMatchedLine` 截断了，因此，如果需要匹配BeginReg，那么一定是在开头，所以 `nBytes` 为 0。）
在 ReadGBK 中，`moreData` 为 true，`resultCharCount` 为 0。

2023-06-08 15:47 UTC, yyuuttaaoo requested changes

2023-06-09 07:58 UTC, Abingcbc commented on core/profiler/LogtailAlarm.h
> +    LOG_TOO_LONG_SPLIT_ALARM = 65
done

2023-06-09 07:58 UTC, Abingcbc commented on core/reader/LogFileReader.cpp
> +        LOG_WARNING(sLogger, ("Log is too long and is splitted at position", mLastFilePos + nbytes));
done

2023-06-12 08:51 UTC, yyuuttaaoo approved these changes

2023-06-12 08:51 UTC, merged