Support to collect cmd output： input_command(exec shell script from scriptcontent)
alibaba/ilogtail pull request #925
Opened 2023-06-14 04:03 UTC by didachuxing

# Command 插件
## 参数
```
ScriptType    string //脚本类型, bash, shell
User          string //执行的用户
ScriptContent string //脚本内容 PlainText|Base64  两种格式
ContentType   string //指定脚本格式  PlainText|Base64
LineSplitSep  string //行分隔符
ScriptDataDir string //执行脚本的存放目录
//脚本执行后输出的格式
//sls_metrics
//json 暂不支持
//prometheus 暂不支持
OutputDataType    string //目前先支持sls_metrics格式
ExecScriptTimeOut int    //单位:毫秒 执行一次脚本的超时时间， 不超过collect的采集频率,超时后会通知context.Alarm@todo 
IntervalMs        int    //单位:毫秒 collect触发频率  单位毫秒@todo
```
## 默认参数
```
pluginName              = "metric_command"
defaultContent          = `echo -e "__labels__:hostname#\$#idc_cluster_env_name|ip#\$#ip_address    __value__:0  __name__:metric_command_example"`
defaultScriptType       = "Bash"
defaultUser             = "nobody"
defaultContentType      = "PlainText"
defaultLineSplitSep     = `\n`
defaultOutputDataType   = SlsMetricDataType
defaultScirptDataDir    = "/workspaces/ilogtail/scriptStorage/"
defaultIntervalMs       = 30000 //ms 30s
defaltExecScriptTimeOut = 3000  //单位ms 设置为3秒超时
```

## 脚本输出格式 
### sls_metrics
格式举例： 
```
# 这是一个注释
#  __value__:0  __name__:metric_command_example_without_labels
__labels__:b#$#2|a#$#1   __value__:0.0  __name__:metric_command_example  
__value__:0  __name__:metric_command_example_without_labels 

```
## 单元测试用例
1. TestCommandTestInit 测试参数初始化
2. TestCommandTestCollect 测试脚本内容为PlainText格式的执行和采集
3. TestCommandTestCollecetUserBase64  测试脚本内容为Base64格式的执行和采集
4. TestCommandTestCollecetUserBase64WithTimeout  基于测试脚本超时时间的测试

2023-06-14 04:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=925) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=925) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=925) it.</sub>

2023-07-05 01:17 UTC, messixukejia requested changes

2023-07-05 01:17 UTC, messixukejia commented on docs/cn/data-pipeline/input/metric-command.md
> +`metric_command` `metric_command`插件可以通过配置脚本内容，在agent机器上生成可执行的脚本，并通过指定的`cmdpath` 执行该脚本，插件会从脚本执行后`stdout`获得内容进行解析，从而获取脚本内容执行后的信息。
插件名看看怎么改下 @linrunqi08

2023-07-07 02:17 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +		return false, fmt.Errorf("not support ExecScriptTimeOut > IntervalMs(脚本执行时间不能大于采集的频率)")
取最小值生效

2023-07-07 02:18 UTC, linrunqi08 commented on docs/cn/data-pipeline/input/metric-command.md
> +| ScriptDataDir |  String | 否 | 脚本内容在机器上会被存储为脚本，需要指定存储目录 默认为ilogtail的目录下|
这个默认是logtail的checkpoint目录，会添加一个子目录：scripts

2023-07-07 02:19 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +		//return false, fmt.Errorf("exec command not support user root")
需要打开

2023-07-07 02:35 UTC, linrunqi08 commented on docs/cn/data-pipeline/input/metric-command.md
> +`metric_command` `metric_command`插件可以通过配置脚本内容，在agent机器上生成可执行的脚本，并通过指定的`cmdpath` 执行该脚本，插件会从脚本执行后`stdout`获得内容进行解析，从而获取脚本内容执行后的信息。
插件名就叫input_command吧，init的时候，插件list新增定义为pipeline.CronInputs

2023-07-10 08:29 UTC, quzard commented on docs/cn/data-pipeline/input/metric-command.md
> +| ScriptDataDir |  String | 否 | 脚本内容在机器上会被存储为脚本，需要指定存储目录 默认为ilogtail的目录下|
需要强调ScriptDataDir不能存在空格

2023-07-13 06:10 UTC, quzard commented on plugins/input/command/command_script_storage.go
> +	cmd.SysProcAttr.Credential = &syscall.Credential{Uid: uint32(uid), Gid: uint32(gid)}
这个操作需要root权限才能运行成功，需要调研其他的实现方法

2023-07-17 11:33 UTC, linrunqi08 commented on docs/cn/data-pipeline/input/input-command.md
> +| ScriptDataDir       | String   | 否    | 存储脚本的目录路径，脚本在机器上会被存储为文件，指定存储目录时不能包含空格，默认为ilogtail的目录下，存储脚本的文件名为配置名的base64。                                                                              |
这个参数不要了，我们不去其他目录进行写操作

2023-07-17 11:33 UTC, linrunqi08 commented on pluginmanager/logstore_config.go
> +								if _, isMetricInput := pipeline.MetricInputs[typeNameStr]; isMetricInput {
这里注释一下，pipeline.MetricInputs的命名下个pr会改掉

2023-07-17 11:33 UTC, linrunqi08 commented on plugins/input/command/command_script_storage.go
> +func GetStorage(dataDir string) *ScriptStorage {
dataDir不需要从外面制定之后，这里是不是可以简化一下

2023-07-17 11:33 UTC, linrunqi08 commented on plugins/input/command/command_script_storage.go
> +	fileName := base64.StdEncoding.EncodeToString([]byte(configName))
这里注释一下，用配置完整名字的base64作为文件名，确保一个配置只会有一个脚本

2023-07-17 11:33 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +		logger.Error(in.context.GetRuntimeContext(), "INPUT_INIT_ALARM", "init input_command error", err)
这里Alarm还是用CATEGORY_CONFIG_ALARM吧，不要自己定义了

2023-07-17 11:33 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +	stdoutStr, stderrStr, isKilled, err := RunCommandWithTimeOut(in.TimeoutMilliSeconds, in.cmdUser, in.CmdPath, in.Environments, in.scriptPath)
这里err和stderrStr的关系是什么？有err会有stderrStr吗？

2023-07-17 11:33 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +			logger.Error(in.context.GetRuntimeContext(), "INPUT_Collect_ALARM", "input_command Collect error", err)
![Uploading image.png…]()
从这里找一下吧

2023-07-17 12:16 UTC, quzard commented on plugins/input/command/input_command.go
> +	stdoutStr, stderrStr, isKilled, err := RunCommandWithTimeOut(in.TimeoutMilliSeconds, in.cmdUser, in.CmdPath, in.Environments, in.scriptPath)
有err不会有stderr，Stderr是用于存储命令执行过程中产生的标准错误输出。

2023-07-17 12:24 UTC, quzard commented on plugins/input/command/input_command.go
> +		logger.Error(in.context.GetRuntimeContext(), "INPUT_INIT_ALARM", "init input_command error", err)
看了一下，LOGTAIL_CONFIG_ALARM 比较好一点

2023-07-17 14:21 UTC, quzard commented on plugins/input/command/input_command.go
> +	stdoutStr, stderrStr, isKilled, err := RunCommandWithTimeOut(in.TimeoutMilliSeconds, in.cmdUser, in.CmdPath, in.Environments, in.scriptPath)
有err时会有stderrStr，stderrStr是命令执行过程中产生的标准错误输出。

2023-07-18 02:24 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +	stdoutStr, stderrStr, isKilled, err := RunCommandWithTimeOut(in.TimeoutMilliSeconds, in.cmdUser, in.CmdPath, in.Environments, in.scriptPath)
没有err的时候，会有stderrStr吗

2023-07-18 02:30 UTC, quzard commented on plugins/input/command/input_command.go
> +	stdoutStr, stderrStr, isKilled, err := RunCommandWithTimeOut(in.TimeoutMilliSeconds, in.cmdUser, in.CmdPath, in.Environments, in.scriptPath)
> 没有err的时候，会有stderrStr吗

会有，主要看执行的脚本会不会输出err

2023-07-18 02:31 UTC, quzard commented on plugins/input/command/input_command.go
> +			logger.Error(in.context.GetRuntimeContext(), "INPUT_Collect_ALARM", "input_command Collect error", err)
找了OBSERVER_RUNTIME_ALARM

2023-07-18 02:31 UTC, quzard commented on plugins/input/command/command_script_storage.go
> +	fileName := base64.StdEncoding.EncodeToString([]byte(configName))
已添加注释
// Use the base64-encoded full name of the configuration as the filename to ensure that each configuration will only have one script.

2023-07-18 02:32 UTC, quzard commented on plugins/input/command/command_script_storage.go
> +func GetStorage(dataDir string) *ScriptStorage {
删除了storageOnce和storageInstance，简化了一下

2023-07-18 02:33 UTC, quzard commented on pluginmanager/logstore_config.go
> +								if _, isMetricInput := pipeline.MetricInputs[typeNameStr]; isMetricInput {
已添加注释
// Load MetricInput plugin defined in pipeline.MetricInputs
// pipeline.MetricInputs will be renamed in a future version

2023-07-18 02:33 UTC, quzard commented on docs/cn/data-pipeline/input/input-command.md
> +| ScriptDataDir       | String   | 否    | 存储脚本的目录路径，脚本在机器上会被存储为文件，指定存储目录时不能包含空格，默认为ilogtail的目录下，存储脚本的文件名为配置名的base64。                                                                              |
删除了关于ScriptDataDir的逻辑和文档

2023-07-18 02:34 UTC, quzard commented on plugins/input/command/command_const.go
> +	ScriptMd5               = "script_md5"
已处理

2023-07-18 02:53 UTC, quzard commented on docs/cn/data-pipeline/input/metric-command.md
> +| CmdPath | String | 否 | 执行生成脚本的命令路径 默认:/usr/bin/sh|
现在的CmdPath是能指定任意路径的

2023-07-18 02:54 UTC, linrunqi08 commented on docs/cn/data-pipeline/input/metric-command.md
> +| CmdPath | String | 否 | 执行生成脚本的命令路径 默认:/usr/bin/sh|
这个只是填执行脚本的bin的路径

2023-07-18 02:58 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +		logger.Error(in.context.GetRuntimeContext(), "LOGTAIL_CONFIG_ALARM", "init input_command error", err)
这里还是应该是CATEGORY_CONFIG_ALARM

2023-07-18 03:03 UTC, quzard commented on plugins/input/command/input_command.go
> +		logger.Error(in.context.GetRuntimeContext(), "LOGTAIL_CONFIG_ALARM", "init input_command error", err)
已修改，添加了intErrorAlarmType和collectErrorAlarmType常量用于存储AlarmType，分别为CATEGORY_CONFIG_ALARM和OBSERVER_RUNTIME_ALARM

2023-07-18 03:08 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +			logger.Error(in.context.GetRuntimeContext(), "INPUT_Collect_ALARM", "input_command Collect error", err)
这里语义也不太对，先叫INPUT_COLLECT_ALARM吧，抽在一个公共的const文件，就叫LogtailAlarm.go。后续所有alarm都引用这里的const

2023-07-18 03:12 UTC, linrunqi08 commented on plugins/input/command/input_command.go
> +			logger.Error(in.context.GetRuntimeContext(), "INPUT_Collect_ALARM", "input_command Collect error", err)
这里具体的ALARM后面得再设计一下，你可以记下这个事情，近期做一下

2023-07-18 03:16 UTC, quzard commented on plugins/input/command/input_command.go
> +			logger.Error(in.context.GetRuntimeContext(), "INPUT_Collect_ALARM", "input_command Collect error", err)
已添加LogtailAlarm.go

2023-07-18 03:19 UTC, linrunqi08 approved these changes

2023-07-18 05:38 UTC, messixukejia approved these changes

2023-07-18 05:38 UTC, messixukejia commented on docs/cn/data-pipeline/input/input-command.md
> +| CmdPath             | String   | 否    | 执行脚本命令的路径，如果与默认路径不一致，请指定命令路径。默认路径如下：<br/>- bash: /usr/bin/bash<br/>- shell: /usr/bin/sh<br/>- python2: /usr/bin/python2<br/>- python3: /usr/bin/python3 |
针对CmdPath的取值加一下校验吧，必须跟我们支持的有关。防止配一些类似rm之类的命令。

2023-07-18 05:56 UTC, quzard commented on docs/cn/data-pipeline/input/input-command.md
> +| User                | String   | 是    | 执行该脚本内容的用户， 不支持root                                                                                                                                     |
"该插件需要在root用户下使用"的原因是golang执行cmd需要fork/exec，只有root用户才有权限，所以iLogtial需要在root下使用。

该插件是在root环境下，使用User的权限执行命令。执行的命令所能接触到的文件权限收敛到User。

我修改一下这个文档，更直观一下
运行命令使用的用户名，只支持非Root用户(建议配置最小权限，只给需要关注的目录/文件rwx权限)
--


<br class="Apple-interchange-newline">

2023-07-18 05:57 UTC, quzard commented on docs/cn/data-pipeline/input/input-command.md
> +| CmdPath             | String   | 否    | 执行脚本命令的路径，如果与默认路径不一致，请指定命令路径。默认路径如下：<br/>- bash: /usr/bin/bash<br/>- shell: /usr/bin/sh<br/>- python2: /usr/bin/python2<br/>- python3: /usr/bin/python3 |
对ContentEncoding的内容做校验？

2023-07-28 08:18 UTC, merged