无法创建snapshot目录
alibaba/ilogtail pull request #945
Opened 2023-06-20 05:01 UTC by CyshallChan

#944 

如果在k8s中部署ilogtial并将`apsara_log_conf.json`文件挂载为`ConfigMap`，将导致无法创建snapshot目录。
这主要是因为原逻辑只要检测到 `apsara_log_conf.json`文件，并且配置文件中存在某些选项，就不会创建snapshot目录。现添加一个`CheckSnapshotDir()`函数，在读取`apsara_log_conf.json`文件成功后调用，主要判断snapshot目录是否存在，不存在就创建。

2023-07-27 01:51 UTC, CyshallChan commented
@messixukejia 麻烦看下这个pr

2023-07-27 02:05 UTC, yyuuttaaoo commented
> @messixukejia 麻烦看下这个pr

我看一下

2023-07-27 02:33 UTC, yyuuttaaoo requested changes

2023-07-27 02:33 UTC, yyuuttaaoo commented on core/logger/Logger.cpp
> +        CheckSnapshotDir();
是不是放到270行这个位置更好一些，一看就必然执行，函数名改为EnsureSnapshotDirExist，同时LoadAllDefaultConfigs中那段创建dir的也就不要了。

2023-07-27 02:33 UTC, yyuuttaaoo commented on core/logger/Logger.cpp
> +    if (access(dirPath.c_str(), F_OK) == 0) {
access在windows上编译不了，考虑使用core/common/FileSystemUtil.h中的CheckExistance

2023-07-27 03:33 UTC, CyshallChan commented on core/logger/Logger.cpp
> +    if (access(dirPath.c_str(), F_OK) == 0) {
@yyuuttaaoo 都改好了，你看下最新的提交吧。

2023-07-27 07:54 UTC, yyuuttaaoo commented on core/logger/Logger.cpp
> +void Logger::EnsureSnapshotDirExist(std::map<std::string, SinkConfig>& sinkCfgs) {
这个函数不应该只负责dir的创建么？怎么把sinkCfgs也混进来了，那两行应该留在原来的函数里。

2023-07-27 08:06 UTC, CyshallChan commented on core/logger/Logger.cpp
> +void Logger::EnsureSnapshotDirExist(std::map<std::string, SinkConfig>& sinkCfgs) {
`LoadAllDefaultConfigs` 函数里会根据`snapshot`的目录往`sinkCfgs`塞`ilogtail_status.LOG`和`ilogtail_profile.LOG`文件，而你前面说要把`LoadAllDefaultConfigs`函数里创建dir的代码删掉，那后续操作`sinkCfgs`代码就没办法用了，所以也就只能把操作`sinkCfgs`代码放到这里。

2023-07-27 11:47 UTC, yyuuttaaoo commented on core/logger/Logger.cpp
> +void Logger::EnsureSnapshotDirExist(std::map<std::string, SinkConfig>& sinkCfgs) {
dirPath耦合了对吧。这么说现在的做法可能不太通用，因为配置不是ilogtail生成而是挂载的，这种情况下snapshot目录也不一定就是GetProcessExecutionDir() + STRING_FLAG(logtail_snapshot_dir)了。那么此时Mkdir(dirPath)的dirPath目录似乎应该从sinkCfgs的logFilePath中读取。是否将Ensure放在281行的位置，函数接收sinkCfgs并遍历每条sinkCfg.dirPath进行Mkdir是更通用的做法。ref: std::string ParentPath(const std::string& path); in FileSystemUtil.h

2023-07-27 14:36 UTC, CyshallChan commented on core/logger/Logger.cpp
> +void Logger::EnsureSnapshotDirExist(std::map<std::string, SinkConfig>& sinkCfgs) {
已按照你的意思修改了，你在看下吧，另外解释下换成`boost::filesystem::create_directories`函数创建目录是因为`Mkdir()`函数不能递归创建目录。

2023-07-28 02:06 UTC, yyuuttaaoo approved these changes

2023-07-28 02:07 UTC, merged