feat: support nanosecond
alibaba/ilogtail pull request #952
Opened 2023-06-28 05:53 UTC by Abingcbc

2023-06-28 07:14 UTC, yyuuttaaoo requested changes

2023-06-29 12:44 UTC, yyuuttaaoo commented on pkg/protocol/decoder/opentelemetry/otlpDataToSLSProto.go
> +	timeNs := uint32(0)
这里这样做比较危险，不能确定0和不设是否完全等价

2023-06-29 12:44 UTC, yyuuttaaoo commented on plugin_main/plugin_export.go
> +	success := config.LoadGlobalConfig(jsonStr)
retcode

2023-06-29 16:17 UTC, yyuuttaaoo approved these changes

2023-06-30 01:46 UTC, messixukejia requested changes

2023-06-30 02:54 UTC, Abingcbc commented on plugin_main/plugin_export.go
> +			util.SetNetworkIdentification(config.LogtailGlobalConfig.HostIP, config.LogtailGlobalConfig.Hostname)
LoadGlobalConfig里面依赖 logger 的话，导致了循环依赖。这个函数只在这里发生了调用，所以移出来了。

2023-06-30 02:56 UTC, Abingcbc commented on core/observer/network/NetworkObserver.cpp
> +        item.set_time(ts.tv_sec);
done

2023-06-30 02:56 UTC, Abingcbc commented on core/common/TimeUtil.cpp
> +    return (preciseTimestamp * (int64_t)pow(10, toFillDigitsNum)) % 1000000000;
一共三种情况，改成switch了

2023-06-30 03:45 UTC, messixukejia commented on plugin_main/plugin_export.go
> +			util.SetNetworkIdentification(config.LogtailGlobalConfig.HostIP, config.LogtailGlobalConfig.Hostname)
注释说明下

2023-06-30 04:01 UTC, henryzhx8 requested changes

2023-07-02 06:01 UTC, messixukejia approved these changes

2023-07-02 06:32 UTC, henryzhx8 approved these changes

2023-07-02 10:53 UTC, merged