add containerd custom rootpath support
alibaba/ilogtail pull request #963
Opened 2023-06-30 09:29 UTC by gsakun

配置采集容器内文件采集异常，通过查看日志发现
```
2023-06-30 06:45:44 [WRN] [metric_docker_file.go:359] [Collect] [config#/usr/local/ilogtail/./user_yaml_config.d/test.yaml,]AlarmType:DOCKER_FILE_MATCH_ALARM       unknow error:can't find path from this container        path:/home/test-log     container:busybox   logstore:       config:config#/usr/local/ilogtail/./user_yaml_config.d/test.yaml
```

然后查看[源码](https://github.com/alibaba/ilogtail/blob/main/pkg/helper/docker_cri_adapter.go#L603)，发现containerd container rootfs查找方法是通过固定的路径查询。目前调用containerd接口也无法获取rootfs目录，所以建议添加环境变量支持用户配置自定义目录。

2023-06-30 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=963) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=963) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=963) it.</sub>

2023-07-01 15:02 UTC, yyuuttaaoo requested changes

2023-07-01 15:02 UTC, yyuuttaaoo commented on pkg/helper/docker_cri_adapter.go
> +			aDirs = append(aDirs, absPath)
顺序需要倒一下custom的在最前，否则在某些场景如K3s，多个aDirs下面可能都有rootfs目录，就找错了，指定custom也没用了。

2023-07-01 15:23 UTC, gsakun commented on pkg/helper/docker_cri_adapter.go
> +	// TODO If the containerd interface provides the absolute path to the rootfs, optimize lookupContainerRootfsAbsDir method.
如果containerd ContainerInfo接口提供rootfs的完整路径就可以，我打算再看看containerd的源码

2023-07-01 15:27 UTC, gsakun commented on pkg/helper/docker_cri_adapter.go
> +			aDirs = append(aDirs, absPath)
好的，我看一下

2023-07-04 06:06 UTC, closed without merging