feat: support multiple regex pattern in LastMatchedLine
alibaba/ilogtail pull request #978
Opened 2023-07-05 07:47 UTC by Abingcbc

1. 为 LastMatchedLine 新增了 Continue 和 End 两种正则匹配。同时，兼容了原有的多行行首正则的行为。
2. 收拢了所有逆向回退的代码，统一在 LastMatchedLine 中进行。LastMatchedLine 的语义为给定任意日志，回退掉末尾不完整的日志。

2023-07-09 10:26 UTC, messixukejia requested changes

2023-07-09 10:26 UTC, messixukejia commented on core/config/Config.cpp
>          reader->SetLogBeginRegex(STRING_DEEP_COPY(mLogBeginReg));
后面自己养成习惯，提交文档、changelog。

企业版相关特性需要后续修改官网文档。

2023-07-09 10:26 UTC, messixukejia commented on core/config_manager/ConfigYamlToJson.cpp
> +    mFileConfigMap["LogContinueRegex"] = "log_continue_reg";
这个功能需不需要针对之前的做支持？

是不是新的pipeline一起好了？

@yyuuttaaoo @henryzhx8

2023-07-09 10:26 UTC, messixukejia commented on core/reader/LogFileReader.h
> +    void SetLogContinueRegex(const std::string& reg) {
都没有调用点？

这次pr是个不完整的代码？

2023-07-12 12:09 UTC, Abingcbc commented on core/config/Config.cpp
>          reader->SetLogBeginRegex(STRING_DEEP_COPY(mLogBeginReg));
done

2023-07-12 12:23 UTC, Abingcbc commented on core/config/Config.cpp
>          reader->SetLogBeginRegex(STRING_DEEP_COPY(mLogBeginReg));
done

2023-07-16 16:35 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
>              ++rollbackLineFeedCount;
如果这里不上来就++下面计算行数会更自然一些吗？

2023-07-16 16:35 UTC, yyuuttaaoo commented on core/reader/LogFileReader.cpp
> +                            if (multiBeginIndex != begIndex && mUnmatch == "append") {
prepend？

2023-07-18 03:27 UTC, Abingcbc commented on core/config_manager/ConfigYamlToJson.cpp
> +    mFileConfigMap["LogContinueRegex"] = "log_continue_reg";
1. 之前的功能相当于现在的子集，都是兼容的。
2. 功能合入后会先在开源版本中使用。商业版会和v2的配置一起上线，v1的暂时不支持。

2023-07-18 05:28 UTC, messixukejia requested changes

2023-07-18 05:28 UTC, messixukejia commented on core/reader/LogFileReader.cpp
> +                    if (!IsMultiLine()) {
这个代码可以参考状态机模式重构下。

2023-07-18 05:28 UTC, messixukejia commented on core/reader/LogFileReader.cpp
> +            if (mLogContinueRegPtr != NULL && BoostRegexMatch(buffer + lineBegin, endPs - lineBegin, *mLogContinueRegPtr, exception)) {
![image](https://github.com/alibaba/ilogtail/assets/13250519/23fac56e-a8f0-43a3-8de3-5678a89d5345)
这个实现嵌套过于深了。可以考虑更改下实现，例如外层循环改成行，可能会更清晰些。 具体可以找@yyuuttaaoo交流下。

2023-07-18 05:28 UTC, messixukejia commented on core/reader/LogFileReader.cpp
>  int32_t LogFileReader::LastMatchedLine(char* buffer, int32_t size, int32_t& rollbackLineFeedCount) {
这些函数都比较复杂，最好注释（类似LogFileReader::GetRawData）举例说明下各场景的输入输出。

2023-07-18 05:39 UTC, Abingcbc commented on core/reader/LogFileReader.cpp
> +                            if (multiBeginIndex != begIndex && mUnmatch == "append") {
prepend不需要额外的操作，只需要把unmatch的日志留在缓冲区里。下次匹配到一个完整日志时，会自动将其一起取出，拼接到一起。

2023-07-18 06:36 UTC, Abingcbc commented on core/reader/LogFileReader.cpp
> +    mUnmatch = "discard";
改成了使用枚举，在SetLogMultilinePolicy中，由用户的配置字符串转为枚举类型。

2023-07-18 07:13 UTC, Abingcbc commented on core/reader/LogFileReader.cpp
>  int32_t LogFileReader::LastMatchedLine(char* buffer, int32_t size, int32_t& rollbackLineFeedCount) {
所有场景的输入输出都在单测里面，注释里补充了一些期望的行为

2023-07-18 12:10 UTC, messixukejia commented on core/reader/LogFileReader.cpp
>  int32_t LogFileReader::LastMatchedLine(char* buffer, int32_t size, int32_t& rollbackLineFeedCount) {
ut太远了，函数功能注释可能更好些

2023-08-05 15:36 UTC, yyuuttaaoo requested changes

2023-08-05 15:36 UTC, yyuuttaaoo commented on core/unittest/reader/LastMatchedLineUnittest.cpp
> +        std::string expectMatch = LOG_BEGIN_STRING + "\n" + LOG_CONTINUE_STRING + "\n" + LOG_CONTINUE_STRING + "\n" + LOG_UNMATCH + "\n";
这个没太理解，没有下个begin不应该全部回退了么

2023-08-05 15:36 UTC, yyuuttaaoo commented on core/unittest/reader/LastMatchedLineUnittest.cpp
> +    { // case: end with unmatch
只有end pattern + discard unmatch是什么语义？与begin + discard unmatched对称吗？感觉这个组合不太成立啊？end + prepend是不是合理一些？
SetLogMultilinePolicy里的逻辑是否正确。当有begin时，默认的兼容老begin策略是begin + append吗?
感觉too long而无法split的场景，好像无法用当前的unmatched discard表示

2023-08-05 15:36 UTC, yyuuttaaoo commented on core/unittest/reader/LastMatchedLineUnittest.cpp
> +        std::string expectMatch = LOG_BEGIN_STRING + "\n" + LOG_CONTINUE_STRING + "\n" + LOG_CONTINUE_STRING + "\n" + LOG_UNMATCH + "\n";
没有end也没下一个begin为什么不是全回滚？

2023-08-20 06:38 UTC, yyuuttaaoo approved these changes

2023-08-21 02:53 UTC, messixukejia approved these changes

2023-08-21 02:53 UTC, messixukejia commented on docs/cn/data-pipeline/accelerator/regex-accelerate.md
> +- 表3:多行切分正则模式组合
![image](https://github.com/alibaba/ilogtail/assets/13250519/457d7364-4a47-4ffb-ad25-330ba5ff4d74)
应该是错位了，文档没解析好

2023-08-21 04:59 UTC, Abingcbc commented on docs/cn/data-pipeline/accelerator/regex-accelerate.md
> +- 表3:多行切分正则模式组合
已修复

2023-08-21 11:09 UTC, Takuka0311 approved these changes

2023-08-24 01:50 UTC, merged