Elasticsearch flusher 新功能特性
alibaba/ilogtail pull request #979
Opened 2023-07-05 11:04 UTC by liangry

1. 使用 bulk 接口批量发送请求
2. 支持动态索引
3. 修复后端连接错误引起的 panic

2023-07-06 01:07 UTC, messixukejia requested changes

2023-07-06 01:07 UTC, messixukejia commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +		switch res.StatusCode / 100 {
不要用除吧，用大小判断是不是更合适些？

2023-07-06 01:07 UTC, messixukejia commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +	filteredKeys := make([]string, 0, len(indexKeys))
包括下面的FormatIndex，增加下ut？

2023-07-06 01:07 UTC, messixukejia commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +		if !strings.HasPrefix(key, "+") {
注释说明下原因

2023-07-06 01:52 UTC, liangry commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +		switch res.StatusCode / 100 {
这里参考了 http flusher，我也第一次见这种用法
```
	switch response.StatusCode / 100 {
	case 2:
		return true, false, nil
	case 5:
		logger.Error(f.context.GetRuntimeContext(), "FLUSHER_FLUSH_ALARM", "http flusher write data returned error, url", req.URL.String(), "status", response.Status, "body", string(body))
		return false, true, fmt.Errorf("err status returned: %v", response.Status)
	default:
		if response.StatusCode == http.StatusUnauthorized || response.StatusCode == http.StatusForbidden {
			return false, true, fmt.Errorf("err status returned: %v", response.Status)
		}
		logger.Error(f.context.GetRuntimeContext(), "FLUSHER_FLUSH_ALARM", "http flusher write data returned error, url", req.URL.String(), "status", response.Status, "body", string(body))
		return false, false, fmt.Errorf("unexpected status returned: %v", response.Status)
	}
```

2023-07-06 02:14 UTC, shalousun commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +			ESIndex, err := fmtstr.FormatIndex(valueMap, f.Index, uint32(nowTime.Unix()))
这个地方如果发现indexKeys没有表达式key可以不用调FormatIndex，没有动态index需求的场景下性能会好一些

2023-07-06 02:18 UTC, messixukejia requested changes

2023-07-06 02:18 UTC, messixukejia commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
>  	"context"
changelog
文档
都帮忙补充下吧

2023-07-06 02:18 UTC, messixukejia commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
>  import (
请帮忙在https://github.com/alibaba/ilogtail/tree/main/example_config/user_contrib 按照这个格式增加一个使用样例吧，多谢

2023-07-06 02:29 UTC, shalousun commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
>  		Addresses: f.Addresses,
es这个config可以考虑把一些参数开放出来，现在配置过于简单了，例如重试配置

2023-07-06 03:09 UTC, shalousun commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +			buffer = append(buffer, fmt.Sprintf(`{"index": {"_index": "%s"}}`, *ESIndex))
fmt.Sprintf属于性能比较差一种，在性能要求高的地方建议换个其他方式，例如strings.Builder

2023-07-06 03:13 UTC, shalousun commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +		req := esapi.BulkRequest{
bulk这块看能不能用esutil.NewBulkIndexer来处理，主要是官方做了一些封装，逻辑会更加完善和丰富一些

2023-07-06 03:22 UTC, shalousun commented
flusher-elasticsearch.md这个文档完善下，补充下es的动态索引配置例子和规则说明，https://github.com/alibaba/ilogtail/issues/883 这里提到的配置错误也可以修正下

2023-07-10 08:11 UTC, liangry commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
>  		Addresses: f.Addresses,
配置修改可能涉及较多的条目，不如先看看效果，听听社区有哪些需求和反馈？

2023-07-10 08:13 UTC, liangry commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +			buffer = append(buffer, fmt.Sprintf(`{"index": {"_index": "%s"}}`, *ESIndex))
好的，我抽空连同其它问题一块提交

2023-07-12 02:06 UTC, liangry commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +	filteredKeys := make([]string, 0, len(indexKeys))
> 包括下面的FormatIndex，增加下ut？

现在的 unit test 是否有问题，实际没有运行的？

```
[root@1fba4b423fc4 elasticsearch]# go test -run InvalidTestConnectAndWrite
testing: warning: no tests to run
PASS
ok  	github.com/alibaba/ilogtail/plugins/flusher/elasticsearch	0.023s
[root@1fba4b423fc4 elasticsearch]# go test
testing: warning: no tests to run
PASS
ok  	github.com/alibaba/ilogtail/plugins/flusher/elasticsearch	0.022s
```

2023-07-12 03:41 UTC, liangry commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +	filteredKeys := make([]string, 0, len(indexKeys))
是否可以改用 Convey 写单元测试案例？原来的不用了

2023-07-12 12:28 UTC, messixukejia commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +	filteredKeys := make([]string, 0, len(indexKeys))
好的，麻烦改下吧。

2023-07-13 07:01 UTC, liangry commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +	filteredKeys := make([]string, 0, len(indexKeys))
> 好的，麻烦改下吧。

done

2023-07-19 06:38 UTC, henryzhx8 approved these changes

2023-07-19 11:21 UTC, shalousun approved these changes

2023-07-20 22:58 UTC, messixukejia approved these changes

2023-07-20 22:59 UTC, messixukejia commented
后面麻烦把解决的问题点下resolve吧

2023-07-21 01:27 UTC, liangry commented on plugins/flusher/elasticsearch/flusher_elasticsearch.go
> +		switch res.StatusCode / 100 {
已改回 if else 判断并返回错误

2023-07-26 09:35 UTC, merged

2023-07-27 09:38 UTC, Pefeng commented
按天动态创建索引失败。使用镜像版本: ilogtail:1.7.0
AlarmType:FLUSHER_FLUSH_ALARM   flush elasticsearch convert log fail, error:unsupported field: +yyyy.MM.dd

2023-07-27 10:11 UTC, liangry commented
> 按天动态创建索引失败。使用镜像版本: ilogtail:1.7.0 AlarmType:FLUSHER_FLUSH_ALARM flush elasticsearch convert log fail, error:unsupported field: +yyyy.MM.dd

目前需要使用开发镜像编译源代码执行