add_dockerClient_conn_test and and modified whether enabledocker
alibaba/ilogtail pull request #980
Opened 2023-07-06 09:20 UTC by gsakun

目前基础环境为k8s+containerd的模式，查看logtail_plugin.LOG发现。即便不使用docker，也会初始化dockerClient,并且多次尝试连接，错误日志如下
```
2023-07-06 08:37:02 [INF] [plugin_manager.go:120] [Init] init plugin, local env tags:[_node_name_ ihuman _node_ip_ 10.2.112.25]
2023-07-06 08:37:02 [INF] [checkpoint_manager.go:96] [Init] init checkpoint:<nil>
2023-07-06 08:37:02 [INF] [logstore_config.go:666] [loadBuiltinConfig] load built-in config statistics, config name: shennong_log_profile, logstore: logtail_plugin_profile
2023-07-06 08:37:02 [INF] [logstore_config.go:666] [loadBuiltinConfig] load built-in config alarm, config name: logtail_alarm, logstore: logtail_alarm
2023-07-06 08:37:02 [INF] [logstore_config.go:666] [loadBuiltinConfig] load built-in config container, config name: logtail_containers, logstore: logtail_containers
2023-07-06 08:37:02 [INF] [plugin_manager.go:138] [Init] loadBuiltinConfig container:
2023-07-06 08:37:02 [INF] [logstore_config.go:655] [LoadLogstoreConfig] load config:config#/usr/local/ilogtail/./user_yaml_config.d/ilogtail-path.yaml      logstore:
2023-07-06 08:37:02 [ERR] [logger.go:363] [1] AlarmType:CATCH_STANDARD_OUTPUT_ALARM     err:read |0: file already closed
2023-07-06 08:37:02 [ERR] [logger.go:363] [1] AlarmType:CATCH_STANDARD_OUTPUT_ALARM     err:read |0: file already closed
2023-07-06 08:37:02 [INF] [docker_center.go:637] [func1] [CRIRuntime] create cri-runtime client successfully
2023-07-06 08:37:02 [INF] [container_discover_controller.go:167] [Init] input:param     docker discover:true    cri discover:true   static discover:false
2023-07-06 08:37:02 [INF] [container_discover_controller.go:193] [Init] init docker center, fetch all seconds:5m0s
2023-07-06 08:37:02 [INF] [container_discover_controller.go:203] [Init] init docker center, fecth all success timeout:1h40m0s
2023-07-06 08:37:02 [INF] [container_discover_controller.go:213] [Init] init docker center, client request timeout:30s
2023-07-06 08:37:02 [INF] [container_discover_controller.go:224] [Init] init docker center, max fetchOne count per second:200
2023-07-06 08:37:02 [WRN] [docker_center.go:701] [setLastError] AlarmType:DOCKER_CENTER_ALARM   message:list container errorerror found:Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2023-07-06 08:37:02 [WRN] [docker_center.go:701] [setLastError] AlarmType:DOCKER_CENTER_ALARM   message:list container errorerror found:Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2023-07-06 08:37:02 [WRN] [docker_center.go:701] [setLastError] AlarmType:DOCKER_CENTER_ALARM   message:list container errorerror found:Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2023-07-06 08:37:02 [ERR] [container_discover_controller.go:236] [Init] AlarmType:DOCKER_CENTER_ALARM   fetch docker containers error in 3 times, close docker discover
```
查看代码，发现初始化dockerClient时并没有检查连接是否可用。并且我认为如果成功初始化了criRuntimeWrapper，就没必要初始化dockerClient了。做了些修改，麻烦查看一下

2023-07-09 15:14 UTC, yyuuttaaoo requested changes

2023-07-09 15:14 UTC, yyuuttaaoo commented on pkg/helper/docker_center.go
> +		var enableDocker = false
if !enableCriFinding 没必要，原来3者就是并行的关系，没有说非此即彼，允许在k8s节点上也装一个单机docker并采集它的日志

2023-07-09 15:14 UTC, yyuuttaaoo commented on pkg/helper/container_export.go
> +	"github.com/alibaba/ilogtail/pkg/logger"
import还原一下吧，感觉是设置不一样导致被ororder了。原来先系统 三方 自己的顺序挺好

2023-07-10 01:43 UTC, gsakun commented on pkg/helper/docker_center.go
> +		var enableDocker = false
> if !enableCriFinding 没必要，原来3者就是并行的关系，没有说非此即彼，允许在k8s节点上也装一个单机docker并采集它的日志

好的

2023-08-05 08:51 UTC, yyuuttaaoo requested changes

2023-08-08 01:47 UTC, gsakun commented on pkg/helper/container_export.go
> +	_, err = client.Ping(pingCtx)
> 

好的，我仔细看一下

2023-08-09 03:16 UTC, gsakun commented on pkg/helper/container_export.go
> +	_, err = client.Ping(pingCtx)
> 我想多问一下，低版本的docker是否测试过在Negotiate前Ping是work的？
> 
> 我又看了一下NegotiateAPIVersion的实现，里面实际上做了ping，这样的话，是不是给Negotiate加上contextwithtimeout就可以了？另外超时改为10s如何？看了一下其他withtimeout大多数都是10s
> 
> // NegotiateAPIVersion queries the API and updates the version to match the // API version. Any errors are silently ignored. If a manual override is in place, // either through the `DOCKER_API_VERSION` environment variable, or if the client // was initialized with a fixed version (`opts.WithVersion(xx)`), no negotiation // will be performed. func (cli *Client) NegotiateAPIVersion(ctx context.Context) { if !cli.manualOverride { ping, _ := cli.Ping(ctx) cli.negotiateAPIVersionPing(ping) } }

你好，我刚刚看了下。之所以Negotiate前又加了Ping是因为这个方法所有的错误都被忽略了，无法传递出来

2023-08-09 03:51 UTC, yyuuttaaoo commented on pkg/helper/container_export.go
> +	_, err = client.Ping(pingCtx)
你说的有道理，可以用NegotiateAPIVersionPing这个api替代一下，里面不重复ping了

2023-08-09 03:55 UTC, gsakun commented on pkg/helper/container_export.go
> +	_, err = client.Ping(pingCtx)
OK

2023-08-09 04:02 UTC, yyuuttaaoo approved these changes

2023-08-09 06:25 UTC, merged