[example config] Create linux-var-log-auth-sshd.md
alibaba/ilogtail pull request #989
Opened 2023-07-10 15:51 UTC by shouao

2023-07-10 15:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=989) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=989) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=989) it.</sub>

2023-07-10 23:23 UTC, messixukejia commented on example_config/user_contrib/linux-var-log-auth-sshd.md
> +[`shouao.chen`](https://github.com/shouao)
很好的例子。👍🏻

2023-07-10 23:23 UTC, messixukejia commented on example_config/user_contrib/linux-var-log-auth-sshd.md
> +  - Type: processor_regex
/var/log/auth.log 中主要包含以下几类日志：
登录事件日志：记录用户登录系统的事件，包括成功登录和失败登录。
su 命令日志：记录用户使用 su 命令切换账户的事件。
sudo 命令日志：记录用户使用 sudo 命令执行特权操作的事件。
SSH 连接日志：记录 SSH 服务的连接事件，包括成功和失败的连接。
PAM 日志：记录 PAM（Pluggable Authentication Modules）模块的事件，包括用户认证、账户管理等。
认证错误日志：记录用户认证失败的事件，包括密码错误、账户锁定等。
认证成功日志：记录用户认证成功的事件，包括密码正确、账户解锁等。

这些日志都是混在一起的。因此配一个解析规则会导致其他不符合的报错。两种思路，可以考虑下：
思路1、用通用的规则解析上述所有日志。（建议）
思路2、加过滤条件，只过滤ssh日志。参考https://ilogtail.gitbook.io/ilogtail-docs/data-pipeline/processor/processor-filter-regex

2023-07-10 23:23 UTC, messixukejia commented on example_config/user_contrib/linux-var-log-auth-sshd.md
> +  - Type: processor_regex
之前有一个空的[linux-var-log-auth.md](https://github.com/alibaba/ilogtail/blob/main/example_config/user_contrib/linux-var-log-auth.md)，如果冲突可以删掉这个。

2023-07-10 23:23 UTC, messixukejia commented on example_config/user_contrib/linux-var-log-auth-sshd.md
> +     - time
https://github.com/alibaba/ilogtail/tree/main/plugins/processor/strptime

时间建议用提取下日志时间，参考https://github.com/alibaba/ilogtail/blob/main/example_config/user_contrib/linux-bash-history.md

2023-07-13 02:16 UTC, henryzhx8 requested changes

2023-07-13 02:16 UTC, henryzhx8 commented on example_config/user_contrib/linux-var-log-auth.md
> +```
```后边加上语言类型，比如plain或yaml等

2023-07-13 02:16 UTC, henryzhx8 commented on example_config/user_contrib/linux-var-log-auth.md
> +    Topic: bash_history
这行删了

2023-07-14 02:43 UTC, henryzhx8 requested changes
conflit需要处理一下

2023-07-14 23:26 UTC, messixukejia approved these changes

2023-07-17 01:45 UTC, henryzhx8 approved these changes

2023-07-17 01:46 UTC, merged