[example config]windows-vscode-sign
alibaba/ilogtail pull request #994
Opened 2023-07-11 15:18 UTC by SuperGoodGame

2023-07-11 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/ilogtail?pullRequest=994) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/ilogtail?pullRequest=994) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/ilogtail?pullRequest=994) it.</sub>

2023-07-11 23:26 UTC, messixukejia commented on example_config/user_contrib/windows-vocode-sign.md
> +默认为打开vscode时直接输出到控制台，如果捕获需要手动操作保存到文件中。
手动操作保存到文件：方法简单介绍下？

2023-07-13 02:07 UTC, henryzhx8 requested changes

2023-07-13 02:07 UTC, henryzhx8 commented on example_config/user_contrib/windows-vocode-sign.md
> +备注：无
删去

2023-07-13 02:07 UTC, henryzhx8 commented on example_config/user_contrib/windows-vocode-sign.md
> +`.vscode_microsoft_sign`记录了用户在windows端启动vscode 中执行过程中的记录，用于在windows系统下登录windows系统，并且申请相关文件使用权限等
1. Windows，VSCode，注意专有名词大小写，以及多余的空格
2. 这句话不太通顺，没太看懂

2023-07-13 02:07 UTC, henryzhx8 commented on example_config/user_contrib/windows-vocode-sign.md
> +    Topic: bash_history
删去这个

2023-07-13 02:07 UTC, henryzhx8 commented on example_config/user_contrib/windows-vocode-sign.md
> +
删去空行

2023-07-13 02:15 UTC, henryzhx8 reviewed
CLA问题请签一下名

2023-07-18 01:39 UTC, henryzhx8 approved these changes

2023-07-18 01:40 UTC, merged