[WIP] C++ pipeline stage1: processors
alibaba/ilogtail pull request #995
Opened 2023-07-11 15:45 UTC by yyuuttaaoo

2023-07-13 05:33 UTC, henryzhx8 requested changes

2023-07-13 05:33 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +    if (!processor->Plugin()->Init(config, mContext)) {
```suggestion
    if (!processor->Init(config, mContext)) {
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/DynamicCProcessorCreator.cpp
> +    next = nullptr;
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginCreatorInterface.cpp
可以删了

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginCreatorInterface.h
> +    PluginCreatorInterface* next = nullptr;
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginCreatorInterface.h
> +    virtual bool IsDynamic() = 0;
好像没有调用点？
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginCreatorInterface.h
> +    virtual void Destroy(PluginInstance* ins);
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginCreatorInterface.h
> +    virtual PluginInstance* Create(const std::string& pluginId) = 0;
```suggestion
    virtual std::unique_ptr<PluginInstance> Create(const std::string& pluginId) = 0;
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginInstance.h
> +    PluginInstance* next = nullptr;
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginInstance.h
> +    PluginCreatorInterface* Creator() { return mCreator; }
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginInstance.h
> +    PluginInstance(const std::string& pluginId, PluginCreatorInterface* creator) : mId(pluginId), mCreator(creator) {}
```suggestion
    PluginInstance(const std::string& pluginId) : mId(pluginId) {}
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginInstance.h
> +    const std::string& Id() { return mId; }
```suggestion
    const std::string& Id() const { return mId; }
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginInstance.h
> +    std::string mId;
```suggestion
    const std::string mId;
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginRegistry.h
> +    void Destroy(PluginInstance* ins);
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginRegistry.cpp
> +}
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/ProcessorInstance.h
> +    ProcessorInterface* Plugin() { return mPlugin; };
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/ProcessorInstance.h
> +    PipelineContext mContext;
private成员？

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/ProcessorInstance.h
> +        : PluginInstance(pluginId, creator), mPlugin(plugin) {}
```suggestion
    ProcessorInstance(ProcessorInterface* plugin, const std::string& pluginId)
        : PluginInstance(pluginId), mPlugin(plugin) {}
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginRegistry.h
> +    ProcessorInstance* CreateProcessor(const std::string& name, const std::string& pluginId);
```suggestion
    std::unique_ptr<ProcessorInstance> CreateProcessor(const std::string& name, const std::string& pluginId);
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginRegistry.h
> +    enum PluginCat { INPUT_PLUGIN, PROCESSOR_PLUGIN, FLUSHER_PLUGIN };
```suggestion
    enum class PluginCat { INPUT_PLUGIN, PROCESSOR_PLUGIN, FLUSHER_PLUGIN };
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginRegistry.h
> +    PluginInstance* Create(PluginCat cat, const std::string& name, const std::string& pluginId);
这个函数我觉得可以不要了，直接createXXX做就行了，避免类型来回转
```suggestion
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginRegistry.h
> +    void LoadPlugins();
```suggestion
    void LoadPluginCreators();
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginRegistry.h
> +    void UnloadPlugins();
```suggestion
    void UnloadPluginCreators();
```

2023-07-13 05:33 UTC, henryzhx8 commented on core/plugin/PluginCreatorInterface.h
> +class PluginCreatorInterface {
接口别明写吧，后面用的地方看着很怪
```suggestion
class PluginCreator {
```

2023-07-13 05:47 UTC, henryzhx8 requested changes

2023-07-13 05:47 UTC, henryzhx8 commented on core/plugin/PluginRegistry.h
> +    std::unordered_map<PluginKey, std::shared_ptr<PluginCreatorInterface>, PluginKeyHash> mPluginDict;
```suggestion
    size_t hasher(const PluginKey& obj) const {
        return std::hash<int>()(obj.cat) ^ std::hash<std::string>()(obj.name);
    }
    std::unordered_map<PluginKey, std::shared_ptr<PluginCreatorInterface>, decltype(hasher)*> mPluginDict;
```

2023-07-17 07:53 UTC, yyuuttaaoo commented on core/plugin/PluginCreatorInterface.h
> +    virtual bool IsDynamic() = 0;
暂时先留着

2023-07-17 08:48 UTC, yyuuttaaoo commented on core/plugin/PluginRegistry.h
> +    PluginInstance* Create(PluginCat cat, const std::string& name, const std::string& pluginId);
这个在内部做转换用

2023-07-17 12:54 UTC, yyuuttaaoo commented on core/plugin/PluginRegistry.h
> +    void UnloadPlugins();
暂时不动

2023-08-11 07:10 UTC, henryzhx8 reviewed
统一一下吧，入参unique_ptr应该都是右值引用，shared_ptr如果要增加引用计数用值传递，否则用左值引用

2023-08-11 09:01 UTC, henryzhx8 requested changes

2023-08-11 23:15 UTC, messixukejia commented on core/models/PipelineEvent.cpp
> +const std::string& PipelineEventTypeToString(PipelineEventType t) {
这个函数还用到了static，目的是？

2023-08-11 23:15 UTC, messixukejia commented on core/processor/ProcessorParseTimestampNative.cpp
> +            if (GetContext().GetAlarm().IsLowLevelAlarmValid()) {
bool ProcessorParseTimestampNative::ProcessEvent(StringView logPath, PipelineEventPtr& e, StringView& timeStrCache) {
    if (!e.Is<LogEvent>()) {
        return true;
    }

插件属于日志还是指标，这个放到插件初始化里作为一个属性吧。在函数里加一个if，后面开发很容易写漏了

2023-08-11 23:15 UTC, messixukejia commented on core/processor/ProcessorSplitLogStringNative.cpp
> +    mSplitKey = DEFAULT_CONTENT_KEY;
这个不支持设置？

2023-08-12 15:03 UTC, yyuuttaaoo commented on core/models/LogEvent.h
>      LogContents contents;
其实是故意没有抄过来，有必要的时候加就好了，现在还不太理解功能和其必要性。少抄也是为了避免当前代码有性能问题，这里又多构造了好多string

2023-08-12 15:04 UTC, yyuuttaaoo commented on core/models/PipelineEvent.cpp
> +const std::string& PipelineEventTypeToString(PipelineEventType t) {
返回值不重复构造。

2023-08-12 15:06 UTC, yyuuttaaoo commented on core/processor/ProcessorSplitLogStringNative.cpp
> +    mSplitKey = DEFAULT_CONTENT_KEY;
当前不支持，因为config还没改。现在基本有雏形了，后面加也就方便了。

2023-08-12 23:18 UTC, messixukejia commented on core/models/LogEvent.h
>      LogContents contents;
Offset是可以家过来的吧

2023-08-13 08:33 UTC, yyuuttaaoo commented on core/models/LogEvent.h
>      static std::unique_ptr<LogEvent> CreateEvent(std::shared_ptr<SourceBuffer>& sb);
因为这里不想隐藏细节，返回的不希望是基类unique_ptr，另外也是和go那边形式类似吧。这个后面看看是不是还可以优化一下，特别是CreateEvent是不是可以有个Arena什么，毕竟反复创建Contents的Map还挺耗时的。

2023-08-13 08:36 UTC, yyuuttaaoo commented on core/models/LogEvent.h
>      LogContents& ModifiableContents() { return contents; }
目前没用到，先删了

2023-08-13 08:41 UTC, yyuuttaaoo commented on core/models/LogEvent.h
> +    void SetContentNoCopy(const StringBuffer& key, const StringBuffer& val);
这个有用

2023-08-13 08:49 UTC, yyuuttaaoo commented on core/models/LogEvent.h
>      void SetContentNoCopy(const StringView& key, const StringView& val);
将SetContent函数和SetContentNoCopy区分开的目的就是让用户在没理解如何使用时都用SetContent。而没有提供仅复制value而不复制key的函数是因为这样类似函数太多了。

2023-08-13 09:01 UTC, yyuuttaaoo commented on core/models/PipelineEvent.h
>  enum PipelineEventType { VOID_EVENT_TYPE = 0, LOG_EVENT_TYPE = 1, METRIC_EVENT_TYPE = 2, SPAN_EVENT_TYPE = 3 };
升级后GCC版本后再改，现在转int费劲

2023-08-13 09:06 UTC, yyuuttaaoo commented on core/models/PipelineEvent.h
>  class PipelineGroupEvents;
当前代码都放在最后，所以不是大问题，继续follow

2023-08-13 09:07 UTC, yyuuttaaoo commented on core/models/PipelineEvent.h
1. 是，一个Source出来的都共享。
2. 当前代码都放在最后，所以不是大问题，继续follow
3. del

2023-08-13 09:17 UTC, yyuuttaaoo commented on core/models/PipelineEventPtr.h
>  class PipelineEventPtr {
等用到了，证明必要性可以加。

2023-08-13 12:52 UTC, yyuuttaaoo commented on core/pipeline/Pipeline.cpp
> +#include "../processor/ProcessorFillGroupInfoNative.h"
misspell

2023-08-13 12:52 UTC, yyuuttaaoo commented on core/plugin/PluginRegistry.h
> +    std::unique_ptr<PluginInstance> Create(PluginCat cat, const std::string& name, const std::string& pluginId);
现在问题不大，主要是这个版本gcc还缺少static转unique_ptr工具

2023-08-13 12:52 UTC, yyuuttaaoo commented on core/processor/ProcessorParseTimestampNative.cpp
> +            if (GetContext().GetAlarm().IsLowLevelAlarmValid()) {
加了一个IsSupportedEvent函数

2023-08-16 03:39 UTC, henryzhx8 approved these changes

2023-08-16 05:32 UTC, messixukejia approved these changes

2023-08-16 11:36 UTC, merged