[example config] add golang-zap.md/c++-glog.md/linux-tcpdump.md
alibaba/ilogtail pull request #999
Opened 2023-07-12 06:38 UTC by jyf111

2023-07-13 02:20 UTC, henryzhx8 requested changes

2023-07-13 02:20 UTC, henryzhx8 commented on example_config/user_contrib/c++-glog.md
> +```
所有的```后面都加上语言类型，比如plain

2023-07-13 02:20 UTC, henryzhx8 commented on example_config/user_contrib/c++-glog.md
> +W20220926 21:37:44.070065 3276269 main.cpp:25] warning message
这个multiline的例子最好用一些实际的日志

2023-07-13 02:20 UTC, henryzhx8 commented on example_config/user_contrib/golang-zap.md
> +go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0x987e770, {0x0, 0x0, 0x0})
这边能否把panic的日志保存为一条日志，而不是一行一条？

2023-07-13 04:56 UTC, jyf111 commented on example_config/user_contrib/golang-zap.md
> +go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0x987e770, {0x0, 0x0, 0x0})
用多行切分把panic产生的多行日志合并在一起。由于是非json格式的，所以用正则把消息提取到了panic字段中。

2023-07-13 04:58 UTC, jyf111 commented on example_config/user_contrib/c++-glog.md
> +W20220926 21:37:44.070065 3276269 main.cpp:25] warning message
改成了一个打印函数栈的例子，此时会涉及到换行问题。

考虑到单条日志中存在换行的情况可能不是很常见，添加了一个[注释](https://github.com/alibaba/ilogtail/pull/999/commits/5bf7bfd28002c3af00d87fa6653084a0566ce7a4#diff-e7eab4ee61dbac23581d29b87265e39325177395f3b98d7e2ef32da24df58b7aR67)说明如果不涉及多行问题，就不需要用多行切分插件处理。

2023-07-14 02:30 UTC, henryzhx8 approved these changes

2023-07-14 02:30 UTC, merged